UPDATE courses SET
    course_description = '<div class="span7 content"> <p style="font-weight:bold;">Who is this course for?</p> <p><span>Greenwich College offers five levels of General English from Beginner to Upper Intermediate. General English will help you build a strong foundation and give you the language and skills you need to thrive in an English-speaking country. This course is also great if you’re looking to progress to outcome-focused courses such as IELTS, Cambridge, or Academic English. </span></p> <p><span>Classes operate across 5 levels:</span></p> <ul class="general-english"> <li><span style="">Beginner</span></li> <li><span style="">Elementary</span></li> <li><span style="">Pre-intermediate</span></li> <li><span style="">Intermediate</span></li> <li><span style="">Upper-intermediate</span></li> </ul> <div class="hs-cta-node"> <span class="hs_cos_wrapper hs_cos_wrapper_widget hs_cos_wrapper_type_cta" data-hs-cos-general-type="widget" data-hs-cos-type="cta" id="hs_cos_wrapper_widget_1686645670229_" style=""></span> </div> </div>',
    total_course_duration = '1 week',
    offshore_tuition_fee = '',
    entry_requirements = '',
    apply_form = 'https://www.greenwichcollege.edu.au/english-courses/general-english-course?hsLang=en-au',
    updated_at = NOW()
WHERE cricos_course_code = '101351';

UPDATE courses SET
    course_description = '<div class="span7 content"> <p style="font-weight:bold;">Who is this course for?</p> <p>Do you wonder if people can understand you? Are you having trouble understanding the people around you? Do you have difficulty with certain English sounds? Do you want to become a better communicator?</p> <p>This fun, interactive course has been designed for students who want to be more confident speaking and listening in English. </p> <p> </p> <p> </p> <div class="hs-cta-node"> <span class="hs_cos_wrapper hs_cos_wrapper_widget hs_cos_wrapper_type_cta" data-hs-cos-general-type="widget" data-hs-cos-type="cta" id="hs_cos_wrapper_widget_1686645419705_" style=""></span> </div> </div>',
    total_course_duration = '4 weeks',
    offshore_tuition_fee = '',
    entry_requirements = '',
    apply_form = 'https://www.greenwichcollege.edu.au/english-courses/english-pronunciation-course?hsLang=en-au',
    updated_at = NOW()
WHERE cricos_course_code = '101354';

UPDATE courses SET
    course_description = '',
    total_course_duration = '',
    offshore_tuition_fee = '',
    entry_requirements = '',
    apply_form = 'https://www.greenwichcollege.edu.au/ielts-preparation-courses?hsLang=en-au',
    updated_at = NOW()
WHERE cricos_course_code = '101352';

UPDATE courses SET
    course_description = '<div class="span7 content"> <p style="font-weight:bold;"><span>Choose the course that''s best for </span><span>your level</span></p> <ul> <li><a href="/cambridge-exam-preparation-courses/key-english-test-ket-course?hsLang=en-au" rel="noopener">Cambridge A2 Key (KET)</a></li> <li><a href="/cambridge-exam-preparation-courses/preliminary-english-test-pet-course?hsLang=en-au" rel="noopener">Cambridge B1 Preliminary (PET)</a></li> <li><a href="/cambridge-exam-preparation-courses/first-certificate-in-english-fce-course?hsLang=en-au" rel="noopener">Cambridge B2 First (FCE)</a></li> <li><a href="/cambridge-exam-preparation-courses/certificate-of-advanced-english-cae-course?hsLang=en-au" rel="noopener">Cambridge C1 Advanced (CAE)</a></li> </ul> <p>Completing one course will prepare you for the next one.</p> <div class="hs-cta-node"> <span class="hs_cos_wrapper hs_cos_wrapper_widget hs_cos_wrapper_type_cta" data-hs-cos-general-type="widget" data-hs-cos-type="cta" id="hs_cos_wrapper_widget_1686815595267_" style=""></span> </div> </div>',
    total_course_duration = '',
    offshore_tuition_fee = '',
    entry_requirements = '',
    apply_form = 'https://www.greenwichcollege.edu.au/cambridge-exam-preparation-courses?hsLang=en-au',
    updated_at = NOW()
WHERE cricos_course_code = '101356';

UPDATE courses SET
    course_description = '<div class="span7 content"> <p style="font-weight:bold;">Who is this course for?</p> <p><span>This course is for Intermediate and Upper-Intermediate level students who want to feel more confident communicating in a business context.</span></p> <p> </p> <div class="hs-cta-node"> <span class="hs_cos_wrapper hs_cos_wrapper_widget hs_cos_wrapper_type_cta" data-hs-cos-general-type="widget" data-hs-cos-type="cta" id="hs_cos_wrapper_widget_1686642306675_" style=""></span> </div> </div>',
    total_course_duration = '4 weeks',
    offshore_tuition_fee = '',
    entry_requirements = '',
    apply_form = 'https://www.greenwichcollege.edu.au/english-courses/business-english-course?hsLang=en-au',
    updated_at = NOW()
WHERE cricos_course_code = '101355';

UPDATE courses SET
    course_description = '<div class="span7 content"> <p style="font-weight:bold;">Who is this course for?</p> <p>EAP is designed for upper intermediate-level English students who want to improve their academic English skills in preparation for further study at University or College in an English-speaking country.</p> <p>EAP provides a pathway to many Colleges and Universities in Australia</p> <div class="hs-cta-node"> <span class="hs_cos_wrapper hs_cos_wrapper_widget hs_cos_wrapper_type_cta" data-hs-cos-general-type="widget" data-hs-cos-type="cta" id="hs_cos_wrapper_dnd_area-module-3_" style=""></span> </div> </div>',
    total_course_duration = '12 weeks',
    offshore_tuition_fee = '',
    entry_requirements = '',
    apply_form = 'https://www.greenwichcollege.edu.au/english-courses/english-for-academic-purposes-eap?hsLang=en-au',
    updated_at = NOW()
WHERE cricos_course_code = '101353';

UPDATE courses SET
    course_description = '<div class="span7 content"> <p style="font-weight:bold;">Who is this course for?</p> <p><span>English for Vocational Studies (EVS) is tailored for Upper Intermediate-level English students seeking an immersive academic English program for success in vocational studies.</span></p> <p><span>Upon completion, this course opens the door to certificate or diploma programs at leading Australian colleges. It also serves as a stepping stone to our English for Academic Purposes course, priming you for advanced studies at the university level.</span></p> <p><span>EVS is the ideal preparation for your upcoming vocational studies, providing a direct route to admission at Greenwich Hospitality, Health and Care, or Management College and other esteemed Australian vocational institutions.</span></p> <div class="hs-cta-node"> <span class="hs_cos_wrapper hs_cos_wrapper_widget hs_cos_wrapper_type_cta" data-hs-cos-general-type="widget" data-hs-cos-type="cta" id="hs_cos_wrapper_dnd_area-module-3_" style=""></span> </div> </div>',
    total_course_duration = '5 weeks',
    offshore_tuition_fee = '',
    entry_requirements = '',
    apply_form = 'https://www.greenwichcollege.edu.au/english-courses/english-vocational-studies-evs?hsLang=en-au',
    updated_at = NOW()
WHERE cricos_course_code = '101357';

UPDATE courses SET
    course_description = '',
    total_course_duration = '',
    offshore_tuition_fee = '',
    entry_requirements = '',
    apply_form = 'https://www.greenwichcollege.edu.au/management-courses/certificate-2-ii-business?hsLang=en-au',
    updated_at = NOW()
WHERE cricos_course_code = '104741J';

UPDATE courses SET
    course_description = '<div class="span7 content"> <p style="font-weight:bold;">Who is this course for?</p> <p>The Certificate IV in Business is designed for students who want to start a successful career in Business in an English-speaking country.</p> <p>This course equips learners with sound business knowledge and extends their skills so that they can learn the basics of successfully contributing in a business. Students will learn to implement customer service strategies and basic leadership skills.</p> <p>Through our expert trainers and real-life case study approach, our graduates are job-ready faster. Our Studio+ programme offers students industry internship placement opportunities.</p> <div class="hs-cta-node"> <span class="hs_cos_wrapper hs_cos_wrapper_widget hs_cos_wrapper_type_cta" data-hs-cos-general-type="widget" data-hs-cos-type="cta" id="hs_cos_wrapper_widget_1680705460735_" style=""></span> </div> </div>',
    total_course_duration = '40-44 weeks',
    offshore_tuition_fee = '',
    entry_requirements = ' <p><strong>Entry Requirement</strong></p> <ul> <li>All students must be 18 years or older at the commencement of their course</li> </ul> <p><strong>English Language Requirement</strong></p> <ul> <li>All students must have a minimum English language proficiency of IELTS 5.5 or equivalent<span> (Please visit Greenwich College Direct Entry Requirements) </span><strong>OR</strong></li> <li>Have successfully completed one of the following courses with Greenwich English College: General English (Upper Intermediate Level 8 weeks*), English for Business (12 weeks), Cambridge PET * FCE <strong>OR</strong> CAE, EVS, EAP <strong>OR</strong> IELTS* (*With exit point of 5.5 or higher)</li> <li>Direct entry to students on passing Greenwich English College Placement Test (online and on campus testing options)</li> </ul> <p><strong>Academic Requirement</strong></p> <ul> <li>Students must have successfully completed Australian Year 10 or overseas equivalent to Australian Year 10</li> </ul> </div>',
    apply_form = 'https://www.greenwichcollege.edu.au/management-courses/certificate-4-iv-business?hsLang=en-au',
    updated_at = NOW()
WHERE cricos_course_code = '104743G';

UPDATE courses SET
    course_description = '',
    total_course_duration = '40-44 weeks',
    offshore_tuition_fee = '',
    entry_requirements = ' <p><strong>Entry Requirement</strong></p> <ul> <li>All students must be 18 years or older at the commencement of their course</li> </ul> <p><strong>English Language Requirement</strong></p> <ul> <li>All students must have a minimum English language proficiency of IELTS 5.5 or equivalent<span> </span><strong>OR</strong></li> <li>Have successfully completed one of the following courses with Greenwich English College: General English (Upper Intermediate Level 8 weeks*), English for Business (12 weeks), Cambridge PET * FCE and CAE, EVS, EAP and IELTS* (*With exit point of 5.5 or higher)</li> <li>Direct entry to students on passing Greenwich English College Placement Test (online and on campus testing options)</li> </ul> <p><strong>Academic Requirement</strong></p> <ul> <li>Students must have successfully completed Australian Year 10 or overseas equivalent to Australian Year 10</li> </ul> </div>',
    apply_form = 'https://www.greenwichcollege.edu.au/management-college/courses/certificate-iv-in-leadership-and-management?hsLang=en-au',
    updated_at = NOW()
WHERE cricos_course_code = '103951G';

UPDATE courses SET
    course_description = '<div class="span7 content"> <p style="font-weight:bold;">Who is this course for?</p> <p>The Certificate IV in Project Management Practice is designed for people looking to develop and apply project management skills and knowledge within any industry or for any project.</p> <p>This course teaches all facets of project management from concept to close out. Theory sessions, practical activities, written and practical assessments will be conducted throughout the course.</p> <p>Gain valuable knowledge and skills to manage a range of projects across a range of industries, all taught using real-world case studies and projects. Learn the processes behind developing efficient and systematic ways to delivering projects on time and on budget.</p> <p>Transition from Certificate IV to Diploma and finally the Advanced Diploma to lead you into your career as a high level Program and Project Manager.</p> <div class="hs-cta-node"> <span class="hs_cos_wrapper hs_cos_wrapper_widget hs_cos_wrapper_type_cta" data-hs-cos-general-type="widget" data-hs-cos-type="cta" id="hs_cos_wrapper_widget_1686908727459_" style=""></span> </div> </div>',
    total_course_duration = '40-44 weeks',
    offshore_tuition_fee = '',
    entry_requirements = ' <p><strong>Entry Requirement</strong></p> <ul style="list-style-type: square;"> <li>All students must be 18 years or older at the commencement of their course</li> </ul> <strong>English Language Requirement</strong><br/> <ul style="list-style-type: square;"> <li>All students must have a minimum English language proficiency of IELTS 5.5 or equivalent <strong>OR</strong></li> <li>Have successfully completed one of the following courses with Greenwich English College: General English (Upper Intermediate Level 8 weeks*), English for Business (12 weeks), Cambridge PET * FCE and CAE, EVS, EAP and IELTS* (*With exit point of 5.5 or higher)</li> <li>Direct entry to students on passing Greenwich English College Placement Test (online and <g class="gr_ gr_10 gr-alert gr_spell gr_inline_cards gr_run_anim ContextualSpelling ins-del multiReplace" data-gr-id="10" id="10">on campus</g> testing options)</li> </ul> <strong>Academic Requirement</strong><br/> <ul style="list-style-type: square;"> <li>Students must have successfully completed Australian Year 10 or overseas equivalent to Australian Year 10</li> </ul> <p> </p> </div>',
    apply_form = 'https://www.greenwichcollege.edu.au/management-courses/certificate-4-iv-project-management-practice?hsLang=en-au',
    updated_at = NOW()
WHERE cricos_course_code = '103918H';

UPDATE courses SET
    course_description = '<div class="span7 content"> <p style="font-weight:bold;">Who is this course for?</p> <p>Are you ready to embark on a journey in the world of Marketing and Communication within the digital and social media landscape? Learn the essential skills necessary for success in the marketing communication industry and cultivate strong technical abilities to expedite your career progression.</p> <p>Our courses are continuously evolving to incorporate the latest trends in the marketing industry, including AI and other emerging technologies. This ensures that our students are well-equipped to hit the ground running in the fast-paced world of marketing.</p> <div class="hs-cta-node"> <span class="hs_cos_wrapper hs_cos_wrapper_widget hs_cos_wrapper_type_cta" data-hs-cos-general-type="widget" data-hs-cos-type="cta" id="hs_cos_wrapper_widget_1680705972422_" style=""></span> </div> </div>',
    total_course_duration = '40-44 weeks',
    offshore_tuition_fee = '',
    entry_requirements = ' <strong>Entry Requirement</strong><br/> <ul> <li>All students must be 18 years or older at the commencement of their course</li> </ul> <strong>English Language Requirement</strong><br/> <ul> <li>All students must have a minimum English language proficiency of IELTS 5.5 or equivalent<span> </span><strong>OR</strong></li> <li>Have successfully completed one of the following courses with Greenwich English College: General English (Upper Intermediate Level 8 weeks*), English for Business (12 weeks), Cambridge PET * FCE and CAE, AEP, EAP and IELTS* (*With exit point of 5.5 or higher), <span style="font-size: 14px;">10 weeks of EVS</span></li> <li>Direct entry to students on passing Greenwich English College Placement Test (online and<span> </span><g data-gr-id="11" id="11">on campus</g><span> </span>testing options)</li> </ul> <strong>Academic Requirement</strong><br/> <ul> <li>Students must have successfully completed Australian Year 10 or overseas equivalent to Australian Year 10</li> </ul> </div>',
    apply_form = 'https://www.greenwichcollege.edu.au/management-courses/certificate-4-iv-marketing-communication?hsLang=en-au',
    updated_at = NOW()
WHERE cricos_course_code = '104746D';

UPDATE courses SET
    course_description = '<div class="span7 content"> <p style="font-weight:bold;">Who is this course for?</p> <p>The Diploma of Business <em>(Digital Transformation)</em> is designed for people looking to gain a deeper understanding of the digital world. We''ve recognised the need for this qualification to help upskill students in all aspects of the data management and usage, digital marketing, communication and other industry relevant digital skills.</p> <p>Throughout the course we''ll teach you how to optimise your digital and data strategies and tactics to get 100% job ready.</p> <p>Our educators are industry experts, who create, review and update the course content on a regular basis, so you always have cutting edge resources to learn from.</p> <p>We''ll also connect you to our network of businesses through our Client-Connect program, so you can gain valuable hands-on experience and put the theory you learn into practice.</p> <div class="hs-cta-node"> <span class="hs_cos_wrapper hs_cos_wrapper_widget hs_cos_wrapper_type_cta" data-hs-cos-general-type="widget" data-hs-cos-type="cta" id="hs_cos_wrapper_widget_1686910007262_" style=""></span> </div> </div>',
    total_course_duration = '40-44 weeks',
    offshore_tuition_fee = '',
    entry_requirements = ' <p><strong>Entry Requirement</strong></p> <ul> <li>All students must be 18 years or older at the commencement of their course</li> </ul> <p><strong>English Language Requirement</strong></p> <ul> <li>All students must have a minimum English language proficiency of IELTS 5.5 or equivalent<span> </span><strong>OR</strong></li> <li>Have successfully completed one of the following courses with Greenwich English College: General English (Upper Intermediate Level 8 weeks*), English for Business (12 weeks), Cambridge PET * FCE and CAE, EVS, EAP and IELTS* (*With exit point of 5.5 or higher)</li> <li>Direct entry to students on passing Greenwich English College Placement Test (online and<span> </span><g data-gr-id="10" id="10">on campus</g><span> </span>testing options)</li> </ul> <p><strong>Academic Requirement</strong></p> <ul> <li>Students must have successfully completed Australian Year 10 or overseas equivalent to Australian Year 10</li> </ul> </div>',
    apply_form = 'https://www.greenwichcollege.edu.au/management-courses/diploma-business-master-digital-marketing?hsLang=en-au',
    updated_at = NOW()
WHERE cricos_course_code = '104744F';

UPDATE courses SET
    course_description = '',
    total_course_duration = '52 weeks',
    offshore_tuition_fee = '',
    entry_requirements = ' <p><strong>Entry Requirement</strong></p> <ul style="list-style-type: square;"> <li>All students must be 18 years or older at the commencement of their course</li> </ul> <p> </p> <p><strong>English Language Requirement</strong></p> <ul style="list-style-type: square;"> <li>All students must have a minimum English language proficiency of IELTS 5.5 or equivalent <strong>OR</strong></li> <li>Have successfully completed one of the following courses with Greenwich English College: General English (Upper Intermediate Level 8 weeks*), English for Business (12 weeks), Cambridge PET * FCE and CAE, EVS, EAP and IELTS* (*With exit point of 5.5 or higher)</li> <li>Direct entry to students on passing Greenwich English College Placement Test (online and <g class="gr_ gr_10 gr-alert gr_spell gr_inline_cards gr_run_anim ContextualSpelling ins-del multiReplace" data-gr-id="10" id="10">on campus</g> testing options)</li> </ul> <p> </p> <p><strong>Academic Requirement</strong></p> <ul style="list-style-type: square;"> <li>Students must have successfully completed Australian Year 10 or overseas equivalent to Australian Year 10</li> </ul> <p> </p> </div>',
    apply_form = 'https://www.greenwichcollege.edu.au/management-courses/diploma-of-leadership-management?hsLang=en-au',
    updated_at = NOW()
WHERE cricos_course_code = '104165C';

UPDATE courses SET
    course_description = '<div class="span7 content"> <p style="font-weight:bold;">Who is this course for?</p> <p>Diploma of Project Management is designed for people wanting to succeed in delivering projects across a number of industries in a variety of context such as leading new growth strategies, changing systems, restructuring teams or launching marketing events.</p> <p>Develop the knowledge and skills to effectively lead a project through from start to finish - including all aspects of a project from budget setting and tracking progress to managing development, controlling communication and managing human resources.</p> <p>Through our expert trainers and real-life case study approach, our graduates are job-ready faster.</p> <p>You will also have the opportunity to study for a globally recognised Project Management certification for FREE. Exclusive to Greenwich College students, save $1200 and join our <a href="/online-academy/capm-certification-preparation-course?hsLang=en-au" rel="noopener"><strong>Certified Associate in Project Management</strong></a> (CAPM) certification preparation course.</p> <div class="hs-cta-node"> <span class="hs_cos_wrapper hs_cos_wrapper_widget hs_cos_wrapper_type_cta" data-hs-cos-general-type="widget" data-hs-cos-type="cta" id="hs_cos_wrapper_widget_1686911807463_" style=""></span> </div> </div>',
    total_course_duration = '52 weeks',
    offshore_tuition_fee = '',
    entry_requirements = ' <p><strong>Entry Requirement</strong></p> <ul style="list-style-type: square;"> <li>All students must be 18 years or older at the commencement of their course</li> </ul> <p> </p> <p><strong>English Language Requirement</strong></p> <ul style="list-style-type: square;"> <li>All students must have a minimum English language proficiency of IELTS 5.5 or equivalent <strong>OR</strong></li> <li>Have successfully completed one of the following courses with Greenwich English College: General English (Upper Intermediate Level 8 weeks*), English for Business (12 weeks), Cambridge PET * FCE and CAE, EVS, EAP and IELTS* (*With exit point of 5.5 or higher)</li> <li>Direct entry to students on passing Greenwich English College Placement Test (online and <g class="gr_ gr_10 gr-alert gr_spell gr_inline_cards gr_run_anim ContextualSpelling ins-del multiReplace" data-gr-id="10" id="10">on campus</g> testing options)</li> </ul> <p> </p> <p><strong>Academic Requirement</strong></p> <ul style="list-style-type: square;"> <li>Students must have successfully completed Australian Year 10 or overseas equivalent to Australian Year 10</li> </ul> <p> </p> </div>',
    apply_form = 'https://www.greenwichcollege.edu.au/management-courses/diploma-project-management?hsLang=en-au',
    updated_at = NOW()
WHERE cricos_course_code = '104117M';

UPDATE courses SET
    course_description = '<div class="span7 content"> <p style="font-weight:bold;">Who is this course for?</p> <p>The Diploma of Marketing and Communication is designed for students who want to become a savvy marketing and communications practitioner with digital and creative thinking skills in order to drive measurable marketing success.</p> <p>Learn the leading digital and social media tools and best practices used in modern business to succeed in the marketing communication industry and gain expertise in communication, marketing concepts, media planning and social media.</p> <p>Our course is designed with today digital world at the core of our syllabus. All learning concepts are delivered in a relevant digital context.</p> <p><strong>There is no direct entry into this course. Students are required to complete a Certificate IV in Marketing and Communication (BSB40820) as a pre-requisite.</strong></p> <div class="hs-cta-node"> <span class="hs_cos_wrapper hs_cos_wrapper_widget hs_cos_wrapper_type_cta" data-hs-cos-general-type="widget" data-hs-cos-type="cta" id="hs_cos_wrapper_widget_1680775804761_" style=""></span> </div> </div>',
    total_course_duration = '52 weeks',
    offshore_tuition_fee = '',
    entry_requirements = ' <p><strong>Entry Requirements</strong></p> <ul style="list-style-type: square;"> <li>All students must be 18 years or older at the commencement of their course</li> </ul> <p> </p> <p><strong>English Language Requirements</strong></p> <ul style="list-style-type: square;"> <li>All students must have a minimum English language proficiency of IELTS 5.5 or equivalent <strong>OR</strong></li> <li>Have successfully completed one of the following courses with Greenwich English College: General English (Upper Intermediate Level 8 weeks*), English for Business (12 weeks), Cambridge PET * FCE and CAE, EVS, EAP and IELTS* (*With exit point of 5.5 or higher)</li> <li>Direct entry to students on passing Greenwich English College Placement Test (online and <g class="gr_ gr_12 gr-alert gr_spell gr_inline_cards gr_run_anim ContextualSpelling ins-del multiReplace" data-gr-id="12" id="12">on campus</g> testing options)</li> </ul> <p> </p> <p><strong>Academic Requirement</strong><br/><br/>Entry to this qualification is limited to those individuals who:</p> <ul style="list-style-type: square;"> <li>Have completed all core units in BSB42415 Certificate IV in Marketing and Communication.</li> </ul> <p> </p> </div>',
    apply_form = 'https://www.greenwichcollege.edu.au/diploma-marketing-communication?hsLang=en-au',
    updated_at = NOW()
WHERE cricos_course_code = '104747C';

UPDATE courses SET
    course_description = '<div class="span7 content"> <p style="font-weight:bold;">Who is this course for?</p> <p>Advanced Diploma of Program Management is best suited for people who have experience in a project management role and are seeking to enhance their program management skills to further their career.</p> <p>This course will provide students with a solid foundation in Program Management across a range of industry contexts. Individuals at this level use initiative and judgement to direct, plan and lead a range of program functions.</p> <p>A program is defined as a set of interrelated projects, each of which has a Project Manager. A ‘program’ of projects refers to a number of related projects managed by the same person.</p> <p>You will also have the opportunity to study for a globally recognised Project Management certification for <strong>FREE</strong>. Exclusive to Greenwich College students, save $1200 and join our <a href="https://www.greenwichcollege.edu.au/hubfs/2022/CAPM%20CERTIFICATION%20-%20PREP%20COURSE.pdf?hsLang=en-au" rel="noopener" target="_blank"><strong>Certified Associate in Project Management</strong></a> (CAPM) certification preparation course.</p> <div class="hs-cta-node"> <span class="hs_cos_wrapper hs_cos_wrapper_widget hs_cos_wrapper_type_cta" data-hs-cos-general-type="widget" data-hs-cos-type="cta" id="hs_cos_wrapper_widget_1686908168205_" style=""></span> </div> </div>',
    total_course_duration = '76 weeks',
    offshore_tuition_fee = '',
    entry_requirements = ' <p><strong>Entry Requirement</strong></p> <span></span> <ul> <li>All students must be 18 years or older at the commencement of their course</li> </ul> <p><strong>English Language Requirement</strong></p> <span></span> <ul> <li>All students must have a minimum English language proficiency of IELTS 5.5 or equivalent <strong>OR</strong></li> <li>Have successfully completed one of the following courses with Greenwich English College: General English (Upper Intermediate Level 8 weeks*), English for Business (12 weeks), Cambridge PET * FCE and CAE, EVS, EAP and IELTS* (*With exit point of 5.5 or higher)</li> <li>Direct entry to students on passing Greenwich English College Placement Test (online and<span> </span><g data-gr-id="13" id="13">on campus</g><span> </span>testing options</li> </ul> <div> <div> <div> <div> <div data-w="12" data-widget-type="cell" data-x="0"> <div> <div> <div data-w="12" data-widget-type="cell" data-x="0"> <div> <div> <div data-w="12" data-widget-type="rich_text" data-x="0"> <div> <p><strong>Academic Requirement</strong></p> <span data-hs-cos-general-type="widget" data-hs-cos-type="rich_text"> </span> <p>Entry to this qualification is limited to those individuals who:</p> <ul> <li>Have completed a Diploma of Project Management qualification. <strong>OR</strong></li> <li>Have completed two years equivalent full-time relevant<span> </span><g data-gr-id="15" id="15">workplace</g><span> </span>experience at a significant level within a project or program environment within an enterprise.</li> </ul> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div> <div> <div> <div> <div> <div data-w="12" data-widget-type="global_group" data-x="0"> <div data-global-widget-path="generated_global_groups/3910102441.html"> <div> <div> <div data-w="12" data-widget-type="cell" data-x="0"> <div> <div> <div data-w="12" data-widget-type="header" data-x="0"> <div> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div>',
    apply_form = 'https://www.greenwichcollege.edu.au/management-courses/advanced-diploma-program-management?hsLang=en-au',
    updated_at = NOW()
WHERE cricos_course_code = '104433K';

UPDATE courses SET
    course_description = '<div class="span7 content"> <p style="font-weight:bold;">Who is this course for?</p> <p style="text-align: justify;">Advanced Diploma of Leadership and Management is designed for students looking to develop a senior management skill set and leadership attributes across a range of areas, including business administration and management, general administration and business communication. Students will learn leadership and management strategies and techniques to help them excel in the work place, including how to develop organisational strategies, how to create business development plans and how to lead and manage organisational change.<br/><br/>To enable an accelerated path to a chosen career, students will be at the cutting edge of human resources, company innovation and learn how to communicate with influence. <br/><br/><strong>There is no direct entry into this course. Students are required to complete a Diploma course with a BSB code as a pre-requisite.</strong><br/><br/><strong>Here are available Greenwich Management College BSB Diploma course options: </strong><br/><a href="/management-courses/diploma-business-digital-transformation?hsLang=en-au" rel="noopener"><strong>Diploma of Business | Digital Transformation (BSB50120)</strong></a><br/><a href="/management-courses/diploma-marketing-communication?hsLang=en-au" rel="noopener"><strong>Diploma of Marketing and Communication (BSB50620)</strong></a><br/><a href="/management-courses/diploma-of-leadership-management?hsLang=en-au" rel="noopener"><strong>Diploma of Leadership and Management (BSB50420)</strong></a><br/><a href="/management-courses/diploma-project-management?hsLang=en-au" rel="noopener"><strong>Diploma of Project Management (BSB50820)</strong></a></p> <div class="hs-cta-node"> <span class="hs_cos_wrapper hs_cos_wrapper_widget hs_cos_wrapper_type_cta" data-hs-cos-general-type="widget" data-hs-cos-type="cta" id="hs_cos_wrapper_widget_1681179321642_" style=""></span> </div> </div>',
    total_course_duration = '76 weeks',
    offshore_tuition_fee = '',
    entry_requirements = ' <strong>Entry Requirement</strong><br/> <ul> <li>All students must be 18 years or older at the commencement of their course</li> </ul> <strong>English Language Requirement</strong><br/> <ul> <li>All students must have a minimum English language proficiency of IELTS 5.5 or equivalent<span> </span><strong>OR</strong></li> <li>Have successfully completed one of the following courses with Greenwich English College: General English (Upper Intermediate Level 8 weeks*), English for Business (12 weeks), Cambridge PET * FCE and CAE, EVS, EAP and IELTS* (*With exit point of 5.5 or higher)</li> <li>Direct entry to students on passing Greenwich English College Placement Test (online and<span> </span><g data-gr-id="10" id="10">on campus</g><span> </span>testing options)</li> </ul> <strong>Academic Requirement</strong><br/> <ul> <li>Have completed a Diploma or Advanced Diploma from the BSB Training Package (current or superseded equivalent versions).<br/>or</li> <li>Have two years equivalent full-time relevant workplace experience in an operational or leadership role in an enterprise.</li> </ul> </div>',
    apply_form = 'https://www.greenwichcollege.edu.au/management-courses/advanced-diploma-leadership-management?hsLang=en-au',
    updated_at = NOW()
WHERE cricos_course_code = '104745E';

UPDATE courses SET
    course_description = '<div class="span7 content"> <p style="font-weight:bold;">Who is this course for?</p> <p>The Graduate Diploma of Management (Learning) is the perfect choice for those who wish to advance their knowledge and skills for professional or further learning. It develops and refines the relevant skills and knowledge to empower students to achieve success in roles involving management and leadership. Aspects of these are covered in a holistic manner, including</p> <ul> <li>Planning for and managing operational plans</li> <li>Managing workplace relationships</li> <li>Managing key HR functions</li> <li>Understanding and interpreting legislative requirements</li> <li>Sourcing and applying information</li> <li>Building and leading effective teams</li> <li>Engaging a wide range of stakeholders and coordinating promotional activities</li> </ul> <p> </p> <div class="hs-cta-node"> <span class="hs_cos_wrapper hs_cos_wrapper_widget hs_cos_wrapper_type_cta" data-hs-cos-general-type="widget" data-hs-cos-type="cta" id="hs_cos_wrapper_widget_1686912598991_" style=""></span> </div> </div>',
    total_course_duration = '68 weeks',
    offshore_tuition_fee = '',
    entry_requirements = ' <strong>Entry Requirement</strong><br/> <ul> <li>All students must be 18 years or older at the commencement of their course</li> </ul> <strong>English Language Requirement</strong><br/> <ul> <li>All students<span> </span><span>must</span><span> </span>have a minimum English language proficiency of IELTS 5.5 or equivalent<span> </span><strong>OR</strong></li> <li>Have successfully completed one of the following courses with Greenwich English College: General English (Upper Intermediate Level 8 weeks*), English for Business (12 weeks), Cambridge PET * FCE and CAE, EVS, EAP and IELTS* (*With exit point of 5.5 or higher)</li> <li>Direct entry to students on passing Greenwich English College Placement Test (online and<span> </span><g data-gr-id="11" id="11">on campus</g><span> </span>testing options)</li> </ul> <strong>Academic Requirement</strong><br/> <ul> <li>Students must have successfully completed Australian Year 12 or overseas equivalent at minimum;<span> </span><strong>AND</strong></li> <li>Completion of an AQF level 5 (Diploma level qualification) or higher in Australia or an overseas equivalent<span> </span><strong>OR</strong> </li> <li>Have at least 1.5 years equivalent full-time relevant workplace experience in an operational / leadership or management role in an enterprise. </li> </ul> </div>',
    apply_form = 'https://www.greenwichcollege.edu.au/management-courses/graduate-diploma-management-course?hsLang=en-au',
    updated_at = NOW()
WHERE cricos_course_code = '107097H';

UPDATE courses SET
    course_description = '<div class="span7 content"> <p style="font-weight:bold;">Who is this course for?</p> <p>- Aspiring E-commerce professionals: Those looking to start a career in the rapidly growing e-commerce industry.</p> <p>- Current business owners: Entrepreneurs and small business owners who want to expand their online presence and improve their digital business strategies.</p> <p>- Marketing and sales professionals: Individuals in marketing or sales roles who wish to enhance their e-commerce skills and knowledge.</p> <p>- Career changers: Professionals from other fields who are seeking to transition into the e-commerce sector.</p> <div class="hs-cta-node"> <span class="hs_cos_wrapper hs_cos_wrapper_widget hs_cos_wrapper_type_cta" data-hs-cos-general-type="widget" data-hs-cos-type="cta" id="hs_cos_wrapper_widget_1680775804761_" style=""></span> </div> </div>',
    total_course_duration = '52 weeks',
    offshore_tuition_fee = '',
    entry_requirements = ' <p><strong>Entry Requirements</strong></p> <ul style="list-style-type: square;"> <li>All students must be 18 years or older at the commencement of their course</li> </ul> <p> </p> <p><strong>English Language Requirements</strong></p> <ul style="list-style-type: square;"> <li>All students must have a minimum English language proficiency of IELTS 5.5 or equivalent <strong>OR</strong></li> <li>Have successfully completed one of the following courses with Greenwich English College: General English (Upper Intermediate Level 8 weeks*), English for Business (12 weeks), Cambridge PET * FCE and CAE, EVS, EAP and IELTS* (*With exit point of 5.5 or higher)</li> <li>Direct entry to students on the Greenwich English College Placement Test (online and <g class="gr_ gr_12 gr-alert gr_spell gr_inline_cards gr_run_anim ContextualSpelling ins-del multiReplace" data-gr-id="12" id="12">on campus</g> testing options)</li> </ul> <p> </p> <p><strong>Academic Requirements</strong><br/><br/>Entry to this qualification is limited to those individuals who:</p> <ul> <li style="border: none;">Have completed an Australian Year 10 certificate or overseas equivalent at a minimum.</li> </ul> <br/><br/><br/> <p> </p> </div>',
    apply_form = 'https://www.greenwichcollege.edu.au/management-courses/diploma-of-e-commerce?hsLang=en-au',
    updated_at = NOW()
WHERE cricos_course_code = '116131C';

UPDATE courses SET
    course_description = '<div class="span7 content"> <p style="font-weight:bold;">Who is this course for?</p> <p><strong>Marketing Professionals:</strong> Those looking to deepen their expertise in marketing automation and improve campaign efficiency. <strong>Digital Marketers:</strong> Individuals wanting to integrate automation tools and strategies into their marketing efforts. <strong>Career Changers:</strong> Professionals seeking to enter the digital marketing field with a focus on automation. <strong>Business Owners:</strong> Entrepreneurs who want to leverage marketing automation to enhance their business operations.</p> <div class="hs-cta-node"> <span class="hs_cos_wrapper hs_cos_wrapper_widget hs_cos_wrapper_type_cta" data-hs-cos-general-type="widget" data-hs-cos-type="cta" id="hs_cos_wrapper_widget_1680775804761_" style=""></span> </div> </div>',
    total_course_duration = '76 weeks',
    offshore_tuition_fee = '',
    entry_requirements = ' <p><strong>Entry Requirements</strong></p> <ul style="list-style-type: square;"> <li>All students must be 18 years or older at the commencement of their course</li> </ul> <p> </p> <p><strong>English Language Requirements</strong></p> <ul style="list-style-type: square;"> <li>All students must have a minimum English language proficiency of IELTS 5.5 or equivalent <strong>OR</strong></li> <li>Have successfully completed one of the following courses with Greenwich English College: General English (Upper Intermediate Level 8 weeks*), English for Business (12 weeks), Cambridge PET * FCE and CAE, EVS, EAP and IELTS* (*With exit point of 5.5 or higher)</li> <li>Direct entry to students on the Greenwich English College Placement Test (online and <g class="gr_ gr_12 gr-alert gr_spell gr_inline_cards gr_run_anim ContextualSpelling ins-del multiReplace" data-gr-id="12" id="12">on campus</g> testing options)</li> </ul> <p> </p> <p><strong>Academic Requirements</strong></p> <ul> <li><span></span><span>Have completed an Australian Year 12 certificate or overseas equivalent at a minimum;<strong> OR</strong></span></li> <li><span></span><span>Have completed any Diploma level qualification from any training package <strong>or </strong>one (1) year of work experience in a relevant field</span></li> </ul> <p> </p> <br/> <p> </p> </div>',
    apply_form = 'https://www.greenwichcollege.edu.au/management-courses/advanced-diploma-of-marketing-automation?hsLang=en-au',
    updated_at = NOW()
WHERE cricos_course_code = '116360A';

UPDATE courses SET
    course_description = '',
    total_course_duration = '6 weeks',
    offshore_tuition_fee = '',
    entry_requirements = ' <p> </p> <p><strong>Entry Requirement</strong></p> <span></span> <ul> <li>All students must be at least 18 years old at the commencement of their course and must have completed Year 12 (or above)</li> </ul> <p><strong>English Language Requirement</strong></p> <span></span> <ul> <li>All students must have a minimum English language proficiency of IELTS 5.5 or equivalent <strong>OR</strong></li> <li>Have successfully completed one of the following courses with Greenwich English College: General English (Upper Intermediate Level 8 weeks*), English for Business (12 weeks), Cambridge PET * FCE and CAE, EVS, EAP and IELTS* (*With exit point of 5.5 or higher)</li> <li>Direct entry to students on passing Greenwich English College Placement Test (online and<span> </span><g data-gr-id="13" id="13">on campus</g><span> </span>testing options</li> </ul> <div> <div data-w="12" data-widget-type="cell" data-x="0"> <div data-w="12" data-widget-type="cell" data-x="0"> <div data-w="12" data-widget-type="rich_text" data-x="0"> <p><strong>Academic Requirement</strong></p> <span data-hs-cos-general-type="widget" data-hs-cos-type="rich_text"> </span> <p>There are no academic prerequisites to enter this course</p> </div> </div> </div> </div> <div> <div data-w="12" data-widget-type="global_group" data-x="0"> <div data-global-widget-path="generated_global_groups/3910102441.html"> </div> </div> </div> </div>',
    apply_form = 'https://www.greenwichcollege.edu.au/advanced-diploma-of-information-technology?hsLang=en-au',
    updated_at = NOW()
WHERE cricos_course_code = '117327E';

UPDATE courses SET
    course_description = '<div class="span7 content"> <p style="font-weight:bold;"><strong>Who are our courses suited for?</strong></p> Whether you are upskilling in your current field or looking for a change in career path, our courses are the perfect choice for you.<br/><br/>Our courses are practical and combine real life work based skills and hands-on learning to give you the best possible opportunity to succeed.<br/><br/>Greenwich College is able to offer our students a high level of industry engagement and interaction with hospitality venues. This ensures that our graduates are best placed to enter the hospitality industry successfully. <div class="hs-cta-node"> <span class="hs_cos_wrapper hs_cos_wrapper_widget hs_cos_wrapper_type_cta" data-hs-cos-general-type="widget" data-hs-cos-type="cta" id="hs_cos_wrapper_widget_1719904320304_" style=""></span> </div> </div>',
    total_course_duration = '84 weeks',
    offshore_tuition_fee = '',
    entry_requirements = ' <strong>Entry Requirement</strong><br/> <ul> <li>All students must be 18 years or older at the commencement of their course</li> </ul> <strong>English Language Requirement</strong><br/> <ul> <li>All students must have a minimum English language proficiency of IELTS 5.0 or equivalent<span> </span><strong>OR</strong></li> <li>Have successfully completed one of the following courses with Greenwich English College: General English (Intermediate Level 8 weeks*), English for Business (12 weeks), Cambridge PET * FCE and CAE, EVS, EAP and IELTS* (*Need to be equivalent IELTS 5.0+ and have 80%+ attendance)</li> <li>Direct entry to students on passing Greenwich English College Placement Test (<a href="/your-exams/book-a-placement-test?hsLang=en-au" rel="noopener" target="_blank">online</a> and on campus testing options)</li> </ul> <strong>Academic Requirement</strong><br/> <ul> <li>Students must have successfully completed Australian Year 10 or overseas equivalent to Australian Year 10</li> </ul> </div>',
    apply_form = 'https://www.greenwichcollege.edu.au/hospitality-courses/certificate-iv-in-kitchen-management?hsLang=en-au',
    updated_at = NOW()
WHERE cricos_course_code = '111584C';

UPDATE courses SET
    course_description = '<div class="span7 content"> <p style="font-weight:bold;"><strong>Who are our courses suited for?</strong></p> Whether you are upskilling in your current field or looking for a change in career path, our courses are the perfect choice for you.<br/><br/>Our courses are practical and combine real life work based skills and hands-on learning to give you the best possible opportunity to succeed.<br/><br/>Greenwich College is able to offer our students a high level of industry engagement and interaction with hospitality venues. This ensures that our graduates are best placed to enter the hospitality industry successfully. <div class="hs-cta-node"> <span class="hs_cos_wrapper hs_cos_wrapper_widget hs_cos_wrapper_type_cta" data-hs-cos-general-type="widget" data-hs-cos-type="cta" id="hs_cos_wrapper_widget_1719903347190_" style=""></span> </div> </div>',
    total_course_duration = '26 weeks',
    offshore_tuition_fee = '',
    entry_requirements = ' <p><strong>Entry Requirement</strong></p> <ul> <li>All students must be 18 years or older at the commencement of their course</li> </ul> <p><strong>English Language Requirement</strong></p> <span></span> <ul> <li>All students must have a minimum English language proficiency of IELTS 5.5 or equivalent<span> </span><strong>OR</strong></li> <li>Have successfully completed the following courses with Greenwich English College: General English (Upper Intermediate Level 8 weeks*), English for Business (12 weeks), Cambridge PET * FCE and CAE, EVS, EAP and IELTS* (*With exit point of 5.5 or higher)</li> <li>Direct entry to students on passing Greenwich English College Placement Test (online and<span> </span><g data-gr-id="10" id="10">on campus</g><span> </span>testing options)</li> </ul> <p><strong>Academic Requirement</strong></p> <span></span> <ul> <li>Students must have successfully completed Australian Year 12 or overseas equivalent to Australian Year 10.</li> <li>There is no direct entry into the Diploma of Hospitality Management (26 weeks/3 terms) or Advanced Diploma of Hospitality<br/>Management (32 weeks/ 4 terms). Students are required to complete Certificate IV Kitchen Management or Diploma of Hospitality Management<br/>(specialising in culinary).</li> </ul> </div>',
    apply_form = 'https://www.greenwichcollege.edu.au/hospitality-courses/diploma-of-hospitality-management?hsLang=en-au',
    updated_at = NOW()
WHERE cricos_course_code = '111585B';

UPDATE courses SET
    course_description = '<div class="span7 content"> <p style="font-weight:bold;"><strong>Who is this course for?</strong></p> <p>This qualification has been designed specifically for international students who are wishing to fill a senior management role in the hospitality industry, with particular emphasis on Front of House and Operations.</p> <p>The course covers high-level management skills such as managing budgets, operational plans, and staff performance and will teach students how to develop business plans, marketing strategies, and customer services practices that can then be transferred into real world working environments.</p> <div class="hs-cta-node"> <span class="hs_cos_wrapper hs_cos_wrapper_widget hs_cos_wrapper_type_cta" data-hs-cos-general-type="widget" data-hs-cos-type="cta" id="hs_cos_wrapper_widget_1719904573374_" style=""></span> </div> </div>',
    total_course_duration = '32 weeks',
    offshore_tuition_fee = '',
    entry_requirements = ' <p><strong>Entry Requirement</strong></p> <ul> <li>All students must be 18 years or older at the commencement of their course</li> </ul> <strong>English Language Requirement</strong><br/> <ul> <li>All students must have a minimum English language proficiency of IELTS 5.5 or equivalent<span> </span><strong>OR</strong></li> <li>Have successfully completed the following courses with Greenwich English College: General English (Upper Intermediate Level 8 weeks*), English for Business (12 weeks), Cambridge PET * FCE and CAE, EVS, EAP and IELTS* (*With exit point of 5.5 or higher)</li> <li>Direct entry to students on passing Greenwich English College Placement Test (online and<span> </span><g data-gr-id="10" id="10">on campus</g><span> </span>testing options)</li> </ul> <p><strong>Academic Requirement</strong></p> <ul> <li>Students must have successfully completed Australian Year 12 or overseas equivalent to Australian Year 12</li> <li>There is no direct entry into the Diploma of Hospitality Management (26 weeks/3 terms) or Advanced Diploma of Hospitality<br/>Management (32 weeks/ 4 terms). Students are required to complete Certificate IV Kitchen Management and Diploma of Hospitality Management<br/>(specialising in culinary).</li> </ul> </div>',
    apply_form = 'https://www.greenwichcollege.edu.au/hospitality-courses/advanced-diploma-of-hospitality-management?hsLang=en-au',
    updated_at = NOW()
WHERE cricos_course_code = '111586A';

UPDATE courses SET
    course_description = '<div class="span7 content"> <p style="font-weight:bold;"> </p> <p style="font-weight:bold;">Who is this course for?</p> <p>This course is for those who like to help others and are looking at a rewarding career in the community services field. It empowers you with the skills and knowledge to offer personalised support using a person-centered approach to individuals facing disability or aging.</p> <p>Earn a Certificate III in Individual Support (Ageing &amp; Disability) for a fulfilling career and the opportunity to give back to your community.</p> <div class="hs-cta-node"> <span class="hs_cos_wrapper hs_cos_wrapper_widget hs_cos_wrapper_type_cta" data-hs-cos-general-type="widget" data-hs-cos-type="cta" id="hs_cos_wrapper_widget_1685698025050_" style=""></span> </div> </div>',
    total_course_duration = '32 weeks',
    offshore_tuition_fee = '',
    entry_requirements = ' <strong>Entry Requirement</strong><br/> <ul> <li>All students must be 18 years or older at the commencement of their course</li> </ul> <strong>English Language Requirement</strong><br/> <ul> <li>All students must have a minimum English language proficiency of IELTS 5.0 or equivalent<span> </span><strong>OR</strong></li> <li>Have successfully completed one of the following courses with Greenwich English College: General English (Intermediate Level 8 weeks*), English for Business (12 weeks), Cambridge PET * FCE and CAE, EVS, EAP and IELTS* (<span>*Need to be equivalent IELTS 5.0+ and have 80%+ attendance)</span></li> <li>Direct entry to students on passing Greenwich English College Placement Test (<a href="/your-exams/book-a-placement-test?hsLang=en-au" rel="noopener" target="_blank">online</a> and on campus testing options)</li> </ul> <strong>Academic Requirement</strong><br/> <ul> <li>Students must have successfully completed Australian Year 10 or overseas equivalent to Australian Year 10</li> </ul> </div>',
    apply_form = 'https://www.greenwichcollege.edu.au/health-and-care-courses-certificate-individual-support?hsLang=en-au',
    updated_at = NOW()
WHERE cricos_course_code = '114522D';

UPDATE courses SET
    course_description = '<div class="span7 content"> <p style="font-weight:bold;"> </p> <p style="font-weight:bold;">Who is this course for?</p> <p>This course empowers you with the skills and knowledge to offer personalised support using a person-centered approach to individuals facing disability or ageing. Earn a Certificate IV in Individual Support (Ageing) for a fulfilling career and the opportunity to give back to your community.</p> <div class="hs-cta-node"> <span class="hs_cos_wrapper hs_cos_wrapper_widget hs_cos_wrapper_type_cta" data-hs-cos-general-type="widget" data-hs-cos-type="cta" id="hs_cos_wrapper_widget_1685698025050_" style=""></span> </div> </div>',
    total_course_duration = '52 weeks',
    offshore_tuition_fee = '',
    entry_requirements = ' <strong>Entry Requirement</strong><br/> <ul> <li>All students must be 18 years or older at the commencement of their course</li> </ul> <strong>English Language Requirement</strong><br/> <ul> <li>All students must have a minimum English language proficiency of IELTS 5.5 or equivalent<span> </span><strong>OR</strong></li> <li>Have successfully completed one of the following courses with Greenwich English College: General English (Upper Intermediate Level 8 weeks*), English for Business (12 weeks), Cambridge PET * FCE and CAE, EVS, EAP and IELTS* (*With exit point of 5.5 or higher)</li> <li>Direct entry to students on passing Greenwich English College Placement Test (<a href="/your-exams/book-a-placement-test?hsLang=en-au" rel="noopener" target="_blank">online</a> and on campus testing options)</li> </ul> <strong>Academic Requirement</strong><br/> <ul> <li>Students must have successfully completed Australian Year 10 or overseas equivalent </li> </ul> </div>',
    apply_form = 'https://www.greenwichcollege.edu.au/health-and-care-courses-certificate-iv-ageing-support?hsLang=en-au',
    updated_at = NOW()
WHERE cricos_course_code = '114523C';

UPDATE courses SET
    course_description = '<div class="span7 content"> <p style="font-weight:bold;"> </p> <p style="font-weight:bold;">Who is this course for?</p> <p>The Diploma of Community Services (Case Management) is designed for individuals who are interested in pursuing a career in community services with a focus on case management.</p> <p> This course is suitable for those who wish to work in roles that involve providing support, guidance, and tailored assistance to individuals and communities in need.</p> <p> If you have a passion for making a positive impact, empowering others, and playing a key role in the well-being of the community, this course is tailored to help you build the necessary skills and knowledge for a rewarding career in the field of community services.</p> <p> </p> <div class="hs-cta-node"> <span class="hs_cos_wrapper hs_cos_wrapper_widget hs_cos_wrapper_type_cta" data-hs-cos-general-type="widget" data-hs-cos-type="cta" id="hs_cos_wrapper_widget_1685698025050_" style=""></span> </div> </div>',
    total_course_duration = '76 weeks',
    offshore_tuition_fee = '',
    entry_requirements = ' <strong>Entry Requirement</strong><br/> <ul> <li>All students must be 18 years or older at the commencement of their course</li> </ul> <strong>English Language Requirement</strong><br/> <ul> <li>All students must have a minimum English language proficiency of IELTS 5.5 or equivalent<span> </span><strong>OR</strong></li> <li>Have successfully completed one of the following courses with Greenwich English College: General English (Upper Intermediate Level 8 weeks*), English for Business (12 weeks), Cambridge PET * FCE and CAE, EVS, EAP and IELTS* (*With exit point of 5.5 or higher)</li> <li>Direct entry to students on passing Greenwich English College Placement Test (<a href="/your-exams/book-a-placement-test?hsLang=en-au" rel="noopener" target="_blank">online</a> and on campus testing options)</li> </ul> <strong>Academic Requirement</strong><br/> <ul> <li>Students must have successfully completed Australian Year 12 or overseas equivalent </li> </ul> </div>',
    apply_form = 'https://www.greenwichcollege.edu.au/health-and-care-courses-diploma-community-services?hsLang=en-au',
    updated_at = NOW()
WHERE cricos_course_code = '114524B';