-- Update provider institution details
UPDATE provider_institution SET
    intake_date = 'February, April, July, October',
    updated_at = NOW()
WHERE cricos_provider_code = '00011G';

UPDATE courses SET
    course_description = '<h4>Course Description</h4><p>Learn the fundamentals of good design as you utilise your creativity and love of design and construction to create your own (virtual) building design projects. </p><p>This course is highly regarded by industry. It provides the practical skills, knowledge and qualifications to work as a building designer. You will gain specialist design skills applicable to residential and commercial design within the building design sector in a project-based setting, reflective of real office practice. Importantly, our strong industry partnerships allow students to work on live projects and graduate work-ready. </p><p>There are also opportunities to pursue further studies with pathways to university, where this course will provide you excellent grounding to take your studies further into Architecture and/or Building. </p><h5>Possible career outcomes</h5><ul><li>Building designers</li> <li>Architectural assistants </li> <li>Building design assistants </li> <li>Architectural draftspersons </li></ul>',
    total_course_duration = 'Full-time: 2 years',
    offshore_tuition_fee = 26000,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = 860,
    entry_requirements = '<h4>Entry Requirements</h4><h5>Academic:</h5><p>Successful completion of Australian Year 12 or equivalent – Equivalents can be found on our <a href="/international/helpful-information/country-equivalencies">Entry Requirements</a> page.</p><h5>English:</h5><p>IELTS Academic overall score of 6.0 with no band below 5.5 (or equivalent) – Equivalents can be found on our <a href="/international/helpful-information/el-equivalency">English language equivalency</a> page.</p><h5>Age/other requirements:</h5><p>You must be 18 years or over at the time of course commencement.</p><h5>Personal Learning Requirements</h5><p>There are personal learning requirements for each qualification at The Gordon. These are essential personal capabilities and skills required to successfully complete the course and be ready to work in the industry.</p><p><a href="/getmedia/9f66b990-74b0-41d3-b98a-ed680de3f636/22627VIC-Advanced-Diploma-of-Building-Design-(Architectural).pdf">Please review the requirements here</a> and consider any challenges you may have in meeting them. When applying for your course, please let us know what support you may need. </p>',
    apply_form = 'https://www.thegordon.edu.au/international/international-courses/22627vic-advanced-diploma-of-building-design-(arch',
    updated_at = NOW()
WHERE cricos_course_code = '114639B';

UPDATE courses SET
    course_description = '<h4>Course Description</h4><p>Are you looking for a rewarding career working with young children? This entry-level course will equip you with the foundation skills and knowledge you need to become a qualified assistant within this sector. In addition, you will learn about effective interaction and communication with children, appropriate care for babies, toddlers and children, first aid, safety and working legally and ethically.</p>',
    total_course_duration = 'Full-time: 12 Months',
    offshore_tuition_fee = 10500,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = 860,
    entry_requirements = '<h4>Entry Requirements</h4><h5>Academic:</h5><p>Successful completion of Australian Year 11 or equivalent – Equivalents can be found on our <a href="/international/helpful-information/country-equivalencies">Entry Requirements</a> page.</p><h5>English:</h5><p>IELTS Academic overall score of 6.0 with no band below 5.5 (or equivalent) – Equivalents can be found on our <a href="/international/helpful-information/el-equivalency">English language equivalency</a> page.</p><h5>Age/other requirements:</h5><p>You must be 18 years or over at the time of course commencement.</p><h5>Personal Learning Requirements</h5><p>There are personal learning requirements for each qualification at The Gordon. These are essential personal capabilities and skills required to successfully complete the course and be ready to work in the industry.</p><p><a href="/getmedia/6e2a3d4f-20c8-4fce-9c1b-c611fa7c3881/CHC30121-Certificate-III-in-Early-Childhood-Education-and-Care.pdf">Please review the requirements here</a> and consider any challenges you may have in meeting them. When applying for your course, please let us know what support you may need. </p><h5>Work placement requirements</h5><ul><li>Applicants are required to hold a current Working with Children Check.</li><li>Applicants must provide Covid vaccination evidence as per guidelines of Department of Education and Training.</li></ul>',
    apply_form = 'https://www.thegordon.edu.au/international/international-courses/chc30121-certificate-iii-in-early-childhood-educat',
    updated_at = NOW()
WHERE cricos_course_code = '109312A';

UPDATE courses SET
    course_description = '<h4>Course Description</h4><p>Do you have an empathetic nature, good people skills and are looking for flexible work? A healthcare career could be for you. </p><p>The Certificate III in Individual Support (Ageing and Disability) prepares you for working with elderly and/or people living with disabilities in a community or residential setting. You will learn to communicate and work in health or community services, provide individualised support, recognise healthy body systems, work with diverse people, support independence and wellbeing, follow safe work practices and work legally and ethically. </p><p>Individual support has two specialisations, disability and ageing, in one. Students will gain both streams by studying this dual specialisation.</p><h5>Work placement/industry experience</h5>',
    total_course_duration = 'Full-time: 8 Months',
    offshore_tuition_fee = 13000,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = 670,
    entry_requirements = '<h4>Entry Requirements</h4><h5>Academic:</h5><p>Successful completion of Australian Year 11 or equivalent – Equivalents can be found on our <a href="/international/helpful-information/country-equivalencies">Entry Requirements</a> page.</p><h5>English:</h5><p>IELTS Academic overall score of 6.0 with no band below 5.5 (or equivalent) – Equivalents can be found on our <a href="/international/helpful-information/el-equivalency">English language equivalency</a> page.</p><h5>Age/other requirements:</h5><p>You must be 18 years or over at the time of course commencement.</p><h5>Personal Learning Requirements</h5><p>There are personal learning requirements for each qualification at The Gordon. These are essential personal capabilities and skills required to successfully complete the course and be ready to work in the industry.</p><p><a href="/getmedia/14366ada-708a-4a51-abc2-caf1c32d31c6/CHC33021-Certificate-III-in-Individual-Support-(Ageing-Disability).pdf">Please review the requirements here</a> and consider any challenges you may have in meeting them. When applying for your course, please let us know what support you may need. </p>',
    apply_form = 'https://www.thegordon.edu.au/international/international-courses/chc33021-certificate-iii-in-individual-support',
    updated_at = NOW()
WHERE cricos_course_code = '114640J';

UPDATE courses SET
    course_description = '<h4>Course Description</h4><p>Support your community and people experiencing hardship as you develop the knowledge needed for a rewarding career in the diverse community services industry. </p><p>The Diploma of Community Services course will build your leadership capabilities and give you the specialised skills you need to work in the community services sector, supporting the wellbeing of individuals, families and communities and helping to facilitate social change. </p><p>You’ll be qualified to manage a range of responsibilities while supporting people who are disadvantaged and vulnerable. If you''re driven to empower diverse communities, passionate about social justice and want to challenge the social structures that maintain disadvantage, then this qualification can help you achieve your goals. </p><p>Community Services workers empower and support disadvantaged and vulnerable people to achieve their goals. They provide housing, mental health, disability, multicultural, financial, youth, domestic and family violence support. Your experience and career goals will help determine your pathway.</p>',
    total_course_duration = 'Full-time: 15 months',
    offshore_tuition_fee = 13500,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = 1030,
    entry_requirements = '<h4>Entry Requirements</h4><h5>Academic:</h5><p>Successful completion of Australian Year 12 or equivalent – Equivalents can be found on our <a href="/international/helpful-information/country-equivalencies">Entry Requirements</a> page.</p><h5>English:</h5><p>IELTS Academic overall score of 6.0 with no band below 5.5 (or equivalent); or completion of Australian Year 12; or a qualification undertaken in Australia at Certificate IV or higher and completed within the past 5 years; or University studies in Australia of at least 2 years duration.</p><h5>Age/other requirements:</h5><p>You must be aged 18 years or over at the time of course commencement.</p><h5>Personal Learning Requirements</h5><p>There are personal learning requirements for each qualification at The Gordon. These are essential personal capabilities and skills required to successfully complete the course and be ready to work in the industry.</p><p><a href="/getmedia/9b42441e-5bf2-4ceb-b0c9-8c332a064240/CHC52025-Diploma-of-Community-Services-PLR.pdf">Please review the requirements here</a> and consider any challenges you may have in meeting them. When applying for your course, please let us know what support you may need. </p>',
    apply_form = 'https://www.thegordon.edu.au/international/international-courses/chc52025-diploma-of-community-services',
    updated_at = NOW()
WHERE cricos_course_code = '118872E';

UPDATE courses SET
    course_description = '<h4>Course Description</h4><p>This popular course will equip you with the knowledge and practical skills you need to register as an enrolled nurse or create a pathway to university. <br/><br/>Our experienced team of trainers will teach you about anatomy and physiology, communication skills, medical terminology, infection control, legal and ethical issues associated with nursing, nursing patients with complex needs, administering medications, and nursing patients with mental health needs. Our partnerships with Barwon Health, St John of God Hospital, and other healthcare providers also provide excellent work placement and employment opportunities. <br/><br/>This course is accredited by the Nursing and Midwifery Board of Australia (NMBA). Upon completing your studies, you will be eligible to register as an enrolled nurse with the NMBA.</p>',
    total_course_duration = 'Full-time: 2 Years',
    offshore_tuition_fee = 43000,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = 1430,
    entry_requirements = '<h4>Entry Requirements</h4><h5>Academic:</h5><p>Successful completion of Australian Year 12 or equivalent – Equivalents can be found on our <a href="/international/helpful-information/country-equivalencies">Entry Requirements</a> page.</p><ul><li>Police and Working with Children check prior to placement</li><li>Computer skills</li><li>Up to date immunisation/vaccination record</li><li>Year 11 General Maths</li></ul><h5>English:</h5><p>You must be able to demonstrate that you meet the requirements of the Nursing and Midwifery Board of Australia’s (NMBA) English language skills registration standard.</p><p>For further information regarding the English Language Requirements, please refer to <a href="https://www.nursingmidwiferyboard.gov.au/registration-standards/english-language-skills.aspx">Nursing and Midwifery Board of Australia - English language skills</a></p><h5>Age/other requirements:</h5><ul><li>You must be 18 years or over at the time of course commencement.</li></ul><h5>Personal Learning Requirements</h5><p>There are personal learning requirements for each qualification at The Gordon. These are essential personal capabilities and skills required to successfully complete the course and be ready to work in the industry.</p><p><a href="/getmedia/7cee7801-174e-42c5-9e0c-e0dab05e649d/HLT54121-Diploma-of-Nursing.pdf">Please review the requirements here</a> and consider any challenges you may have in meeting them. When applying for your course, please let us know what support you may need. </p>',
    apply_form = 'https://www.thegordon.edu.au/international/international-courses/hlt54121-diploma-of-nursing',
    updated_at = NOW()
WHERE cricos_course_code = '111651H';

UPDATE courses SET
    course_description = '<h4>Course Description</h4><p>If you’re looking for a hands-on science course that will make you job-ready, our laboratory techniques course is ideal. </p><p>The course will equip you to successfully enter the pathology, biotechnology, biological and environmental sector, or related science industries. The course teaches you fundamental theory and practice in a variety of laboratory techniques. In addition to the technical skills, you also learn to apply quality, WHS and sustainability skills to the workplace. Areas of study include microbiology, chemistry, food testing, histology testing, data management and communication. </p>',
    total_course_duration = 'Full-time: 1 Year',
    offshore_tuition_fee = 13000,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = 1150,
    entry_requirements = '<h4>Entry Requirements</h4><h5>Academic:</h5><p>Successful completion of Australian Year 11 or equivalent – Equivalents can be found on our <a href="/international/helpful-information/country-equivalencies">Entry Requirements</a> page.</p><h5>English:</h5><p>IELTS Academic overall score of 6.0 with no band below 5.5 (or equivalent) – Equivalents can be found on our <a href="/international/helpful-information/el-equivalency">English language equivalency</a> page.</p><h5>Age/other requirements:</h5><p>You must be 18 years or over at the time of course commencement.</p><h5>Personal Learning Requirements</h5><p>There are personal learning requirements for each qualification at The Gordon. These are essential personal capabilities and skills required to successfully complete the course and be ready to work in the industry.</p><p><a href="/getmedia/0f594b25-f784-446d-ab11-f8896a6f353a/MSL40122-Certificate-IV-in-Laboratory-Techniques.pdf">Please review the requirements here</a> and consider any challenges you may have in meeting them. When applying for your course, please let us know what support you may need. </p>',
    apply_form = 'https://www.thegordon.edu.au/international/international-courses/msl40122-certificate-iv-in-laboratory-techniques',
    updated_at = NOW()
WHERE cricos_course_code = '112035B';

UPDATE courses SET
    course_description = '<h4>Course Description</h4><p>Would you like to become a qualified beauty therapist working in a salon, day spa, resort spa, or international spa? This diverse beauty therapy course equips you with advanced skills and knowledge to work at a senior level in the industry.</p><p>You’ll develop practical skills and theoretical knowledge in beauty therapy fundamentals, business marketing and planning, and advanced spa therapy treatments, including waxing, lash and brow tinting, manicures and pedicures, facials, and massage; relaxation, hot stone, aromatherapy and lymphatic.</p><p>You will gain valuable hands-on experience at our practical clinic <a href="/future-students/training-facilities/training-venues/studio">The Studio</a>, at the Geelong City Campus. Our Diploma program is well-regarded in the industry. Our graduates have achieved a 100% employment rate for the last two years!</p><h5>Work placement/industry experience</h5>',
    total_course_duration = 'Full-time: 12 months',
    offshore_tuition_fee = 19000,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = 5100,
    entry_requirements = '<h4>Entry Requirements</h4><h5>Academic:</h5><p>Successful completion of Australian Year 12 or equivalent – Equivalents can be found on our <a href="/international/helpful-information/country-equivalencies">Entry Requirements</a> page.</p><h5>English:</h5><p>IELTS Academic overall score of 6.0 with no band below 5.5 (or equivalent) – Equivalents can be found on our <a href="/international/helpful-information/el-equivalency">English language equivalency</a> page.</p><h5>Age/other requirements:</h5><p>You must be 18 years or over at the time of course commencement.</p><h5>Personal Learning Requirements</h5><p>There are personal learning requirements for each qualification at The Gordon. These are essential personal capabilities and skills required to successfully complete the course and be ready to work in the industry.</p><p><a href="/getmedia/fc52f90f-2a39-401e-b306-6481f3698335/SHB50121-Diploma-of-Beauty-Therapy.pdf">Please review the requirements here</a> and consider any challenges you may have in meeting them. When applying for your course, please let us know what support you may need. </p>',
    apply_form = 'https://www.thegordon.edu.au/international/international-courses/shb50121-diploma-of-beauty-therapy',
    updated_at = NOW()
WHERE cricos_course_code = '112051B';

UPDATE courses SET
    course_description = '<h4>Course Description</h4><p>A career in food and the culinary arts is your destiny if you have a love of making people happy with food, see yourself as a team player, and love to explore and create in a fast-paced dynamic kitchen environment.</p><p>Learn the fundamentals of food preparation and cooking skills and applying and practicing them across:</p><ul><li>A range of appetisers and salads</li><li>Poultry and game</li><li>Seafood and meat</li><li>A variety of hot and cold desserts,</li><li>Cakes and yeast goods</li></ul><p>You will also master the basics such as:</p><ul><li>Stocks, sauces and soups</li><li>Vegan and vegetarian dishes</li><li>Egg and pasta dishes.</li></ul><p>Learn practical skills too, such as food costs, effective communication and time management and have the opportunity to demonstrate these skills during live service periods.</p><p>View The Gordon''s <a href="/getmedia/f919541a-fb27-4946-a651-71157323a506/10530-Cookery-A4-Student-Info-Sheet-2024.pdf">Uniform and Toolkit requirements here</a>.</p>',
    total_course_duration = 'Full-time: 12 Months',
    offshore_tuition_fee = 15500,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = 2790,
    entry_requirements = '<h4>Entry Requirements</h4><h5>Academic:</h5><p>Successful completion of Australian Year 11 or equivalent – Equivalents can be found on our <a href="/international/helpful-information/country-equivalencies">Entry Requirements</a> page.</p><h5>English:</h5><p>IELTS Academic overall score of 6.0 with no band below 5.5 (or equivalent) – Equivalents can be found on our <a href="/international/helpful-information/el-equivalency">English language equivalency</a> page.</p><h5>Age/other requirements:</h5><p>You must be 18 years or over at the time of course commencement.</p><h5>Personal Learning Requirements</h5><p>There are personal learning requirements for each qualification at The Gordon. These are essential personal capabilities and skills required to successfully complete the course and be ready to work in the industry.</p><p><a href="/getmedia/4b1fe1ae-6b54-4829-8253-fcae665df087/SIT30821-Certificate-III-in-Commercial-Cookery.pdf">Please review the requirements here</a> and consider any challenges you may have in meeting them. When applying for your course, please let us know what support you may need. </p>',
    apply_form = 'https://www.thegordon.edu.au/international/international-courses/sit30821-certificate-iii-in-commercial-cookery',
    updated_at = NOW()
WHERE cricos_course_code = '109762H';

UPDATE courses SET
    course_description = '<h4>Course Description</h4><p>Are you an experienced industry professional looking for more than a standard cook’s qualification or dreaming of managing a professional kitchen? This course will equip you with the skills for both! </p><p>You will learn all facets of organising a professional kitchen, including selection, preparation, executing and cooking different menus and techniques. You will cover hygiene and safety procedures, staffing, environmental considerations, seasonal produce, quality control, stock control, bulk cooking, catering revenue and costs, finance, leadership, management and human resources. You will also have the opportunity to practice the skills learnt to run a series of live events both on campus and externally. You will take part in local foraging excursions, meet with primary producers and local business owners and learn from our highly skilled industry professionals. </p>',
    total_course_duration = 'Full-time: 6 months with current Certificate III in Commercial Cookery',
    offshore_tuition_fee = 8400,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = 1220,
    entry_requirements = '<h4>Entry Requirements</h4><h5>Academic:</h5><p>Applicants must have completed the SIT30821 Certificate III in Commercial Cookery.</p><h5>English:</h5><p>IELTS Academic overall score of 6.0 with no band below 5.5 (or equivalent) – Equivalents can be found on our <a href="/international/helpful-information/el-equivalency">English language equivalency</a> page.</p><h5>Other requirements:</h5><p>Applicants applying on a basis of entry other than successful completion of Certificate III in Commercial Cookery from The Gordon may be required to complete one or more prerequisite units which will incur extra unit tuition fee. Further information is provided at the time of enrolment.</p><h5>Personal Learning Requirements</h5><p>There are personal learning requirements for each qualification at The Gordon. These are essential personal capabilities and skills required to successfully complete the course and be ready to work in the industry.</p><p><a href="/getmedia/02069676-612e-4b1c-be36-183801fe4f42/SIT40521-Certificate-IV-in-Kitchen-Management.pdf">Please review the requirements here</a> and consider any challenges you may have in meeting them. When applying for your course, please let us know what support you may need. </p>',
    apply_form = 'https://www.thegordon.edu.au/international/international-courses/sit40521-certificate-iv-in-kitchen-management',
    updated_at = NOW()
WHERE cricos_course_code = '109624G';

UPDATE courses SET
    course_description = '<h4>Course Description</h4><p>If you love working with people and are looking for a rewarding career in the hospitality industry, then this course is for you!</p><p>You will learn to develop quality customer service skills, manage finances within a budget, and manage staff and regulatory requirements. The learning style combines hands-on and theory, teaching you everything you need to become a highly skilled manager in the hospitality industry.</p><h5>How often do I attend?</h5><p>Full time - 3 days a week</p>',
    total_course_duration = 'Full-time: 6 Months',
    offshore_tuition_fee = 7350,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = 480,
    entry_requirements = '<h4>Entry Requirements</h4><h5>Academic:</h5><p>Pre requisite courses - successfully completed:</p><ul><li>SIT30821 Certificate III in Commercial Cookery (1 year)</li><li>SIT40521 Certificate IV in Kitchen Management (6 months)</li></ul><h5>English:</h5><p>IELTS Academic overall score of 6.0 with no band below 5.5 (or equivalent) – Equivalents can be found on our <a href="/international/helpful-information/el-equivalency">English language equivalency</a> page.</p><h5>Age/other requirements:</h5><ul><li>You must be 18 years or over at the time of course commencement.</li><li>Applicants applying on a basis of entry other than successful completion of Certificate III in Commercial Cookery and Certificate IV in Kitchen Management from The Gordon may be required to complete one or more prerequisite units which will incur extra unit tuition fee. Further information is provided at the time of enrolment.</li></ul><h5>Personal Learning Requirements</h5><p>There are personal learning requirements for each qualification at The Gordon. These are essential personal capabilities and skills required to successfully complete the course and be ready to work in the industry.</p><p><a href="/getmedia/3a32f2b1-ffe2-4dcf-8a18-73a80894b05f/SIT50422-Diploma-of-Hospitality-Management.pdf">Please review the requirements here</a> and consider any challenges you may have in meeting them. When applying for your course, please let us know what support you may need. </p>',
    apply_form = 'https://www.thegordon.edu.au/international/international-courses/sit50422-diploma-of-hospitality-management',
    updated_at = NOW()
WHERE cricos_course_code = '113590M';

