UPDATE courses SET
    course_description = '<p>The UEE30820 Certificate III in Electrotechnology Electrician qualification is a pathway to a career in the electrotechnology sector. It will give students the required knowledge and practical exercises required by industry. This qualification allows graduates to apply for a NSW Electrician’s Licence. It covers electrical systems and equipment installation, testing, fault finding, repair, and maintenance of circuitry needed to apply for an Electrician licence. </p>',
    total_course_duration = '128 weeks',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="row"> <div class="col-sm-6"> <div class="width-90"> <h6 class="sec-headers">International Students</h6> <ul class="black-square"> <li>Students must be 18 years or above.</li> <li>Complete a Pre-Enrolment Review prior to enrolment</li> <li>Complete an online language, literacy and numeracy (LLN) assessment (on campus)</li> <li>Basic -intermediate level of computer skills</li> <li>Proficient in English International Students require either an <ul> <li>IELTS level of 5.5 or above with no band under 5.0 or</li> <li>TOEFL 62 (internet-based) or</li> <li>Pearson Test of English Academic (PTE) 46 or</li> <li>Cambridge English Advanced (CAE) score of 162 or</li> <li>OET score of C for each test component</li> </ul> </li> </ul> </div> </div> <div class="col-sm-6"> <h6 class="sec-headers">Domestic Students</h6> <ul class="black-square"> <li>18 years of age or older</li> <li>Satisfactorily completed Year 12 or equivalent </li> <li>Be able to read and comprehend course requirements</li> <li>Have an intermediate understanding of computers and the internet to assist with</li> <li>conducting research and complete assessments</li> </ul> </div> </div>',
    apply_form = 'https://ahsi.edu.au/uee30280-certificate-iii-in-electrotechnology-electrician/',
    updated_at = NOW()
WHERE cricos_course_code = '116822J';

UPDATE courses SET
    course_description = '<p>This qualification covers competencies to select, install, commission, fault find and maintain fire protection control systems in buildings. This qualification allows NSW approved Electricians to go to the next step in their career. It covers competencies to select, install, commission, fault find and maintain electrical systems and equipment with options, typically in explosion protection; electrical machines; electrical inspection; safety auditing; contracting; lifts and energy supply/distribution. </p>',
    total_course_duration = '52 weeks',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="row"> <div class="col-sm-6"> <div class="width-90"> <h6 class="sec-headers">International Students</h6> <ul class="black-square"> <li>Students must be 18 years or above.</li> <li>Students must have completed UEE30820 Cert III in Electrotechnology Electrician or have a current Unrestricted Electricians Licence or its equivalent issued in an Australian State or Territory</li> <li>Complete a Pre-Enrolment Review prior to enrolment</li> <li>Complete an online language, literacy and numeracy (LLN) assessment (on campus)</li> <li>Basic -intermediate level of computer skills</li> <li>Proficient in English International Students require either an <ul> <li>IELTS level of 5.5 or above with no band under 5.0 or</li> <li>TOEFL 62 (internet-based) or</li> <li>Pearson Test of English Academic (PTE) 46 or</li> <li>Cambridge English Advanced (CAE) score of 162 or</li> <li>OET score of C for each test component</li> </ul> </li> </ul> </div> </div> <div class="col-sm-6"> <h6 class="sec-headers">Domestic Students</h6> <ul class="black-square"> <li>18 years of age or older</li> <li>Students must have completed UEE30820 Cert III in Electrotechnology Electrician or have a current Unrestricted Electricians Licence or its equivalent issued in an Australian State or Territory</li> <li>Satisfactorily completed Year 12 or equivalent </li> <li>Be able to read and comprehend course requirements</li> <li>Have an intermediate understanding of computers and the internet to assist with</li> <li>conducting research and complete assessments</li> </ul> </div> </div>',
    apply_form = 'https://ahsi.edu.au/uee40620-certificate-iv-in-electrotechnology-electrician/',
    updated_at = NOW()
WHERE cricos_course_code = '116669B';

UPDATE courses SET
    course_description = '<p>This qualification covers competencies required to design and validate/evaluate electrical equipment and systems and provide technical advice/sales. Throughout the course students will build expertise in installing, testing and monitoring equipment and systems, solving problems and managing large electrical projects. The graduates will be able to work in the electrical industry. </p>',
    total_course_duration = '104 weeks',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="row"> <div class="col-sm-6"> <div class="width-90"> <h6 class="sec-headers">International Students</h6> <ul class="black-square"> <li>Students must be 18 years or above.</li> <li>Complete a Pre-training Review prior to commencing training</li> <li>Complete an online language, literacy and numeracy (LLN) assessment (on campus)</li> <li>Basic -intermediate level of computer skills</li> <li>Successful completion of a Certificate III or above qualification in a related Engineering or Electrical pathway.</li> <li>Proficient in English International Students require either an <ul> <li>IELTS level of 5.5 or above with no band under 5.0 or</li> <li>TOEFL 62 (internet-based) or</li> <li>Pearson Test of English Academic (PTE) 46 or</li> <li>Cambridge English Advanced (CAE) score of 162 or</li> <li>OET score of C for each test component</li> </ul> </li> </ul> </div> </div> <div class="col-sm-6"> <h6 class="sec-headers">Domestic Students</h6> <ul class="black-square"> <li>18 years of age or older</li> <li> Successful completion of a Certificate III or above qualification in a related Engineering or Electrical pathway.</li> <li>Satisfactorily completed Year 12 or equivalent </li> <li>Be able to read and comprehend course requirements</li> <li>Have an intermediate understanding of computers and the internet to assist with</li> <li>conducting research and complete assessments</li> </ul> </div> </div>',
    apply_form = 'https://ahsi.edu.au/uee62122-advanced-diploma-of-engineering-technology-electrical-2/',
    updated_at = NOW()
WHERE cricos_course_code = '117011C';

UPDATE courses SET
    course_description = '<p>The CPC30220 – Certificate III in Carpentry qualification is a pathway to a career in the building sector. It will give graduates a trade outcome in carpentry, covering common skills for the construction industry including setting out, manufacturing, constructing, assembling, installing and repairing products made using timber and non-timber materials. </p>',
    total_course_duration = '104 weeks',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="row"> <div class="col-sm-6"> <div class="width-90"> <h6 class="sec-headers">International Students</h6> <ul class="black-square"> <li>Students must be 18 years or above.</li> <li>Complete a Pre-Enrolment Review prior to enrolment</li> <li>Complete an online language, literacy and numeracy (LLN) assessment (on campus)</li> <li>Basic -intermediate level of computer skills</li> <li>Proficient in English International Students require either an <ul> <li>IELTS level of 5.5 or above with no band under 5.0 or</li> <li>TOEFL 62 (internet-based) or</li> <li>Pearson Test of English Academic (PTE) 46 or</li> <li>Cambridge English Advanced (CAE) score of 162 or</li> <li>OET score of C for each test component</li> </ul> </li> </ul> </div> </div> <div class="col-sm-6"> <h6 class="sec-headers">Domestic Students</h6> <ul class="black-square"> <li>18 years of age or older</li> <li>Satisfactorily completed Year 12 or equivalent </li> <li>Be able to read and comprehend course requirements</li> <li>Have an intermediate understanding of computers and the internet to assist with</li> <li>conducting research and complete assessments</li> </ul> </div> </div>',
    apply_form = 'https://ahsi.edu.au/cpc30220-certificate-iii-in-carpentry/',
    updated_at = NOW()
WHERE cricos_course_code = '119123A';

UPDATE courses SET
    course_description = '<p>This qualification reflects the role of workers in a range of early childhood education settings who work within the requirements of the Education and Care Services National Regulations and the National Quality Standard. They support the implementation of an approved learning framework, and support children’s well being, learning and development. Depending on the setting, educators may work under direct supervision or autonomously.</p>',
    total_course_duration = '',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="row"> <div class="col-sm-6"> <div class="width-90"> <h6 class="sec-headers">International Students</h6> <ul class="black-square"> <li>Students must be 18 years or above.</li> <li>Complete a Pre-Enrolment Review prior to enrolment</li> <li>Complete an online language, literacy and numeracy (LLN) assessment (on campus)</li> <li>Basic -intermediate level of computer skills</li> <li>Proficient in English International Students require either an <ul> <li>IELTS level of 5.5 or above with no band under 5.0 or</li> <li>TOEFL 46-49 (internet-based) or</li> <li>Pearson Test of English Academic (PTE) 42 or</li> <li>Cambridge English Advanced (CAE) score of 162 or</li> <li>OET score of C for each test component</li> </ul> </li> <!-- <li>18 years of age or older</li> <li>Completed an overseas equivalent of Year 12</li> <li>Must meet Student Visa Requirements</li> <li>Proficient in English International Students require either an <ul> <li>IELTS level of 5.5 or above with no band under 5.0 or</li> <li>TOEFL 46 (internet-based) or</li> <li>Pearson Test of English Academic (PTE) 42 or</li> <li>Cambridge English Advanced (CAE) score of 162 or</li> <li>OET score of B for each test component</li> </ul> </li> <li>Be able to read and comprehend course requirements</li> <li>Have an intermediate understanding of computers and the internet to assist with</li> <li>conducting research and complete assessments</li> --> </ul> </div> </div> <div class="col-sm-6"> <h6 class="sec-headers">Domestic Students</h6> <ul class="black-square"> <li>18 years of age or older</li> <li>Satisfactorily completed Year 12 or equivalent </li> <li>Be able to read and comprehend course requirements</li> <li>Have an intermediate understanding of computers and the internet to assist with</li> <li>conducting research and complete assessments</li> </ul> </div> </div>',
    apply_form = 'https://ahsi.edu.au/chc30121-certificate-iii-in-early-childhood-education-and-care/',
    updated_at = NOW()
WHERE cricos_course_code = '111824C';

UPDATE courses SET
    course_description = '<p>This qualification reflects the role of workers in the community and/or residential settings. You may follow individualised plans to provide person-centred support to people in need due to ageing, disability or some other reason. You will also be able to work in nursing homes and short term accommodation facilities. Work involves using discretion and judgement in relation to individual support as well as taking responsibility for own outputs. Workers have a range of factual, technical and procedural knowledge, as well as some theoretical knowledge of the concepts and practices required to provide person-centred support.</p>',
    total_course_duration = '',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="row"> <div class="col-sm-5 no-R-padding"> <img alt="" class="img-responsive img-100" src="https://ahsi.edu.au/wp-content/uploads/2019/09/course_blue_img.jpg"/> </div> <div class="col-sm-7"> <div class="course-blue-R"> <h3 class="sec-headers">Course Structure</h3> <p>This qualification consists of 15 units of competency and includes 9 core units and 6 elective units</p> <p>All students enrolled in this qualification are required to undertake work placement. Work placement provides the student with the opportunity to put into practice the skills learned in the classroom. Work placement requirements will be discussed during Student Orientation.</p> <p>AHSI will organise the work placement opportunities for students and where possible in organisations located close to their address. Should a student wish to change the work placement provider, they will need AHSI suitability approval and this can only take place after AHSI has assessed that organisation and signed a contract with the new provider.</p> <h3 class="sec-headers">Work placement requirements</h3> <ul> <li>Hold a Working with Children Certificate</li> <li>Hold a National Criminal Police Check</li> <li>Are physically, mentally and emotionally healthy to respond appropriately to personal needs</li> <li>First Aid Course certificate</li> <li>Up to date immunisation including COVID19</li> </ul> </div> </div> </div>',
    apply_form = 'https://ahsi.edu.au/chc33021-certificate-iii-in-individual-support/',
    updated_at = NOW()
WHERE cricos_course_code = '113484B';

UPDATE courses SET
    course_description = '<p>This qualification reflects the role of support workers who complete specialised tasks and functions in aged services; either in residential, home or community-based environments. To achieve this qualification, the candidate must have completed at least 120 hours of work as detailed in the Assessment Requirements of the units of competency description.</p>',
    total_course_duration = '34 weeks',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="row"> <div class="col-sm-5 no-R-padding"> <img alt="" class="img-responsive img-100" src="https://ahsi.edu.au/wp-content/uploads/2019/09/course_blue_img.jpg"/> </div> <div class="col-sm-7"> <div class="course-blue-R"> <h3 class="sec-headers">Course Structure</h3> <p>This qualification consists of 18 units of competency that is made up of 15 core units and 3 elective units</p> <p>All students enrolled in this qualification are required to undertake work placement. Work placement provides the student with the opportunity to put into practice the skills learned in the classroom. Work placement requirements will be discussed during Student Orientation.</p> <p>AHSI will organise the work placement opportunities for students and where possible in organisations located close to their address. Should a student wish to change the work placement provider, they will need AHSI suitability approval and this can only take place after AHSI has assessed that organisation and signed a contract with the new provider.</p> <h3 class="sec-headers">Work placement requirements</h3> <ul> <li>Hold a Working with Children Check</li> <li>Hold a National Criminal Police Check</li> <li>Are physically, mentally and emotionally healthy to respond appropriately to personal needs</li> <li>First Aid Course certificate</li> <li>Up to date immunisation including COVID19</li> </ul> </div> </div> </div>',
    apply_form = 'https://ahsi.edu.au/chc43015-certificate-iv-in-ageing-support/',
    updated_at = NOW()
WHERE cricos_course_code = '103564G';

UPDATE courses SET
    course_description = '<p>This qualification reflects the role of workers who provide services to clients in relation to mental health issues. You will learn how to support people with mental health issues, explore trauma informed practice, liaise with other agencies involved in the patient-care approach, empower people through the recovery model and communicate effectively with clients and other services.</p>',
    total_course_duration = '52 weeks',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="row"> <div class="col-sm-5 no-R-padding"> <img alt="" src="https://ahsi.edu.au/wp-content/uploads/2020/03/pn2ndr0g-1.jpg" style="width:100%;"/> </div> <div class="col-sm-7"> <div class="course-blue-R"> <h3 class="sec-headers">Course Structure</h3> <p>This qualification consists of 15 units of competency that is made up of 11 core units and 4 elective units</p> <p>All students enrolled in this qualification are required to undertake work placement. Work placement provides the student with the opportunity to put into practice the skills learned in the classroom. Work placement requirements will be discussed during Student Orientation.</p> <p>AHSI will organise the work placement opportunities for students and where possible in organisations located close to their address. Should a student wish to change the work placement provider, they will need AHSI suitability approval and this can only take place after AHSI has assessed that organisation and signed a contract with the new provider.</p> <h3 class="sec-headers">Work placement requirements</h3> <ul> <li>Hold a Working with Children Check</li> <li>Hold a National Criminal Police Check</li> <li>Are physically, mentally and emotionally healthy to respond appropriately to personal needs</li> <li>First Aid Course certificate</li> <li>Up to date immunisation including COVID19</li> </ul> </div> </div> </div>',
    apply_form = 'https://ahsi.edu.au/chc43315-certificate-iv-in-mental-health/',
    updated_at = NOW()
WHERE cricos_course_code = '108965E';

UPDATE courses SET
    course_description = '<p>This course will provide you with skills that will be extremely helpful in a variety of career pathways. If you are planning to embark on a career in counselling, are looking to improve your current career or want to further your own personal development our framework ensures you will be getting the most out your studies. As part of our counselling course you will become familiar with evidence-based counselling models, strategies and therapies as well as techniques from strength-based therapy.</p>',
    total_course_duration = '78 weeks',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="row"> <div class="col-sm-6"> <div class="width-90"> <h6 class="sec-headers">International Students</h6> <ul class="black-square"> <li>Students must be 18 years or above</li> <li>Have a minimum IELTS score of 5.5 or equivalent.</li> <li>Complete a Pre-Enrolment Review prior to enrolment</li> <li>Complete an online language, literacy and numeracy (LLN) assessment (on campus)</li> <li>Basic -intermediate level of computer skills</li> <li>Proficient in English International Students require either an <ul> <li>IELTS level of 5.5 or above with no band under 5.0 or</li> <li>TOEFL 46 (internet-based) or</li> <li>Pearson Test of English Academic (PTE) 42 or</li> <li>Cambridge English Advanced (CAE) score of 162 or</li> <li>OET score of B for each test component</li> </ul> </li> <!-- <li>18 years of age or older</li> <li>Completed an overseas equivalent of Year 12</li> <li>Must meet Student Visa Requirements</li> <li>Proficient in English International Students require either an <ul> <li>IELTS level of 5.5 or above with no band under 5.0 or</li> <li>TOEFL 46 (internet-based) or</li> <li>Pearson Test of English Academic (PTE) 42 or</li> <li>Cambridge English Advanced (CAE) score of 162 or</li> <li>OET score of B for each test component</li> </ul> </li> <li>Be able to read and comprehend course requirements</li> <li>Have an intermediate to advanced understanding of computers and the internet to assist with conducting research and complete assessments</li> --> </ul> </div> </div> <div class="col-sm-6"> <h6 class="sec-headers">Domestic Students</h6> <ul class="black-square"> <li>18 years of age or older</li> <li>Satisfactorily completed Year 12 or equivalent </li> <li>Be able to read and comprehend course requirements</li> <li>Have an intermediate to advanced understanding of computers and the internet to assist with conducting research and complete assessments</li> </ul> <p></p> <!-- <div class="course-blue-custom"> <h3 class="sec-headers" style="margin-bottom:1.7%;">Work Placement Requirement</h3> <ul class="black-square"> <li>Hold a Working with Children Check</li> <li>Hold a National Criminal Police Check</li> <li>Are physically, mentally and emotionally healthy to respond appropriately to personal needs</li> <li>First Aid Course certificate</li> <li>HHA Certificate (Hands Hygiene Australia) </li> <li>NDIS Course Certificate</li> <li>Up-to-date Vaccination Record</li> <h3 class="sec-headers">Course Structure</h3> <p>This qualification consists of 17 units of competency that is made up of 15 core units and 3 elective units</p> </ul> </div> --> </div> </div>',
    apply_form = 'https://ahsi.edu.au/chc51015-diploma-of-counselling/',
    updated_at = NOW()
WHERE cricos_course_code = '090797A';

UPDATE courses SET
    course_description = '<p>This qualification reflects the role of community services, case management and social housing workers involved in the managing, co-ordinating and/or delivering of person-centred services to individuals, groups and communities. Workers have specialised skills in community services and work autonomously under broad directions from senior management. Workers are usually providing direct support to individuals or groups of individuals. Workers may also have responsibility for the supervision of other workers and volunteers and/or case management, program coordination or the development of new business opportunities.</p>',
    total_course_duration = '104 weeks',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="row"> <div class="col-sm-6"> <div class="width-90"> <h6 class="sec-headers">International Students</h6> <ul class="black-square"> <li>Students must be 18 years or above Have a minimum IELTS score of 5.5 or equivalent. Complete a Pre-Enrolment Review prior to enrolment</li> <li>Complete an online language, literacy and numeracy (LLN) assessment (on campus)</li> <li>Basic -intermediate level of computer skills</li> <li>Completed education level of year 12 or equivalent</li> <li>Proficient in English International Students require either an <ul> <li>IELTS level of 5.5 or above with no band under 5.0 or</li> <li>TOEFL 46-49 (internet-based) or</li> <li>Pearson Test of English Academic (PTE) 42 or</li> <li>Cambridge English Advanced (CAE) score of 162 or</li> <li>OET score of C for each test component</li> </ul> </li> <!-- <li>18 years of age or older</li> <li>Completed an overseas equivalent of Year 12</li> <li>Must meet Student Visa Requirements</li> <li>Proficient in English International Students require either an <ul> <li>IELTS level of 5.5 or above with no band under 5.0 or</li> <li>TOEFL 46 (internet-based) or</li> <li>Pearson Test of English Academic (PTE) 42 or</li> <li>Cambridge English Advanced (CAE) score of 162 or</li> <li>OET score of B for each test component</li> </ul> </li> <li>Be able to read and comprehend course requirements</li> <li>Have an intermediate to advanced understanding of computers and the internet to assist with conducting research and complete assessments</li> --> </ul> </div> </div> <div class="col-sm-6"> <h6 class="sec-headers">Domestic Students</h6> <ul class="black-square"> <li>18 years of age or older</li> <li>Satisfactorily completed Year 12 or equivalent </li> <li>Be able to read and comprehend course requirements</li> <li>Have an intermediate to advanced understanding of computers and the internet to assist with conducting research and complete assessments</li> </ul> </div> </div>',
    apply_form = 'https://ahsi.edu.au/chc52015-diploma-of-community-services/',
    updated_at = NOW()
WHERE cricos_course_code = '089593A';

UPDATE courses SET
    course_description = '<p>This qualification reflects the role of community services, case management and social housing workers involved in the managing, coordinating and/or delivering of person-centred services to individuals, groups and communities. Workers have specialised skills in community services and work autonomously under broad directions from senior management. Workers are usually providing direct support to individuals or groups of individuals. Workers may also have responsibility for the supervision of other workers and volunteers and/or case management, program coordination or the development of new business opportunities.</p>',
    total_course_duration = '104 weeks',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="row"> <div class="col-sm-6"> <div class="width-90"> <h6 class="sec-headers">International Students</h6> <ul class="black-square"> <li>Students must be 18 years or above.</li> <li>Must meet Student Visa Requirements</li> <li>Complete a Pre-Enrolment Review prior to enrolment</li> <li>Complete an online language, literacy and numeracy (LLN) assessment (on campus)</li> <li>Basic -intermediate level of computer skills</li> <li>Completed education level of year 12 or equivalent</li> <li>Proficient in English International Students require either an <ul> <li>IELTS level of 6.0 or above with no band under 5.5 or</li> <li>TOEFL 60-78 (internet-based) or</li> <li>Pearson Test of English Academic (PTE) 52 or</li> <li>Cambridge English Advanced (CAE) score of 169 or</li> <li>OET score of C for each test component</li> </ul> </li> </ul> </div> </div> <div class="col-sm-6"> <h6 class="sec-headers">Domestic Students</h6> <ul class="black-square"> <li>18 years of age or older</li> <li>Satisfactorily completed Year 12 or equivalent </li> <li>Be able to read and comprehend course requirements</li> <li>Have an intermediate to advanced understanding of computers and the internet to assist with conducting research and complete assessments</li> </ul> </div> </div>',
    apply_form = 'https://ahsi.edu.au/chc52021-diploma-of-community-services/',
    updated_at = NOW()
WHERE cricos_course_code = '113485A';

UPDATE courses SET
    course_description = '<p></p>',
    total_course_duration = '104 weeks',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="row"> <div class="col-sm-6"> <div class="width-90"> <h6 class="sec-headers">International Students</h6> <ul class="black-square"> <li>Students must be 18 years or above.</li> <li>Must meet Student Visa Requirements</li> <li>Complete a Pre-Enrolment Review prior to enrolment</li> <li>Complete an online language, literacy and numeracy (LLN) assessment (on campus)</li> <li>Basic -intermediate level of computer skills</li> <li>Completed education level of year 12 or equivalent</li> <li>Proficient in English International Students require either an <ul> <li>IELTS level of 6.0 or above with no band under 5.5 or</li> <li>TOEFL 60-78 (internet-based) or</li> <li>Pearson Test of English Academic (PTE) 52 or</li> <li>Cambridge English Advanced (CAE) score of 169 or</li> <li>OET score of C for each test component</li> </ul> </li> </ul> </div> </div> <div class="col-sm-6"> <h6 class="sec-headers">Domestic Students</h6> <ul class="black-square"> <li>18 years of age or older</li> <li>Satisfactorily completed Year 12 or equivalent </li> <li>Be able to read and comprehend course requirements</li> <li>Have an intermediate to advanced understanding of computers and the internet to assist with conducting research and complete assessments</li> </ul> </div> </div>',
    apply_form = 'https://ahsi.edu.au/chc52025-diploma-of-community-services/',
    updated_at = NOW()
WHERE cricos_course_code = '118721J';

UPDATE courses SET
    course_description = '<p>This qualification reflects the role of early childhood educators who are responsible for designing and implementing curriculum in early childhood education and care services. In doing so they work to implement an approved learning framework within the requirements of the Education and Care Services National Regulations and the National Quality Standard.</p>',
    total_course_duration = '52 weeks',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="row"> <div class="col-sm-6"> <div class="width-90"> <h6 class="sec-headers">International Students</h6> <ul class="black-square"> <li>Students must be 18 years or above</li> <li>Students must have completed Certificate III in Early Childhood Education and Care – either CHC30113 or CHC30121</li> <li>Complete a Pre-Enrolment Review prior to enrolment</li> <li>Complete an online language, literacy and numeracy (LLN) assessment (on campus)</li> <li>Basic -intermediate level of computer skills</li> <li>Completed education level of year 12 or equivalent</li> <li>Proficient in English International Students require either an <ul> <li>IELTS level of 5.5 or above with no band under 5.0 or</li> <li>TOEFL 46-49 (internet-based) or</li> <li>Pearson Test of English Academic (PTE) 42 or</li> <li>Cambridge English Advanced (CAE) score of 162 or</li> <li>OET score of C for each test component</li> </ul> </li> <!-- <li>18 years of age or older</li> <li>Completed an overseas equivalent of Year 12</li> <li>Must meet Student Visa Requirements</li> <li>Proficient in English International Students require either an <ul> <li>IELTS level of 5.5 or above with no band under 5.0 or</li> <li>TOEFL 46 (internet-based) or</li> <li>Pearson Test of English Academic (PTE) 42 or</li> <li>Cambridge English Advanced (CAE) score of 162 or</li> <li>OET score of B for each test component</li> </ul> </li> <li>Be able to read and comprehend course requirements</li> --> </ul> </div> </div> <div class="col-sm-6"> <h6 class="sec-headers">Domestic Students</h6> <ul class="black-square"> <li>18 years of age or older</li> <li>Students must have completed Certificate III in Early Childhood Education and Care – either CHC30113 or CHC30121</li> <li>Be able to read and comprehend course requirements</li> <li>Have an intermediate to advanced understanding of computers and the internet to assist with conducting research and complete assessments</li> </ul> </div> </div>',
    apply_form = 'https://ahsi.edu.au/chc50121-diploma-of-early-childhood-education-and-care/',
    updated_at = NOW()
WHERE cricos_course_code = '111823D';

UPDATE courses SET
    course_description = '<p>This qualification reflects the role of workers who provide services to clients in relation to mental health issues. They can provide counselling, referral, advocacy and education/health promotion services. These workers are required to have high level specialist knowledge, skills and competencies especially regarding laws affecting people with mental health issues, the range of services available to them and health issues related to mental health.</p>',
    total_course_duration = '104 weeks',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="row"> <div class="col-sm-5 no-R-padding"> <img alt="" src="https://ahsi.edu.au/wp-content/uploads/2020/03/pn2ndr0g-1.jpg" style="width:100%;"/> </div> <div class="col-sm-7"> <div class="course-blue-R"> <h3 class="sec-headers">Course Structure</h3> <p>This qualification consists of 20 units of competency that is made up of 15 core units and 5 elective units</p> <p>All students enrolled in this qualification are required to undertake work placement. Work placement provides the student with the opportunity to put into practice the skills learned in the classroom. Work placement requirements will be discussed during Student Orientation.</p> <p>AHSI will organise the work placement opportunities for students and where possible in organisations located close to their address. Should a student wish to change the work placement provider, they will need AHSI suitability approval and this can only take place after AHSI has assessed that organisation and signed a contract with the new provider.</p> <h3 class="sec-headers">Work placement requirements</h3> <ul> <li>Hold a Working with Children Check</li> <li>Hold a National Criminal Police Check</li> <li>Are physically, mentally and emotionally healthy to respond appropriately to personal needs</li> <li>First Aid Course certificate</li> <li>Up to date immunisation including COVID19</li> </ul> </div> </div> </div>',
    apply_form = 'https://ahsi.edu.au/chc53315-diploma-of-mental-health/',
    updated_at = NOW()
WHERE cricos_course_code = '';

UPDATE courses SET
    course_description = '<p>Cybersecurity has seen an increasing demand for skilled workers in every industry that uses computers, networks and the Internet. Cybersecurity experts work on measures to protect the data from theft, damage or ransomware when locked. The data can cover sensitive information, personally identifiable data (PII), health information, banking or other financial details, Intellectual property and government or industry information. </p>',
    total_course_duration = '4 weeks',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="row"> <div class="col-sm-6"> <div class="width-90"> <ul class="black-square"> <li>Must be 18 years of age or above</li> <li>Complete a Language, Literacy and Numeracy assessment prior to enrolment to assist with determining eligibility and to identify learning support needs</li> <li>Completed year 10 certificate or above</li> <li>Students should come with their own laptop or tablet</li> </ul> </div> </div> </div>',
    apply_form = 'https://ahsi.edu.au/bsbss00094-cyber-security-awareness-skill-set/',
    updated_at = NOW()
WHERE cricos_course_code = '';

UPDATE courses SET
    course_description = '<p>A Diploma in IT with a Cyber security specialisation will place you in a fast growing sector that lacks qualified workers. According to AustCyber, 51,309 dedicated workers last year worked in cyber security in Australia in 2023 but 12,500 jobs were vacant. The workforce needs to grow by 66 per cent to reach the 85,000 required by 2030, or just over 4800 jobs every year. This course will give a thorough understanding of IT, of Cyber security and how to meet business needs through IT solutions. Successful completion of this course will qualify you to work in IT and cyber security environments, will allow you to plan and implement complex IT networks, install virtual computing environments, gather and analyse threat information and protect critical infrastructure. .</p>',
    total_course_duration = '76 weeks',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="row"> <div class="col-sm-6"> <div class="width-90"> <h6 class="sec-headers">International Students</h6> <ul class="black-square"> <li>Students must be 18 years or above.</li> <li>Must meet Student Visa Requirements</li> <li>Complete a Pre-Enrolment Review prior to enrolment</li> <li>Complete an online language, literacy and numeracy (LLN) assessment (on campus)</li> <li>Basic -intermediate level of computer skills</li> <li>Completed education level of year 12 or equivalent</li> <li>Proficient in English International Students require either an <ul> <li>IELTS level of 6.0 or above with no band under 5.5 or</li> <li>TOEFL 60-78 (internet-based) or</li> <li>Pearson Test of English Academic (PTE) 52 or</li> <li>Cambridge English Advanced (CAE) score of 169 or</li> <li>OET score of C for each test component</li> </ul> </li> </ul> </div> </div> <div class="col-sm-6"> <h6 class="sec-headers">Domestic Students</h6> <ul class="black-square"> <li>18 years of age or older</li> <li>Satisfactorily completed Year 12 or equivalent </li> <li>Be able to read and comprehend course requirements</li> <li>Have an intermediate to advanced understanding of computers and the internet to assist with conducting research and complete assessments</li> </ul> </div> </div>',
    apply_form = 'https://ahsi.edu.au/ict50220-diploma-of-it-specialisation-cyber-security/',
    updated_at = NOW()
WHERE cricos_course_code = '116670J';

UPDATE courses SET
    course_description = '<p>An Advanced Diploma in IT with Telecommunications and Cyber security specialisations will take you to the next level after the Diploma of IT with Cyber security specialisation. According to AustCyber, 51,309 dedicated workers last year worked in cyber security in Australia in 2023 but 12,500 jobs were vacant. The workforce needs to grow by 66 per cent to reach the 85,000 required by 2030, or just over 4800 jobs every year. This course will advance your proficiency in IT, Cyber security and how to help businesses navigate the Cyber security threats and choice of solutions to be implemented. Successful completion of this course will qualify you to work in Telecommunications, IT and cyber security environments, will allow you to produce network designs, manage network traffic, monitor cyber alerts, threats and policies, implement best practices for identity management, for Cyber risk and evaluate the organisation’s compliance with legal obligations and security standards .</p>',
    total_course_duration = '76 weeks',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="row"> <div class="col-sm-6"> <div class="width-90"> <h6 class="sec-headers">International Students</h6> <ul class="black-square"> <li>Students must be 18 years or above.</li> <li>Must meet Student Visa Requirements</li> <li>Complete a Pre-Enrolment Review prior to enrolment</li> <li>Complete an online language, literacy and numeracy (LLN) assessment (on campus)</li> <li>Basic -intermediate level of computer skills</li> <li>Completed education level of year 12 or equivalent</li> <li>Proficient in English International Students require either an <ul> <li>IELTS level of 6.0 or above with no band under 5.5 or</li> <li>TOEFL 60-78 (internet-based) or</li> <li>Pearson Test of English Academic (PTE) 52 or</li> <li>Cambridge English Advanced (CAE) score of 169 or</li> <li>OET score of C for each test component</li> </ul> </li> </ul> </div> </div> <div class="col-sm-6"> <h6 class="sec-headers">Domestic Students</h6> <ul class="black-square"> <li>18 years of age or older</li> <li>Satisfactorily completed Year 12 or equivalent </li> <li>Be able to read and comprehend course requirements</li> <li>Have an intermediate to advanced understanding of computers and the internet to assist with conducting research and complete assessments</li> </ul> </div> </div>',
    apply_form = 'https://ahsi.edu.au/ict60220-advanced-diploma-of-it-specialisation-cyber-security/',
    updated_at = NOW()
WHERE cricos_course_code = '116671H';

UPDATE courses SET
    course_description = '<p>BSB80120 is the latest version of the Graduate Diploma of Management(Learning) approved by ASQA. This qualification reflects the role of individuals who apply highly specialised knowledge and skills in the field of organisational learning and capability development. Individuals in these roles generate and evaluate complex ideas. They also initiate, design and execute major learning and development functions within an organisation. Typically, they would have full responsibility and accountability for the personal output and work of others. </p>',
    total_course_duration = '128 weeks',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="row"> <div class="col-sm-6"> <div class="width-90"> <h6 class="sec-headers">International Students</h6> <ul class="black-square"> <li>Completed a Year 12 HSC or equivalent</li> <li>Must be 18 years of age or above</li> <li>Have intermediate computer skills</li> <li>Completed a bachelor’s degree in related fields of study<br/> <b>or</b><br/> Have completed a Diploma or Advanced Diploma qualification in related fields of study AND 1-year equivalent full-time relevant workplace experience </li> <li>Complete a Pre-Enrolment Review and Language, Literacy and Numeracy assessment</li> <li>Have a minimum IELTS score of 6.0 with no band below 5.5, or equivalent</li> </ul> </div> </div> <div class="col-sm-6"> <h6 class="sec-headers">Domestic Students</h6> <ul class="black-square"> <li>Completed a Year 12 HSC or equivalent</li> <li>Must be 18 years of age or above</li> <li>Have intermediate computer skills</li> <li>Completed a bachelor’s degree in related fields of study<br/> <b>or</b><br/> Have completed a Diploma or Advanced Diploma qualification in related fields of study AND 1-year equivalent full-time relevant workplace experience </li> <li>Complete a Pre-Enrolment Review and Language, Literacy and Numeracy assessment</li> </ul> </div> </div>',
    apply_form = 'https://ahsi.edu.au/bsb80120-graduate-diploma-of-management-learning/',
    updated_at = NOW()
WHERE cricos_course_code = '105526H';

UPDATE courses SET
    course_description = '<p>There is increased opportunity for new workers to pick up skills in direct care and progress to an entry level role. This skill set is for individuals who use introductory care practices to support fully qualified carers within an aged care or disability support environment.</p>',
    total_course_duration = '3 weeks',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="row"> <div class="col-sm-6"> <h3 class="sec-headers">Units of Study</h3> <table class="cdtable-2 table table-responsive" style="margin-bottom:5%;"> <tbody><tr> <td>CHCCCS015</td> <td>Provide individualised support</td> </tr> <tr> <td>HLTINF006</td> <td>Apply basic principles and practices of infection prevention and control</td> </tr> <tr> <td>HLTWHS002</td> <td>Follow safe work practices for direct client care</td> </tr> </tbody></table> </div> <div class="col-sm-6"> <div class="pad-l5"> <h3 class="sec-headers">Career opportunities</h3> <p style="margin-bottom:3%;">Possible career opportunities relevant to this qualification include:</p> <ul class="black-square"> <li>Aged care assistant</li> <li>Disability care assistant</li> </ul> <br/> </div> </div> <p></p> </div>',
    apply_form = 'https://ahsi.edu.au/chcss00114-entry-into-care-roles-skills-set/',
    updated_at = NOW()
WHERE cricos_course_code = '';

UPDATE courses SET
    course_description = '',
    total_course_duration = '',
    offshore_tuition_fee = '',
    entry_requirements = '',
    apply_form = 'https://ahsi.edu.au/individual-units-of-competency/',
    updated_at = NOW()
WHERE cricos_course_code = '';

UPDATE courses SET
    course_description = '<p>The General English course will help students build skills in reading, writing, speaking, listening and understanding other English speakers. The course will also help them learn to communicate in English in everyday scenarios, how to adapt to the Australian life and culture and also learn the words, phrases and core knowledge to be able to confidently continue a vocational course. It also offers a foundation for sitting IELTS tests. The course is for beginners, intermediate and advanced students. Classes will be offered across 5 levels: A1 beginner, A2 elementary, B1 pre-intermediate, B1+ intermediate, and B2 upper-intermediate. </p>',
    total_course_duration = '12 weeks',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="row"> <div class="col-sm-6"> <div class="width-90"> <h6 class="sec-headers">International Students</h6> <ul class="black-square"> <li>Completed a Year 12 HSC or equivalent</li> <li>Must be 18 years of age or above</li> <li>Have intermediate computer skills</li> <li>Complete a Pre-Enrolment Review and Language, Literacy and Numeracy assessment to allow AHSI to ascertain the student’s level</li> <li>There is no minimum IELTS score</li> </ul> </div> </div> <div class="col-sm-6"> <h6 class="sec-headers">Domestic Students</h6> <ul class="black-square"> <li>This course does not apply to domestic students</li> </ul> </div> </div>',
    apply_form = 'https://ahsi.edu.au/elicos-english-courses/',
    updated_at = NOW()
WHERE cricos_course_code = '117206C';