UPDATE courses SET
    course_description = '<div class="content"> <p>This qualification reflects the role of highly skilled senior managers who use a broad range of hospitality skills combined with specialised managerial skills and substantial knowledge of industry to coordinate hospitality operations. They operate with significant autonomy and are responsible for making strategic business management decisions.</p> <p>This qualification provides a pathway to work in any hospitality industry sector and for a diversity of employers including restaurants, hotels, motels, catering operations, clubs, pubs, cafés, and coffee shops. This qualification allows for multi-skilling and for acquiring targeted skills in accommodation services, cookery, food and beverage and gaming.</p> <p>The skills in this qualification must be applied in accordance with Commonwealth and State/Territory legislation, Australian standards and industry codes of practice.</p> <p>No occupational licensing, certification or specific legislative requirements apply to this qualification at the time of publication.</p> </div>',
    total_course_duration = '104 weeks',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="content"> <p>There is no pre-requisites or specific entry requirement for this qualification. This course is available to all international students as along as they can provide the evidence that:</p> <ul> <li aria-level="1">The Student must be 18 years or older at the time of course commencement,</li> <li aria-level="1">The Student has successfully completed the Australian Year 12 (or equivalent) and,</li> <li aria-level="1">The Student have an IELTS score of at least 6.0 or PTE Academic score of 50 (or equivalent) OR Successful completion of ELICOS (English for Academic Purposes (EAP) or General English) at Advanced level.</li> <li aria-level="1">Note: Citizens of certain countries are exempted from the English proficiency requirement, please contact AIA for further details or visit the <a href="https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/student-500#Eligibility" rel="noopener" target="_blank">DOHA Website</a>.</li> </ul> </div>',
    apply_form = 'https://auscanus.edu.au/courses/advanced-diploma-of-hospitality-management/',
    updated_at = NOW()
WHERE cricos_course_code = '114256F';

UPDATE courses SET
    course_description = '<div class="content"> <p>This qualification reflects the role of individuals in a range of community settings and peoples’ homes, who provide support in a manner that empowers people with disabilities to achieve greater levels of independence, self-reliance, community participation and wellbeing. Workers promote a person-centred approach, work according to and may contribute to an individualised plan, and work without direct supervision. They may be required to supervise and/or coordinate a small team.</p> <p>The skills in this qualification must be applied in accordance with Commonwealth and State/Territory legislation, Australian standards and industry codes of practice.</p> </div>',
    total_course_duration = '52 weeks',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="content"> <p>This course is available to all international students and there are no specific entry requirements as per the qualification details or training packages. However, the student must meet the following entry requirements;</p> <ul> <li>The Student must be 18 years or older at the time of course commencement and,</li> <li>The Student have an IELTS score of at least 6.0 <strong>OR</strong> TOEFL IBT 60 <strong>OR</strong> PTE Academic score of 50 (or equivalent) <strong>OR </strong>A minimum of two (2) years of study at an AQF Level 4 or higher completed in Australia <strong>OR</strong> as per below.</li> </ul> <p>English language competence can also be demonstrated through documented evidence of any of the following:</p> <ul> <li>Minimum five (5) years of study in English in Australia, Canada, New Zealand, Britain, America, South America or Ireland.</li> <li>Completed in Australia in English a substantial component (at least 50%) of a qualification at AQF level 5 or higher.</li> <li>Completed in Australia in English Year 12 of secondary school.</li> <li>Completed a recognised ELICOS program and achieved an English Proficiency level of upper intermediate or equivalent.</li> <li>Applicants without the documented evidence to demonstrate the required English language competence may undertake the Language Literacy and Numeracy (LLN) test online to achieve a result of ACSF level 4-5 to meet Auscanus Institute of Australia’s entry requirement.</li> </ul> <p>Note: Citizens of certain countries are exempted from the English proficiency requirement, please contact AIA for further details or visit the <a href="https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/student-500#Eligibility" rel="noopener" target="_blank">DOHA Website</a>.</p> </div>',
    apply_form = 'https://auscanus.edu.au/courses/certificate-iv-in-disability-support/',
    updated_at = NOW()
WHERE cricos_course_code = '118321C';

UPDATE courses SET
    course_description = '<div class="content"> <p>This qualification reflects the role of support workers who complete specialised tasks and functions in aged services; either in residential, home or community-based environments. Workers will take responsibility for their own outputs within defined organisation guidelines and maintain quality service delivery through the development, facilitation and review of individualised service planning and delivery.</p> <p>Workers may be required to demonstrate leadership and have limited responsibility for the organisation and the quantity and quality of outputs of others within limited parameters.</p> <p>To achieve this qualification, the candidate must have completed at least 120 hours of work as detailed in the Assessment Requirements of the units of competency.</p> </div>',
    total_course_duration = '52 weeks',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="content"> <p>This course is available to all international students and there are no specific entry requirements as per the qualification details or training packages. However, the student must meet the following entry requirements;</p> <ul> <li>The Student must be 18 years or older at the time of course commencement and,</li> <li>The Student have an IELTS score of at least 6.0 <strong>OR</strong> TOEFL IBT 60 <strong>OR</strong> PTE Academic score of 50 (or equivalent) <strong>OR </strong>A minimum of two (2) years of study at an AQF Level 4 or higher completed in Australia <strong>OR</strong> as per below.</li> </ul> <p>English language competence can also be demonstrated through documented evidence of any of the following:</p> <ul> <li>Minimum five (5) years of study in English in Australia, Canada, New Zealand, Britain, America, South America or Ireland.</li> <li>Completed in Australia in English a substantial component (at least 50%) of a qualification at AQF level 5 or higher.</li> <li>Completed in Australia in English Year 12 of secondary school.</li> <li>Completed a recognised ELICOS program and achieved an English Proficiency level of upper intermediate or equivalent.</li> <li>Applicants without the documented evidence to demonstrate the required English language competence may undertake the Language Literacy and Numeracy (LLN) test online to achieve a result of ACSF level 4-5 to meet Auscanus Institute of Australia’s entry requirement.</li> </ul> <p>Note: Citizens of certain countries are exempted from the English proficiency requirement, please contact AIA for further details or visit the <a href="https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/student-500#Eligibility" rel="noopener" target="_blank">DOHA Website</a>.</p> </div>',
    apply_form = 'https://auscanus.edu.au/courses/certificate-iv-in-ageing-support/',
    updated_at = NOW()
WHERE cricos_course_code = '118320D';

UPDATE courses SET
    course_description = '<div class="content"> <p>This qualification reflects the role of individuals who apply specialised knowledge and skills, together with experience in leadership and management, across a range of enterprise and industry contexts.</p> <p>Individuals at this level use initiative and judgement to plan and implement a range of leadership and management functions, with accountability for personal and team outcomes within broad parameters.</p> <p>They use cognitive and communication skills to identify, analyse and synthesise information from a variety of sources and transfer their knowledge to others, and creative or conceptual skills to express ideas and perspectives or respond to complex problems.</p> </div>',
    total_course_duration = '78 weeks',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="content"> <p>This course is available to all international students – However, the entry to this course is limited to those who have:</p> <ul> <li>Completed a Diploma or Advanced Diploma from the BSB Training Package (current or superseded equivalent versions) or/</li> <li>Have two years equivalent full-time relevant workplace experience in an operational or leadership role in an enterprise.</li> </ul> <p>The student also must provide the evidence that:</p> <ul> <li aria-level="1">The Student must be 18 years or older at the time of course commencement,</li> <li aria-level="1">The Student has successfully completed the Australian Year 12 (or equivalent) and,</li> <li aria-level="1">The Student have an IELTS score of at least 6.0 or PTE Academic score of 50 (or equivalent) OR Successful completion of ELICOS (English for Academic Purposes (EAP) or General English) at Advanced level.</li> <li aria-level="1">Note: Citizens of certain countries are exempted from the English proficiency requirement, please contact AIA for further details or visit the <a href="https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/student-500#Eligibility" rel="noopener" target="_blank">DOHA Website</a>.</li> </ul> </div>',
    apply_form = 'https://auscanus.edu.au/courses/advanced-diploma-of-leadership-and-management/',
    updated_at = NOW()
WHERE cricos_course_code = '111216E';

UPDATE courses SET
    course_description = '<div class="content"> <p>This qualification reflects the role of individuals working as developing and emerging leaders and managers in a range of enterprise and industry contexts.</p> <p>As well as assuming responsibility for their own performance, individuals at this level are likely to provide leadership, guidance and support to others. They may also have some responsibility for organising and monitoring the output of teams.</p> <p>They apply solutions to a defined range of predictable and unpredictable problems and analyse and evaluate information from a variety of sources.</p> </div>',
    total_course_duration = '52 weeks',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="content"> <p>There is no pre-requisites or specific entry requirement for this qualification. This course is available to all international students as along as they can provide the evidence that:</p> <ul> <li aria-level="1">The Student must be 18 years or older at the time of course commencement,</li> <li aria-level="1">The Student has successfully completed the Australian Year 12 (or equivalent) and,</li> <li aria-level="1">The Student have an IELTS score of at least 6.0 or PTE Academic score of 50 (or equivalent) OR Successful completion of ELICOS (English for Academic Purposes (EAP) or General English) at Advanced level.</li> <li aria-level="1">Note: Citizens of certain countries are exempted from the English proficiency requirement, please contact AIA for further details or visit the <a href="https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/student-500#Eligibility" rel="noopener" target="_blank">DOHA Website</a>.</li> </ul> </div>',
    apply_form = 'https://auscanus.edu.au/courses/certificate-iv-in-leadership-and-management/',
    updated_at = NOW()
WHERE cricos_course_code = '111213H';

UPDATE courses SET
    course_description = '<div class="content"> <p><b>(Note: This qualification does not contain any specialisation)</b></p> <p>This qualification reflects the role of individuals in a variety of Business Services job roles. These individuals may have frontline management accountabilities.</p> <p>Individuals in these roles carry out moderately complex tasks in a specialist field of expertise that requires business operations skills. They may possess substantial experience in a range of settings but seek to further develop their skills across a wide range of business functions.</p> </div>',
    total_course_duration = '52 weeks',
    offshore_tuition_fee = '',
    entry_requirements = '',
    apply_form = 'https://auscanus.edu.au/courses/diploma-of-business/',
    updated_at = NOW()
WHERE cricos_course_code = '111214G';

UPDATE courses SET
    course_description = '<div class="content"> <p>This qualification reflects the role of individuals who apply knowledge, practical skills and experience in leadership and management across a range of enterprise and industry contexts.</p> <p>Individuals at this level display initiative and judgement in planning, organising, implementing and monitoring their own workload and the workload of others. They use communication skills to support individuals and teams to meet organisational or enterprise requirements.</p> <p>They may plan, design, apply and evaluate solutions to unpredictable problems, and identify, analyse and synthesise information from a variety of sources.</p> </div>',
    total_course_duration = '',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="content"> <p>There is no pre-requisites or specific entry requirement for this qualification. This course is available to all international students as along as they can provide the evidence that:</p> <ul> <li aria-level="1">The Student must be 18 years or older at the time of course commencement,</li> <li aria-level="1">The Student has successfully completed the Australian Year 12 (or equivalent) and,</li> <li aria-level="1">The Student have an IELTS score of at least 6.0 or PTE Academic score of 50 (or equivalent) OR Successful completion of ELICOS (English for Academic Purposes (EAP) or General English) at Advanced level.</li> <li aria-level="1">Note: Citizens of certain countries are exempted from the English proficiency requirement, please contact AIA for further details or visit the <a href="https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/student-500#Eligibility" rel="noopener" target="_blank">DOHA Website</a>.</li> </ul> </div>',
    apply_form = 'https://auscanus.edu.au/courses/diploma-of-leadership-and-management/',
    updated_at = NOW()
WHERE cricos_course_code = '111215F';

UPDATE courses SET
    course_description = '<div class="content"> <p>This qualification reflects the role of highly skilled senior operators who use a broad range of hospitality skills combined with managerial skills and sound knowledge of industry to coordinate hospitality operations. They operate independently, have responsibility for others and make a range of operational business decisions.</p> <p>This qualification provides a pathway to work in any hospitality industry sector as a departmental or small business manager. The diversity of employers includes restaurants, hotels, motels, catering operations, clubs, pubs, cafés, and coffee shops. This qualification allows for multiskilling and for acquiring targeted skills in accommodation services, cookery, food and beverage and gaming.</p> <p>The skills in this qualification must be applied in accordance with Commonwealth and State/Territory legislation, Australian standards and industry codes of practice.</p> <p>No occupational licensing, certification or specific legislative requirements apply to this qualification at the time of publication.</p> </div>',
    total_course_duration = '104 weeks',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="content"> <p>There is no pre-requisites or specific entry requirement for this qualification. This course is available to all international students as along as they can provide the evidence that:</p> <ul> <li aria-level="1">The Student must be 18 years or older at the time of course commencement,</li> <li aria-level="1">The Student has successfully completed the Australian Year 12 (or equivalent) and,</li> <li aria-level="1">The Student have an IELTS score of at least 6.0 or PTE Academic score of 50 (or equivalent) OR Successful completion of ELICOS (English for Academic Purposes (EAP) or General English) at Advanced level.</li> <li aria-level="1">Note: Citizens of certain countries are exempted from the English proficiency requirement, please contact AIA for further details or visit the <a href="https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/student-500#Eligibility" rel="noopener" target="_blank">DOHA Website</a>.</li> </ul> </div>',
    apply_form = 'https://auscanus.edu.au/courses/diploma-of-hospitality-management/',
    updated_at = NOW()
WHERE cricos_course_code = '114255G';

UPDATE courses SET
    course_description = '<div class="content"> <p>This qualification reflects the role of chefs and cooks who have a supervisory or team leading role in the kitchen. They operate independently or with limited guidance from others and use discretion to solve non-routine problems.</p> <p>This qualification provides a pathway to work in organisations such as restaurants, hotels, clubs, pubs, cafes and coffee shops, or to run a small business in these sectors. The skills in this qualification must be applied in accordance with Commonwealth and State or Territory legislation, Australian standards and industry codes of practice.</p> <p> </p> <p>No occupational licensing, certification or specific legislative requirements apply to this qualification at the time of publication.</p> </div>',
    total_course_duration = '',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="content"> <p>There is no pre-requisites or specific entry requirement for this qualification. This course is available to all international students as along as they can provide the evidence that:</p> <ul> <li aria-level="1">The Student must be 18 years or older at the time of course commencement,</li> <li aria-level="1">The Student has successfully completed the Australian Year 12 (or equivalent) and,</li> <li aria-level="1">The Student have an IELTS score of at least 6.0 or PTE Academic score of 50 (or equivalent) OR Successful completion of ELICOS (English for Academic Purposes (EAP) or General English) at Advanced level.</li> <li aria-level="1">Note: Citizens of certain countries are exempted from the English proficiency requirement, please contact AIA for further details or visit the <a href="https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/student-500#Eligibility" rel="noopener" target="_blank">DOHA Website</a>.</li> </ul> </div>',
    apply_form = 'https://auscanus.edu.au/courses/certificate-iv-in-kitchen-management/',
    updated_at = NOW()
WHERE cricos_course_code = '114254H';

UPDATE courses SET
    course_description = '<div class="content"> <p>This qualification reflects the role of cooks who use a wide range of well-developed cookery skills and sound knowledge of kitchen operations to prepare food and menu items. Using discretion and judgement, they work with some independence and under limited supervision using plans, policies and procedures to guide work activities.</p> <p>Completion of this qualification contributes to recognition as a trade cook.</p> <p>This qualification provides a pathway to work as a cook in organisations such as restaurants, hotels, clubs, pubs, cafes, and coffee shops. The skills in this qualification must be applied in accordance with Commonwealth and State or Territory legislation, Australian standards and industry codes of practice.</p> <p>No occupational licensing, certification or specific legislative requirements apply to this qualification at the time of publication.</p> </div>',
    total_course_duration = '',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="content"> <p>There is no pre-requisites or specific entry requirement for this qualification. This course is available to all international students as along as they can provide the evidence that:</p> <ul> <li aria-level="1">The Student must be 18 years or older at the time of course commencement,</li> <li aria-level="1">The Student has successfully completed the Australian Year 12 (or equivalent) and,</li> <li aria-level="1">The Student have an IELTS score of at least 6.0 or PTE Academic score of 50 (or equivalent) OR Successful completion of ELICOS (English for Academic Purposes (EAP) or General English) at Advanced level.</li> <li aria-level="1">Note: Citizens of certain countries are exempted from the English proficiency requirement, please contact AIA for further details or visit the <a href="https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/student-500#Eligibility" rel="noopener" target="_blank">DOHA Website</a>.</li> </ul> </div>',
    apply_form = 'https://auscanus.edu.au/courses/certificate-iii-in-commercial-cookery/',
    updated_at = NOW()
WHERE cricos_course_code = '114253J';

UPDATE courses SET
    course_description = '<div class="content"> <p>The General English Courses (ELICOS) is designed to help international students in Australia to develop their English language skills for social interactions and future vocational (VET) courses. These programs focus on everyday language usage, grammar and the four main language skills of listening, speaking, reading, and writing.</p> <p>The courses integrate these skills to improve students’ understanding of language forms, features, and functions. Students will also enhance their ability to analyse, respond to and create different types of texts typical of social interactions in Australia. Additionally, the courses will help students learn various learning strategies and styles.</p> <p>ELICOS courses can also be used to prepare for further study in Australia, including in the Vocational Education and Training (VET) sector, or for higher education entry requirements through English for Academic Purposes (EAP) Programs.</p> </div>',
    total_course_duration = '58 weeks',
    offshore_tuition_fee = '',
    entry_requirements = '',
    apply_form = 'https://auscanus.edu.au/courses/elicos-general-english/',
    updated_at = NOW()
WHERE cricos_course_code = '115159K';

UPDATE courses SET
    course_description = '<div class="content"> <p>The ELICOS for Academic Purpose (EAP) Program is to meet the academic skills required for the learners to gain an entry into vocational programs (VET) at Auscanus Institute of Australia or other education providers, TAFE and Universities in Australia or in tertiary education qualification.</p> <p>Each level of EAP program is for 10-week (without break), face-to-face program with 20 hours of lessons per week, covering Monday to Friday for 4 hours each day.</p> <p>AIA believes that learning is best when students are interested in the subject and the study is related to real-life situations. Students will complete projects like essays and presentations, listen to lectures, read academic texts and participate in discussions.</p> <p>Vocabulary and grammar learning will be in the context of real-world academic tasks. Language learning should be communicative and interactive, with students spending time speaking with other students to enhance their learning experience.</p> </div>',
    total_course_duration = '',
    offshore_tuition_fee = '',
    entry_requirements = '',
    apply_form = 'https://auscanus.edu.au/courses/elicos-academic-purposes/',
    updated_at = NOW()
WHERE cricos_course_code = '115160F';

UPDATE courses SET
    course_description = '<div class="content"> <p>Our Hospitality Stream (Major in Operations) package has been designed to the requirement of the Tourism, Travel and Hospitality Training Package (SIT).</p> <p>This stream includes the <em><strong><a href="https://auscanus.edu.au/courses/diploma-of-hospitality-management/" rel="noopener">Diploma of Hospitality Management</a></strong></em> and <a href="https://auscanus.edu.au/courses/advanced-diploma-of-hospitality-management/"><em><strong>Advanced Diploma of Hospitality Management</strong></em></a> program is an intensive and comprehensive course designed to equip students with essential knowledge, skills and competencies required to thrive in the dynamic field of commercial cookery and hospitality management.</p> <p>This course combines practical training, theory and industry experience to prepare students for a successful career in the culinary and hospitality</p> </div>',
    total_course_duration = '130 weeks',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="content"> <p>There is no pre-requisites or specific entry requirement for this qualification. This course is available to all international students as along as they can provide the evidence that:</p> <ul> <li>The Student must be 18 years or older at the time of course commencement,</li> <li>The Student has successfully completed the Australian Year 12 (or equivalent) and,</li> <li>The Student have an IELTS score of at least 6.0 or PTE Academic score of 50 (or equivalent) OR Successful completion of ELICOS (English for Academic Purposes (EAP) or General English) at Upper Intermediate level.</li> <li>Note: Citizens of certain countries are exempted from the English proficiency requirement, please contact AIA for further details or visit the <a href="https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/student-500#Eligibility" rel="noopener" target="_blank">DOHA Website</a>.</li> </ul> <p><strong>Additional Entry Requirements:</strong></p> <ul> <li>Students commencing this course will be required to complete the Language, Literacy and Numeracy (LLN) assessment on the orientation day. This will assist AIA to identify the student needs for any additional support during their study.</li> <li>Practical’s for students must complete their practical in AIA kitchen facilities or as advised otherwise. Where students are required to come to campus or kitchen, and use the available facilities and resources, they should be advised of the date and time of the delivery and assessment, where they are required to visit the campus and/or kitchen and complete their assessment requirements in the compliant way and in accordance with Standard 1.8 of SRTO 2015.</li> <li>AIA will make all possible efforts and aim to secure workplace arrangements for all enrolled students.</li> <li>Students must have access to working PC or laptop with a configuration suitable to meet study requirements – please seek your trainer/assessor assistance in this regard.</li> <li>Students must have basic digital literacy such as, the ability to communicate and access the information through digital technologies, social media, search engines, emails and/or basic use of Microsoft Office products and have access to the working internet.</li> <li>If the student educational qualification does not meet the AIA’s admission requirements, other factors may be considered at the discretion of AIA. For more information, please see the AIA’s Admissions Policy available in the Forms &amp; Policies page.</li> </ul> </div>',
    apply_form = 'https://auscanus.edu.au/courses/hospitality-stream-operations/',
    updated_at = NOW()
WHERE cricos_course_code = '114255G';

UPDATE courses SET
    course_description = '<div class="content"> <p>Our Leadership &amp; Management Stream (LMS) package has been designed to the requirement of the BSB Training package.</p> <p>By enrolling in our comprehensive Leadership and Management Stream (LMS) program, you can discover your leadership potential and prepare for success in the workplace. This stream includes <a href="https://auscanus.edu.au/courses/diploma-of-leadership-and-management/"><em><strong>Diploma of Leadership and Management </strong></em></a>and <a href="https://auscanus.edu.au/courses/advanced-diploma-of-leadership-and-management/"><em><strong>Advanced Diploma of Leadership and Management </strong></em></a>and the course is designed to produce self-assured and effective leaders.</p> <p>It will equip you with the knowledge and skills you need to succeed in a variety of organisational settings. You will receive instruction from experienced trainers and a hands-on learning opportunity that will prepare you for graduation and demonstrate foresight and influence as a leader. The BSB Training package’s requirements have been taken into consideration when designing this stream.</p> </div>',
    total_course_duration = '',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="content"> <p>There is no pre-requisites or specific entry requirement for this qualification. This course is available to all international students as along as they can provide the evidence that:</p> <ul> <li>The Student must be 18 years or older at the time of course commencement,</li> <li>The Student has successfully completed the Australian Year 12 (or equivalent) and,</li> <li>The Student have an IELTS score of at least 6.0 or PTE Academic score of 50 (or equivalent) OR Successful completion of ELICOS (English for Academic Purposes (EAP) or General English) at Upper Intermediate level.</li> <li>Note: Citizens of certain countries are exempted from the English proficiency requirement, please contact AIA for further details or visit the <a href="https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/student-500#Eligibility" rel="noopener" target="_blank">DOHA Website</a>.</li> </ul> <p><strong>Additional Entry Requirements:</strong></p> <ul> <li>Students commencing this course will be required to complete the Language, Literacy and Numeracy (LLN) assessment on the orientation day. This will assist AIA to identify the student needs for any additional support during their study.</li> <li>AIA will make all possible efforts and aim to secure workplace arrangements for all enrolled students.</li> <li>Students must have access to working PC or laptop with a configuration suitable to meet study requirements – please seek your trainer/assessor assistance in this regard.</li> <li>Students must have basic digital literacy such as, the ability to communicate and access the information through digital technologies, social media, search engines, emails and/or basic use of Microsoft Office products and have access to the working internet.</li> <li>If the student educational qualification does not meet the AIA’s admission requirements, other factors may be considered at the discretion of AIA. For more information, please see the AIA’s Admissions Policy available in the Forms &amp; Policies page.</li> </ul> </div>',
    apply_form = 'https://auscanus.edu.au/courses/leadership-management-stream/',
    updated_at = NOW()
WHERE cricos_course_code = '111215F';

UPDATE courses SET
    course_description = '<div class="content"> <p>The requirements of the Tourism, Travel, and Hospitality Training Package (SIT) have been incorporated into the design of our Commercial Cookery Stream Plus (CCS+) Stream/package.</p> <p>This stream includes the <em><strong><a href="https://auscanus.edu.au/courses/certificate-iii-in-commercial-cookery/" rel="noopener">Certificate III in Commercial Cookery</a>,</strong> <strong><a href="https://auscanus.edu.au/courses/certificate-iv-in-kitchen-management/" rel="noopener">Certificate IV in Kitchen Management,</a></strong></em> <em><strong><a href="https://auscanus.edu.au/courses/diploma-of-hospitality-management/" rel="noopener">Diploma of Hospitality Management</a></strong></em> and <a href="https://auscanus.edu.au/courses/advanced-diploma-of-hospitality-management/" rel="noopener" target="_blank"><em><strong>Advanced</strong> <strong>Diploma of Hospitality Management,</strong></em></a> is a rigorous and comprehensive program that aims to provide students with the fundamental knowledge, abilities and competencies they need to succeed in the ever-changing field of commercial cooking and hospitality management. Students will be well-prepared for a successful career in the culinary and hospitality industries by completing this course, which combines theory, practice, and industry experience.</p> </div>',
    total_course_duration = '130 weeks',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="content"> <p>There is no pre-requisites or specific entry requirement for this qualification. This course is available to all international students as along as they can provide the evidence that:</p> <ul> <li>The Student must be 18 years or older at the time of course commencement,</li> <li>The Student has successfully completed the Australian Year 12 (or equivalent) and,</li> <li>The Student have an IELTS score of at least 6.0 or PTE Academic score of 50 (or equivalent) OR Successful completion of ELICOS (English for Academic Purposes (EAP) or General English) at Upper Intermediate level.</li> <li>Note: Citizens of certain countries are exempted from the English proficiency requirement, please contact AIA for further details or visit the <a href="https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/student-500#Eligibility" rel="noopener" target="_blank">DOHA Website</a>.</li> </ul> <p><strong>Additional Entry Requirements:</strong></p> <ul> <li>Students commencing this course will be required to complete the Language, Literacy and Numeracy (LLN) assessment on the orientation day. This will assist AIA to identify the student needs for any additional support during their study.</li> <li>Practical’s for students must complete their practical in AIA kitchen facilities or as advised otherwise. Where students are required to come to campus or kitchen, and use the available facilities and resources, they should be advised of the date and time of the delivery and assessment, where they are required to visit the campus and/or kitchen and complete their assessment requirements in the compliant way and in accordance with Standard 1.8 of SRTO 2015.</li> <li>AIA will make all possible efforts and aim to secure workplace arrangements for all enrolled students.</li> <li>Students must have access to working PC or laptop with a configuration suitable to meet study requirements – please seek your trainer/assessor assistance in this regard.</li> <li>Students must have basic digital literacy such as, the ability to communicate and access the information through digital technologies, social media, search engines, emails and/or basic use of Microsoft Office products and have access to the working internet.</li> <li>If the student educational qualification does not meet the AIA’s admission requirements, other factors may be considered at the discretion of AIA. For more information, please see the AIA’s Admissions Policy available in the Forms &amp; Policies page.</li> </ul> </div>',
    apply_form = 'https://auscanus.edu.au/courses/commercial-cookery-stream-plus-ccs-2/',
    updated_at = NOW()
WHERE cricos_course_code = '114253J';

UPDATE courses SET
    course_description = '<div class="content"> <p>This qualification reflects the role of individuals who apply highly specialised knowledge and skills in the field of organisational learning and capability development. Individuals in these roles generate and evaluate complex ideas. They also initiate, design and execute major learning and development functions within an organisation. Typically, they would have full responsibility and accountability for the personal output and work of others.</p> <p>This qualification may apply to leaders and managers in an organisation where learning is used to build organisational capability. The job roles that relate to this qualification may also include RTO Manager and RTO Director.</p> </div>',
    total_course_duration = '52 weeks',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="content"> <p>This course is available to all international students and there are no specific entry requirements as per the qualification details or training packages. However, the student must meet the following entry requirements;</p> <ul> <li>Must completed the equivalent of any Australian Diploma or Higher <strong>OR/</strong></li> <li>Have completed Australian Year 12 or equivalent (minimum) with two years (2 Years) equivalent full-time relevant workplace experience in an operational or leadership role in an enterprise.</li> </ul> <p>The student also must provide the evidence that:</p> <ul> <li>The Student must be 18 years or older at the time of course commencement and,</li> <li>The Student have an IELTS score of at least 6.0 <strong>OR</strong> TOEFL IBT 60 <strong>OR</strong> PTE Academic score of 50 (or equivalent) – <strong>OR</strong> as per below.</li> </ul> <p>English language competence can also be demonstrated through documented evidence of any of the following:</p> <ul> <li>Minimum five (5) years of study in English in Australia, Canada, New Zealand, Britain, America, South America or Ireland.</li> <li>Completed in Australia in English a substantial component (at least 50%) of a qualification at AQF level 5 or higher.</li> <li>Completed in Australia in English Year 12 of secondary school.</li> <li>Completed a recognised ELICOS program and achieved an English Proficiency level of upper intermediate or equivalent.</li> <li>Applicants without the documented evidence to demonstrate the required English language competence may undertake the Language Literacy and Numeracy (LLN) test online to achieve a result of ACSF level 4-5 to meet Auscanus Institute of Australia’s entry requirement.</li> </ul> <p>Note: Citizens of certain countries are exempted from the English proficiency requirement, please contact AIA for further details or visit the <a href="https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/student-500#Eligibility" rel="noopener" target="_blank">DOHA Website</a>.</p> </div>',
    apply_form = 'https://auscanus.edu.au/courses/graduate-diploma-of-management-learning/',
    updated_at = NOW()
WHERE cricos_course_code = '117128A';

UPDATE courses SET
    course_description = '<div class="content"> <p>This qualification reflects the role of community services workers involved in the delivery, management and coordination of person-centred services to individuals, groups, and communities.</p> <p>At this level, workers have specialised skills in community services and work autonomously within their scope of practice under broad directions from senior management.</p> <p>Workers support people to make change in their lives to improve personal and social wellbeing and may also have responsibility for the supervision of other workers and volunteers. They may also undertake case management and program coordination.</p> <p>To achieve this qualification, the candidate must have completed at least 200 hours of work as detailed in the Assessment Requirements of units of competency. The skills in this qualification must be applied in accordance with Commonwealth and State or Territory legislation, Australian standards and industry codes of practice.</p> </div>',
    total_course_duration = '104 weeks',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="content"> <p>This course is available to all international students and there are no specific entry requirements as per the qualification details or training packages. However, the student must meet the following entry requirements;</p> <ul> <li>The Student must be 18 years or older at the time of course commencement and,</li> <li>The Student have an IELTS score of at least 6.0 <strong>OR</strong> TOEFL IBT 60 <strong>OR</strong> PTE Academic score of 50 (or equivalent) <strong>OR </strong>A minimum of two (2) years of study at an AQF Level 4 or higher completed in Australia <strong>OR</strong> as per below.</li> </ul> <p>English language competence can also be demonstrated through documented evidence of any of the following:</p> <ul> <li>Minimum five (5) years of study in English in Australia, Canada, New Zealand, Britain, America, South America or Ireland.</li> <li>Completed in Australia in English a substantial component (at least 50%) of a qualification at AQF level 5 or higher.</li> <li>Completed in Australia in English Year 12 of secondary school.</li> <li>Completed a recognised ELICOS program and achieved an English Proficiency level of upper intermediate or equivalent.</li> <li>Applicants without the documented evidence to demonstrate the required English language competence may undertake the Language Literacy and Numeracy (LLN) test online to achieve a result of ACSF level 4-5 to meet Auscanus Institute of Australia’s entry requirement.</li> </ul> <p>Note: Citizens of certain countries are exempted from the English proficiency requirement, please contact AIA for further details or visit the <a href="https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/student-500#Eligibility" rel="noopener" target="_blank">DOHA Website</a>.</p> </div>',
    apply_form = 'https://auscanus.edu.au/courses/diploma-of-community-services/',
    updated_at = NOW()
WHERE cricos_course_code = '118319H';

UPDATE courses SET
    course_description = '<div class="content"> <p>This qualification reflects the role of individuals in the community, home or residential care setting who work under supervision and delegation as a part of a multi-disciplinary team, following an individualised plan to provide person-centred support to people who may require support due to ageing, disability or some other reason.</p> <p>These individuals take responsibility for their own outputs within the scope of their job role and delegation. Workers have a range of factual, technical and procedural knowledge, as well as some theoretical knowledge of the concepts and practices required to provide person-centred support.</p> <p>The skills in this qualification must be applied in accordance with Commonwealth and State/Territory legislation, Australian standards and industry codes of practice.</p> <p>To achieve this qualification, the candidate must have completed at least 120 hours of work as detailed in the Assessment Requirements of the units of competency</p> </div>',
    total_course_duration = '52 weeks',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="content"> <p>This course is available to all international students and there are no specific entry requirements as per the qualification details or training packages. However, the student must meet the following entry requirements;</p> <ul> <li>The Student must be 18 years or older at the time of course commencement and,</li> <li>The Student have an IELTS score of at least 6.0 <strong>OR</strong> TOEFL IBT 60 <strong>OR</strong> PTE Academic score of 50 (or equivalent) <strong>OR </strong>A minimum of two (2) years of study at an AQF Level 4 or higher completed in Australia <strong>OR</strong> as per below.</li> </ul> <p>English language competence can also be demonstrated through documented evidence of any of the following:</p> <ul> <li>Minimum five (5) years of study in English in Australia, Canada, New Zealand, Britain, America, South America or Ireland.</li> <li>Completed in Australia in English a substantial component (at least 50%) of a qualification at AQF level 5 or higher.</li> <li>Completed in Australia in English Year 12 of secondary school.</li> <li>Completed a recognised ELICOS program and achieved an English Proficiency level of upper intermediate or equivalent.</li> <li>Applicants without the documented evidence to demonstrate the required English language competence may undertake the Language Literacy and Numeracy (LLN) test online to achieve a result of ACSF level 4-5 to meet Auscanus Institute of Australia’s entry requirement.</li> </ul> <p>Note: Citizens of certain countries are exempted from the English proficiency requirement, please contact AIA for further details or visit the <a href="https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/student-500#Eligibility" rel="noopener" target="_blank">DOHA Website</a>.</p> </div>',
    apply_form = 'https://auscanus.edu.au/courses/certificate-iii-in-individual-support/',
    updated_at = NOW()
WHERE cricos_course_code = '118318J';