UPDATE courses SET
    course_description = '<p class="kt-adv-heading_3dcf2b-33 wp-block-kadence-advancedheading" data-kb-block="kb-adv-heading_3dcf2b-33"> </p> <p>This qualification reflects the role of individuals who apply knowledge, practical skills and experience in leadership and management across a range of enterprise and industry contexts.</p> <p>Individuals at this level display initiative and judgement in planning, organising, implementing, and monitoring their own workload and the workload of others. They use communication skills to support individuals and teams to meet organisational or enterprise requirements.</p> <p>They may plan, design, apply and evaluate solutions to unpredictable problems, and identify, analyse, and synthesise information from a variety of sources.<br/> The latest release of the qualification and packaging rules can be found at the following link:</p> <p><a href="https://training.gov.au/Training/Details/BSB50420">https://training.gov.au/Training/Details/BSB50420</a></p> <p></p>',
    total_course_duration = '',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="kt-accordion-panel-inner"> <p>Canberra Institute of Education and Technology has the following entry requirements:</p> <p>You must:</p> <ul> <li aria-level="1">be at least 18 years of age.</li> <li aria-level="1">participate in a course entry interview to determine suitability for the course and student needs. The course entry interview will also assess whether students can use digital technologies.</li> <li aria-level="1">have sufficient language, literacy and numeracy skills as tested through a language, literacy and numeracy assessment. Students will need to achieve ACSF level 4 for reading, writing, numeracy and oral communication to enter the course.</li> <li aria-level="1">have an IELTS* score of 6.0 (test results must be no more than 2 years old). English language competence can also be demonstrated through documented evidence of any of the following: <ul style="list-style-type: circle;"> <li aria-level="1">educated for 5 years in an English-speaking country; or</li> <li aria-level="1">successful completion of an English Placement Test at IELTS level 6.0.</li> </ul> </li> </ul> <p>*Note that other English language tests such as PTE and TOEFL can be accepted. Students are required to provide their results so that it can be confirmed they are equivalent to IELTS 6.0.</p> <p>Domestic students must have sufficient language, literacy and numeracy skills as tested through a language, literacy and numeracy assessment. Students will need to achieve ACSF level 3 for reading, writing, numeracy and oral communication to enter the course.</p> </div>',
    apply_form = 'https://ciet.edu.au/course/bsb50420-diploma-of-leadership-and-management/',
    updated_at = NOW()
WHERE cricos_course_code = '110097D';

UPDATE courses SET
    course_description = '<p class="kt-adv-heading_3dcf2b-33 wp-block-kadence-advancedheading" data-kb-block="kb-adv-heading_3dcf2b-33"> </p> <p>This qualification reflects the role of individuals who apply specialised knowledge and skills, together with experience in leadership and management, across a range of enterprise and industry contexts.</p> <p>Individuals at this level use initiative and judgement to plan and implement a range of leadership and management functions, with accountability for personal and team outcomes within broad parameters.</p> <p>They use cognitive and communication skills to identify, analyse and synthesise information from a variety of sources and transfer their knowledge to others, and creative or conceptual skills to express ideas and perspectives or respond to complex problems.</p> <p>The latest release of the qualification and packaging rules can be found at the following link:</p> <p><a href="https://training.gov.au/Training/Details/BSB60420">https://training.gov.au/Training/Details/BSB60420</a></p> <p></p>',
    total_course_duration = '',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="kt-accordion-panel-inner"> <p>Canberra Institute of Education and Technology has the following entry requirements:</p> <p>You must:</p> <ul> <li aria-level="1">be at least 18 years of age.</li> <li aria-level="1">participate in a course entry interview to determine suitability for the course and student needs. The course entry interview will also assess whether students can use digital technologies.</li> <li aria-level="1">have sufficient language, literacy and numeracy skills as tested through a language, literacy and numeracy assessment. Students will need to achieve ACSF level 4 for reading, writing, numeracy and oral communication to enter the course.</li> <li aria-level="1">have an IELTS* score of 6.0 (test results must be no more than 2 years old). English language competence can also be demonstrated through documented evidence of any of the following: <ul style="list-style-type: circle;"> <li aria-level="1">educated for 5 years in an English-speaking country; or</li> <li aria-level="1">successful completion of an English Placement Test at IELTS level 6.0.</li> </ul> </li> </ul> <p>*Note that other English language tests such as PTE and TOEFL can be accepted. Students are required to provide their results so that it can be confirmed they are equivalent to IELTS 6.0.</p> <p>Domestic students must have sufficient language, literacy and numeracy skills as tested through a language, literacy and numeracy assessment. Students will need to achieve ACSF level 3 for reading, writing, numeracy and oral communication to enter the course.</p> </div>',
    apply_form = 'https://ciet.edu.au/course/bsb60420-advanced-diploma-of-leadership-and-management/',
    updated_at = NOW()
WHERE cricos_course_code = '110098C';

UPDATE courses SET
    course_description = '<p class="kt-adv-heading_3dcf2b-33 wp-block-kadence-advancedheading" data-kb-block="kb-adv-heading_3dcf2b-33"> </p> <p><span style="font-weight: 400;">This qualification reflects the role of individuals who apply highly specialised knowledge and skills in the field of organisational learning and capability development. </span></p> <p><span style="font-weight: 400;">Individuals in these roles generate and evaluate complex ideas. They also initiate, design and execute major learning and development functions within an organisation. Typically, they would have full responsibility and accountability for the personal output and work of others.</span></p> <p><span style="font-weight: 400;">This qualification may apply to leaders and managers in an organisation where learning is used to build organisational capability. The job roles that relate to this qualification may also include RTO Manager and RTO Director.</span></p> <p><span style="font-weight: 400;">The latest release of the qualification and packaging rules can be found at the following link:</span></p> <p><a href="https://training.gov.au/Training/Details/BSB80120"><span style="font-weight: 400;">https://training.gov.au/Training/Details/BSB80120</span></a><span style="font-weight: 400;"> </span></p> <p></p>',
    total_course_duration = '',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="kt-accordion-panel-inner"> <p>Canberra Institute of Education and Technology has the following entry requirements:</p> <p>You must:</p> <ul> <li aria-level="1">be at least 18 years of age.</li> <li aria-level="1">participate in a course entry interview to determine suitability for the course and student needs. The course entry interview will also assess whether students can use digital technologies.</li> <li aria-level="1">have sufficient language, literacy and numeracy skills as tested through a language, literacy and numeracy assessment. Students will need to achieve ACSF level 4 for reading, writing, numeracy and oral communication to enter the course.</li> <li aria-level="1">have an IELTS* score of 6.0 (test results must be no more than 2 years old). English language competence can also be demonstrated through documented evidence of any of the following: <ul style="list-style-type: circle;"> <li aria-level="1">educated for 5 years in an English-speaking country; or</li> <li aria-level="1">successful completion of an English Placement Test at IELTS level 6.0.</li> </ul> </li> </ul> <p>*Note that other English language tests such as PTE and TOEFL can be accepted. Students are required to provide their results so that it can be confirmed they are equivalent to IELTS 6.0.</p> <p>Domestic students must have sufficient language, literacy and numeracy skills as tested through a language, literacy and numeracy assessment. Students will need to achieve ACSF level 3 for reading, writing, numeracy and oral communication to enter the course.</p> </div>',
    apply_form = 'https://ciet.edu.au/course/bsb80120-graduate-diploma-of-management-learning/',
    updated_at = NOW()
WHERE cricos_course_code = '110099B';

UPDATE courses SET
    course_description = '<p class="kt-adv-heading_3dcf2b-33 wp-block-kadence-advancedheading" data-kb-block="kb-adv-heading_3dcf2b-33"> </p> <p>This qualification reflects the role of individuals in the community, home or residential care setting who work under supervision and delegation as a part of a multi-disciplinary team, following an individualised plan to provide person-centred support to people who may require support due to ageing, disability or some other reason.</p> <p> These individuals take responsibility for their own outputs within the scope of their job role and delegation. Workers have a range of factual, technical and procedural knowledge, as well as some theoretical knowledge of the concepts and practices required to provide person-centred support.</p> <p> The skills in this qualification must be applied in accordance with Commonwealth and State/Territory legislation, Australian standards and industry codes of practice.</p> <p>To achieve this qualification, the candidate must have completed at least 120 hours of work as detailed in the Assessment Requirements of the units of competency.</p> <p>No licensing, legislative, regulatory or certification requirements apply to this qualification at the time of publication.</p> <p><a href="https://training.gov.au/training/details/CHC33021">https://training.gov.au/training/details/CHC33021</a></p> <p></p>',
    total_course_duration = '',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="kt-accordion-panel-inner"> <p>Canberra Institute of Education and Technology has the following entry requirements:</p> <p>You must:</p> <ul> <li aria-level="1">be at least 18 years of age.</li> <li aria-level="1">participate in a course entry interview to determine suitability for the course and student needs. The course entry interview will also assess whether students can use digital technologies.</li> <li aria-level="1">have sufficient language, literacy and numeracy skills as tested through a language, literacy and numeracy assessment. Students will need to achieve ACSF level 4 for reading, writing, numeracy and oral communication to enter the course.</li> <li aria-level="1">have an IELTS* score of 6.0 (test results must be no more than 2 years old). English language competence can also be demonstrated through documented evidence of any of the following: <ul style="list-style-type: circle;"> <li aria-level="1">educated for 5 years in an English-speaking country; or</li> <li aria-level="1">successful completion of an English Placement Test at IELTS level 6.0.</li> </ul> </li> </ul> <p>*Note that other English language tests such as PTE and TOEFL can be accepted. Students are required to provide their results so that it can be confirmed they are equivalent to IELTS 6.0.</p> <p>Domestic students must have sufficient language, literacy and numeracy skills as tested through a language, literacy and numeracy assessment. Students will need to achieve ACSF level 3 for reading, writing, numeracy and oral communication to enter the course.</p> </div>',
    apply_form = 'https://ciet.edu.au/course/chc33021-certificate-iii-in-individual-support/',
    updated_at = NOW()
WHERE cricos_course_code = '117674H';

UPDATE courses SET
    course_description = '<p class="kt-adv-heading_3dcf2b-33 wp-block-kadence-advancedheading" data-kb-block="kb-adv-heading_3dcf2b-33"> </p> <p>This qualification reflects the role of individuals in a range of community settings and peoples’ homes, who provide support in a manner that empowers people with disabilities to achieve greater levels of independence, self-reliance, community participation and wellbeing. Workers promote a person-centred approach, work according to and may contribute to an individualised plan, and work without direct supervision. They may be required to supervise and/or coordinate a small team.</p> <p>The skills in this qualification must be applied in accordance with Commonwealth and State/Territory legislation, Australian standards and industry codes of practice.</p> <p>No licensing, legislative, regulatory or certification requirements apply to this qualification at the time of publication.</p> <p><a href="https://training.gov.au/training/details/CHC43121">https://training.gov.au/training/details/CHC43121</a></p> <p></p>',
    total_course_duration = '',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="kt-accordion-panel-inner"> <p>Canberra Institute of Education and Technology has the following entry requirements:</p> <p>You must:</p> <ul> <li aria-level="1">be at least 18 years of age.</li> <li aria-level="1">participate in a course entry interview to determine suitability for the course and student needs. The course entry interview will also assess whether students can use digital technologies.</li> <li aria-level="1">have sufficient language, literacy and numeracy skills as tested through a language, literacy and numeracy assessment. Students will need to achieve ACSF level 4 for reading, writing, numeracy and oral communication to enter the course.</li> <li aria-level="1">have an IELTS* score of 6.0 (test results must be no more than 2 years old). English language competence can also be demonstrated through documented evidence of any of the following: <ul style="list-style-type: circle;"> <li aria-level="1">educated for 5 years in an English-speaking country; or</li> <li aria-level="1">successful completion of an English Placement Test at IELTS level 6.0.</li> </ul> </li> </ul> <p>*Note that other English language tests such as PTE and TOEFL can be accepted. Students are required to provide their results so that it can be confirmed they are equivalent to IELTS 6.0.</p> <p>Domestic students must have sufficient language, literacy and numeracy skills as tested through a language, literacy and numeracy assessment. Students will need to achieve ACSF level 3 for reading, writing, numeracy and oral communication to enter the course.</p> </div>',
    apply_form = 'https://ciet.edu.au/course/chc43121-certificate-iv-in-disability-support/',
    updated_at = NOW()
WHERE cricos_course_code = '117675G';

UPDATE courses SET
    course_description = '<p class="kt-adv-heading_3dcf2b-33 wp-block-kadence-advancedheading" data-kb-block="kb-adv-heading_3dcf2b-33"> </p> <p><span style="font-weight: 400;">This qualification reflects the role of community services workers involved in the delivery, management and coordination of person-centred services to individuals, groups, and communities.</span></p> <p><span style="font-weight: 400;">At this level, workers have specialised skills in community services and work autonomously within their scope of practice under broad directions from senior management.</span></p> <p><span style="font-weight: 400;">Workers support people to make change in their lives to improve personal and social wellbeing and may also have responsibility for the supervision of other workers and volunteers. They may also undertake case management and program coordination.</span></p> <p><span style="font-weight: 400;">To achieve this qualification, the candidate must have completed at least 200 hours of work as detailed in the Assessment Requirements of units of competency. (Radix Education has schedule 220 hours of work placement; please refer to the detailed training and assessment schedule)</span></p> <p><span style="font-weight: 400;">The skills in this qualification must be applied in accordance with Commonwealth and State or Territory legislation, Australian standards and industry codes of practice.</span></p> <p><span style="font-weight: 400;">No occupational licensing, certification or specific legislative requirements apply to this qualification at the time of publication.</span></p> <p><a href="https://training.gov.au/training/details/CHC52025">https://training.gov.au/training/details/CHC52025</a></p> <p></p>',
    total_course_duration = '',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="kt-accordion-panel-inner"> <p>Canberra Institute of Education and Technology has the following entry requirements:</p> <p>You must:</p> <ul> <li aria-level="1">be at least 18 years of age.</li> <li aria-level="1">participate in a course entry interview to determine suitability for the course and student needs. The course entry interview will also assess whether students can use digital technologies.</li> <li aria-level="1">have sufficient language, literacy and numeracy skills as tested through a language, literacy and numeracy assessment. Students will need to achieve ACSF level 4 for reading, writing, numeracy and oral communication to enter the course.</li> <li aria-level="1">have an IELTS* score of 6.0 (test results must be no more than 2 years old). English language competence can also be demonstrated through documented evidence of any of the following: <ul style="list-style-type: circle;"> <li aria-level="1">educated for 5 years in an English-speaking country; or</li> <li aria-level="1">successful completion of an English Placement Test at IELTS level 6.0.</li> </ul> </li> </ul> <p>*Note that other English language tests such as PTE and TOEFL can be accepted. Students are required to provide their results so that it can be confirmed they are equivalent to IELTS 6.0.</p> <p>Domestic students must have sufficient language, literacy and numeracy skills as tested through a language, literacy and numeracy assessment. Students will need to achieve ACSF level 3 for reading, writing, numeracy and oral communication to enter the course.</p> </div>',
    apply_form = 'https://ciet.edu.au/course/chc52025-diploma-of-community-services/',
    updated_at = NOW()
WHERE cricos_course_code = '118791F';

UPDATE courses SET
    course_description = '<p class="kt-adv-heading_3dcf2b-33 wp-block-kadence-advancedheading" data-kb-block="kb-adv-heading_3dcf2b-33"> </p> <p><span style="font-weight: 400;">This is a trade qualification for carpenters in residential and commercial workplaces. It includes setting out, manufacturing, constructing, assembling, installing and repairing products made using timber and non-timber materials.</span></p> <p><span style="font-weight: 400;">Occupational titles may include:</span></p> <p><span style="font-weight: 400;">State and territory jurisdictions may have different licensing, legislative, regulatory or certification requirements. Relevant state and territory regulatory authorities should be consulted to confirm those requirements.</span></p> <p><span style="font-weight: 400;">Completion of the general construction induction training program, specified in the Safe Work Australia model Code of Practice: Construction Work, is required by anyone carrying out construction work. Achievement of CPCCWHS1001 Prepare to work safely in the construction industry meets this requirement.</span></p> <p><span style="font-weight: 400;">This qualification is suitable for an Australian apprenticeship pathway.</span></p> <p><a href="https://training.gov.au/training/details/CPC30220">https://training.gov.au/training/details/CPC30220</a></p> <p></p>',
    total_course_duration = '',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="kt-accordion-panel-inner"> <p>Canberra Institute of Education and Technology has the following entry requirements:</p> <p>You must:</p> <ul> <li aria-level="1">be at least 18 years of age.</li> <li aria-level="1">participate in a course entry interview to determine suitability for the course and student needs. The course entry interview will also assess whether students can use digital technologies.</li> <li aria-level="1">have sufficient language, literacy and numeracy skills as tested through a language, literacy and numeracy assessment. Students will need to achieve ACSF level 4 for reading, writing, numeracy and oral communication to enter the course.</li> <li aria-level="1">have an IELTS* score of 6.0 (test results must be no more than 2 years old). English language competence can also be demonstrated through documented evidence of any of the following: <ul style="list-style-type: circle;"> <li aria-level="1">educated for 5 years in an English-speaking country; or</li> <li aria-level="1">successful completion of an English Placement Test at IELTS level 6.0.</li> </ul> </li> </ul> <p>*Note that other English language tests such as PTE and TOEFL can be accepted. Students are required to provide their results so that it can be confirmed they are equivalent to IELTS 6.0.</p> <p>Domestic students must have sufficient language, literacy and numeracy skills as tested through a language, literacy and numeracy assessment. Students will need to achieve ACSF level 3 for reading, writing, numeracy and oral communication to enter the course.</p> </div>',
    apply_form = 'https://ciet.edu.au/course/cpc30220-certificate-iii-in-carpentry/',
    updated_at = NOW()
WHERE cricos_course_code = '110897E';

UPDATE courses SET
    course_description = '<p class="kt-adv-heading_3dcf2b-33 wp-block-kadence-advancedheading" data-kb-block="kb-adv-heading_3dcf2b-33"> </p> <p>This qualification provides a trade outcome in painting and decorating for residential and commercial construction work.</p> <p>Occupational titles may include:</p> <p>Licensing, legislative and regulatory or certification requirements for painting and decorating work differ between States and Territories.</p> <p>Please consult with the relevant regulatory authority. This qualification is suitable for an Australian Apprenticeship pathway.</p> <p>Completion of the general construction induction training program, specified in the Safe Work Australia model Code of Practice: Construction Work, is required by anyone carrying out construction work. Achievement of CPCCWHS1001 Prepare to work safely in the construction industry meets this requirement.</p> <p><a href="https://training.gov.au/training/details/CPC30620">https://training.gov.au/training/details/CPC30620</a></p> <p></p>',
    total_course_duration = '',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="kt-accordion-panel-inner"> <p>Canberra Institute of Education and Technology has the following entry requirements:</p> <p>You must:</p> <ul> <li aria-level="1">be at least 18 years of age.</li> <li aria-level="1">participate in a course entry interview to determine suitability for the course and student needs. The course entry interview will also assess whether students can use digital technologies.</li> <li aria-level="1">have sufficient language, literacy and numeracy skills as tested through a language, literacy and numeracy assessment. Students will need to achieve ACSF level 4 for reading, writing, numeracy and oral communication to enter the course.</li> <li aria-level="1">have an IELTS* score of 6.0 (test results must be no more than 2 years old). English language competence can also be demonstrated through documented evidence of any of the following: <ul style="list-style-type: circle;"> <li aria-level="1">educated for 5 years in an English-speaking country; or</li> <li aria-level="1">successful completion of an English Placement Test at IELTS level 6.0.</li> </ul> </li> </ul> <p>*Note that other English language tests such as PTE and TOEFL can be accepted. Students are required to provide their results so that it can be confirmed they are equivalent to IELTS 6.0.</p> <p>Domestic students must have sufficient language, literacy and numeracy skills as tested through a language, literacy and numeracy assessment. Students will need to achieve ACSF level 3 for reading, writing, numeracy and oral communication to enter the course.</p> </div>',
    apply_form = 'https://ciet.edu.au/course/cpc30620-certificate-iii-in-painting-and-decorating/',
    updated_at = NOW()
WHERE cricos_course_code = '117677E';

UPDATE courses SET
    course_description = '<p class="kt-adv-heading_3dcf2b-33 wp-block-kadence-advancedheading" data-kb-block="kb-adv-heading_3dcf2b-33"> </p> <p><span style="font-weight: 400;">This qualification reflects the trade qualified role of a bricklayer, block layer or paver who may have responsibility for undertaking heritage bricklaying, refractory bricklaying, bricklaying, block laying and paving work in residential, industrial and commercial contexts, in both existing and new constructions. Occupational titles could include:</span></p> <p><span style="font-weight: 400;">The bricklaying, block laying and paving industry strongly affirms that training and assessment leading to recognition of skills must be undertaken in a real or closely simulated workplace environment and this qualification requires all units of competency to be delivered and assessed in this context.</span></p> <p><span style="font-weight: 400;">Licensing, legislative, regulatory and certification requirements vary between states. Relevant state and territory regulatory authorities should be consulted to confirm those requirements.</span></p> <p><span style="font-weight: 400;">Completion of the general construction induction training program, specified in the Safe Work Australia model Code of Practice: Construction Work, is required by anyone carrying out construction work. Achievement of CPCCWHS1001 Prepare to work safely in the construction industry meets this requirement.</span></p> <p><a href="https://training.gov.au/training/details/CPC33020">https://training.gov.au/training/details/CPC33020</a></p> <p></p>',
    total_course_duration = '',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="kt-accordion-panel-inner"> <p>Canberra Institute of Education and Technology has the following entry requirements:</p> <p>You must:</p> <ul> <li aria-level="1">be at least 18 years of age.</li> <li aria-level="1">participate in a course entry interview to determine suitability for the course and student needs. The course entry interview will also assess whether students can use digital technologies.</li> <li aria-level="1">have sufficient language, literacy and numeracy skills as tested through a language, literacy and numeracy assessment. Students will need to achieve ACSF level 4 for reading, writing, numeracy and oral communication to enter the course.</li> <li aria-level="1">have an IELTS* score of 6.0 (test results must be no more than 2 years old). English language competence can also be demonstrated through documented evidence of any of the following: <ul style="list-style-type: circle;"> <li aria-level="1">educated for 5 years in an English-speaking country; or</li> <li aria-level="1">successful completion of an English Placement Test at IELTS level 6.0.</li> </ul> </li> </ul> <p>*Note that other English language tests such as PTE and TOEFL can be accepted. Students are required to provide their results so that it can be confirmed they are equivalent to IELTS 6.0.</p> <p>Domestic students must have sufficient language, literacy and numeracy skills as tested through a language, literacy and numeracy assessment. Students will need to achieve ACSF level 3 for reading, writing, numeracy and oral communication to enter the course.</p> </div>',
    apply_form = 'https://ciet.edu.au/course/cpc33020-certificate-iii-in-bricklaying-and-blocklaying/',
    updated_at = NOW()
WHERE cricos_course_code = '110898D';

UPDATE courses SET
    course_description = '<p class="kt-adv-heading_3dcf2b-33 wp-block-kadence-advancedheading" data-kb-block="kb-adv-heading_3dcf2b-33"> </p> <p><span style="font-weight: 400;">This qualification reflects the role of builders, site managers and managers of small to medium-sized building businesses who apply knowledge of structural principles, codes, standards and legal requirements to Class 1 and 10, to a maximum of two storeys and Class 2 to 9 Type C constructions, and who plan and supervise safe building and construction work, prepare and administer contracts, and who apply quality principles to building and construction projects.</span></p> <p><span style="font-weight: 400;">Building relates to construction and Site Management is about managing the factors around construction, such as the deployment of crews with specialised skills (including builders), product compliance, deployment of contract specialised skills, weather and site location.</span></p> <p><span style="font-weight: 400;">Occupational titles depending on packaging options selected may include:</span></p> <p><span style="font-weight: 400;">The qualification is designed to enable two specialised occupational outcome pathways depending on elective options which will be reflected as:</span></p> <p><span style="font-weight: 400;">Completion of the general construction induction training program specified by the model Code of Practice for Construction Work is required for any person who is to carry out construction work. Achievement of unit CPCCWHS1001 Prepare to work safely in the construction industry meets this requirement.</span></p> <p><span style="font-weight: 400;">Builder and Site Supervisor licensing varies across States and Territories and requirements additional to the attainment of this qualification may be required.</span></p> <p>The latest release of the qualification and packaging rules can be found at the following link:</p> <p><a draggable="false" href="https://training.gov.au/Training/Details/CPC40120" rel="noopener" target="_blank">https://training.gov.au/Training/Details/CPC40120</a></p> <p></p>',
    total_course_duration = '',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="kt-accordion-panel-inner"> <p>Canberra Institute of Education and Technology has the following entry requirements:</p> <p>You must:</p> <ul> <li aria-level="1">be at least 18 years of age.</li> <li aria-level="1">participate in a course entry interview to determine suitability for the course and student needs. The course entry interview will also assess whether students can use digital technologies.</li> <li aria-level="1">have sufficient language, literacy and numeracy skills as tested through a language, literacy and numeracy assessment. Students will need to achieve ACSF level 4 for reading, writing, numeracy and oral communication to enter the course.</li> <li aria-level="1">have an IELTS* score of 6.0 (test results must be no more than 2 years old). English language competence can also be demonstrated through documented evidence of any of the following: <ul style="list-style-type: circle;"> <li aria-level="1">educated for 5 years in an English-speaking country; or</li> <li aria-level="1">successful completion of an English Placement Test at IELTS level 6.0.</li> </ul> </li> </ul> <p>*Note that other English language tests such as PTE and TOEFL can be accepted. Students are required to provide their results so that it can be confirmed they are equivalent to IELTS 6.0.</p> <p>Domestic students must have sufficient language, literacy and numeracy skills as tested through a language, literacy and numeracy assessment. Students will need to achieve ACSF level 3 for reading, writing, numeracy and oral communication to enter the course.</p> </div>',
    apply_form = 'https://ciet.edu.au/course/cpc40120-cert-iv-in-building-construction/',
    updated_at = NOW()
WHERE cricos_course_code = '110100C';

UPDATE courses SET
    course_description = '<p class="kt-adv-heading_3dcf2b-33 wp-block-kadence-advancedheading" data-kb-block="kb-adv-heading_3dcf2b-33"> </p> <p><span style="font-weight: 400;">This qualification reflects the role of building professionals who apply knowledge of structural principles, risk, and financial management, estimating, preparing, and administering building and construction contracts, selecting contractors, overseeing the work and its quality, and managing construction work in building projects including residential and commercial with the following limitations:</span></p> <p><span style="font-weight: 400;">Occupational titles may include:</span></p> <p><span style="font-weight: 400;">The construction industry strongly affirms that training and assessment leading to recognition of skills must be undertaken in a real or very closely simulated workplace environment. To achieve this qualification, the candidate must have access to a live building and construction workplace to meet the requirements detailed in the Assessment Requirements of core unit CPCCBC4008 Supervise communication and administration processes for building and construction projects.</span></p> <p><span style="font-weight: 400;">Completion of the general construction induction training program specified by the model Code of Practice for Construction Work is required for any person who is to carry out construction work. Achievement of unit CPCCWHS1001 Prepare to work safely in the construction industry meets this requirement.</span></p> <p><span style="font-weight: 400;">Builder licensing varies across States and Territories and requirements additional to the attainment of this qualification may be required.</span></p> <p><span style="font-weight: 400;">The latest release of the qualification and packaging rules can be found at the following link:</span></p> <p><a href="https://training.gov.au/Training/Details/CPC50220"><span style="font-weight: 400;">https://training.gov.au/Training/Details/CPC50220</span></a><span style="font-weight: 400;"> </span></p> <p></p>',
    total_course_duration = '',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="kt-accordion-panel-inner"> <p>Canberra Institute of Education and Technology has the following entry requirements:</p> <p>You must:</p> <ul> <li aria-level="1">be at least 18 years of age.</li> <li aria-level="1">participate in a course entry interview to determine suitability for the course and student needs. The course entry interview will also assess whether students can use digital technologies.</li> <li aria-level="1">have sufficient language, literacy and numeracy skills as tested through a language, literacy and numeracy assessment. Students will need to achieve ACSF level 4 for reading, writing, numeracy and oral communication to enter the course.</li> <li aria-level="1">have an IELTS* score of 6.0 (test results must be no more than 2 years old). English language competence can also be demonstrated through documented evidence of any of the following: <ul style="list-style-type: circle;"> <li aria-level="1">educated for 5 years in an English-speaking country; or</li> <li aria-level="1">successful completion of an English Placement Test at IELTS level 6.0.</li> </ul> </li> </ul> <p>*Note that other English language tests such as PTE and TOEFL can be accepted. Students are required to provide their results so that it can be confirmed they are equivalent to IELTS 6.0.</p> <p>Domestic students must have sufficient language, literacy and numeracy skills as tested through a language, literacy and numeracy assessment. Students will need to achieve ACSF level 3 for reading, writing, numeracy and oral communication to enter the course.</p> </div>',
    apply_form = 'https://ciet.edu.au/course/cpc50220-diploma-of-building-and-construction-building/',
    updated_at = NOW()
WHERE cricos_course_code = '110101B';

UPDATE courses SET
    course_description = '<p class="kt-adv-heading_3dcf2b-33 wp-block-kadence-advancedheading" data-kb-block="kb-adv-heading_3dcf2b-33"> </p> <p><span style="font-weight: 400;">This qualification is designed to meet the needs of builders or senior managers within the building and construction industry who apply knowledge of building, construction and sustainability systems and processes, structural principles, codes, standards and legal obligations to construction projects including high rise.</span></p> <p><span style="font-weight: 400;">Occupational titles may include:</span></p> <p><span style="font-weight: 400;">The construction industry strongly affirms that training and assessment leading to recognition of skills must be undertaken in a real or very closely simulated workplace environment and this qualification requires all included units of competency to be delivered in this context.</span></p> <p><span style="font-weight: 400;">Completion of the general construction induction training program specified by the model Code of Practice for Construction Work is required for any person who is to carry out construction work. Achievement of unit CPCCWHS1001 Prepare to work safely in the construction industry meets this requirement.</span></p> <p><span style="font-weight: 400;">Builder licensing varies across States and Territories and requirements additional to the attainment of this qualification may be required. Additional or prescribed units of competency may also be required to meet builder registration requirements in various States and Territories.</span></p> <p>The latest release of the qualification and packaging rules can be found at the following link:</p> <p><a href="https://training.gov.au/Training/Details/CPC60220">https://training.gov.au/Training/Details/CPC60220</a> </p> <p></p>',
    total_course_duration = '',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="kt-accordion-panel-inner"> <p>Canberra Institute of Education and Technology has the following entry requirements:</p> <p>You must:</p> <ul> <li aria-level="1">be at least 18 years of age.</li> <li aria-level="1">participate in a course entry interview to determine suitability for the course and student needs. The course entry interview will also assess whether students can use digital technologies.</li> <li aria-level="1">have sufficient language, literacy and numeracy skills as tested through a language, literacy and numeracy assessment. Students will need to achieve ACSF level 4 for reading, writing, numeracy and oral communication to enter the course.</li> <li aria-level="1">have an IELTS* score of 6.0 (test results must be no more than 2 years old). English language competence can also be demonstrated through documented evidence of any of the following: <ul style="list-style-type: circle;"> <li aria-level="1">educated for 5 years in an English-speaking country; or</li> <li aria-level="1">successful completion of an English Placement Test at IELTS level 6.0.</li> </ul> </li> </ul> <p>*Note that other English language tests such as PTE and TOEFL can be accepted. Students are required to provide their results so that it can be confirmed they are equivalent to IELTS 6.0.</p> <p>Domestic students must have sufficient language, literacy and numeracy skills as tested through a language, literacy and numeracy assessment. Students will need to achieve ACSF level 3 for reading, writing, numeracy and oral communication to enter the course.</p> </div>',
    apply_form = 'https://ciet.edu.au/course/cpc60220-adv-diploma-of-building-construction/',
    updated_at = NOW()
WHERE cricos_course_code = '104882G';

UPDATE courses SET
    course_description = '<p class="kt-adv-heading_3dcf2b-33 wp-block-kadence-advancedheading" data-kb-block="kb-adv-heading_3dcf2b-33"> </p> <p>CIET offers a White Card course that combines face-to-face, a self-paced learning and assessment programme. National code-compliant safety training for workers in the ACT and NSW construction industry. (CPCWHS1001 Work safely in the construction industry). All persons on a construction site must complete WHS Induction training and obtain the General Construction Induction (White Card Training) before they are permitted on a building site.</p> <p>There are no prerequisites for this course. You also need to have Personal Protective Equipment (PPE) including a hard hat, high vest, ear protection, and eye protection. If you don’t have PPE, you can get it from CIET staff once you’ve enrolled and paid for the course. Please email at admin@ciet.edu.au to find out where and when you can pick up your PPE. </p> <p>Please feel free to contact CIET by email: admin@ciet.edu.au to complete the details required prior to enrolling in the course.</p> <p>Payment can be made in person at CIET Student Services at Ground Floor 15 Barry Drive, Turner ACT 2612. Payment must be made prior to the course start date.</p> <p>Parking- Free parking is available at the back of the college building.</p> <p>Timings- 9:00 am to 3.30 pm </p> <p>Students that satisfactorily complete the competency will be eligible to apply for the National Construction Induction Card. You have 60 days from the issue of the transcript to apply for your card. Applications are made online via the Access Canberra Website. The cost will be $100 and is payable</p> <p></p>',
    total_course_duration = '',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="kt-accordion-panel-inner"> <p>Canberra Institute of Education and Technology has the following entry requirements:</p> <p>You must:</p> <ul> <li aria-level="1">be at least 18 years of age.</li> <li aria-level="1">participate in a course entry interview to determine suitability for the course and student needs. The course entry interview will also assess whether students can use digital technologies.</li> <li aria-level="1">have sufficient language, literacy and numeracy skills as tested through a language, literacy and numeracy assessment. Students will need to achieve ACSF level 4 for reading, writing, numeracy and oral communication to enter the course.</li> <li aria-level="1">have an IELTS* score of 6.0 (test results must be no more than 2 years old). English language competence can also be demonstrated through documented evidence of any of the following: <ul style="list-style-type: circle;"> <li aria-level="1">educated for 5 years in an English-speaking country; or</li> <li aria-level="1">successful completion of an English Placement Test at IELTS level 6.0.</li> </ul> </li> </ul> <p>*Note that other English language tests such as PTE and TOEFL can be accepted. Students are required to provide their results so that it can be confirmed they are equivalent to IELTS 6.0.</p> <p>Domestic students must have sufficient language, literacy and numeracy skills as tested through a language, literacy and numeracy assessment. Students will need to achieve ACSF level 3 for reading, writing, numeracy and oral communication to enter the course.</p> </div>',
    apply_form = 'https://ciet.edu.au/course/cpcwhs1001-white-card/',
    updated_at = NOW()
WHERE cricos_course_code = 'A';

UPDATE courses SET
    course_description = '<p class="kt-adv-heading_3dcf2b-33 wp-block-kadence-advancedheading" data-kb-block="kb-adv-heading_3dcf2b-33"> </p> <p>This first aid course teaches the skills and knowledge needed to recognize emergencies and provide immediate and effective first aid to anyone suffering from a sudden illness or injury, in accordance with the legal, workplace, and community considerations, as well as the guidelines of the Australian Resuscitation Council and other national peak clinical bodies in Australia.</p> <p>Assessing the casualty, providing safety, contacting emergency services, and using resources to provide first aid, such as CPR and the use of a defibrillator, administering an autoinjector for anaphylaxis, administering asthma medication, assisting someone who is choking, using appropriate immobilization techniques for envenomation, fractures, dislocations, sprains and strains, and managing casualties with non-life-threatening bleeding and shock. The importance of the survival chain, written and verbal reporting of event information, reviewing occurrences to enhance personal abilities and response times, recognizing psychological effects, and seeking help as required will be discussed during the study period.</p> <p></p>',
    total_course_duration = '',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="kt-accordion-panel-inner"> <p>Canberra Institute of Education and Technology has the following entry requirements:</p> <p>You must:</p> <ul> <li aria-level="1">be at least 18 years of age.</li> <li aria-level="1">participate in a course entry interview to determine suitability for the course and student needs. The course entry interview will also assess whether students can use digital technologies.</li> <li aria-level="1">have sufficient language, literacy and numeracy skills as tested through a language, literacy and numeracy assessment. Students will need to achieve ACSF level 4 for reading, writing, numeracy and oral communication to enter the course.</li> <li aria-level="1">have an IELTS* score of 6.0 (test results must be no more than 2 years old). English language competence can also be demonstrated through documented evidence of any of the following: <ul style="list-style-type: circle;"> <li aria-level="1">educated for 5 years in an English-speaking country; or</li> <li aria-level="1">successful completion of an English Placement Test at IELTS level 6.0.</li> </ul> </li> </ul> <p>*Note that other English language tests such as PTE and TOEFL can be accepted. Students are required to provide their results so that it can be confirmed they are equivalent to IELTS 6.0.</p> <p>Domestic students must have sufficient language, literacy and numeracy skills as tested through a language, literacy and numeracy assessment. Students will need to achieve ACSF level 3 for reading, writing, numeracy and oral communication to enter the course.</p> </div>',
    apply_form = 'https://ciet.edu.au/course/hltaid0011-provide-first-aid/',
    updated_at = NOW()
WHERE cricos_course_code = 'A';

UPDATE courses SET
    course_description = '<p class="kt-adv-heading_3dcf2b-33 wp-block-kadence-advancedheading" data-kb-block="kb-adv-heading_3dcf2b-33"> </p> <p><span style="font-weight: 400;">The latest release of the qualification and packaging rules can be found at the following link:</span></p> <p><a href="https://training.gov.au/Training/Details/ICT50220"><span style="font-weight: 400;">https://training.gov.au/Training/Details/ICT50220</span></a><span style="font-weight: 400;"> </span></p> <p></p>',
    total_course_duration = '',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="kt-accordion-panel-inner"> <p>Canberra Institute of Education and Technology has the following entry requirements:</p> <p>You must:</p> <ul> <li aria-level="1">be at least 18 years of age.</li> <li aria-level="1">participate in a course entry interview to determine suitability for the course and student needs. The course entry interview will also assess whether students can use digital technologies.</li> <li aria-level="1">have sufficient language, literacy and numeracy skills as tested through a language, literacy and numeracy assessment. Students will need to achieve ACSF level 4 for reading, writing, numeracy and oral communication to enter the course.</li> <li aria-level="1">have an IELTS* score of 6.0 (test results must be no more than 2 years old). English language competence can also be demonstrated through documented evidence of any of the following: <ul style="list-style-type: circle;"> <li aria-level="1">educated for 5 years in an English-speaking country; or</li> <li aria-level="1">successful completion of an English Placement Test at IELTS level 6.0.</li> </ul> </li> </ul> <p>*Note that other English language tests such as PTE and TOEFL can be accepted. Students are required to provide their results so that it can be confirmed they are equivalent to IELTS 6.0.</p> <p>Domestic students must have sufficient language, literacy and numeracy skills as tested through a language, literacy and numeracy assessment. Students will need to achieve ACSF level 3 for reading, writing, numeracy and oral communication to enter the course.</p> </div>',
    apply_form = 'https://ciet.edu.au/course/ict50220-diploma-of-information-technology/',
    updated_at = NOW()
WHERE cricos_course_code = '110102A';

UPDATE courses SET
    course_description = '<p class="kt-adv-heading_3dcf2b-33 wp-block-kadence-advancedheading" data-kb-block="kb-adv-heading_3dcf2b-33"> </p> <p><span style="font-weight: 400;">This qualification reflects the role of individuals in a variety of information and communications technology (ICT) roles who have significant experience in specialist technical skills, or managerial business and people management skills.</span></p> <p><span style="font-weight: 400;">Individuals in these roles carry out complex tasks in a specialist field, working independently, leading a team or a strategic direction of a business. They apply their skills across a wide range of industries and business functions, or as a business owner (sole trader/contractor). </span></p> <p><span style="font-weight: 400;">The skills required for these roles may include, but are not restricted to:</span></p> <p><span style="font-weight: 400;">No licensing, legislative or certification apply to this qualification at the time of publication.</span></p> <p>The latest release of the qualification and packaging rules can be found at the following link:</p> <p><a href="https://training.gov.au/training/details/ICT60220">https://training.gov.au/training/details/ICT60220</a> </p> <p></p>',
    total_course_duration = '',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="kt-accordion-panel-inner"> <p>Canberra Institute of Education and Technology has the following entry requirements:</p> <p>You must:</p> <ul> <li aria-level="1">be at least 18 years of age.</li> <li aria-level="1">participate in a course entry interview to determine suitability for the course and student needs. The course entry interview will also assess whether students can use digital technologies.</li> <li aria-level="1">have sufficient language, literacy and numeracy skills as tested through a language, literacy and numeracy assessment. Students will need to achieve ACSF level 4 for reading, writing, numeracy and oral communication to enter the course.</li> <li aria-level="1">have an IELTS* score of 6.0 (test results must be no more than 2 years old). English language competence can also be demonstrated through documented evidence of any of the following: <ul style="list-style-type: circle;"> <li aria-level="1">educated for 5 years in an English-speaking country; or</li> <li aria-level="1">successful completion of an English Placement Test at IELTS level 6.0.</li> </ul> </li> </ul> <p>*Note that other English language tests such as PTE and TOEFL can be accepted. Students are required to provide their results so that it can be confirmed they are equivalent to IELTS 6.0.</p> <p>Domestic students must have sufficient language, literacy and numeracy skills as tested through a language, literacy and numeracy assessment. Students will need to achieve ACSF level 3 for reading, writing, numeracy and oral communication to enter the course.</p> </div>',
    apply_form = 'https://ciet.edu.au/course/ict60220-adv-diploma-of-information-technology/',
    updated_at = NOW()
WHERE cricos_course_code = '110103M';

UPDATE courses SET
    course_description = '<p class="kt-adv-heading_3dcf2b-33 wp-block-kadence-advancedheading" data-kb-block="kb-adv-heading_3dcf2b-33"> </p> <p><span style="font-weight: 400;">This qualification reflects the role of cooks who use a wide range of well-developed cookery skills and sound knowledge of kitchen operations to prepare food and menu items. Using discretion and judgement, they work with some independence and under limited supervision using plans, policies and procedures to guide work activities.</span></p> <p><span style="font-weight: 400;">Completion of this qualification contributes to recognition as a trade cook.</span></p> <p><span style="font-weight: 400;">This qualification provides a pathway to work as a cook in organisations such as restaurants, hotels, clubs, pubs, cafes, and coffee shops.</span></p> <p><span style="font-weight: 400;">The skills in this qualification must be applied in accordance with Commonwealth and State or Territory legislation, Australian standards and industry codes of practice.</span></p> <p>The latest release of the qualification and packaging rules can be found at the following link:</p> <p><a href="https://training.gov.au/training/details/SIT30821">https://training.gov.au/training/details/SIT30821</a></p> <p></p>',
    total_course_duration = '',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="kt-accordion-panel-inner"> <p>Canberra Institute of Education and Technology has the following entry requirements:</p> <p>You must:</p> <ul> <li aria-level="1">be at least 18 years of age.</li> <li aria-level="1">participate in a course entry interview to determine suitability for the course and student needs. The course entry interview will also assess whether students can use digital technologies.</li> <li aria-level="1">have sufficient language, literacy and numeracy skills as tested through a language, literacy and numeracy assessment. Students will need to achieve ACSF level 4 for reading, writing, numeracy and oral communication to enter the course.</li> <li aria-level="1">have an IELTS* score of 6.0 (test results must be no more than 2 years old). English language competence can also be demonstrated through documented evidence of any of the following: <ul style="list-style-type: circle;"> <li aria-level="1">educated for 5 years in an English-speaking country; or</li> <li aria-level="1">successful completion of an English Placement Test at IELTS level 6.0.</li> </ul> </li> </ul> <p>*Note that other English language tests such as PTE and TOEFL can be accepted. Students are required to provide their results so that it can be confirmed they are equivalent to IELTS 6.0.</p> <p>Domestic students must have sufficient language, literacy and numeracy skills as tested through a language, literacy and numeracy assessment. Students will need to achieve ACSF level 3 for reading, writing, numeracy and oral communication to enter the course.</p> </div>',
    apply_form = 'https://ciet.edu.au/course/sit30816-certificate-iii-in-commercial-cookery/',
    updated_at = NOW()
WHERE cricos_course_code = '110643E';

UPDATE courses SET
    course_description = '<p class="kt-adv-heading_3dcf2b-33 wp-block-kadence-advancedheading" data-kb-block="kb-adv-heading_3dcf2b-33"> </p> <p>This qualification reflects the role of commercial cooks who have a supervisory or team leading role in the kitchen. They operate independently or with limited guidance from others and use discretion to solve non-routine problems.<br/> This qualification provides a pathway to work in organisations such as restaurants, hotels, clubs, pubs, cafes and coffee shops, or to run a small business in these sectors.</p> <p> The latest release of the qualification and packaging rules can be found at the following link:<br/> <a href="https://training.gov.au/training/details/SIT40521">https://training.gov.au/training/details/SIT40521</a></p> <p></p>',
    total_course_duration = '',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="kt-accordion-panel-inner"> <p>Canberra Institute of Education and Technology has the following entry requirements:</p> <p>You must:</p> <ul> <li aria-level="1">be at least 18 years of age.</li> <li aria-level="1">participate in a course entry interview to determine suitability for the course and student needs. The course entry interview will also assess whether students can use digital technologies.</li> <li aria-level="1">have sufficient language, literacy and numeracy skills as tested through a language, literacy and numeracy assessment. Students will need to achieve ACSF level 4 for reading, writing, numeracy and oral communication to enter the course.</li> <li aria-level="1">have an IELTS* score of 6.0 (test results must be no more than 2 years old). English language competence can also be demonstrated through documented evidence of any of the following: <ul style="list-style-type: circle;"> <li aria-level="1">educated for 5 years in an English-speaking country; or</li> <li aria-level="1">successful completion of an English Placement Test at IELTS level 6.0.</li> </ul> </li> </ul> <p>*Note that other English language tests such as PTE and TOEFL can be accepted. Students are required to provide their results so that it can be confirmed they are equivalent to IELTS 6.0.</p> <p>Domestic students must have sufficient language, literacy and numeracy skills as tested through a language, literacy and numeracy assessment. Students will need to achieve ACSF level 3 for reading, writing, numeracy and oral communication to enter the course.</p> </div>',
    apply_form = 'https://ciet.edu.au/course/sit40516-certificate-iv-in-commercial-cookery-2/',
    updated_at = NOW()
WHERE cricos_course_code = '110635E';

UPDATE courses SET
    course_description = '<p class="kt-adv-heading_3dcf2b-33 wp-block-kadence-advancedheading" data-kb-block="kb-adv-heading_3dcf2b-33"> </p> <p><span style="font-weight: 400;">This qualification reflects the role of highly skilled senior operators who use a broad range of hospitality skills combined with managerial skills and sound knowledge of industry to coordinate hospitality operations. They operate independently, have responsibility for others and make a range of operational business decisions.</span></p> <p><span style="font-weight: 400;">This qualification provides a pathway to work in any hospitality industry sector as a departmental or small business manager. The diversity of employers includes restaurants, hotels, motels, catering operations, clubs, pubs, cafés, and coffee shops. This qualification allows for multiskilling and for acquiring targeted skills in accommodation services, cookery, food and beverage and gaming.</span></p> <p><span style="font-weight: 400;">The skills in this qualification must be applied in accordance with Commonwealth and State/Territory legislation, Australian standards and industry codes of practice.</span></p> <p><span style="font-weight: 400;">No occupational licensing, certification or specific legislative requirements apply to this qualification at the time of publication.</span></p> <p>The latest release of the qualification and packaging rules can be found at the following link:</p> <p><a href="https://training.gov.au/training/details/SIT50422">https://training.gov.au/training/details/SIT50422</a></p> <p></p>',
    total_course_duration = '',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="kt-accordion-panel-inner"> <p>Canberra Institute of Education and Technology has the following entry requirements:</p> <p>You must:</p> <ul> <li aria-level="1">be at least 18 years of age.</li> <li aria-level="1">participate in a course entry interview to determine suitability for the course and student needs. The course entry interview will also assess whether students can use digital technologies.</li> <li aria-level="1">have sufficient language, literacy and numeracy skills as tested through a language, literacy and numeracy assessment. Students will need to achieve ACSF level 4 for reading, writing, numeracy and oral communication to enter the course.</li> <li aria-level="1">have an IELTS* score of 6.0 (test results must be no more than 2 years old). English language competence can also be demonstrated through documented evidence of any of the following: <ul style="list-style-type: circle;"> <li aria-level="1">educated for 5 years in an English-speaking country; or</li> <li aria-level="1">successful completion of an English Placement Test at IELTS level 6.0.</li> </ul> </li> </ul> <p>*Note that other English language tests such as PTE and TOEFL can be accepted. Students are required to provide their results so that it can be confirmed they are equivalent to IELTS 6.0.</p> <p>Domestic students must have sufficient language, literacy and numeracy skills as tested through a language, literacy and numeracy assessment. Students will need to achieve ACSF level 3 for reading, writing, numeracy and oral communication to enter the course.</p> </div>',
    apply_form = 'https://ciet.edu.au/course/sit50416-diploma-of-hospitality-management/',
    updated_at = NOW()
WHERE cricos_course_code = '110895G';

UPDATE courses SET
    course_description = '<p class="kt-adv-heading_3dcf2b-33 wp-block-kadence-advancedheading" data-kb-block="kb-adv-heading_3dcf2b-33"> </p> <p>The Advanced Diploma of Hospitality Management qualification provides the skills and knowledge for a student to be competent as a senior manager in any hospitality functional area (except kitchen). This individual would analyse, design and execute judgements using wide-ranging technical, creative, conceptual or managerial competencies. Their knowledge base may be specialised or broad and they are often accountable for group outcomes. Work would be undertaken in various hospitality settings, such as restaurants, hotels, catering operations, motels, clubs, pubs, cafes and coffee shops.</p> <p>Subject areas include all subjects at Diploma level and additional subjects such as:</p> <p><a href="https://training.gov.au/training/details/SIT60322">https://training.gov.au/training/details/SIT60322</a></p> <p></p>',
    total_course_duration = '',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="kt-accordion-panel-inner"> <p>Canberra Institute of Education and Technology has the following entry requirements:</p> <p>You must:</p> <ul> <li aria-level="1">be at least 18 years of age.</li> <li aria-level="1">participate in a course entry interview to determine suitability for the course and student needs. The course entry interview will also assess whether students can use digital technologies.</li> <li aria-level="1">have sufficient language, literacy and numeracy skills as tested through a language, literacy and numeracy assessment. Students will need to achieve ACSF level 4 for reading, writing, numeracy and oral communication to enter the course.</li> <li aria-level="1">have an IELTS* score of 6.0 (test results must be no more than 2 years old). English language competence can also be demonstrated through documented evidence of any of the following: <ul style="list-style-type: circle;"> <li aria-level="1">educated for 5 years in an English-speaking country; or</li> <li aria-level="1">successful completion of an English Placement Test at IELTS level 6.0.</li> </ul> </li> </ul> <p>*Note that other English language tests such as PTE and TOEFL can be accepted. Students are required to provide their results so that it can be confirmed they are equivalent to IELTS 6.0.</p> <p>Domestic students must have sufficient language, literacy and numeracy skills as tested through a language, literacy and numeracy assessment. Students will need to achieve ACSF level 3 for reading, writing, numeracy and oral communication to enter the course.</p> </div>',
    apply_form = 'https://ciet.edu.au/course/sit60322-advanced-diploma-of-hospitality-management/',
    updated_at = NOW()
WHERE cricos_course_code = '110896F';