-- Le Cordon Bleu Australia (02380M) - Webscrape Update
UPDATE provider_institution SET intake_date='May', updated_at=NOW() WHERE cricos_provider_code='02380M';

UPDATE courses SET
    course_duration_per_week = 104,
    offshore_tuition_fee = 47854,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '072294G';
UPDATE courses SET
    course_duration_per_week = 156,
    offshore_tuition_fee = 70758,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '072295F';
UPDATE courses SET
    course_duration_per_week = 104,
    offshore_tuition_fee = 48303,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '075349F';
UPDATE courses SET
    course_duration_per_week = 156,
    offshore_tuition_fee = 68263,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '075350B';
UPDATE courses SET
    course_duration_per_week = 104,
    offshore_tuition_fee = 54783,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '088607G';
UPDATE courses SET
    course_duration_per_week = 156,
    offshore_tuition_fee = 82551,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '088609F';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 15854,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '088611A';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 31708,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '088612M';
UPDATE courses SET
    course_duration_per_week = 104,
    offshore_tuition_fee = 51170,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '088614J';
UPDATE courses SET
    course_duration_per_week = 156,
    offshore_tuition_fee = 75976,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '089883B';
UPDATE courses SET
    course_duration_per_week = 156,
    offshore_tuition_fee = 78734,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '089885M';
UPDATE courses SET
    course_duration_per_week = 117,
    offshore_tuition_fee = 13468,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '091098J';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 19000,
    onshore_tuition_fee = NULL,
    enrolment_fee = 2400,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '099243G';
UPDATE courses SET
    course_duration_per_week = 156,
    offshore_tuition_fee = 61676,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '107447B';
UPDATE courses SET
    course_duration_per_week = 156,
    offshore_tuition_fee = 59880,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '107448A';
UPDATE courses SET
    course_duration_per_week = 208,
    offshore_tuition_fee = 79840,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '107449M';
UPDATE courses SET
    course_duration_per_week = 156,
    offshore_tuition_fee = 51440,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '107453D';
UPDATE courses SET
    course_duration_per_week = 104,
    offshore_tuition_fee = 54080,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '107454C';
UPDATE courses SET
    course_duration_per_week = 156,
    offshore_tuition_fee = 81096,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '107455B';
UPDATE courses SET
    course_duration_per_week = 93,
    offshore_tuition_fee = 12428,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '109462J';
UPDATE courses SET
    course_duration_per_week = 93,
    offshore_tuition_fee = 12428,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '109648K';
UPDATE courses SET
    course_duration_per_week = 69,
    offshore_tuition_fee = 37609,
    onshore_tuition_fee = NULL,
    enrolment_fee = 2409,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '109727M';
UPDATE courses SET
    course_duration_per_week = 69,
    offshore_tuition_fee = 37609,
    onshore_tuition_fee = NULL,
    enrolment_fee = 2409,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '109781E';
UPDATE courses SET
    course_duration_per_week = 117,
    offshore_tuition_fee = 13468,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '111684K';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 13520,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '111909J';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 27040,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '111910E';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 13520,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '111911D';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 27040,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '111912C';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 9980,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '112750H';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 9980,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '112751G';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 9980,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '112752F';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 9980,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '112753E';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 9980,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '112754D';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 9980,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '112755C';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 9980,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '112756B';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 9980,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '112757A';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 9980,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '112758M';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 9980,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '112759K';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 9980,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '112766M';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 9980,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '112767K';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 9980,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '112768J';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 9980,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '112769H';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 9980,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '112770D';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 9980,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '112771C';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 9980,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '112772B';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 13520,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '112805J';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 13520,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '112806H';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 13520,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '112807G';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 13520,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '112808F';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 13520,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '112809E';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 13520,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '112810A';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 13520,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '112811M';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 13520,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '112812K';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 13520,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '112813J';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 13520,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '112814H';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 13520,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '112815G';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 13520,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '112816F';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 13520,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '112817E';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 13520,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '112818D';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 13520,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '112819C';
UPDATE courses SET
    course_duration_per_week = 104,
    offshore_tuition_fee = 54080,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '113965G';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 13520,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '113966F';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 27040,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '113967E';
UPDATE courses SET
    course_duration_per_week = 104,
    offshore_tuition_fee = 54080,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '113968D';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 27040,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '113969C';
UPDATE courses SET
    course_duration_per_week = 156,
    offshore_tuition_fee = 81120,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '113970K';
UPDATE courses SET
    course_duration_per_week = 156,
    offshore_tuition_fee = 81120,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '113971J';
UPDATE courses SET
    course_duration_per_week = 156,
    offshore_tuition_fee = 81120,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '113972H';
UPDATE courses SET
    course_duration_per_week = 156,
    offshore_tuition_fee = 81120,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'https://www.cordonbleu.edu/australia',
    updated_at = NOW()
WHERE cricos_course_code = '113973G';
