-- Update provider institution details
UPDATE provider_institution SET
    intake_date = 'January, February, April, May, July, August, October, November',
    updated_at = NOW()
WHERE cricos_provider_code = '03882C';

UPDATE courses SET
    course_description = '<div> <div> <div> <div> <p>This qualification reflects accounting job roles in financial services and other industries, including tax agents, accounts payable and accounts receivable officers, payroll service providers, and employees performing a range of accounting tasks for organisations in a range of industries. Individuals in these roles apply solutions to a range of often complex problems, and analyse and evaluate information from a variety of sources. They apply initiative to plan, coordinate and evaluate their own work and provide guidance to others within defined guidelines</p> </div> </div> </div> </div>',
    course_duration_per_week = 78,
    offshore_tuition_fee = 18000,
    onshore_tuition_fee = 18000,
    enrolment_fee = 250,
    materials_fee = 450,
    entry_requirements = '<h4>Entry Requirements</h4><div> <div> <div> <div> <ul><li>Must be 18 years of age or older.</li> <li>Must provide proof of school studies which is equivalent to Australian Year 12 or other higher qualifications.</li> <li>Must have completed following units of competency ( or equivalent) which may have been acieved through completion of <ul><li>FNSSS00014 Accounting Principles Skill Set;</li> <li>FNSACC321 Process financial transactions and extract interim reports</li> <li>FNSACC322 Administer subsidiary accounts and ledger</li> <li>FNSACC418 Work effectively in the accounting and bookkeeping industry</li> <li>FNSACC421 Prepare financial reports ( this unit is the equivalent version of BSBFIA401 Prepare financial reports) or</li> <li>FNS40222 Certificate IV in Accounting and Bookkeeping.</li> </ul></li> <li>Must provide valid academic IELTS* score of 6.0 overall with no band less than 5.5 or equivalent unless exempted or need to submit English Proficiency certificate from an approved ELICOS provider of upper intermediate level or above; or completion of substantial part of studies of at least an AQF Certificate IV qualification or higher within the last 2 years; or have successfully passed the Rockford College English Placement Test. For further details; please refer to the Department of Home Affairs (DOHA) website for Acceptable English and Exemptions.</li> <li>Participate in the Course Entry Requirement Interview.</li> <li>International Students must meet the Student Visa (SC500) requirements.* Note that other English Language Test such as PTE and TOEFL can be accepted.</li> </ul></div> </div> </div> </div>',
    apply_form = 'https://rockford.edu.au/course/fns50222-diploma-of-accounting/',
    updated_at = NOW()
WHERE cricos_course_code = '112146F';
UPDATE courses SET
    course_description = '<div> <div> <div> <div> <p>This qualification reflects the role of individuals who apply knowledge, practical skills and experience in leadership and management across a range of enterprise and industry contexts.</p> <p>Individuals at this level display initiative and judgement in planning, organizing, implementing and monitoring their own workload and the workload of others. They use communication skills to support individuals and teams to meet organizational or enterprise requirements.</p> <p>They plan, design, apply and evaluate solutions to unpredictable problems, and identify, analyses and synthesis information from a variety of sources.</p> </div> </div> </div> </div>',
    course_duration_per_week = 78,
    offshore_tuition_fee = 18000,
    onshore_tuition_fee = 18000,
    enrolment_fee = 250,
    materials_fee = 450,
    entry_requirements = '<h4>Entry Requirements</h4><div> <div> <div> <div> <ul><li>Must be 18 years of age or older.</li> <li>Must provide proof of school studies which is equivalent to Australian Year 12 or other higher qualifications.</li> <li>Must provide valid academic IELTS* score of 6.0 overall with no band less than 5.5 or equivalent unless exempted or need to submit English Proficiency certificate from an approved ELICOS provider of upper intermediate level or above; or completion of substantial part of studies of at least an AQF Certificate IV qualification or higher within the last 2 years; or have successfully passed the Rockford College English Placement Test. For further details; please refer to the <a href="https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/student-500#Eligibility">Department of Home Affairs (DOHA)</a> website for Acceptable English and Exemptions.</li> <li>Participate in the Course Entry Requirement Interview.</li> <li>International Students must meet the Student Visa (SC500) requirements.</li> </ul><p>* Note that other English Language Test such as PTE and TOEFL can be accepted.</p> </div> </div> </div> </div>',
    apply_form = 'https://rockford.edu.au/course/bsb50420-diploma-of-leadership-and-management/',
    updated_at = NOW()
WHERE cricos_course_code = '104423A';
UPDATE courses SET
    course_description = '<div> <div> <div> <div> <p>This qualification reflects the role of individuals who apply project management skills and knowledge in a variety of contexts, across a number of industry sectors. The job roles that relate to this qualification may include Project Manager and Project Team Leader.</p> <p>Individuals in these roles have project leadership and management roles and are responsible for achieving project objectives. They possess a sound theoretical knowledge base and use a range of specialised, technical and managerial competencies to initiate, plan, execute and evaluate their own work and/or the work of others.</p> </div> </div> </div> </div>',
    course_duration_per_week = 78,
    offshore_tuition_fee = 18000,
    onshore_tuition_fee = 18000,
    enrolment_fee = 250,
    materials_fee = 450,
    entry_requirements = '<h4>Entry Requirements</h4><div> <div> <div> <div> <ul><li>Must be 18 years of age or older.</li> <li>Must provide proof of school studies which is equivalent to Australian Year 12 or other higher qualifications.</li> <li>Must provide valid academic IELTS* score of 6.0 overall with no band less than 5.5 or equivalent unless exempted or need to submit English Proficiency certificate from an approved ELICOS provider of upper intermediate level or above; or completion of substantial part of studies of at least an AQF Certificate IV qualification or higher within the last 2 years; or have successfully passed the Rockford College English Placement Test. For further details; please refer to the Department of Home Affairs (DOHA) website for Acceptable English and Exemptions.</li> <li>Participate in the Course Entry Requirement Interview.</li> <li>International Students must meet the Student Visa (SC500) requirements.* Note that other English Language Test such as PTE and TOEFL can be accepted.</li> </ul></div> </div> </div> </div>',
    apply_form = 'https://rockford.edu.au/course/bsb50820-diploma-of-project-management/',
    updated_at = NOW()
WHERE cricos_course_code = '108672G';
UPDATE courses SET
    course_description = '<div> <div> <div> <div> <p>This qualification reflects the role of individuals who apply specialised knowledge and skills, together with experience in program management across a range of enterprise and industry contexts. The job roles that relate to this qualification include Program Manager.</p> <p>Individuals in these roles are responsible for managing or directing a program to achieve organisational objectives. A program is defined as a set of interrelated projects, each of which has a project manager.</p> <p>Individuals at this level use initiative and judgement to direct, plan, and lead a range of program functions, with accountability for personal and team outcomes within broad parameters. They use cognitive and communication skills to identify, analyse and synthesise information from a variety of sources and transfer their knowledge to others, and creative or conceptual skills to express ideas and perspectives or respond to complex problems.</p> </div> </div> </div> </div>',
    course_duration_per_week = 78,
    offshore_tuition_fee = 18000,
    onshore_tuition_fee = 18000,
    enrolment_fee = 250,
    materials_fee = 450,
    entry_requirements = '<h4>Entry Requirements</h4><div> <div> <div> <div> <ul><li>Must be 18 years of age or older.</li> <li>Must provide proof of school studies which is equivalent to Australian Year 12 or other higher qualifications and have completed one of the following qualifications: BSB50820 Diploma of Project Management; or BSB51415 Diploma of Project Management (or a superseded equivalent version).Or have completed two years equivalent full-time relevant workplace experience at a significant level within a project or program environment within an enterprise.</li> <li>Must provide valid academic IELTS* score of 6.0 overall with no band less than 5.5 or equivalent unless exempted or need to submit English Proficiency certificate from an approved ELICOS provider of upper intermediate level or above; or completion of substantial part of studies of at least an AQF Certificate IV qualification or higher within the last 2 years; or have successfully passed the Rockford College English Placement Test. For further details; please refer to the Department of Home Affairs (DOHA) website for Acceptable English and Exemptions.</li> <li>Participate in the Course Entry Requirement Interview.</li> <li>International Students must meet the Student Visa (SC500) requirements.* Note that other English Language Test such as PTE and TOEFL can be accepted.</li> </ul></div> </div> </div> </div>',
    apply_form = 'https://rockford.edu.au/course/bsb60720-advanced-diploma-of-program-management/',
    updated_at = NOW()
WHERE cricos_course_code = '103309M';
UPDATE courses SET
    course_description = '<div> <div> <div> <div> <p>This qualification reflects the role of individuals who apply highly specialised knowledge and skills in the field of organisational learning and capability development. Individuals in these roles generate and evaluate complex ideas. They also initiate, design and execute major learning and development functions within an organisation. Typically, they would have full responsibility and accountability for the personal output and work of others.</p> <p>This qualification may apply to leaders and managers in an organisation where learning is used to build organisational capability. The job roles that relate to this qualification may also include RTO Manager and RTO Director.</p> </div> </div> </div> </div>',
    course_duration_per_week = 104,
    offshore_tuition_fee = 24000,
    onshore_tuition_fee = 24000,
    enrolment_fee = 250,
    materials_fee = 600,
    entry_requirements = '<h4>Entry Requirements</h4><div> <div> <div> <div> <ul><li>Must be 18 years of age or older.</li> <li>Must have completed AQF Diploma level qualification or above from the BSB Training Package or equivalent or equivalent of 3 years bachelor’s degree.</li> <li>Must provide valid academic IELTS* of at least 6.0 overall score or equivalent unless exempted or need to submit English Proficiency certificate from an approved ELICOS provider of upper intermediate level or above; or completion of substantial part of studies of at least an AQF Certificate IV qualification or higher within the last 2 years; or have successfully passed the Rockford College English Placement Test. For further details; please refer to the Department of Home Affairs (DOHA) website for Acceptable English and Exemptions.</li> <li>Participate in the Course Entry Requirement Interview.</li> <li>International Students must meet the Student Visa (SC500) requirements.* Note that other English Language Test such as PTE and TOEFL can be accepted.</li> </ul></div> </div> </div> </div>',
    apply_form = 'https://rockford.edu.au/course/bsb80120-graduate-diploma-of-management-learning/',
    updated_at = NOW()
WHERE cricos_course_code = '105704F';
UPDATE courses SET
    course_description = '<div> <div> <div> <div> <p>This qualification reflects the role of educators in early childhood education and care who work in regulated children’s education and care services in Australia. They support children’s wellbeing, and development in the context of an approved learning framework. Educators use a range of well-developed skills and knowledge using discretion and judgment when carrying out their work in the context of established policies and procedures. They may work independently or under the guidance of others, though in some contexts that guidance may not be on-site.</p> <p>Early childhood educators work in long day care centres, family day care, pre-schools or kindergartens.<br/> To achieve this qualification, the individual must have completed a total of least 160 hours of work in a regulated children’s education and care service in Australia as detailed in the Assessment Requirements of units of competency. The total number of hours may be applied collectively across all units of competency that include the requirement for workplace hours.</p> <p>No occupational licensing, certification or specific legislative requirements apply to this qualification at the time of publication.</p> <p>Under the Education and Care Services National Law (2011) the Australian Children’s Education and Care Quality Authority (ACECQA) publishes lists of approved early childhood education and care qualifications and information regarding regulatory requirements here: www.acecqa.gov.au.</p> </div> </div> </div> </div>',
    course_duration_per_week = 52,
    offshore_tuition_fee = 12000,
    onshore_tuition_fee = 12000,
    enrolment_fee = 250,
    materials_fee = 1000,
    entry_requirements = '<h4>Entry Requirements</h4><div> <div> <div> <div> <p>• Must be 18 years of age or older.<br/> • Must provide proof of school studies which is equivalent to Australian Year 11 or other higher qualifications.<br/> • Must provide valid academic IELTS* of at least 6.0 overall or equivalent with no band less than 5.5 or equivalent score unless exempted or need to submit English Proficiency certificate from an approved ELICOS provider of upper intermediate level or above; or completion of substantial part of studies of at least an AQF Certificate IV qualification or higher within the last 2 years; or have successfully passed the Rockford College English Placement Test. For further details, please refer to the Department of Home Affairs (DOHA) website for Acceptable English and Exemptions.<br/> • Participate in the Course Entry Requirement Interview.<br/> • International Students must meet the Student Visa (SC500) requirements.<br/> * Note that other English Language Test such as PTE and TOEFL can be accepted.</p> </div> </div> </div> </div>',
    apply_form = 'https://rockford.edu.au/course/chc30125-certificate-iii-in-early-childhood-education-and-care/',
    updated_at = NOW()
WHERE cricos_course_code = '113472F';
UPDATE courses SET
    course_description = '<div> <div> <div> <div> <p>This qualification reflects the role of individuals in the community, home or residential care setting who work under supervision and delegation as a part of a multi-disciplinary team, following an individualised plan to provide person-centred support to people who may require support due to ageing, disability or some other reason.</p> <p>These individuals take responsibility for their own outputs within the scope of their job role and delegation. Workers have a range of factual, technical and procedural knowledge, as well as some theoretical knowledge of the concepts and practices required to provide person-centred support.</p> <p>The skills in this qualification must be applied in accordance with Commonwealth and State/Territory legislation, Australian standards and industry codes of practice.</p> <p>To achieve this qualification, the candidate must have completed at least 120 hours of work as detailed in the Assessment Requirements of the units of competency.</p> <p>No licensing, legislative, regulatory or certification requirements apply to this qualification at the time of publication.</p> </div> </div> </div> </div>',
    course_duration_per_week = 52,
    offshore_tuition_fee = 12000,
    onshore_tuition_fee = 12000,
    enrolment_fee = 250,
    materials_fee = 1000,
    entry_requirements = '<h4>Entry Requirements</h4><div> <div> <div> <div> <ul><li>Must be 18 years of age or older.</li> <li>Must provide proof of school studies which is equivalent to Australian Year 11 or other higher qualifications.</li> <li>Must provide valid academic IELTS* score of 6.0 overall with no band less than 5.5 or equivalent unless exempted or need to submit English Proficiency certificate from an approved ELICOS provider of upper intermediate level or above; or completion of substantial part of studies of at least an AQF Certificate IV qualification or higher within the last 2 years; or have successfully passed the Rockford College English Placement Test. For further details, please refer to the Department of Home Affairs (DOHA) website for Acceptable English and Exemptions.</li> <li>Participate in the Course Entry Requirement Interview.</li> <li>International Students must meet the Student Visa (SC500) requirements.* Note that other English Language Test such as PTE and TOEFL can be accepted.</li> </ul></div> </div> </div> </div>',
    apply_form = 'https://rockford.edu.au/course/chc33021-certificate-iii-in-individual-support/',
    updated_at = NOW()
WHERE cricos_course_code = '113474D';
UPDATE courses SET
    course_description = '<div> <div> <div> <div> <p>This qualification reflects the role of support workers who complete specialised tasks and functions in aged services; either in residential, home or community based environments. Workers will take responsibility for their own outputs within defined organisation guidelines and maintain quality service delivery through the development, facilitation and review of individualised service planning and delivery.</p> <p>Workers may be required to demonstrate leadership and have limited responsibility for the organisation and the quantity and quality of outputs of others within limited parameters.</p> <p>To achieve this qualification, the candidate must have completed at least 120 hours of work as detailed in the Assessment Requirements of the units of competency.</p> </div> </div> </div> </div>',
    course_duration_per_week = 78,
    offshore_tuition_fee = 18000,
    onshore_tuition_fee = 18000,
    enrolment_fee = 250,
    materials_fee = 1500,
    entry_requirements = '<h4>Entry Requirements</h4><div> <div> <div> <div> <ul><li>Must be 18 years of age or older.</li> <li>Must provide proof of school studies which is equivalent to Australian Year 12 or other higher qualifications</li> <li>Must provide valid academic IELTS* score of 6.0 overall with no band less than 5.5 or equivalent unless exempted or need to submit English Proficiency certificate from an approved ELICOS provider of intermediate level or above; or completion of substantial part of studies of at least an AQF Certificate IV qualification or higher within the last 2 years; or have successfully passed the Rockford College English Placement Test. For further details; please refer to the Department of Home Affairs (DOHA) website for Acceptable English and Exemptions.</li> <li>Participate in the Course Entry Requirement Interview.</li> <li>International Students must meet the Student Visa (SC500) requirements.</li> </ul><p> </p> <p>* Note that other English language tests such as PTE and TOEFL can be accepted. Students are required to provide their results so that it can be confirmed they are equivalent to IELTS 6.0.</p> </div> </div> </div> </div>',
    apply_form = 'https://rockford.edu.au/course/chc43015-certificate-iv-in-ageing-support/',
    updated_at = NOW()
WHERE cricos_course_code = '115653G';
UPDATE courses SET
    course_description = '<div> <div> <div> <div> <p>This qualification reflects the role of educators in early childhood education and care who work in regulated children’s education and care services in Australia. Educators at this level are responsible for designing and implementing curriculum that meets the requirements of an approved learning framework and for maintaining compliance in other areas of service operations. They use specialised knowledge and analyse and apply theoretical concepts to diverse work situations. They may have responsibility for supervision of volunteers or other educators.</p> <p>Early childhood educators work in long day care centres, family day care, pre-schools, or kindergartens.</p> <p>To achieve this qualification, the individual must have completed a total of at least 280 hours of work in a regulated children’s education and care service in Australia as detailed in the Assessment Requirements of units of competency. The total number of hours may be applied collectively across all units of competency that include the requirement for workplace hours.</p> </div> </div> </div> </div>',
    course_duration_per_week = 78,
    offshore_tuition_fee = 18000,
    onshore_tuition_fee = 18000,
    enrolment_fee = 250,
    materials_fee = 1500,
    entry_requirements = '<h4>Entry Requirements</h4><div> <div> <div> <div> <ul><li>Entry to this qualification is open to individuals who: <ul><li>Hold a CHC30121 Certificate III in Early Childhood Education and Care (or its equivalent successor)</li> <li>CHC30113 Certificate III in Early Childhood Education and Care.</li> <li>Alternatively, individuals may hold: <ul><li>An Australian diploma in Early Childhood Education and Care</li> </ul></li> </ul><p>OR</p> <ul><li>An Australian diploma or certificate III in Children’s Services.</li> </ul><p>AND</p> <ul><li>Demonstrate at least 12 months of cumulative employment (full-time equivalent) within the last 5 years in a regulated education and care service in Australia, supported by verifiable evidence.</li> </ul><p>OR</p> <ul><li>Hold the <a href="https://training.gov.au/training/details/CHCSS00147"><em>CHCSS00147</em></a><em>Entry into Diploma of Early Childhood Education and Care.</em></li> </ul><p>Rockford College has the following entry requirements:</p> <p>International students must:</p> <ul><li>Be at least 18 years of age and have completed the equivalent of Year 12.</li> <li>Participate in a course entry interview to determine suitability for the course and student needs.</li> <li>Have an IELTS* score of 6.0 overall with no band less than 5.5 or equivalent (test results must be no more than 2 years old). English language competence can also be demonstrated through documented evidence of any of the following: <ul><li>Educated for 5 years in an English-speaking country; or</li> <li>Successful completion of an English Placement Test</li> </ul></li> </ul><p>*Note that other English language tests such as PTE and TOEFL can be accepted. Students are required to provide their results so that it can be confirmed they are equivalent to IELTS 6.0.</p></li> </ul></div> </div> </div> </div>',
    apply_form = 'https://rockford.edu.au/course/chc50125-diploma-of-early-childhood-education-and-care/',
    updated_at = NOW()
WHERE cricos_course_code = '113473E';
UPDATE courses SET
    course_description = '<div> <div> <div> <div> <p>This qualification reflects the role of community services workers involved in the delivery, management and coordination of person-centred services to individuals, groups, and communities.</p> <p>At this level, workers have specialised skills in community services and work autonomously within their scope of practice under broad directions from senior management.</p> <p>Workers support people to make change in their lives to improve personal and social wellbeing and may also have responsibility for the supervision of other workers and volunteers. They may also undertake case management and program coordination.</p> <p>To achieve this qualification, the candidate must have completed at least 100 hours of work as detailed in the Assessment Requirements of units of competency.</p> <p>The skills in this qualification must be applied in accordance with Commonwealth and State or Territory legislation, Australian standards and industry codes of practice.</p> <p>No occupational licensing, certification or specific legislative requirements apply to this qualification at the time of publication</p> </div> </div> </div> </div>',
    course_duration_per_week = 104,
    offshore_tuition_fee = 24000,
    onshore_tuition_fee = 24000,
    enrolment_fee = 250,
    materials_fee = 2000,
    entry_requirements = '<h4>Entry Requirements</h4><div> <div> <div> <div> <p>• Must be 18 years of age or older.<br/> • Must provide proof of school studies which is equivalent to Australian Year 12 or other higher qualifications.<br/> • Must provide valid academic IELTS* of at least 6.0 overall score with no band less than 5.5 or equivalent unless exempted or need to submit English Proficiency certificate from an approved ELICOS provider of upper intermediate level or above; or completion of substantial part of studies of at least an AQF Certificate IV qualification or higher within the last 2 years; or have successfully passed the Rockford College English Placement Test. For further details, please refer to the Department of Home Affairs (DOHA) website for Acceptable English and Exemptions.<br/> • Participate in the Course Entry Requirement Interview.<br/> • International Students must meet the Student Visa (SC500) requirements.<br/> * Note that other English Language Test such as PTE and TOEFL can be accepted.</p> </div> </div> </div> </div>',
    apply_form = 'https://rockford.edu.au/course/chc52025-diploma-of-community-services/',
    updated_at = NOW()
WHERE cricos_course_code = '113471G';
UPDATE courses SET
    course_description = '<div> <div> <div> <div> <p>This qualification reflects the role of individuals in the accounting and bookkeeping industry, including business activity statement (BAS) agents and contract bookkeepers; and of those employees performing bookkeeping tasks for organisations in a range of industries. It includes preparing and lodging business and instalment activity statements, data processing, monthly reconciliations, preparing budgets, preparing reports on financial performance and the position of the business, preparing end-of-year adjustments, and finalising financial records after year-end. Dealing with the Commissioner of Taxation on behalf of a taxpayer in relation to activity statements and other lodgement matters is also a key component of the role that this qualification reflects. Individuals in these roles apply theoretical and specialist skills and knowledge to work autonomously, and exercise judgement in completing routine and non-routine activities.</p> </div> </div> </div> </div>',
    course_duration_per_week = 78,
    offshore_tuition_fee = 18000,
    onshore_tuition_fee = 18000,
    enrolment_fee = 250,
    materials_fee = 450,
    entry_requirements = '<h4>Entry Requirements</h4><div> <div> <div> <div> <p>Must be 18 years of age or older.<br/> Must provide proof of school studies which is equivalent to Australian Year 12 or other higher qualifications.<br/> Must provide valid academic IELTS* score of 6.0 overall with no band less than 5.5 or equivalent unless exempted or need to submit English Proficiency certificate from an approved ELICOS provider of upper intermediate level or above; or completion of substantial part of studies of at least an AQF Certificate IV qualification or higher within the last 2 years; or have successfully passed the Rockford College English Placement Test. For further details; please refer to the Department of Home Affairs (DOHA) website for Acceptable English and Exemptions.<br/> Participate in the Course Entry Requirement Interview.<br/> International Students must meet the Student Visa (SC500) requirements.</p> <p>* Note that other English Language Test such as PTE and TOEFL can be accepted.</p> </div> </div> </div> </div>',
    apply_form = 'https://rockford.edu.au/course/fns40222-certificate-iv-in-accounting-and-bookkeeping/',
    updated_at = NOW()
WHERE cricos_course_code = '110023M';
UPDATE courses SET
    course_description = '<div> <div> <div> <div> <p>The General English course is designed to prepare students for conversation, everyday situations and daily interactions that take place when traveling or living in an English-speaking country. Students learn and practice the four macro-skills of listening, reading, writing and speaking in an interactive environment. Levels of difficulty increase over the duration of the course to assist students to develop their skills and to be more confident and fluent in English.</p> </div> </div> </div> </div>',
    course_duration_per_week = 80,
    offshore_tuition_fee = 15000,
    onshore_tuition_fee = 15000,
    enrolment_fee = 250,
    materials_fee = 600,
    entry_requirements = '<h4>Entry Requirements</h4><div> <div> <div> <div> <ul><li>Must be 18 years of age or older.</li> <li>Participate in the English Placement Test and an interview.</li> <li>Participate in the Course Entry Requirement Interview.</li> <li>International Students must meet the Student Visa (SC500) requirements.</li> </ul></div> </div> </div> </div>',
    apply_form = 'https://rockford.edu.au/course/general-english/',
    updated_at = NOW()
WHERE cricos_course_code = '114521E';
UPDATE courses SET
    course_description = '<div> <div> <div> <div> <p>This qualification reflects the role of individuals in a variety of information and communications technology (ICT) roles who have established specialised skills in a technical ICT function.</p> <p>Individuals in these roles carry out moderately complex tasks in a specialist field, working independently, as part of a team or leading a deliverable with others. They may apply their skills across a wide range of industries, business functions and departments, or as a business owner (sole trader/contractor).</p> <p>The skills required for these roles may include, but are not restricted to:</p> <p>advanced networking: configuring and managing virtual computing environments, and security within ICT networks<br/> advanced programming: applying intermediate and advanced programming skills, managing data and building advanced user interfaces to manage organizational requirements<br/> back end web development: developing and maintaining website information architecture and data<br/> business analysis: designing and implementing technical requirements, quality assurance processes, and contingency plans for businesses<br/> cloud architecture: developing, improving and designing cloud infrastructure, including disaster recovery plans<br/> cloud engineering: building, implementing and managing cloud infrastructure and virtual networks<br/> cybersecurity: protecting sensitive data and information through security architecture and developing disaster recovery and contingency plans<br/> database and data management: creating, designing and monitoring systems that store data and optimize organisational knowledge management<br/> front end web development: designing dynamic and complex websites, user experience solutions and documents using extensible mark-up languages<br/> game art and design: creating complex 2D and 3D modelling and animation software through scripts and storyboards<br/> game programming: creating complex 2D and 3D interactive games and media, building graphical user interfaces, and applying artificial intelligence in game development<br/> systems administration: reviewing maintenance procedures and support to help troubleshoot system applications<br/> systems analysis: modelling and testing data objects, data processes and preferred ICT system solutions<br/> telecommunications network engineering: managing logistics, organisational specifications, regulations, and legislative requirements across network projects.</p> </div> </div> </div> </div>',
    course_duration_per_week = 78,
    offshore_tuition_fee = 18000,
    onshore_tuition_fee = 18000,
    enrolment_fee = 250,
    materials_fee = 450,
    entry_requirements = '<h4>Entry Requirements</h4><div> <div> <div> <div> <p>Entry Requirement<br/> Must be 18 years of age or older.<br/> Must provide proof of school studies which is equivalent to Australian Year 12 or other higher qualifications.<br/> Must provide valid academic IELTS* score of 6.0 overall with no band less than 5.5 or equivalent unless exempted or need to submit English Proficiency certificate from an approved ELICOS provider of upper intermediate level or above; or completion of substantial part of studies of at least an AQF Certificate IV qualification or higher within the last 2 years; or have successfully passed the Rockford College English Placement Test. For further details; please refer to the Department of Home Affairs (DOHA) website for Acceptable English and Exemptions.<br/> Participate in the Course Entry Requirement Interview.<br/> International Students must meet the Student Visa (SC500) requirements.</p> <p>* Note that other English Language Test such as PTE and TOEFL can be accepted.</p> </div> </div> </div> </div>',
    apply_form = 'https://rockford.edu.au/course/ict50220-diploma-of-information-technology/',
    updated_at = NOW()
WHERE cricos_course_code = '105702H';
UPDATE courses SET
    course_description = '<div> <div> <div> <div> <p>This qualification reflects the role of individuals in a variety of information and communications technology (ICT) roles who have significant experience in specialist technical skills, or managerial business and people management skills.</p> <p>Individuals in these roles carry out complex tasks in a specialist field, working independently, leading a team or a strategic direction of a business. They apply their skills across a wide range of industries and business functions, or as a business owner (sole trader/contractor).</p> <p>The skills required for these roles may include, but are not restricted to:</p> <ul><li>advanced data management information: creating, designing and monitoring complex systems that store data, and optimising organisational knowledge management</li> <li>cyber security: protecting sensitive data and information through security architecture, and developing disaster recovery and contingency plans</li> <li>full stack web development: building advanced user interfaces, developing representational state transfer application program interfaces (REST APIs) and designing user experience solutions</li> <li>further programming: applying advanced ICT languages to maintain security and manage data</li> <li>IT strategy and organisational development: managing and communicating strategic ICT business solutions</li> <li>systems development and analysis: modelling and testing data objects, data processes and preferred ICT system solutions</li> <li>telecommunications network engineering: managing logistics, organisational specifications, regulations and legislative requirements across network projects.</li> </ul></div> </div> </div> </div>',
    course_duration_per_week = 78,
    offshore_tuition_fee = 18000,
    onshore_tuition_fee = 18000,
    enrolment_fee = 250,
    materials_fee = 450,
    entry_requirements = '<h4>Entry Requirements</h4><div> <div> <div> <div> <ul><li>Must be 18 years of age or older.</li> <li>Must provide proof of school studies which is equivalent to Australian Year 12 or other higher qualifications.</li> <li>Must provide valid academic IELTS* score of 6.0 overall with no band less than 5.5 or equivalent unless exempted or need to submit English Proficiency certificate from an approved ELICOS provider of upper intermediate level or above; or completion of substantial part of studies of at least an AQF Certificate IV qualification or higher within the last 2 years; or have successfully passed the Rockford College English Placement Test. For further details; please refer to the Department of Home Affairs (DOHA) website for Acceptable English and Exemptions.</li> <li>Participate in the Course Entry Requirement Interview.</li> <li>International Students must meet the Student Visa (SC500) requirements.</li> </ul><p>* Note that other English Language Test such as PTE and TOEFL can be accepted.</p> </div> </div> </div> </div>',
    apply_form = 'https://rockford.edu.au/course/ict60220-advanced-diploma-of-information-technology/',
    updated_at = NOW()
WHERE cricos_course_code = '105703G';
UPDATE courses SET
    course_description = '<div> <div> <div> <div> <p>This qualification reflects the role of individuals working as designers or design paraprofessionals who support professional engineers. They perform tasks involving a high level of autonomy and requiring the application of significant judgement in planning and determining the selection of equipment/roles/techniques for themselves and others. They are required to develop site specific work designs to ensure the implementation of the client’s site requirements. They demonstrate the application of a broad range of technical, managerial, coordination and planning skills.</p> </div> </div> </div> </div>',
    course_duration_per_week = 52,
    offshore_tuition_fee = 12000,
    onshore_tuition_fee = 12000,
    enrolment_fee = 250,
    materials_fee = 1000,
    entry_requirements = '<h4>Entry Requirements</h4><div> <div> <div> <div> <ul><li>Must be 18 years of age or older.</li> <li>Must provide proof of school studies which is equivalent to Australian Year 12 or other higher qualifications.</li> <li>Must provide valid academic IELTS* of at least 6.0 overall with no band less than 5.5 or equivalent unless exempted or need to submit English Proficiency certificate from an approved ELICOS provider of upper-intermediate level or above; or completion of substantial part of studies of at least an AQF Certificate IV qualification or higher within the last 2 years; or have successfully passed the Rockford College English Placement Test. For further details; please refer to the Department of Home Affairs (DOHA) website for Acceptable English and Exemptions.</li> <li>Participate in the Course Entry Requirement Interview.</li> <li>International Students must meet the Student Visa (SC500) requirements.<br/> * Note that other English language tests such as PTE and TOEFL can be accepted. Students are required to provide their results so that it can be confirmed they are equivalent to IELTS 6.0.</li> </ul></div> </div> </div> </div>',
    apply_form = 'https://rockford.edu.au/course/rii50520-diploma-of-civil-construction-design/',
    updated_at = NOW()
WHERE cricos_course_code = '120671G';
UPDATE courses SET
    course_description = '<div> <div> <div> <div> <p>This qualification reflects the role of an individual working as a senior civil works designer or a para-professional designer, who supports professional engineers. They perform tasks that are broad, specialised, complex and technical and include strategic areas and initiating activities. They are responsible for the design of complex projects to ensure the implementation of the client’s site requirements and are required to demonstrate self-directed application of theoretical and technical knowledge and initiate solutions to technical problems or management requirements.</p> </div> </div> </div> </div>',
    course_duration_per_week = 104,
    offshore_tuition_fee = 24000,
    onshore_tuition_fee = 24000,
    enrolment_fee = 250,
    materials_fee = 2000,
    entry_requirements = '<h4>Entry Requirements</h4><div> <div> <div> <div> <ul><li>Must be 18 years of age or older.</li> <li>Must provide proof of school studies which is equivalent to Australian Year 12 or other higher qualifications.</li> <li>Must provide valid academic IELTS* score of 6.0 overall with no band less than 5.5 or equivalent unless exempted or need to submit English Proficiency certificate from an approved ELICOS provider of intermediate level or above; or completion of substantial part of studies of at least an AQF Certificate IV qualification or higher within the last 2 years; or have successfully passed the Rockford College English Placement Test. For further details; please refer to the Department of Home Affairs (DOHA) website for Acceptable English and Exemptions.<br/> Participate in the Course Entry Requirement Interview.</li> <li>International Students must meet the Student Visa (SC500) requirements.</li> </ul><p>* Note that other English language tests such as PTE and TOEFL can be accepted. Students are required to provide their results so that it can be confirmed they are equivalent to IELTS 6.0.</p> </div> </div> </div> </div>',
    apply_form = 'https://rockford.edu.au/course/rii60520-advanced-diploma-of-civil-construction-design/',
    updated_at = NOW()
WHERE cricos_course_code = '115652H';
UPDATE courses SET
    course_description = '<div> <div> <div> <div> <p>This qualification reflects the role of chefs and cooks who have a supervisory or team leading role in the kitchen. They operate independently or with limited guidance from others and use discretion to solve non-routine problems.<br/> This qualification provides a pathway to work in organisations such as restaurants, hotels, clubs, pubs, cafes and coffee shops, or to run a small business in these sectors.</p> <p>The skills in this qualification must be applied in accordance with Commonwealth and State or Territory legislation, Australian standards and industry codes of practice.</p> <p>No occupational licensing, certification or specific legislative requirements apply to this qualification at the time of publication.</p> </div> </div> </div> </div>',
    course_duration_per_week = 78,
    offshore_tuition_fee = 18000,
    onshore_tuition_fee = 18000,
    enrolment_fee = 250,
    materials_fee = 450,
    entry_requirements = '<h4>Entry Requirements</h4><div> <div> <div> <div> <ul><li>Must be 18 years of age or older.</li> <li>Must provide proof of school studies which is equivalent to Australian Year 12 or other higher qualifications.</li> <li>Must provide valid academic IELTS* score of 6.0 overall with no band less than 5.5 or equivalent unless exempted or need to submit English Proficiency certificate from an approved ELICOS provider of upper intermediate level or above; or completion of substantial part of studies of at least an AQF Certificate IV qualification or higher within the last 2 years; or have successfully passed the Rockford College English Placement Test. For further details; please refer to the Department of Home Affairs (DOHA) website for Acceptable English and Exemptions.</li> <li>Participate in the Course Entry Requirement Interview.</li> <li>International Students must meet the Student Visa (SC500) requirements.</li> </ul><p>* Note that other English Language Test such as PTE and TOEFL can be accepted.</p> </div> </div> </div> </div>',
    apply_form = 'https://rockford.edu.au/course/sit40521-certificate-iv-in-kitchen-management/',
    updated_at = NOW()
WHERE cricos_course_code = '109591M';
UPDATE courses SET
    course_description = '<div> <div> <div> <div> <p>This qualification reflects the role of highly skilled senior operators who use a broad range of hospitality skills combined with managerial skills and sound knowledge of industry to coordinate hospitality operations. They operate independently, have responsibility for others and make a range of operational business decisions.</p> <p>This qualification provides a pathway to work in any hospitality industry sector as a departmental or small business manager. The diversity of employers includes restaurants, hotels, motels, catering operations, clubs, pubs, cafés, and coffee shops. This qualification allows for multiskilling and for acquiring targeted skills in accommodation services, cookery, food and beverage and gaming.</p> <p>The skills in this qualification must be applied in accordance with Commonwealth and State/Territory legislation, Australian standards and industry codes of practice.</p> <p>No occupational licensing, certification or specific legislative requirements apply to this qualification at the time of publication.</p> </div> </div> </div> </div>',
    course_duration_per_week = 78,
    offshore_tuition_fee = 18000,
    onshore_tuition_fee = 18000,
    enrolment_fee = 250,
    materials_fee = 450,
    entry_requirements = '<h4>Entry Requirements</h4><div> <div> <div> <div> <ul><li>Must be 18 years of age or older.</li> <li>Must provide proof of school studies which is equivalent to Australian Year 12 or other higher qualifications.</li> <li>Must provide valid academic IELTS* score of 6.0 overall with no band less than 5.5 or equivalent unless exempted or need to submit English Proficiency certificate from an approved ELICOS provider of upper intermediate level or above; or completion of substantial part of studies of at least an AQF Certificate IV qualification or higher within the last 2 years; or have successfully passed the Rockford College English Placement Test. For further details, please refer to the Department of Home Affairs (DOHA) website for Acceptable English and Exemptions.</li> <li>Participate in the Course Entry Requirement Interview.</li> <li>International Students must meet the Student Visa (SC500) requirements.* Note that other English Language Test such as PTE and TOEFL can be accepted.</li> </ul></div> </div> </div> </div>',
    apply_form = 'https://rockford.edu.au/course/sit50422-diploma-of-hospitality-management/',
    updated_at = NOW()
WHERE cricos_course_code = '112144H';
UPDATE courses SET
    course_description = '<div> <div> <div> <div> <p>This qualification reflects the role of highly skilled senior managers who use a broad range of hospitality skills combined with specialised managerial skills and substantial knowledge of industry to coordinate hospitality operations. They operate with significant autonomy and are responsible for making strategic business management decisions.</p> <p>This qualification provides a pathway to work in any hospitality industry sector and for a diversity of employers including restaurants, hotels, motels, catering operations, clubs, pubs, cafés, and coffee shops. This qualification allows for multi-skilling and for acquiring targeted skills in accommodation services, cookery, food and beverage and gaming.</p> <p>The skills in this qualification must be applied in accordance with Commonwealth and State/Territory legislation, Australian standards and industry codes of practice.</p> </div> </div> </div> </div>',
    course_duration_per_week = 104,
    offshore_tuition_fee = 24000,
    onshore_tuition_fee = 24000,
    enrolment_fee = 250,
    materials_fee = 600,
    entry_requirements = '<h4>Entry Requirements</h4><div> <div> <div> <div> <ul><li>Must be 18 years of age or older.</li> <li>Must provide proof of school studies which is equivalent to Australian Year 12 or other higher qualifications.</li> <li>Must provide valid academic IELTS* of at least 6.0 overall score or equivalent unless exempted or need to submit English Proficiency certificate from an approved ELICOS provider of upper intermediate level or above; or completion of substantial part of studies of at least an AQF Certificate IV qualification or higher within the last 2 years; or have successfully passed the Rockford College English Placement Test. For further details; please refer to the Department of Home Affairs (DOHA) website for Acceptable English and Exemptions.</li> <li>Participate in the Course Entry Requirement Interview.</li> <li>International Students must meet the Student Visa (SC500) requirements.</li> </ul><p>* Note that other English Language Test such as PTE and TOEFL can be accepted.</p> </div> </div> </div> </div>',
    apply_form = 'https://rockford.edu.au/course/sit60322-advanced-diploma-of-hospitality-management/',
    updated_at = NOW()
WHERE cricos_course_code = '112145G';
