-- TAFE SA (00092B) - Webscrape Update
UPDATE provider_institution SET intake_date='February, July', updated_at=NOW() WHERE cricos_provider_code='00092B';

UPDATE courses SET
    course_duration_per_week = 104,
    offshore_tuition_fee = 45290,
    onshore_tuition_fee = NULL,
    enrolment_fee = 2300,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '0100003';
UPDATE courses SET
    course_duration_per_week = 50,
    offshore_tuition_fee = 16080,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '064265A';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 8040,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '064266M';
UPDATE courses SET
    course_duration_per_week = 104,
    offshore_tuition_fee = 41520,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '066407J';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 8040,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '086001K';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 11805,
    onshore_tuition_fee = NULL,
    enrolment_fee = 550,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '090936F';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 9585,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '090954D';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 5875,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '090981A';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 9580,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '091139E';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 9070,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '091649E';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 9070,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '091697G';
UPDATE courses SET
    course_duration_per_week = 104,
    offshore_tuition_fee = 41520,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '092136M';
UPDATE courses SET
    course_duration_per_week = 104,
    offshore_tuition_fee = 41520,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '092137K';
UPDATE courses SET
    course_duration_per_week = 104,
    offshore_tuition_fee = 41520,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '092138J';
UPDATE courses SET
    course_duration_per_week = 78,
    offshore_tuition_fee = 26430,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '092418A';
UPDATE courses SET
    course_duration_per_week = 39,
    offshore_tuition_fee = 9080,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '092419M';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 10565,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '092587F';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 8410,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '093603C';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 16455,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '093604B';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 7875,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '093606M';
UPDATE courses SET
    course_duration_per_week = 104,
    offshore_tuition_fee = 28785,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '094561M';
UPDATE courses SET
    course_duration_per_week = 78,
    offshore_tuition_fee = 22600,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '094562K';
UPDATE courses SET
    course_duration_per_week = 156,
    offshore_tuition_fee = 52720,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '099074G';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 17575,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '099075G';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 18135,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '103612D';
UPDATE courses SET
    course_duration_per_week = 78,
    offshore_tuition_fee = 21360,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '104666D';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 18705,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '104670H';
UPDATE courses SET
    course_duration_per_week = 130,
    offshore_tuition_fee = 50300,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '104672F';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 17885,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '104847K';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 10895,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '105563C';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 17960,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '105802D';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 19205,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '105815K';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 7875,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '106024M';
UPDATE courses SET
    course_duration_per_week = 104,
    offshore_tuition_fee = 70260,
    onshore_tuition_fee = NULL,
    enrolment_fee = 10000,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '107254M';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 15740,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '107350M';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 17580,
    onshore_tuition_fee = NULL,
    enrolment_fee = 1050,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '107363F';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 19800,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '108424A';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 15285,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '108425M';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 18705,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '108426K';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 21365,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '108455E';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 21365,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '108456D';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 15760,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '109109D';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 12615,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '109486A';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 12040,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '109627D';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 16950,
    onshore_tuition_fee = NULL,
    enrolment_fee = 550,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '109755G';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 16950,
    onshore_tuition_fee = NULL,
    enrolment_fee = 550,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '109764F';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 15760,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '110568M';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 12095,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '111778D';
UPDATE courses SET
    course_duration_per_week = 92,
    offshore_tuition_fee = 22935,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '111779C';
UPDATE courses SET
    course_duration_per_week = 78,
    offshore_tuition_fee = 28390,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '111780K';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 14490,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '111781J';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 14490,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '111782H';
UPDATE courses SET
    course_duration_per_week = 92,
    offshore_tuition_fee = 36960,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '111783G';
UPDATE courses SET
    course_duration_per_week = 104,
    offshore_tuition_fee = 37640,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '111974M';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 7875,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '112001A';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 20470,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '112006G';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 18825,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '112280M';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 18825,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '112281K';
UPDATE courses SET
    course_duration_per_week = 39,
    offshore_tuition_fee = 11985,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '113727K';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 7875,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '113728J';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 15760,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '113729H';
UPDATE courses SET
    course_duration_per_week = 104,
    offshore_tuition_fee = 36105,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '114486C';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 11805,
    onshore_tuition_fee = NULL,
    enrolment_fee = 550,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '114650G';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 9585,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '114651F';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 5875,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '114652E';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 9580,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '114653D';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 7875,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '114654C';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 15745,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '114655B';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 16455,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '114657M';
UPDATE courses SET
    course_duration_per_week = 63,
    offshore_tuition_fee = 12315,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '115249H';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 10895,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '117143B';
UPDATE courses SET
    course_duration_per_week = 104,
    offshore_tuition_fee = 41520,
    onshore_tuition_fee = NULL,
    enrolment_fee = 2000,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '117357K';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 10895,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '117361C';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 12095,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '118243A';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 14545,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '118570H';
UPDATE courses SET
    course_duration_per_week = 63,
    offshore_tuition_fee = 12315,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '118875B';
UPDATE courses SET
    course_duration_per_week = 22,
    offshore_tuition_fee = 8410,
    onshore_tuition_fee = NULL,
    enrolment_fee = 235,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '119499B';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 14490,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '119573H';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 9070,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '120261C';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 19800,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '120446E';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 19800,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = '',
    updated_at = NOW()
WHERE cricos_course_code = '120447D';
