-- Update provider institution details
UPDATE provider_institution SET
    intake_date = 'January, February, March, April, May, June, July, August, September, October, November, December',
    updated_at = NOW()
WHERE cricos_provider_code = '03904B';

UPDATE courses SET
    course_description = '<h4>Course Overview</h4> <p><strong>RII60520 – Advanced Diploma of Civil Construction Design </strong> reflects the role of an individual working as a senior civil works designer or a para-professional designer, who supports professional engineers. They perform tasks that are broad, specialised, complex and technical and include strategic areas and initiating activities. They are responsible for the design of complex projects to ensure the implementation of the client’s site requirements and are required to demonstrate self-directed application of theoretical and technical knowledge and initiate solutions to technical problems or management requirements.</p> <ul><li>This qualification will only fulfil the<strong> academic requirements, </strong>not a licensed trade qualification.</li> </ul>',
    course_duration_per_week = 104,
    offshore_tuition_fee = 29000,
    onshore_tuition_fee = 27000,
    enrolment_fee = 200,
    materials_fee = NULL,
    entry_requirements = '<h4>Entry Requirements</h4> <p>Successful completion of Australian year 12 or equivalent is mandatory.</p> <p>Students must be 18 years old and above.</p> <p>English requirement</p><p>A minimum of IELTS 6.0 or equivalent is required.</p><p>For more information regarding the commonly acceptable types of English language proficiency evidence, along with the verification methods, please <a href="https://reachcollege.edu.au/courses/english/">click here</a></p><p>Student Requirements</p><p>Students are required to have their own laptop prior to the commencement of their course.</p><p>The minimum requirements for the specification of laptops can be found in the Student Equipment Required section below.</p><p>Language, Literacy, Numeracy, and Digital skills (LLND)​</p><p>Prior to enrolment, all prospective students are required to complete a compulsory Language, Literacy, Numeracy and Digital (LLND) assessment. This assessment is completed as part of the pre-enrolment process through the LLND Portal – <a href="https://myllnd.com/login/">myllnd.com/login/</a></p><p>The LLND assessment helps identify whether a student may need additional support during their studies and ensures they are placed in a course that is appropriate for their skill level. Assessments are aligned with the Australian Core Skills Framework (ACSF) and include language, literacy, numeracy and digital skills.</p><p>Students must complete their LLND assessment via the LLND Portal before they can be formally enrolled. Further instructions on how to access and complete the assessment will be provided to prospective students as part of the pre-enrolment process.</p>',
    apply_form = 'https://reachcollege.edu.au/courses/building-construction/advanced-diploma-of-civil-construction-design/',
    updated_at = NOW()
WHERE cricos_course_code = '106655B';
UPDATE courses SET
    course_description = '<h4>Course Overview</h4> <p><strong>RII50520 – Diploma of Civil Construction Design </strong>reflects the role of individuals working as designers or design paraprofessionals who support professional engineers. They perform tasks involving a high level of autonomy and requiring the application of significant judgement in planning and determining the selection of equipment/roles/techniques for themselves and others. They are required to develop site specific work designs to ensure the implementation of the client’s site requirements. They demonstrate the application of a broad range of technical, managerial, coordination and planning skills.</p> <ul><li>This qualification will only fulfil the<strong> academic requirements, </strong>not a licensed trade qualification.</li> </ul>',
    course_duration_per_week = 52,
    offshore_tuition_fee = 19000,
    onshore_tuition_fee = 17000,
    enrolment_fee = 200,
    materials_fee = NULL,
    entry_requirements = '<h4>Entry Requirements</h4> <p>Successful completion of Australian year 12 or equivalent is mandatory.</p> <p>Students must be 18 years old and above.</p> <p>English requirement</p><p>A minimum of IELTS 6.0 or equivalent is required.</p><p>For more information regarding the commonly acceptable types of English language proficiency evidence, along with the verification methods, please <a href="https://reachcollege.edu.au/courses/english/">click here</a></p><p>Student Requirements</p><p>Students are required to have their own laptop prior to the commencement of their course.</p><p>The minimum requirements for the specification of laptops can be found in the Student Equipment Required section below.</p><p>Language, Literacy, Numeracy, and Digital skills (LLND)​</p><p>Prior to enrolment, all prospective students are required to complete a compulsory Language, Literacy, Numeracy and Digital (LLND) assessment. This assessment is completed as part of the pre-enrolment process through the LLND Portal – <a href="https://myllnd.com/login/">myllnd.com/login/</a></p><p>The LLND assessment helps identify whether a student may need additional support during their studies and ensures they are placed in a course that is appropriate for their skill level. Assessments are aligned with the Australian Core Skills Framework (ACSF) and include language, literacy, numeracy and digital skills.</p><p>Students must complete their LLND assessment via the LLND Portal before they can be formally enrolled. Further instructions on how to access and complete the assessment will be provided to prospective students as part of the pre-enrolment process.</p>',
    apply_form = 'https://reachcollege.edu.au/courses/building-construction/diploma-of-civil-construction-design/',
    updated_at = NOW()
WHERE cricos_course_code = '106654C';
UPDATE courses SET
    course_description = '<h4>Course Overview</h4> <p><strong>FNS60222 – Advanced Diploma of Accounting</strong> reflects the role of individuals working in accounting and seeking professional recognition, including tax agents, accounts managers and business analysts; and to employees performing a range of accounts management tasks for organisations in a range of industries. At this level individuals are expected to apply theoretical and technical skills in a range of situations and to display initiative and judgement in planning activities. They have autonomy in performing complex operations and can be responsible for planning, coordinating and evaluating the work of others within broad but generally well-defined parameters.</p>',
    course_duration_per_week = 52,
    offshore_tuition_fee = 16000,
    onshore_tuition_fee = 14000,
    enrolment_fee = 200,
    materials_fee = NULL,
    entry_requirements = '<h4>Entry Requirements</h4> <p>Prior to commencing this qualification an individual must have completed the following qualifications (or equivalent).</p> <ul><li>FNS50222 Diploma of Accounting; or its superseded version FNS50217 Diploma of Accounting or equivalent, provided the listed elective unit BSBTEC402 Design and produce complex spreadsheets (or equivalent) has been completed by those seeking to enrol.</li> </ul><p>Students must be 18 years old and above.</p> <p>Successful completion of Australian Year 12 or Australian equivalent is mandatory.</p> <p>English requirement</p><p>A minimum of IELTS 6.0 or equivalent is required.</p><p>For more information regarding the commonly acceptable types of English language proficiency evidence, along with the verification methods, please <a href="https://reachcollege.edu.au/courses/english/">click here</a></p><p>Student Requirements</p><p>Students are required to have their own laptop prior to the commencement of their course.</p><p>The minimum requirements for the specification of laptops can be found in the Student Equipment Required section below.</p><p>Language, Literacy, Numeracy, and Digital skills (LLND)​</p><p>Prior to enrolment, all prospective students are required to complete a compulsory Language, Literacy, Numeracy and Digital (LLND) assessment. This assessment is completed as part of the pre-enrolment process through the LLND Portal – <a href="https://myllnd.com/login/">myllnd.com/login/</a></p><p>The LLND assessment helps identify whether a student may need additional support during their studies and ensures they are placed in a course that is appropriate for their skill level. Assessments are aligned with the Australian Core Skills Framework (ACSF) and include language, literacy, numeracy and digital skills.</p><p>Students must complete their LLND assessment via the LLND Portal before they can be formally enrolled. Further instructions on how to access and complete the assessment will be provided to prospective students as part of the pre-enrolment process.</p>',
    apply_form = 'https://reachcollege.edu.au/courses/business/advanced-diploma-of-accounting/',
    updated_at = NOW()
WHERE cricos_course_code = '114548E';
UPDATE courses SET
    course_description = '<h4>Course Overview</h4> <p><strong>BSB60120 – Advanced Diploma of Business</strong> reflects the role of individuals with significant experience in a senior administrative role who are seeking to develop expertise across a wider range of business functions.</p> <p>The qualification is suited to individuals who possess significant theoretical business skills and knowledge and wish to consolidate and build pathways to further educational or employment opportunities.</p>',
    course_duration_per_week = 52,
    offshore_tuition_fee = 15000,
    onshore_tuition_fee = 12000,
    enrolment_fee = 200,
    materials_fee = NULL,
    entry_requirements = '<h4>Entry Requirements</h4> <p><strong>Entry to this qualification is limited to those who:</strong></p> <p>Have completed a Diploma or Advanced Diploma from the BSB Training Package (current or superseded equivalent versions).</p> <p>or</p> <p>Have two years equivalent full-time relevant workplace experience in an operational or leadership role in an enterprise.</p> <p>Successful completion of Australian Year 12 or Australian equivalent is mandatory.</p> <p>Students must be 18 years old and above.</p> <p>English requirement</p><p>A minimum of IELTS 6.0 or equivalent is required.</p><p>For more information regarding the commonly acceptable types of English language proficiency evidence, along with the verification methods, please <a href="https://reachcollege.edu.au/courses/english/">click here</a></p><p>Student Requirements</p><p>Students are required to have their own laptop prior to the commencement of their course.</p><p>The minimum requirements for the specification of laptops can be found in the Student Equipment Required section below.</p><p>Language, Literacy, Numeracy, and Digital skills (LLND)​</p><p>Prior to enrolment, all prospective students are required to complete a compulsory Language, Literacy, Numeracy and Digital (LLND) assessment. This assessment is completed as part of the pre-enrolment process through the LLND Portal – <a href="https://myllnd.com/login/">myllnd.com/login/</a></p><p>The LLND assessment helps identify whether a student may need additional support during their studies and ensures they are placed in a course that is appropriate for their skill level. Assessments are aligned with the Australian Core Skills Framework (ACSF) and include language, literacy, numeracy and digital skills.</p><p>Students must complete their LLND assessment via the LLND Portal before they can be formally enrolled. Further instructions on how to access and complete the assessment will be provided to prospective students as part of the pre-enrolment process.</p>',
    apply_form = 'https://reachcollege.edu.au/courses/business/advanced-diploma-of-business/',
    updated_at = NOW()
WHERE cricos_course_code = '105391G';
UPDATE courses SET
    course_description = '<h4>Course Overview</h4> <p><strong>BSB60420 – Advanced Diploma of Leadership and Management </strong>reflects the role of individuals who apply specialised knowledge and skills, together with experience in leadership and management, across a range of enterprise and industry contexts.</p> <p>Individuals at this level use initiative and judgement to plan and implement a range of leadership and management functions, with accountability for personal and team outcomes within broad parameters.</p> <p>They use cognitive and communication skills to identify, analyse and synthesise information from a variety of sources and transfer their knowledge to others, and creative or conceptual skills to express ideas and perspectives or respond to complex problems.</p>',
    course_duration_per_week = 52,
    offshore_tuition_fee = 15000,
    onshore_tuition_fee = 12000,
    enrolment_fee = 200,
    materials_fee = NULL,
    entry_requirements = '<h4>Entry Requirements</h4> <p>Entry to this qualification is limited to those who:<br/> Have completed a Diploma or Advanced Diploma from the BSB Training Package (current or superseded equivalent versions).<br/> or<br/> Have two years equivalent full-time relevant workplace experience in an operational or leadership role in an enterprise.</p> <p>Students must be 18 years old and above.</p> <p>English requirement</p><p>A minimum of IELTS 6.0 or equivalent is required.</p><p>For more information regarding the commonly acceptable types of English language proficiency evidence, along with the verification methods, please <a href="https://reachcollege.edu.au/courses/english/">click here</a></p><p>Student Requirements</p><p>Students are required to have their own laptop prior to the commencement of their course.</p><p>The minimum requirements for the specification of laptops can be found in the Student Equipment Required section below.</p><p>Language, Literacy, Numeracy, and Digital skills (LLND)​</p><p>Prior to enrolment, all prospective students are required to complete a compulsory Language, Literacy, Numeracy and Digital (LLND) assessment. This assessment is completed as part of the pre-enrolment process through the LLND Portal – <a href="https://myllnd.com/login/">myllnd.com/login/</a></p><p>The LLND assessment helps identify whether a student may need additional support during their studies and ensures they are placed in a course that is appropriate for their skill level. Assessments are aligned with the Australian Core Skills Framework (ACSF) and include language, literacy, numeracy and digital skills.</p><p>Students must complete their LLND assessment via the LLND Portal before they can be formally enrolled. Further instructions on how to access and complete the assessment will be provided to prospective students as part of the pre-enrolment process.</p>',
    apply_form = 'https://reachcollege.edu.au/courses/business/advanced-diploma-of-leadership-and-management/',
    updated_at = NOW()
WHERE cricos_course_code = '105426A';
UPDATE courses SET
    course_description = '<h4>Course Overview</h4> <p><strong>BSB60720 – Advanced Diploma in Program Management</strong> reflects the role of individuals who apply specialised knowledge and skills, together with experience in program management across a range of enterprise and industry contexts.</p>',
    course_duration_per_week = 52,
    offshore_tuition_fee = 15000,
    onshore_tuition_fee = 12000,
    enrolment_fee = 200,
    materials_fee = NULL,
    entry_requirements = '<h4>Entry Requirements</h4> <p>Entry to this qualification is limited to those who:<br/> Have completed one of the following qualifications: BSB50820 Diploma of Project Management; or BSB51415 Diploma of Project Management (or a superseded equivalent version).<br/> or Have completed two years equivalent full-time relevant workplace experience at a significant level within a project or program environment within an enterprise.</p> <p>Successful completion of Australian Year 12 or Australian equivalent is mandatory.</p> <p>Students must be 18 years old and above.</p> <p>English requirement</p><p>A minimum of IELTS 6.0 or equivalent is required.</p><p>For more information regarding the commonly acceptable types of English language proficiency evidence, along with the verification methods, please <a href="https://reachcollege.edu.au/courses/english/">click here</a></p><p>Student Requirements</p><p>Students are required to have their own laptop prior to the commencement of their course.</p><p>The minimum requirements for the specification of laptops can be found in the Student Equipment Required section below.</p><p>Language, Literacy, Numeracy, and Digital skills (LLND)​</p><p>Prior to enrolment, all prospective students are required to complete a compulsory Language, Literacy, Numeracy and Digital (LLND) assessment. This assessment is completed as part of the pre-enrolment process through the LLND Portal – <a href="https://myllnd.com/login/">myllnd.com/login/</a></p><p>The LLND assessment helps identify whether a student may need additional support during their studies and ensures they are placed in a course that is appropriate for their skill level. Assessments are aligned with the Australian Core Skills Framework (ACSF) and include language, literacy, numeracy and digital skills.</p><p>Students must complete their LLND assessment via the LLND Portal before they can be formally enrolled. Further instructions on how to access and complete the assessment will be provided to prospective students as part of the pre-enrolment process.</p>',
    apply_form = 'https://reachcollege.edu.au/courses/business/advanced-diploma-of-program-management/',
    updated_at = NOW()
WHERE cricos_course_code = '106649M';
UPDATE courses SET
    course_description = '<h4>Course Overview</h4> <p><strong>TLI60222 – Advanced Diploma of Supply Chain Management</strong> reflects a person who provides leadership and strategic direction in planning and managing supply chain logistics.</p> <p>Successful achievement of this qualification requires the application of a significant range of fundamental principles and complex techniques across a wide and often unpredictable variety of contexts in relation to either varied or highly specific functions. Contribution to developing a broad plan, budget or strategy is involved and accountability and responsibility for self and others in achieving the outcomes is also involved. Significant judgement is required in planning, design, technical or leadership/guidance functions related to products, services, operations or procedures.</p>',
    course_duration_per_week = 52,
    offshore_tuition_fee = 12500,
    onshore_tuition_fee = 12500,
    enrolment_fee = 200,
    materials_fee = NULL,
    entry_requirements = '<h4>Entry Requirements</h4> <p>Successfully completion of Australian Year 12 or Australian equivalent is mandatory.</p> <p>Students must be 18 years old and above.</p> <p>English requirement</p><p>A minimum of IELTS 6.0 or equivalent is required.</p><p>For more information regarding the commonly acceptable types of English language proficiency evidence, along with the verification methods, please <a href="https://reachcollege.edu.au/courses/english/">click here</a></p><p>Student Requirements</p><p>Students are required to have their own laptop prior to the commencement of their course.</p><p>The minimum requirements for the specification of laptops can be found in the Student Equipment Required section below.</p><p>Language, Literacy, Numeracy, and Digital skills (LLND)​</p><p>Prior to enrolment, all prospective students are required to complete a compulsory Language, Literacy, Numeracy and Digital (LLND) assessment. This assessment is completed as part of the pre-enrolment process through the LLND Portal – <a href="https://myllnd.com/login/">myllnd.com/login/</a></p><p>The LLND assessment helps identify whether a student may need additional support during their studies and ensures they are placed in a course that is appropriate for their skill level. Assessments are aligned with the Australian Core Skills Framework (ACSF) and include language, literacy, numeracy and digital skills.</p><p>Students must complete their LLND assessment via the LLND Portal before they can be formally enrolled. Further instructions on how to access and complete the assessment will be provided to prospective students as part of the pre-enrolment process.</p>',
    apply_form = 'https://reachcollege.edu.au/courses/business/advanced-diploma-of-supply-chain-management/',
    updated_at = NOW()
WHERE cricos_course_code = '111988E';
UPDATE courses SET
    course_description = '<h4>Course Overview</h4> <p><strong>FNS40222 – Certificate IV in Accounting and Bookkeeping</strong> reflects the job roles of workers in the accounting industry, including BAS Agents and contract bookkeepers; and of those employees performing bookkeeping tasks for organisations in a range of industries. It includes preparing and lodging business and instalment activity statements, and providing advice or dealing with the Commissioner on behalf of a taxpayer in relation to activity statements. Individuals in these roles apply theoretical and specialist knowledge and skills to work autonomously, and exercise judgement in completing routine and non-routine activities.</p>',
    course_duration_per_week = 52,
    offshore_tuition_fee = 14000,
    onshore_tuition_fee = 12000,
    enrolment_fee = 200,
    materials_fee = NULL,
    entry_requirements = '<h4>Entry Requirements</h4> <p>Students must be 18 years old and above.</p> <p>Successful completion of Australian Year 12 or Australian equivalent is mandatory.</p> <p>English requirement</p><p>A minimum of IELTS 6.0 or equivalent is required.</p><p>For more information regarding the commonly acceptable types of English language proficiency evidence, along with the verification methods, please <a href="https://reachcollege.edu.au/courses/english/">click here</a></p><p>Student Requirements</p><p>Students are required to have their own laptop prior to the commencement of their course.</p><p>The minimum requirements for the specification of laptops can be found in the Student Equipment Required section below.</p><p>Language, Literacy, Numeracy, and Digital skills (LLND)​</p><p>Prior to enrolment, all prospective students are required to complete a compulsory Language, Literacy, Numeracy and Digital (LLND) assessment. This assessment is completed as part of the pre-enrolment process through the LLND Portal – <a href="https://myllnd.com/login/">myllnd.com/login/</a></p><p>The LLND assessment helps identify whether a student may need additional support during their studies and ensures they are placed in a course that is appropriate for their skill level. Assessments are aligned with the Australian Core Skills Framework (ACSF) and include language, literacy, numeracy and digital skills.</p><p>Students must complete their LLND assessment via the LLND Portal before they can be formally enrolled. Further instructions on how to access and complete the assessment will be provided to prospective students as part of the pre-enrolment process.</p>',
    apply_form = 'https://reachcollege.edu.au/courses/business/certificate-iv-in-accounting-and-bookkeeping/',
    updated_at = NOW()
WHERE cricos_course_code = '110024K';
UPDATE courses SET
    course_description = '<h4>Course Overview</h4> <p><strong>FNS50222 – Diploma of Accounting</strong> reflects professional accounting job roles in financial services and other industries, including tax agents, accounts payable and accounts receivable officers, payroll service providers, and employees performing a range of accounting tasks for organisations in a range of industries. Individuals in these roles apply solutions to a range of often complex problems, and analyse and evaluate information from a variety of sources. They apply initiative to plan, coordinate and evaluate their own work and provide guidance to others within defined guidelines.</p>',
    course_duration_per_week = 52,
    offshore_tuition_fee = 12000,
    onshore_tuition_fee = 12000,
    enrolment_fee = 200,
    materials_fee = NULL,
    entry_requirements = '<h4>Entry Requirements</h4> <p>Prior to commencing this qualification an individual must have completed the following units of competency (or equivalent).</p> <p>FNSACC321 Process financial transactions and extract interim reports<br/> FNSACC322 Administer subsidiary accounts and ledgers<br/> FNSACC418 Work effectively in the accounting and bookkeeping industry<br/> FNSACC421 Prepare financial reports (this unit is the equivalent version of BSBFIA401 Prepare financial reports).<br/> These competencies may have been achieved through completion of the following (or their equivalent):</p> <p>FNSSS00014 Accounting Principles Skill Set<br/> or</p> <p>FNS40222 Certificate IV in Accounting and Bookkeeping.</p> <p>Students must be 18 years old and above.</p> <p>Successful completion of Australian Year 12 or Australian equivalent is mandatory.</p> <p>English requirement</p><p>A minimum of IELTS 6.0 or equivalent is required.</p><p>For more information regarding the commonly acceptable types of English language proficiency evidence, along with the verification methods, please <a href="https://reachcollege.edu.au/courses/english/">click here</a></p><p>Student Requirements</p><p>Students are required to have their own laptop prior to the commencement of their course.</p><p>The minimum requirements for the specification of laptops can be found in the Student Equipment Required section below.</p><p>Language, Literacy, Numeracy, and Digital skills (LLND)​</p><p>Prior to enrolment, all prospective students are required to complete a compulsory Language, Literacy, Numeracy and Digital (LLND) assessment. This assessment is completed as part of the pre-enrolment process through the LLND Portal – <a href="https://myllnd.com/login/">myllnd.com/login/</a></p><p>The LLND assessment helps identify whether a student may need additional support during their studies and ensures they are placed in a course that is appropriate for their skill level. Assessments are aligned with the Australian Core Skills Framework (ACSF) and include language, literacy, numeracy and digital skills.</p><p>Students must complete their LLND assessment via the LLND Portal before they can be formally enrolled. Further instructions on how to access and complete the assessment will be provided to prospective students as part of the pre-enrolment process.</p>',
    apply_form = 'https://reachcollege.edu.au/courses/business/diploma-of-accounting/',
    updated_at = NOW()
WHERE cricos_course_code = '114547F';
UPDATE courses SET
    course_description = '<h4>Course Overview</h4> <p><strong>BSB50420 – Diploma of Leadership and Management</strong> reflects the role of individuals who apply knowledge, practical skills and experience in leadership and management across a range of enterprise and industry contexts.</p>',
    course_duration_per_week = 52,
    offshore_tuition_fee = 14000,
    onshore_tuition_fee = 11000,
    enrolment_fee = 200,
    materials_fee = NULL,
    entry_requirements = '<h4>Entry Requirements</h4> <p>Successful completion of Australian Year 12 or Australian equivalent is mandatory.</p> <p>Students must be 18 years old and above.</p> <p>English requirement</p><p>A minimum of IELTS 6.0 or equivalent is required.</p><p>For more information regarding the commonly acceptable types of English language proficiency evidence, along with the verification methods, please <a href="https://reachcollege.edu.au/courses/english/">click here</a></p><p>Student Requirements</p><p>Students are required to have their own laptop prior to the commencement of their course.</p><p>The minimum requirements for the specification of laptops can be found in the Student Equipment Required section below.</p><p>Language, Literacy, Numeracy, and Digital skills (LLND)​</p><p>Prior to enrolment, all prospective students are required to complete a compulsory Language, Literacy, Numeracy and Digital (LLND) assessment. This assessment is completed as part of the pre-enrolment process through the LLND Portal – <a href="https://myllnd.com/login/">myllnd.com/login/</a></p><p>The LLND assessment helps identify whether a student may need additional support during their studies and ensures they are placed in a course that is appropriate for their skill level. Assessments are aligned with the Australian Core Skills Framework (ACSF) and include language, literacy, numeracy and digital skills.</p><p>Students must complete their LLND assessment via the LLND Portal before they can be formally enrolled. Further instructions on how to access and complete the assessment will be provided to prospective students as part of the pre-enrolment process.</p>',
    apply_form = 'https://reachcollege.edu.au/courses/business/diploma-of-leadership-and-management/',
    updated_at = NOW()
WHERE cricos_course_code = '108801C';
UPDATE courses SET
    course_description = '<h4>Course Overview</h4> <p><strong>TLI50224 – Diploma of Logistics</strong> is a general qualification for the integrated management of logistics.</p> <p>Achievement of this qualification will require the self-directed application of knowledge and skills, with substantial depth in some areas where judgement is required in planning and selecting appropriate equipment, services and techniques for self and others.</p> <p>Applications involve participation in the development of strategic initiatives as well as personal responsibility and autonomy in performing complex technical operations or organising others. It may include participation in teams, including those concerned with planning and evaluation functions. Group or team coordination may be involved.</p> <p>Successful achievement of the licensing units within the qualification must align with applicable licensing and regulatory requirements.</p>',
    course_duration_per_week = 52,
    offshore_tuition_fee = 10500,
    onshore_tuition_fee = 10500,
    enrolment_fee = 200,
    materials_fee = NULL,
    entry_requirements = '<h4>Entry Requirements</h4> <p>Successful completion of Australian Year 12 or Australian equivalent is mandatory.</p> <p>Students must be 18 years old and above.</p> <p>English requirement</p><p>A minimum of IELTS 6.0 or equivalent is required.</p><p>For more information regarding the commonly acceptable types of English language proficiency evidence, along with the verification methods, please <a href="https://reachcollege.edu.au/courses/english/">click here</a></p><p>Student Requirements</p><p>Students are required to have their own laptop prior to the commencement of their course.</p><p>The minimum requirements for the specification of laptops can be found in the Student Equipment Required section below.</p><p>Language, Literacy, Numeracy, and Digital skills (LLND)​</p><p>Prior to enrolment, all prospective students are required to complete a compulsory Language, Literacy, Numeracy and Digital (LLND) assessment. This assessment is completed as part of the pre-enrolment process through the LLND Portal – <a href="https://myllnd.com/login/">myllnd.com/login/</a></p><p>The LLND assessment helps identify whether a student may need additional support during their studies and ensures they are placed in a course that is appropriate for their skill level. Assessments are aligned with the Australian Core Skills Framework (ACSF) and include language, literacy, numeracy and digital skills.</p><p>Students must complete their LLND assessment via the LLND Portal before they can be formally enrolled. Further instructions on how to access and complete the assessment will be provided to prospective students as part of the pre-enrolment process.</p>',
    apply_form = 'https://reachcollege.edu.au/courses/business/diploma-of-logistics/',
    updated_at = NOW()
WHERE cricos_course_code = '117272D';
UPDATE courses SET
    course_description = '<h4>Course Overview</h4> <p><strong>BSB50820 – Diploma of Project Management</strong> reflects the role of individuals who apply project management skills and knowledge in a variety of contexts, across a number of industry sectors. The job roles that relate to this qualification may include Project Manager and Project Team Leader.</p> <p>Individuals in these roles have project leadership and management roles and are responsible for achieving project objectives. They possess a sound theoretical knowledge base and use a range of specialised, technical and managerial competencies to initiate, plan, execute and evaluate their own work and/or the work of others.</p>',
    course_duration_per_week = 52,
    offshore_tuition_fee = 14000,
    onshore_tuition_fee = 11000,
    enrolment_fee = 200,
    materials_fee = NULL,
    entry_requirements = '<h4>Entry Requirements</h4> <p>Successfully completion of Australian Year 12 or Australian equivalent is mandatory.</p> <p>Students must be 18 years old and above.</p> <p>English requirement</p><p>A minimum of IELTS 6.0 or equivalent is required.</p><p>For more information regarding the commonly acceptable types of English language proficiency evidence, along with the verification methods, please <a href="https://reachcollege.edu.au/courses/english/">click here</a></p><p>Student Requirements</p><p>Students are required to have their own laptop prior to the commencement of their course.</p><p>The minimum requirements for the specification of laptops can be found in the Student Equipment Required section below.</p><p>Language, Literacy, Numeracy, and Digital skills (LLND)​</p><p>Prior to enrolment, all prospective students are required to complete a compulsory Language, Literacy, Numeracy and Digital (LLND) assessment. This assessment is completed as part of the pre-enrolment process through the LLND Portal – <a href="https://myllnd.com/login/">myllnd.com/login/</a></p><p>The LLND assessment helps identify whether a student may need additional support during their studies and ensures they are placed in a course that is appropriate for their skill level. Assessments are aligned with the Australian Core Skills Framework (ACSF) and include language, literacy, numeracy and digital skills.</p><p>Students must complete their LLND assessment via the LLND Portal before they can be formally enrolled. Further instructions on how to access and complete the assessment will be provided to prospective students as part of the pre-enrolment process.</p>',
    apply_form = 'https://reachcollege.edu.au/courses/business/diploma-of-project-management/',
    updated_at = NOW()
WHERE cricos_course_code = '105425B';
UPDATE courses SET
    course_description = '<h4>Course Overview</h4> <p><strong>BSB80120 – Graduate Diploma of Management (Learning)</strong> reflects the role of individuals who apply highly specialised knowledge and skills in the field of organisational learning and capability development. Individuals in these roles generate and evaluate complex ideas. They also initiate, design and execute major learning and development functions within an organisation. Typically, they would have full responsibility and accountability for the personal output and work of others.</p> <p>This qualification may apply to leaders and managers in an organisation where learning is used to build organisational capability. The job roles that relate to this qualification may also include RTO Manager and RTO Director.</p>',
    course_duration_per_week = 52,
    offshore_tuition_fee = 16000,
    onshore_tuition_fee = 13000,
    enrolment_fee = 200,
    materials_fee = NULL,
    entry_requirements = '<h4>Entry Requirements</h4> <p>Please be advised that students must attend a pre-consultation interview before enrolling in this qualification. This interview is conducted to assess their suitability for the course.</p> <p>Successful completion of Advanced Diploma Qualification or Bachelor Degree or work experience in the field of organisational learning and capability development.</p> <p>Students must be 18 years old and above.</p> <p>English requirement</p><p>A minimum of IELTS 6.5 or equivalent is required.</p><p>For more information regarding the commonly acceptable types of English language proficiency evidence, along with the verification methods, please <a href="https://reachcollege.edu.au/courses/english/">click here</a></p><p>Student Requirements</p><p>Students are required to have their own laptop prior to the commencement of their course.</p><p>The minimum requirements for the specification of laptops can be found in the Student Equipment Required section below.</p><p>Language, Literacy, Numeracy, and Digital skills (LLND)​</p><p>Prior to enrolment, all prospective students are required to complete a compulsory Language, Literacy, Numeracy and Digital (LLND) assessment. This assessment is completed as part of the pre-enrolment process through the LLND Portal – <a href="https://myllnd.com/login/">myllnd.com/login/</a></p><p>The LLND assessment helps identify whether a student may need additional support during their studies and ensures they are placed in a course that is appropriate for their skill level. Assessments are aligned with the Australian Core Skills Framework (ACSF) and include language, literacy, numeracy and digital skills.</p><p>Students must complete their LLND assessment via the LLND Portal before they can be formally enrolled. Further instructions on how to access and complete the assessment will be provided to prospective students as part of the pre-enrolment process.</p>',
    apply_form = 'https://reachcollege.edu.au/courses/business/graduate-diploma-of-management-learning/',
    updated_at = NOW()
WHERE cricos_course_code = '105392F';
UPDATE courses SET
    course_description = '<h4>Course Overview</h4> <p><strong>BSB80320 – Graduate Diploma of Strategic Leadership </strong>reflects the role of individuals who apply advanced knowledge and skills in a range of strategic leadership and management roles.</p> <p>Individuals at this level make high level autonomous decisions and use initiative and judgement to plan and implement a range of leadership and management functions in varied contexts. They have full responsibility and accountability for personal outputs and for the work or function of others.</p> <p>They use cognitive and creative skills to review, critically analyse, consolidate and synthesise knowledge, in order to generate ideas and provide solutions to complex problems. They use communication skills to demonstrate their understanding of theoretical concepts and to transfer knowledge and ideas to others.</p>',
    course_duration_per_week = 52,
    offshore_tuition_fee = 16000,
    onshore_tuition_fee = 13000,
    enrolment_fee = 200,
    materials_fee = NULL,
    entry_requirements = '<h4>Entry Requirements</h4> <p>Please be advised that students must attend a pre-consultation interview before enrolling in this qualification. This interview is conducted to assess their suitability for the course.</p> <p>Students must be 18 years old and above.</p> <p><strong>Academic requirement:</strong></p> <p><strong>Entry to this qualification is limited to those who:</strong></p> <p>Have completed a Diploma or Advanced Diploma qualification in related fields of study and 3 years equivalent full-time relevant workplace experience at a significant level of leadership and management responsibility and/or complexity in an enterprise</p> <p>or</p> <p>Have completed a Bachelor degree in related fields of study and 2 years equivalent full-time relevant workplace experience at a significant level of leadership and management responsibility and/or complexity in an enterprise.</p> <p>or</p> <p>Have five years equivalent full-time relevant workplace experience at a significant level of leadership and management responsibility and/or complexity in an enterprise.</p> <p>English requirement</p><p>A minimum of IELTS 6.5 or equivalent is required.</p><p>For more information regarding the commonly acceptable types of English language proficiency evidence, along with the verification methods, please <a href="https://reachcollege.edu.au/courses/english/">click here</a></p><p>Student Requirements</p><p>Students are required to have their own laptop prior to the commencement of their course.</p><p>The minimum requirements for the specification of laptops can be found in the Student Equipment Required section below.</p><p>Language, Literacy, Numeracy, and Digital skills (LLND)​</p><p>Prior to enrolment, all prospective students are required to complete a compulsory Language, Literacy, Numeracy and Digital (LLND) assessment. This assessment is completed as part of the pre-enrolment process through the LLND Portal – <a href="https://myllnd.com/login/">myllnd.com/login/</a></p><p>The LLND assessment helps identify whether a student may need additional support during their studies and ensures they are placed in a course that is appropriate for their skill level. Assessments are aligned with the Australian Core Skills Framework (ACSF) and include language, literacy, numeracy and digital skills.</p><p>Students must complete their LLND assessment via the LLND Portal before they can be formally enrolled. Further instructions on how to access and complete the assessment will be provided to prospective students as part of the pre-enrolment process.</p>',
    apply_form = 'https://reachcollege.edu.au/courses/business/graduate-diploma-of-strategic-leadership/',
    updated_at = NOW()
WHERE cricos_course_code = '106650G';
UPDATE courses SET
    course_description = '<h4>Course Overview</h4> <p><strong>CHC62015 – Advanced Diploma Of Community Sector Management </strong>reflects the role of workers who are middle managers or managers across a range of community sector organisations. These people work independently and report to executive management, directors or boards of management. They undertake a range of functions requiring the application of knowledge and skills to achieve results in line with the organisation’s goals and strategic directions.</p> <p>At this level, workers have responsibility for planning and monitoring service delivery, recruitment and performance management of other paid or unpaid workers, managing risk and contributing to continuous improvement within the scope of their specific role. This may include management of a specific program or project or broader management of a community-based organisation, early childhood education service, not-for-profit organisation or community centre.</p> <p>This qualification does not require any Student Work Placement hours.</p>',
    course_duration_per_week = 52,
    offshore_tuition_fee = 16000,
    onshore_tuition_fee = 14000,
    enrolment_fee = 200,
    materials_fee = NULL,
    entry_requirements = '<h4>Entry Requirements</h4> <p>Successful completion of Australian Year 12 or Australian equivalent is mandatory.</p> <p>Students must be 18 years old and above.</p> <p>English requirement</p><p>A minimum of IELTS 6.0 or equivalent is required.</p><p>For more information regarding the commonly acceptable types of English language proficiency evidence, along with the verification methods, please <a href="https://reachcollege.edu.au/courses/english/">click here</a></p><p>Student Requirements</p><p>Students are required to have their own laptop prior to the commencement of their course.</p><p>The minimum requirements for the specification of laptops can be found in the Student Equipment Required section below.</p><p>Language, Literacy, Numeracy, and Digital skills (LLND)​</p><p>Prior to enrolment, all prospective students are required to complete a compulsory Language, Literacy, Numeracy and Digital (LLND) assessment. This assessment is completed as part of the pre-enrolment process through the LLND Portal – <a href="https://myllnd.com/login/">myllnd.com/login/</a></p><p>The LLND assessment helps identify whether a student may need additional support during their studies and ensures they are placed in a course that is appropriate for their skill level. Assessments are aligned with the Australian Core Skills Framework (ACSF) and include language, literacy, numeracy and digital skills.</p><p>Students must complete their LLND assessment via the LLND Portal before they can be formally enrolled. Further instructions on how to access and complete the assessment will be provided to prospective students as part of the pre-enrolment process.</p>',
    apply_form = 'https://reachcollege.edu.au/courses/community/advanced-diploma-of-community-sector-management/',
    updated_at = NOW()
WHERE cricos_course_code = '108799C';
UPDATE courses SET
    course_description = '<h4>Course Overview</h4> <p><strong>CHC33021– Certificate III in Individual Support (Ageing) </strong>reflects the role of individuals in the community, home or residential care setting who work under supervision and delegation as a part of a multi-disciplinary team, following an individualised plan to provide person-centred support to people who may require support due to ageing, disability or some other reason.</p> <p>These individuals take responsibility for their own outputs within the scope of their job role and delegation. Workers have a range of factual, technical and procedural knowledge, as well as some theoretical knowledge of the concepts and practices required to provide person-centred support.</p> <p>To achieve this qualification, the candidate must have completed at least <strong>120</strong> hours of work as detailed in the Assessment Requirements of the units of competency.</p>',
    course_duration_per_week = 52,
    offshore_tuition_fee = 14000,
    onshore_tuition_fee = 12000,
    enrolment_fee = 200,
    materials_fee = NULL,
    entry_requirements = '<h4>Entry Requirements</h4> <p>Successful completion of Australian Year 12 or Australian equivalent is mandatory.</p> <p>Students must be 18 years old and above.</p> <p>English requirement</p><p>A minimum of IELTS 6.0 or equivalent is required.</p><p>For more information regarding the commonly acceptable types of English language proficiency evidence, along with the verification methods, please <a href="https://reachcollege.edu.au/courses/english/">click here</a></p><p>Student Requirements</p><p>Students are required to have their own laptop prior to the commencement of their course.</p><p>The minimum requirements for the specification of laptops can be found in the Student Equipment Required section below.</p><p>Language, Literacy, Numeracy, and Digital skills (LLND)​</p><p>Prior to enrolment, all prospective students are required to complete a compulsory Language, Literacy, Numeracy and Digital (LLND) assessment. This assessment is completed as part of the pre-enrolment process through the LLND Portal – <a href="https://myllnd.com/login/">myllnd.com/login/</a></p><p>The LLND assessment helps identify whether a student may need additional support during their studies and ensures they are placed in a course that is appropriate for their skill level. Assessments are aligned with the Australian Core Skills Framework (ACSF) and include language, literacy, numeracy and digital skills.</p><p>Students must complete their LLND assessment via the LLND Portal before they can be formally enrolled. Further instructions on how to access and complete the assessment will be provided to prospective students as part of the pre-enrolment process.</p>',
    apply_form = 'https://reachcollege.edu.au/courses/community/certificate-iii-in-individual-support-ageing/',
    updated_at = NOW()
WHERE cricos_course_code = '114151D';
UPDATE courses SET
    course_description = '<h4>Course Overview</h4> <p><strong>CHC33021– Certificate III in Individual Support (Disability) </strong>reflects the role of individuals in the community, home or residential care setting who work under supervision and delegation as a part of a multi-disciplinary team, following an individualised plan to provide person-centred support to people who may require support due to ageing, disability or some other reason.</p> <p>These individuals take responsibility for their own outputs within the scope of their job role and delegation. Workers have a range of factual, technical and procedural knowledge, as well as some theoretical knowledge of the concepts and practices required to provide person-centred support.</p> <p>To achieve this qualification, the candidate must have completed at least 120 hours of work as detailed in the Assessment Requirements of the units of competency.</p>',
    course_duration_per_week = 52,
    offshore_tuition_fee = 14000,
    onshore_tuition_fee = 12000,
    enrolment_fee = 200,
    materials_fee = NULL,
    entry_requirements = '<h4>Entry Requirements</h4> <p>Successful completion of Australian Year 12 or Australian equivalent is mandatory.</p> <p>Students must be 18 years old and above.</p> <p>English requirement</p><p>A minimum of IELTS 6.0 or equivalent is required.</p><p>For more information regarding the commonly acceptable types of English language proficiency evidence, along with the verification methods, please <a href="https://reachcollege.edu.au/courses/english/">click here</a></p><p>Student Requirements</p><p>Students are required to have their own laptop prior to the commencement of their course.</p><p>The minimum requirements for the specification of laptops can be found in the Student Equipment Required section below.</p><p>Language, Literacy, Numeracy, and Digital skills (LLND)​</p><p>Prior to enrolment, all prospective students are required to complete a compulsory Language, Literacy, Numeracy and Digital (LLND) assessment. This assessment is completed as part of the pre-enrolment process through the LLND Portal – <a href="https://myllnd.com/login/">myllnd.com/login/</a></p><p>The LLND assessment helps identify whether a student may need additional support during their studies and ensures they are placed in a course that is appropriate for their skill level. Assessments are aligned with the Australian Core Skills Framework (ACSF) and include language, literacy, numeracy and digital skills.</p><p>Students must complete their LLND assessment via the LLND Portal before they can be formally enrolled. Further instructions on how to access and complete the assessment will be provided to prospective students as part of the pre-enrolment process.</p>',
    apply_form = 'https://reachcollege.edu.au/courses/community/certificate-iii-in-individual-support-disability/',
    updated_at = NOW()
WHERE cricos_course_code = '114151D';
UPDATE courses SET
    course_description = '<h4>Course Overview</h4> <p><strong>CHC43121 – Certificate IV In Disability Support</strong> reflects the role of individuals in a range of community settings and peoples’ homes, who provide support in a manner that empowers people with disabilities to achieve greater levels of independence, self-reliance, community participation and wellbeing. Workers promote a person-centred approach, work according to and may contribute to an individualised plan, and work without direct supervision. They may be required to supervise and/or coordinate a small team.</p> <p>To achieve this qualification, the candidate must have completed at least 40 hours of work as detailed in the Assessment Requirements of the units of competency.</p>',
    course_duration_per_week = 52,
    offshore_tuition_fee = 15000,
    onshore_tuition_fee = 13000,
    enrolment_fee = 200,
    materials_fee = NULL,
    entry_requirements = '<h4>Entry Requirements</h4> <p>Completion of: CHC33021 Certificate III in Individual Support (Disability)<br/> OR<br/> Completion of: CHC33015 Certificate III in Individual Support (Disability)<br/> OR<br/> Completion of: CHC30408 Certificate III in Disability PLUS the CHCSS00125 Entry to Certificate IV in Disability Support Skill Set.</p> <p>Successfully completion of Australian Year 12 or Australian equivalent is mandatory.</p> <p>Students must be 18 years old and above.</p> <p>English requirement</p><p>A minimum of IELTS 6.0 or equivalent is required.</p><p>For more information regarding the commonly acceptable types of English language proficiency evidence, along with the verification methods, please <a href="https://reachcollege.edu.au/courses/english/">click here</a></p><p>Student Requirements</p><p>Students are required to have their own laptop prior to the commencement of their course.</p><p>The minimum requirements for the specification of laptops can be found in the Student Equipment Required section below.</p><p>Language, Literacy, Numeracy, and Digital skills (LLND)​</p><p>Prior to enrolment, all prospective students are required to complete a compulsory Language, Literacy, Numeracy and Digital (LLND) assessment. This assessment is completed as part of the pre-enrolment process through the LLND Portal – <a href="https://myllnd.com/login/">myllnd.com/login/</a></p><p>The LLND assessment helps identify whether a student may need additional support during their studies and ensures they are placed in a course that is appropriate for their skill level. Assessments are aligned with the Australian Core Skills Framework (ACSF) and include language, literacy, numeracy and digital skills.</p><p>Students must complete their LLND assessment via the LLND Portal before they can be formally enrolled. Further instructions on how to access and complete the assessment will be provided to prospective students as part of the pre-enrolment process.</p>',
    apply_form = 'https://reachcollege.edu.au/courses/community/certificate-iv-in-disability/',
    updated_at = NOW()
WHERE cricos_course_code = '114152C';
UPDATE courses SET
    course_description = '<h4>Course Overview</h4> <p><strong>CHC52025 – Diploma of Community Services</strong> reflects the role of community services workers involved in the delivery, management and coordination of person-centred services to individuals, groups, and communities.</p> <p>At this level, workers have specialised skills in community services and work autonomously within their scope of practice under broad directions from senior management.</p> <p>Workers support people to make change in their lives to improve personal and social wellbeing and may also have responsibility for the supervision of other workers and volunteers. They may also undertake case management and program coordination.</p> <p>To achieve this qualification, the candidate must have completed at least 100 hours of work as detailed in the Assessment Requirements of the units of competency.</p>',
    course_duration_per_week = 52,
    offshore_tuition_fee = 16000,
    onshore_tuition_fee = 14000,
    enrolment_fee = 200,
    materials_fee = NULL,
    entry_requirements = '<h4>Entry Requirements</h4> <p>Successful completion of Australian Year 12 or Australian equivalent is mandatory.</p> <p>Students must be 18 years old and above.</p> <p>English requirement</p><p>A minimum of IELTS 6.0 or equivalent is required.</p><p>For more information regarding the commonly acceptable types of English language proficiency evidence, along with the verification methods, please <a href="https://reachcollege.edu.au/courses/english/">click here</a></p><p>Student Requirements</p><p>Students are required to have their own laptop prior to the commencement of their course.</p><p>The minimum requirements for the specification of laptops can be found in the Student Equipment Required section below.</p><p>Language, Literacy, Numeracy, and Digital skills (LLND)​</p><p>Prior to enrolment, all prospective students are required to complete a compulsory Language, Literacy, Numeracy and Digital (LLND) assessment. This assessment is completed as part of the pre-enrolment process through the LLND Portal – <a href="https://myllnd.com/login/">myllnd.com/login/</a></p><p>The LLND assessment helps identify whether a student may need additional support during their studies and ensures they are placed in a course that is appropriate for their skill level. Assessments are aligned with the Australian Core Skills Framework (ACSF) and include language, literacy, numeracy and digital skills.</p><p>Students must complete their LLND assessment via the LLND Portal before they can be formally enrolled. Further instructions on how to access and complete the assessment will be provided to prospective students as part of the pre-enrolment process.</p>',
    apply_form = 'https://reachcollege.edu.au/courses/community/diploma-of-community-services/',
    updated_at = NOW()
WHERE cricos_course_code = '118803G';
UPDATE courses SET
    course_description = '<h4>Course Overview</h4> <p><strong>SIT60322 – Advanced Diploma of Hospitality Management</strong> reflects the role of highly skilled senior managers who use a broad range of hospitality skills combined with specialised managerial skills and substantial knowledge of industry to coordinate hospitality operations. They operate with significant autonomy and are responsible for making strategic business management decisions.</p> <p>This qualification provides a pathway to work in any hospitality industry sector and for a diversity of employers including restaurants, hotels, motels, catering operations, clubs, pubs, cafés, and coffee shops. This qualification allows for multi-skilling and for specialisation in accommodation services, cookery, food and beverage and gaming.</p> <p><strong>Possible job titles include:</strong></p> <ul><li>area manager or operations manager</li> <li>café owner or manager</li> <li>club secretary or manager</li> <li>executive chef</li> <li>executive housekeeper</li> <li>executive sous chef</li> <li>food and beverage manager</li> <li>head chef</li> <li>motel owner or manager</li> <li>rooms division manager</li> </ul><p>Completion of an REACH qualification does not guarantee an employment outcome.</p> <p>No occupational licensing, certification or specific legislative requirements apply to this qualification at the time of publication.</p>',
    course_duration_per_week = 104,
    offshore_tuition_fee = 24000,
    onshore_tuition_fee = 22000,
    enrolment_fee = 200,
    materials_fee = NULL,
    entry_requirements = '<h4>Entry Requirements</h4> <p>Successfully completion of Australian Year 12 or Australian equivalent is mandatory.</p> <p>Students must be 18 years old and above.</p> <p>English requirement</p><p>A minimum of IELTS 6.0 or equivalent is required.</p><p>For more information regarding the commonly acceptable types of English language proficiency evidence, along with the verification methods, please <a href="https://reachcollege.edu.au/courses/english/">click here</a></p><p>Student Requirements</p><p>Students are required to have their own laptop prior to the commencement of their course.</p><p>The minimum requirements for the specification of laptops can be found in the Student Equipment Required section below.</p><p>Language, Literacy, Numeracy, and Digital skills (LLND)​</p><p>Prior to enrolment, all prospective students are required to complete a compulsory Language, Literacy, Numeracy and Digital (LLND) assessment. This assessment is completed as part of the pre-enrolment process through the LLND Portal – <a href="https://myllnd.com/login/">myllnd.com/login/</a></p><p>The LLND assessment helps identify whether a student may need additional support during their studies and ensures they are placed in a course that is appropriate for their skill level. Assessments are aligned with the Australian Core Skills Framework (ACSF) and include language, literacy, numeracy and digital skills.</p><p>Students must complete their LLND assessment via the LLND Portal before they can be formally enrolled. Further instructions on how to access and complete the assessment will be provided to prospective students as part of the pre-enrolment process.</p>',
    apply_form = 'https://reachcollege.edu.au/courses/hospitality/advanced-diploma-of-hospitality-management/',
    updated_at = NOW()
WHERE cricos_course_code = '114550M';
UPDATE courses SET
    course_description = '<h4>Course Overview</h4> <p><strong>SIT30821 – Certificate III in Commercial Cookery </strong>reflects the role of commercial cooks who use a wide range of well-developed cookery skills and sound knowledge of kitchen operations to prepare food and menu items. Using discretion and judgement, they work with some independence and under limited supervision using plans, policies and procedures to guide work activities.</p> <p>This qualification provides a pathway to work as a commercial cook in organisations such as restaurants, hotels, clubs, pubs, cafés, and coffee shops.</p> <p>No occupational licensing, certification or specific legislative requirements apply to this qualification at the time of publication.</p>',
    course_duration_per_week = 52,
    offshore_tuition_fee = 15000,
    onshore_tuition_fee = 13000,
    enrolment_fee = 200,
    materials_fee = NULL,
    entry_requirements = '<h4>Entry Requirements</h4> <p>Successful completion of Australian Year 12 or Australian equivalent is mandatory.</p> <p>Students must be 18 years old and above.</p> <p>English requirement</p><p>A minimum of IELTS 6.0 or equivalent is required.</p><p>For more information regarding the commonly acceptable types of English language proficiency evidence, along with the verification methods, please <a href="https://reachcollege.edu.au/courses/english/">click here</a></p><p>Student Requirements</p><p>Students are required to have their own laptop prior to the commencement of their course.</p><p>The minimum requirements for the specification of laptops can be found in the Student Equipment Required section below.</p><p>Language, Literacy, Numeracy, and Digital skills (LLND)​</p><p>Prior to enrolment, all prospective students are required to complete a compulsory Language, Literacy, Numeracy and Digital (LLND) assessment. This assessment is completed as part of the pre-enrolment process through the LLND Portal – <a href="https://myllnd.com/login/">myllnd.com/login/</a></p><p>The LLND assessment helps identify whether a student may need additional support during their studies and ensures they are placed in a course that is appropriate for their skill level. Assessments are aligned with the Australian Core Skills Framework (ACSF) and include language, literacy, numeracy and digital skills.</p><p>Students must complete their LLND assessment via the LLND Portal before they can be formally enrolled. Further instructions on how to access and complete the assessment will be provided to prospective students as part of the pre-enrolment process.</p>',
    apply_form = 'https://reachcollege.edu.au/courses/hospitality/certificate-iii-in-commercial-cookery/',
    updated_at = NOW()
WHERE cricos_course_code = '109904K';
UPDATE courses SET
    course_description = '<h4>Course Overview</h4> <p><strong>SIT40521 – Certificate IV in Kitchen Management</strong> reflects the role of commercial cooks who have a supervisory or team leading role in the kitchen. They operate independently or with limited guidance from others and use discretion to solve non-routine problems.</p> <p>This qualification provides a pathway to work in organisations such as restaurants, hotels, clubs, pubs, cafes and coffee shops, or to run a small business in these sectors.</p>',
    course_duration_per_week = 52,
    offshore_tuition_fee = 22000,
    onshore_tuition_fee = 19000,
    enrolment_fee = 200,
    materials_fee = NULL,
    entry_requirements = '<h4>Entry Requirements</h4> <p>Successfully completion of Australian Year 12 or Australian equivalent is mandatory.</p> <p>Students must be 18 years old and above.</p> <p>English requirement</p><p>A minimum of IELTS 6.0 or equivalent is required.</p><p>For more information regarding the commonly acceptable types of English language proficiency evidence, along with the verification methods, please <a href="https://reachcollege.edu.au/courses/english/">click here</a></p><p>Student Requirements</p><p>Students are required to have their own laptop prior to the commencement of their course.</p><p>The minimum requirements for the specification of laptops can be found in the Student Equipment Required section below.</p><p>Language, Literacy, Numeracy, and Digital skills (LLND)​</p><p>Prior to enrolment, all prospective students are required to complete a compulsory Language, Literacy, Numeracy and Digital (LLND) assessment. This assessment is completed as part of the pre-enrolment process through the LLND Portal – <a href="https://myllnd.com/login/">myllnd.com/login/</a></p><p>The LLND assessment helps identify whether a student may need additional support during their studies and ensures they are placed in a course that is appropriate for their skill level. Assessments are aligned with the Australian Core Skills Framework (ACSF) and include language, literacy, numeracy and digital skills.</p><p>Students must complete their LLND assessment via the LLND Portal before they can be formally enrolled. Further instructions on how to access and complete the assessment will be provided to prospective students as part of the pre-enrolment process.</p>',
    apply_form = 'https://reachcollege.edu.au/courses/hospitality/certificate-iv-in-kitchen-management/',
    updated_at = NOW()
WHERE cricos_course_code = '109596F';
UPDATE courses SET
    course_description = '<h4>Course Overview</h4> <p><strong>SIT50422 – Diploma of Hospitality Management</strong> reflects the role of highly skilled senior operators who use a broad range of hospitality skills combined with managerial skills and sound knowledge of industry to coordinate hospitality operations. They operate independently, have responsibility for others and make a range of operational business decisions.</p> <p>This qualification provides a pathway to work in any hospitality industry sector as a departmental or small business manager. The diversity of employers includes restaurants, hotels, motels, catering operations, clubs, pubs, cafés, and coffee shops. This qualification allows for multiskilling and for specialisation in accommodation services, cookery, food and beverage and gaming.</p>',
    course_duration_per_week = 52,
    offshore_tuition_fee = 16000,
    onshore_tuition_fee = 14000,
    enrolment_fee = 200,
    materials_fee = NULL,
    entry_requirements = '<h4>Entry Requirements</h4> <p>Successful completion of Australian Year 12 or Australian equivalent is mandatory.</p> <p>Students must be 18 years old and above.</p> <p>English requirement</p><p>A minimum of IELTS 6.0 or equivalent is required.</p><p>For more information regarding the commonly acceptable types of English language proficiency evidence, along with the verification methods, please <a href="https://reachcollege.edu.au/courses/english/">click here</a></p><p>Student Requirements</p><p>Students are required to have their own laptop prior to the commencement of their course.</p><p>The minimum requirements for the specification of laptops can be found in the Student Equipment Required section below.</p><p>Language, Literacy, Numeracy, and Digital skills (LLND)​</p><p>Prior to enrolment, all prospective students are required to complete a compulsory Language, Literacy, Numeracy and Digital (LLND) assessment. This assessment is completed as part of the pre-enrolment process through the LLND Portal – <a href="https://myllnd.com/login/">myllnd.com/login/</a></p><p>The LLND assessment helps identify whether a student may need additional support during their studies and ensures they are placed in a course that is appropriate for their skill level. Assessments are aligned with the Australian Core Skills Framework (ACSF) and include language, literacy, numeracy and digital skills.</p><p>Students must complete their LLND assessment via the LLND Portal before they can be formally enrolled. Further instructions on how to access and complete the assessment will be provided to prospective students as part of the pre-enrolment process.</p>',
    apply_form = 'https://reachcollege.edu.au/courses/hospitality/diploma-of-hospitality-management/',
    updated_at = NOW()
WHERE cricos_course_code = '114549D';
UPDATE courses SET
    course_description = '<h4>Course Overview</h4> <p><strong>ICT60220 – Advanced Diploma of Information Technology (Telecommunications Network Engineering)</strong> reflects the role of individuals in a variety of information and communications technology (ICT) roles who have significant experience in specialist technical skills or managerial business and people management skills.</p> <p>Individuals in these roles carry out complex tasks in a specialist field, working independently, leading a team or a strategic direction of a business. They apply their skills across a wide range of industries and business functions or as a business owner (sole trader/contractor).</p> <p>The skills required for these roles may include, but are not restricted to:</p> <ul><li>Telecommunications network engineering: managing logistics, organisational specifications, regulations and legislative requirements across network projects.</li> </ul>',
    course_duration_per_week = 104,
    offshore_tuition_fee = 27000,
    onshore_tuition_fee = 23000,
    enrolment_fee = 200,
    materials_fee = NULL,
    entry_requirements = '<h4>Entry Requirements</h4> <p>Successful completion of Australian Year 12 or Australian equivalent is mandatory.</p> <p>Students must be 18 years old and above.</p> <p>English requirement</p><p>A minimum of IELTS 6.0 or equivalent is required.</p><p>For more information regarding the commonly acceptable types of English language proficiency evidence, along with the verification methods, please <a href="https://reachcollege.edu.au/courses/english/">click here</a></p><p>Student Requirements</p><p>Students are required to have their own laptop prior to the commencement of their course.</p><p>The minimum requirements for the specification of laptops can be found in the Student Equipment Required section below.</p><p>Language, Literacy, Numeracy, and Digital skills (LLND)​</p><p>Prior to enrolment, all prospective students are required to complete a compulsory Language, Literacy, Numeracy and Digital (LLND) assessment. This assessment is completed as part of the pre-enrolment process through the LLND Portal – <a href="https://myllnd.com/login/">myllnd.com/login/</a></p><p>The LLND assessment helps identify whether a student may need additional support during their studies and ensures they are placed in a course that is appropriate for their skill level. Assessments are aligned with the Australian Core Skills Framework (ACSF) and include language, literacy, numeracy and digital skills.</p><p>Students must complete their LLND assessment via the LLND Portal before they can be formally enrolled. Further instructions on how to access and complete the assessment will be provided to prospective students as part of the pre-enrolment process.</p>',
    apply_form = 'https://reachcollege.edu.au/courses/it/advanced-diploma-of-information-technology/',
    updated_at = NOW()
WHERE cricos_course_code = '105389A';
UPDATE courses SET
    course_description = '<h4>Course Overview</h4> <p><strong>ICT40120 – Certificate IV in Information Technology </strong>reflects the role of individuals who are job ready and competent in a wide range of information and communications technology (ICT) roles and apply a broad range of skills in varied work contexts, using problem solving skills and effective communication with others.</p> <p>Licensing, legislative, regulatory or certification considerations</p> <p>No licensing, legislative or certification requirements apply to this qualification at the time of publication.</p>',
    course_duration_per_week = 52,
    offshore_tuition_fee = 13000,
    onshore_tuition_fee = 11000,
    enrolment_fee = 200,
    materials_fee = NULL,
    entry_requirements = '<h4>Entry Requirements</h4> <p>Successful completion of Australian Year 12 or Australian equivalent is mandatory.</p> <p>Students must be 18 years old and above.</p> <p>English requirement</p><p>A minimum of IELTS 6.0 or equivalent is required.</p><p>For more information regarding the commonly acceptable types of English language proficiency evidence, along with the verification methods, please <a href="https://reachcollege.edu.au/courses/english/">click here</a></p><p>Student Requirements</p><p>Students are required to have their own laptop prior to the commencement of their course.</p><p>The minimum requirements for the specification of laptops can be found in the Student Equipment Required section below.</p><p>Language, Literacy, Numeracy, and Digital skills (LLND)​</p><p>Prior to enrolment, all prospective students are required to complete a compulsory Language, Literacy, Numeracy and Digital (LLND) assessment. This assessment is completed as part of the pre-enrolment process through the LLND Portal – <a href="https://myllnd.com/login/">myllnd.com/login/</a></p><p>The LLND assessment helps identify whether a student may need additional support during their studies and ensures they are placed in a course that is appropriate for their skill level. Assessments are aligned with the Australian Core Skills Framework (ACSF) and include language, literacy, numeracy and digital skills.</p><p>Students must complete their LLND assessment via the LLND Portal before they can be formally enrolled. Further instructions on how to access and complete the assessment will be provided to prospective students as part of the pre-enrolment process.</p>',
    apply_form = 'https://reachcollege.edu.au/courses/it/certificate-iv-in-information-technology/',
    updated_at = NOW()
WHERE cricos_course_code = '105387C';
UPDATE courses SET
    course_description = '<h4>Course Overview</h4> <p><strong>ICT50220 – Diploma of Information Technology</strong> <strong>(Telecommunications Network Engineering) </strong>reflects the role of individuals in a variety of information and communications technology (ICT) roles who have established specialised skills in a technical ICT function.</p> <p>Individuals in these roles carry out moderately complex tasks in specialist fields, working independently, as part of a team or leading deliverables with others. They may apply their skills across a wide range of industries, business functions and departments or as a business owner (sole trader/contractor).</p>',
    course_duration_per_week = 52,
    offshore_tuition_fee = 15000,
    onshore_tuition_fee = 13000,
    enrolment_fee = 200,
    materials_fee = NULL,
    entry_requirements = '<h4>Entry Requirements</h4> <p>Successful completion of Australian Year 12 or Australian equivalent is mandatory.</p> <p>Students must be 18 years old and above.</p> <p>English requirement</p><p>A minimum of IELTS 6.0 or equivalent is required.</p><p>For more information regarding the commonly acceptable types of English language proficiency evidence, along with the verification methods, please <a href="https://reachcollege.edu.au/courses/english/">click here</a></p><p>Student Requirements</p><p>Students are required to have their own laptop prior to the commencement of their course.</p><p>The minimum requirements for the specification of laptops can be found in the Student Equipment Required section below.</p><p>Language, Literacy, Numeracy, and Digital skills (LLND)​</p><p>Prior to enrolment, all prospective students are required to complete a compulsory Language, Literacy, Numeracy and Digital (LLND) assessment. This assessment is completed as part of the pre-enrolment process through the LLND Portal – <a href="https://myllnd.com/login/">myllnd.com/login/</a></p><p>The LLND assessment helps identify whether a student may need additional support during their studies and ensures they are placed in a course that is appropriate for their skill level. Assessments are aligned with the Australian Core Skills Framework (ACSF) and include language, literacy, numeracy and digital skills.</p><p>Students must complete their LLND assessment via the LLND Portal before they can be formally enrolled. Further instructions on how to access and complete the assessment will be provided to prospective students as part of the pre-enrolment process.</p>',
    apply_form = 'https://reachcollege.edu.au/courses/it/diploma-of-information-technology/',
    updated_at = NOW()
WHERE cricos_course_code = '105388B';
UPDATE courses SET
    course_description = '<h4>Course Overview</h4> <p><strong>AUR30320 – Certificate III in Automotive Electrical Technology</strong> reflects the role of individuals who service, diagnose and repair electrical systems and components in vehicles in the automotive electrical service and repair industry.</p> <p>No licensing, legislative or certification requirements apply to this qualification at the time of publication.</p>',
    course_duration_per_week = 52,
    offshore_tuition_fee = 19000,
    onshore_tuition_fee = 17000,
    enrolment_fee = 200,
    materials_fee = NULL,
    entry_requirements = '<h4>Entry Requirements</h4> <p>Successful completion of Australian Year 12 or Australian equivalent is mandatory.</p> <p>Students must be 18 years old and above.</p> <p>English requirement</p><p>A minimum of IELTS 6.0 or equivalent is required.</p><p>For more information regarding the commonly acceptable types of English language proficiency evidence, along with the verification methods, please <a href="https://reachcollege.edu.au/courses/english/">click here</a></p><p>Student Requirements</p><p>Students are required to have their own laptop prior to the commencement of their course.</p><p>The minimum requirements for the specification of laptops can be found in the Student Equipment Required section below.</p><p>Language, Literacy, Numeracy, and Digital skills (LLND)​</p><p>Prior to enrolment, all prospective students are required to complete a compulsory Language, Literacy, Numeracy and Digital (LLND) assessment. This assessment is completed as part of the pre-enrolment process through the LLND Portal – <a href="https://myllnd.com/login/">myllnd.com/login/</a></p><p>The LLND assessment helps identify whether a student may need additional support during their studies and ensures they are placed in a course that is appropriate for their skill level. Assessments are aligned with the Australian Core Skills Framework (ACSF) and include language, literacy, numeracy and digital skills.</p><p>Students must complete their LLND assessment via the LLND Portal before they can be formally enrolled. Further instructions on how to access and complete the assessment will be provided to prospective students as part of the pre-enrolment process.</p>',
    apply_form = 'https://reachcollege.edu.au/courses/tech-sciences/certificate-iii-in-automotive-electrical-technology/',
    updated_at = NOW()
WHERE cricos_course_code = '105385E';
UPDATE courses SET
    course_description = '<h4>Course Overview</h4> <p><strong>AUR31120 – Certificate III in Heavy Commercial Vehicle Mechanical Technology</strong> reflects the role of individuals who perform a broad range of tasks on a variety of heavy commercial vehicles in the automotive service and repair sector.</p>',
    course_duration_per_week = 52,
    offshore_tuition_fee = 18000,
    onshore_tuition_fee = 16000,
    enrolment_fee = 200,
    materials_fee = NULL,
    entry_requirements = '<h4>Entry Requirements</h4> <p>Successful completion of Australian Year 12 or Australian equivalent is mandatory.</p> <p>Students must be 18 years old and above.</p> <p>English requirement</p><p>A minimum of IELTS 6.0 or equivalent is required.</p><p>For more information regarding the commonly acceptable types of English language proficiency evidence, along with the verification methods, please <a href="https://reachcollege.edu.au/courses/english/">click here</a></p><p>Student Requirements</p><p>Students are required to have their own laptop prior to the commencement of their course.</p><p>The minimum requirements for the specification of laptops can be found in the Student Equipment Required section below.</p><p>Language, Literacy, Numeracy, and Digital skills (LLND)​</p><p>Prior to enrolment, all prospective students are required to complete a compulsory Language, Literacy, Numeracy and Digital (LLND) assessment. This assessment is completed as part of the pre-enrolment process through the LLND Portal – <a href="https://myllnd.com/login/">myllnd.com/login/</a></p><p>The LLND assessment helps identify whether a student may need additional support during their studies and ensures they are placed in a course that is appropriate for their skill level. Assessments are aligned with the Australian Core Skills Framework (ACSF) and include language, literacy, numeracy and digital skills.</p><p>Students must complete their LLND assessment via the LLND Portal before they can be formally enrolled. Further instructions on how to access and complete the assessment will be provided to prospective students as part of the pre-enrolment process.</p>',
    apply_form = 'https://reachcollege.edu.au/courses/tech-sciences/certificate-iii-in-heavy-commercial-vehicle-mechanical-technology/',
    updated_at = NOW()
WHERE cricos_course_code = '105381J';
UPDATE courses SET
    course_description = '<h4>Course Overview</h4> <p><strong>AUR30620 – Certificate III in Light Vehicle Mechanical Technology</strong> reflects the role of individuals who perform a broad range of tasks on a variety of light vehicles in the automotive retail, service and repair industry.</p>',
    course_duration_per_week = 52,
    offshore_tuition_fee = 19000,
    onshore_tuition_fee = 17000,
    enrolment_fee = 200,
    materials_fee = NULL,
    entry_requirements = '<h4>Entry Requirements</h4> <p>Successful completion of Australian Year 12 or Australian equivalent is mandatory.</p> <p>Students must be 18 years old and above.</p> <p>English requirement</p><p>A minimum of IELTS 6.0 or equivalent is required.</p><p>For more information regarding the commonly acceptable types of English language proficiency evidence, along with the verification methods, please <a href="https://reachcollege.edu.au/courses/english/">click here</a></p><p>Student Requirements</p><p>Students are required to have their own laptop prior to the commencement of their course.</p><p>The minimum requirements for the specification of laptops can be found in the Student Equipment Required section below.</p><p>Language, Literacy, Numeracy, and Digital skills (LLND)​</p><p>Prior to enrolment, all prospective students are required to complete a compulsory Language, Literacy, Numeracy and Digital (LLND) assessment. This assessment is completed as part of the pre-enrolment process through the LLND Portal – <a href="https://myllnd.com/login/">myllnd.com/login/</a></p><p>The LLND assessment helps identify whether a student may need additional support during their studies and ensures they are placed in a course that is appropriate for their skill level. Assessments are aligned with the Australian Core Skills Framework (ACSF) and include language, literacy, numeracy and digital skills.</p><p>Students must complete their LLND assessment via the LLND Portal before they can be formally enrolled. Further instructions on how to access and complete the assessment will be provided to prospective students as part of the pre-enrolment process.</p>',
    apply_form = 'https://reachcollege.edu.au/courses/tech-sciences/certificate-iii-in-light-vehicle-mechanical-technology/',
    updated_at = NOW()
WHERE cricos_course_code = '105382H';
UPDATE courses SET
    course_description = '<h4>Course Overview</h4> <p><strong>AUR40620 – Certificate IV in Automotive Electrical Technology</strong> reflects the role of individuals who work as master diagnostic technicians the automotive service and repair industry; servicing, diagnosing and repairing vehicle electrical systems and components. A range of advanced electrical diagnostic skills and knowledge is necessary, and leadership and supervision of others would be expected.</p>',
    course_duration_per_week = 39,
    offshore_tuition_fee = 15000,
    onshore_tuition_fee = 14000,
    enrolment_fee = 200,
    materials_fee = NULL,
    entry_requirements = '<h4>Entry Requirements</h4> <p>Students who are undertaking AUR40620 – Certificate IV in Automotive Electrical Technology must have completed AUR30320 – Certificate III in Automotive Electrical Technology or be able to demonstrate equivalent competency.</p> <p>Students must be 18 years old and above.</p> <p>Successful completion of Australian Year 12 or Australian equivalent is mandatory.</p> <p>English requirement</p><p>A minimum of IELTS 6.0 or equivalent is required.</p><p>For more information regarding the commonly acceptable types of English language proficiency evidence, along with the verification methods, please <a href="https://reachcollege.edu.au/courses/english/">click here</a></p><p>Student Requirements</p><p>Students are required to have their own laptop prior to the commencement of their course.</p><p>The minimum requirements for the specification of laptops can be found in the Student Equipment Required section below.</p><p>Language, Literacy, Numeracy, and Digital skills (LLND)​</p><p>Prior to enrolment, all prospective students are required to complete a compulsory Language, Literacy, Numeracy and Digital (LLND) assessment. This assessment is completed as part of the pre-enrolment process through the LLND Portal – <a href="https://myllnd.com/login/">myllnd.com/login/</a></p><p>The LLND assessment helps identify whether a student may need additional support during their studies and ensures they are placed in a course that is appropriate for their skill level. Assessments are aligned with the Australian Core Skills Framework (ACSF) and include language, literacy, numeracy and digital skills.</p><p>Students must complete their LLND assessment via the LLND Portal before they can be formally enrolled. Further instructions on how to access and complete the assessment will be provided to prospective students as part of the pre-enrolment process.</p>',
    apply_form = 'https://reachcollege.edu.au/courses/tech-sciences/certificate-iv-in-automotive-electrical-technology/',
    updated_at = NOW()
WHERE cricos_course_code = '105386D';
UPDATE courses SET
    course_description = '<h4>Course Overview</h4> <p><strong>AUR40216 – Certificate IV in Automotive Mechanical Diagnosis</strong> reflects the role of individuals who perform advanced diagnostic tasks in the automotive retail, service and repair industry.</p>',
    course_duration_per_week = 39,
    offshore_tuition_fee = 15000,
    onshore_tuition_fee = 14000,
    enrolment_fee = 200,
    materials_fee = NULL,
    entry_requirements = '<h4>Entry Requirements</h4> <p>Those undertaking the Certificate IV in Automotive Mechanical Diagnosis must have completed an automotive mechanical Certificate III qualification, or be able to demonstrate equivalent competency.</p> <p>No licensing, legislative or certification requirements apply to this qualification at the time of publication.</p> <p>Students must be 18 years old and above.</p> <p>Successful completion of Australian Year 12 or Australian equivalent is mandatory.</p> <p>English requirement</p><p>A minimum of IELTS 6.0 or equivalent is required.</p><p>For more information regarding the commonly acceptable types of English language proficiency evidence, along with the verification methods, please <a href="https://reachcollege.edu.au/courses/english/">click here</a></p><p>Student Requirements</p><p>Students are required to have their own laptop prior to the commencement of their course.</p><p>The minimum requirements for the specification of laptops can be found in the Student Equipment Required section below.</p><p>Language, Literacy, Numeracy, and Digital skills (LLND)​</p><p>Prior to enrolment, all prospective students are required to complete a compulsory Language, Literacy, Numeracy and Digital (LLND) assessment. This assessment is completed as part of the pre-enrolment process through the LLND Portal – <a href="https://myllnd.com/login/">myllnd.com/login/</a></p><p>The LLND assessment helps identify whether a student may need additional support during their studies and ensures they are placed in a course that is appropriate for their skill level. Assessments are aligned with the Australian Core Skills Framework (ACSF) and include language, literacy, numeracy and digital skills.</p><p>Students must complete their LLND assessment via the LLND Portal before they can be formally enrolled. Further instructions on how to access and complete the assessment will be provided to prospective students as part of the pre-enrolment process.</p>',
    apply_form = 'https://reachcollege.edu.au/courses/tech-sciences/certificate-iv-in-automotive-mechanical-diagnosis/',
    updated_at = NOW()
WHERE cricos_course_code = '105383G';
UPDATE courses SET
    course_description = '<h4>Course Overview</h4> <p><strong>AUR50116 – Diploma of Automotive Management</strong> reflects the role of individuals who undertake leadership and management roles in the automotive industry. It is suitable for entry into senior management roles in all sectors of the automotive industry.</p>',
    course_duration_per_week = 52,
    offshore_tuition_fee = 15000,
    onshore_tuition_fee = 14000,
    enrolment_fee = 200,
    materials_fee = NULL,
    entry_requirements = '<h4>Entry Requirements</h4> <p>This qualification may be accessed by direct entry.</p> <p>No licensing, legislative or certification requirements apply to this qualification at the time of publication.</p> <p>Successful completion of Australian Year 12 or Australian equivalent is mandatory.</p> <p>Students must be 18 years old and above.</p> <p>English requirement</p><p>A minimum of IELTS 6.0 or equivalent is required.</p><p>For more information regarding the commonly acceptable types of English language proficiency evidence, along with the verification methods, please <a href="https://reachcollege.edu.au/courses/english/">click here</a></p><p>Student Requirements</p><p>Students are required to have their own laptop prior to the commencement of their course.</p><p>The minimum requirements for the specification of laptops can be found in the Student Equipment Required section below.</p><p>Language, Literacy, Numeracy, and Digital skills (LLND)​</p><p>Prior to enrolment, all prospective students are required to complete a compulsory Language, Literacy, Numeracy and Digital (LLND) assessment. This assessment is completed as part of the pre-enrolment process through the LLND Portal – <a href="https://myllnd.com/login/">myllnd.com/login/</a></p><p>The LLND assessment helps identify whether a student may need additional support during their studies and ensures they are placed in a course that is appropriate for their skill level. Assessments are aligned with the Australian Core Skills Framework (ACSF) and include language, literacy, numeracy and digital skills.</p><p>Students must complete their LLND assessment via the LLND Portal before they can be formally enrolled. Further instructions on how to access and complete the assessment will be provided to prospective students as part of the pre-enrolment process.</p>',
    apply_form = 'https://reachcollege.edu.au/courses/tech-sciences/diploma-of-automotive-management/',
    updated_at = NOW()
WHERE cricos_course_code = '105384F';
-- ⚠️ Skipped (no CRICOS course code on page): Welcome to | https://reachcollege.edu.au/courses/general-english-elementary-to-advanced/

