-- TAFE WA - Dept Training & Workforce Dev (00020G) - Webscrape Update
UPDATE provider_institution SET intake_date='September', updated_at=NOW() WHERE cricos_provider_code='00020G';

UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 13140,
    onshore_tuition_fee = NULL,
    enrolment_fee = 1564,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '0100601';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 6570,
    onshore_tuition_fee = NULL,
    enrolment_fee = 1050,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '0100603';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 6570,
    onshore_tuition_fee = NULL,
    enrolment_fee = 415,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '0100606';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 18194,
    onshore_tuition_fee = NULL,
    enrolment_fee = 1581,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '0101214';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 15014,
    onshore_tuition_fee = NULL,
    enrolment_fee = 1653,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '0101518';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 6876,
    onshore_tuition_fee = NULL,
    enrolment_fee = 719,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '090729B';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 9403,
    onshore_tuition_fee = NULL,
    enrolment_fee = 1738,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '091648F';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 9403,
    onshore_tuition_fee = NULL,
    enrolment_fee = 1417,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '091696J';
UPDATE courses SET
    course_duration_per_week = 78,
    offshore_tuition_fee = 21639,
    onshore_tuition_fee = NULL,
    enrolment_fee = 2750,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '096422F';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 13100,
    onshore_tuition_fee = NULL,
    enrolment_fee = 7847,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '103424H';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 12552,
    onshore_tuition_fee = NULL,
    enrolment_fee = 7223,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '103426F';
UPDATE courses SET
    course_duration_per_week = 22,
    offshore_tuition_fee = 7897,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '103577B';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 18806,
    onshore_tuition_fee = NULL,
    enrolment_fee = 4272,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '103611E';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 14910,
    onshore_tuition_fee = NULL,
    enrolment_fee = 638,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '103750E';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 15014,
    onshore_tuition_fee = NULL,
    enrolment_fee = 1155,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '103764K';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 15014,
    onshore_tuition_fee = NULL,
    enrolment_fee = 912,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '103778D';
UPDATE courses SET
    course_duration_per_week = 104,
    offshore_tuition_fee = 26240,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '103797A';
UPDATE courses SET
    course_duration_per_week = 104,
    offshore_tuition_fee = 28180,
    onshore_tuition_fee = NULL,
    enrolment_fee = 4482,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '103833B';
UPDATE courses SET
    course_duration_per_week = 104,
    offshore_tuition_fee = 28180,
    onshore_tuition_fee = NULL,
    enrolment_fee = 4318,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '104856J';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 8108,
    onshore_tuition_fee = NULL,
    enrolment_fee = 998,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '104883F';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 8108,
    onshore_tuition_fee = NULL,
    enrolment_fee = 945,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '104884E';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 16216,
    onshore_tuition_fee = NULL,
    enrolment_fee = 1260,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '104885D';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 16216,
    onshore_tuition_fee = NULL,
    enrolment_fee = 1182,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '104886C';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 12552,
    onshore_tuition_fee = NULL,
    enrolment_fee = 7896,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '105104H';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 16216,
    onshore_tuition_fee = NULL,
    enrolment_fee = 900,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '105229F';
UPDATE courses SET
    course_duration_per_week = 78,
    offshore_tuition_fee = 24324,
    onshore_tuition_fee = NULL,
    enrolment_fee = 1286,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '105244G';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 6570,
    onshore_tuition_fee = NULL,
    enrolment_fee = 630,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '105772E';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 6570,
    onshore_tuition_fee = NULL,
    enrolment_fee = 315,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '105779J';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 13140,
    onshore_tuition_fee = NULL,
    enrolment_fee = 683,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '105790C';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 13140,
    onshore_tuition_fee = NULL,
    enrolment_fee = 1393,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '105801E';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 13140,
    onshore_tuition_fee = NULL,
    enrolment_fee = 1365,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '105814M';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 6570,
    onshore_tuition_fee = NULL,
    enrolment_fee = 326,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '106319G';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 13140,
    onshore_tuition_fee = NULL,
    enrolment_fee = 1040,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '106320C';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 13140,
    onshore_tuition_fee = NULL,
    enrolment_fee = 956,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '106321B';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 6570,
    onshore_tuition_fee = NULL,
    enrolment_fee = 447,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '106615K';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 6570,
    onshore_tuition_fee = NULL,
    enrolment_fee = 227,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '107276E';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 13140,
    onshore_tuition_fee = NULL,
    enrolment_fee = 3010,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '107936G';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 13140,
    onshore_tuition_fee = NULL,
    enrolment_fee = 1680,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '107937F';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 6570,
    onshore_tuition_fee = NULL,
    enrolment_fee = 168,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '107938E';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 13140,
    onshore_tuition_fee = NULL,
    enrolment_fee = 1313,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '108207K';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 13140,
    onshore_tuition_fee = NULL,
    enrolment_fee = 1176,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '108208J';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 15014,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '108209H';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 15014,
    onshore_tuition_fee = NULL,
    enrolment_fee = 105,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '108210D';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 13140,
    onshore_tuition_fee = NULL,
    enrolment_fee = 1370,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '108213A';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 13140,
    onshore_tuition_fee = NULL,
    enrolment_fee = 1470,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '108214M';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 13140,
    onshore_tuition_fee = NULL,
    enrolment_fee = 1918,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '108215K';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 13140,
    onshore_tuition_fee = NULL,
    enrolment_fee = 2233,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '108216J';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 13140,
    onshore_tuition_fee = NULL,
    enrolment_fee = 1370,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '108217H';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 16216,
    onshore_tuition_fee = NULL,
    enrolment_fee = 1061,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '108218G';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 16216,
    onshore_tuition_fee = NULL,
    enrolment_fee = 1323,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '108219F';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 6570,
    onshore_tuition_fee = NULL,
    enrolment_fee = 505,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '109073M';
UPDATE courses SET
    course_duration_per_week = 78,
    offshore_tuition_fee = 25335,
    onshore_tuition_fee = NULL,
    enrolment_fee = 3848,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '109485B';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 8445,
    onshore_tuition_fee = NULL,
    enrolment_fee = 2835,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '109626E';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 16890,
    onshore_tuition_fee = NULL,
    enrolment_fee = 3360,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '109754H';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 16890,
    onshore_tuition_fee = NULL,
    enrolment_fee = 5387,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '109763G';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 6570,
    onshore_tuition_fee = NULL,
    enrolment_fee = 354,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '110029E';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 13140,
    onshore_tuition_fee = NULL,
    enrolment_fee = 1557,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '110615J';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 13752,
    onshore_tuition_fee = NULL,
    enrolment_fee = 977,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '110936C';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 13752,
    onshore_tuition_fee = NULL,
    enrolment_fee = 948,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '110937B';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 9403,
    onshore_tuition_fee = NULL,
    enrolment_fee = 654,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '111816C';
UPDATE courses SET
    course_duration_per_week = 78,
    offshore_tuition_fee = 28209,
    onshore_tuition_fee = NULL,
    enrolment_fee = 7060,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '111837J';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 13140,
    onshore_tuition_fee = NULL,
    enrolment_fee = 2321,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '111838H';
UPDATE courses SET
    course_duration_per_week = 104,
    offshore_tuition_fee = 26280,
    onshore_tuition_fee = NULL,
    enrolment_fee = 1575,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '111973A';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 13140,
    onshore_tuition_fee = NULL,
    enrolment_fee = 840,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '111983K';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 13140,
    onshore_tuition_fee = NULL,
    enrolment_fee = 441,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '111989D';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 13140,
    onshore_tuition_fee = NULL,
    enrolment_fee = 893,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '111991K';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 8108,
    onshore_tuition_fee = NULL,
    enrolment_fee = 707,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '112000B';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 16216,
    onshore_tuition_fee = NULL,
    enrolment_fee = 4217,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '112005H';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 16216,
    onshore_tuition_fee = NULL,
    enrolment_fee = 1530,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '112016E';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 6570,
    onshore_tuition_fee = NULL,
    enrolment_fee = 762,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '112031F';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 13140,
    onshore_tuition_fee = NULL,
    enrolment_fee = 1313,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '112037M';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 13140,
    onshore_tuition_fee = NULL,
    enrolment_fee = 1550,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '112042C';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 6570,
    onshore_tuition_fee = NULL,
    enrolment_fee = 410,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '113113G';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 13140,
    onshore_tuition_fee = NULL,
    enrolment_fee = 3132,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '113319D';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 16890,
    onshore_tuition_fee = NULL,
    enrolment_fee = 1790,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '113481E';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 8445,
    onshore_tuition_fee = NULL,
    enrolment_fee = 1103,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '113482D';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 6570,
    onshore_tuition_fee = NULL,
    enrolment_fee = 210,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '114014B';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 13140,
    onshore_tuition_fee = NULL,
    enrolment_fee = 987,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '114015A';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 6876,
    onshore_tuition_fee = NULL,
    enrolment_fee = 503,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '114743B';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 13752,
    onshore_tuition_fee = NULL,
    enrolment_fee = 1000,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '114745M';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 6570,
    onshore_tuition_fee = NULL,
    enrolment_fee = 420,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '114746K';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 13140,
    onshore_tuition_fee = NULL,
    enrolment_fee = 578,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '114747J';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 6570,
    onshore_tuition_fee = NULL,
    enrolment_fee = 950,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '114748H';
UPDATE courses SET
    course_duration_per_week = 78,
    offshore_tuition_fee = 19710,
    onshore_tuition_fee = NULL,
    enrolment_fee = 2835,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '114749G';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 13140,
    onshore_tuition_fee = NULL,
    enrolment_fee = 3045,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '114750C';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 6876,
    onshore_tuition_fee = NULL,
    enrolment_fee = 1276,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '114751B';
UPDATE courses SET
    course_duration_per_week = 104,
    offshore_tuition_fee = 32432,
    onshore_tuition_fee = NULL,
    enrolment_fee = 3864,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '114752A';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 6876,
    onshore_tuition_fee = NULL,
    enrolment_fee = 492,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '114753M';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 6570,
    onshore_tuition_fee = NULL,
    enrolment_fee = 562,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '116643A';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 13140,
    onshore_tuition_fee = NULL,
    enrolment_fee = 1281,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '117119B';
UPDATE courses SET
    course_duration_per_week = 78,
    offshore_tuition_fee = 21639,
    onshore_tuition_fee = NULL,
    enrolment_fee = 2750,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '117506B';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 13400,
    onshore_tuition_fee = NULL,
    enrolment_fee = 902,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '118569A';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 13752,
    onshore_tuition_fee = NULL,
    enrolment_fee = 1000,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '118873D';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 13140,
    onshore_tuition_fee = NULL,
    enrolment_fee = 1470,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '118929D';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 13140,
    onshore_tuition_fee = NULL,
    enrolment_fee = 683,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '119034B';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 13140,
    onshore_tuition_fee = NULL,
    enrolment_fee = 1370,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '119063H';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 16216,
    onshore_tuition_fee = NULL,
    enrolment_fee = 615,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '119536B';
UPDATE courses SET
    course_duration_per_week = 78,
    offshore_tuition_fee = 24324,
    onshore_tuition_fee = NULL,
    enrolment_fee = 772,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '119537A';
UPDATE courses SET
    course_duration_per_week = 52,
    offshore_tuition_fee = 13752,
    onshore_tuition_fee = NULL,
    enrolment_fee = 977,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '119572J';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 9403,
    onshore_tuition_fee = NULL,
    enrolment_fee = 1738,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '120260D';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 8108,
    onshore_tuition_fee = NULL,
    enrolment_fee = 998,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '120513K';
UPDATE courses SET
    course_duration_per_week = 26,
    offshore_tuition_fee = 6570,
    onshore_tuition_fee = NULL,
    enrolment_fee = 420,
    materials_fee = NULL,
    course_description = '',
    entry_requirements = 'Contact provider for entry requirements',
    apply_form = 'http://www.tafeinternational.wa.edu.au/courses',
    updated_at = NOW()
WHERE cricos_course_code = '120859F';
