UPDATE courses SET
    course_description = '<div class="content"> <p>This qualification reflects the role of highly skilled senior managers who use a broad range of hospitality skills combined with specialised managerial skills and substantial knowledge of industry to coordinate hospitality operations. They operate with significant autonomy and are responsible for making strategic business management decisions.</p> <p>This qualification provides a pathway to work in any hospitality industry sector and for a diversity of employers including restaurants, hotels, motels, catering operations, clubs, pubs, cafés, and coffee shops. This qualification allows for multi-skilling and for acquiring targeted skills in accommodation services, cookery, food and beverage and gaming.</p> <p>The skills in this qualification must be applied in accordance with Commonwealth and State/Territory legislation, Australian standards and industry codes of practice.</p> <p>No occupational licensing, certification or specific legislative requirements apply to this qualification at the time of publication.</p> </div>',
    total_course_duration = '104 weeks',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="content"> <p>This course is available to international students. There are no specific entry requirements listed in the qualification details or training package; however, applicants must meet Auscanus Institute of Australia’s entry requirements below:</p> <p><strong>Applicants must:</strong></p> <p style="margin-bottom: 14px;">Be 18 years of age or older at the time of course commencement.</p> <p style="margin-bottom: 14px;">Have successfully completed Year 12 or equivalent secondary schooling.</p> <p style="margin-bottom: 14px;">Demonstrate English language proficiency through one of the following approved tests: IELTS Academic 6.0, TOEFL iBT 60, PTE Academic 50, or equivalent English language proficiency.</p> <p>English language competence may also be demonstrated through documented evidence of any of the following:</p> <p style="margin-bottom: 14px;">Completion of a recognised ELICOS program with an English proficiency level considered equivalent to the course entry requirements.</p> <p style="margin-bottom: 14px;">Completion of at least two (2) years of study in Australia at AQF Level 4 or higher.</p> <p style="margin-bottom: 14px;">Minimum five (5) years of study in English in Australia, the United Kingdom, the United States of America, Canada, New Zealand, South Africa or the Republic of Ireland.</p> <p style="margin-bottom: 14px;">Completion of Year 12 or equivalent secondary schooling in English.</p> <p style="margin-bottom: 14px;">Applicants without documented evidence of English language proficiency may complete an online Language, Literacy, Numeracy and Digital Literacy (LLND) assessment and achieve a satisfactory outcome to meet AIA’s entry requirements.</p> <p><strong>Note:</strong> English language requirements and exemptions may vary depending on visa requirements and individual circumstances. Please contact AIA for further details or visit the <a href="https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/student-500#HowTo" rel="noopener" target="_blank">Department of Home Affairs website</a>.</p> </div>',
    apply_form = 'https://auscanus.edu.au/courses/advanced-diploma-of-hospitality-management/',
    updated_at = NOW()
WHERE cricos_course_code = '114256F';

UPDATE courses SET
    course_description = '<div class="content"> <p>This qualification reflects the role of individuals in a range of community settings and peoples’ homes, who provide support in a manner that empowers people with disabilities to achieve greater levels of independence, self-reliance, community participation and wellbeing. Workers promote a person-centred approach, work according to and may contribute to an individualised plan, and work without direct supervision. They may be required to supervise and/or coordinate a small team.</p> <p>The skills in this qualification must be applied in accordance with Commonwealth and State/Territory legislation, Australian standards and industry codes of practice.</p> </div>',
    total_course_duration = '52 weeks',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="content"> <p>This course is available to international students. There are no specific entry requirements listed in the qualification details or training package; however, applicants must meet Auscanus Institute of Australia’s entry requirements below:</p> <p><strong>Applicants must:</strong></p> <p style="margin-bottom: 14px;">Be 18 years of age or older at the time of course commencement.</p> <p style="margin-bottom: 14px;">Have successfully completed Year 12 or equivalent secondary schooling.</p> <p style="margin-bottom: 14px;">Demonstrate English language proficiency through one of the following approved tests: IELTS Academic 6.0, TOEFL iBT 60, PTE Academic 50, or equivalent English language proficiency.</p> <p>English language competence may also be demonstrated through documented evidence of any of the following:</p> <p style="margin-bottom: 14px;">Completion of a recognised ELICOS program with an English proficiency level considered equivalent to the course entry requirements.</p> <p style="margin-bottom: 14px;">Completion of at least two (2) years of study in Australia at AQF Level 4 or higher.</p> <p style="margin-bottom: 14px;">Minimum five (5) years of study in English in Australia, the United Kingdom, the United States of America, Canada, New Zealand, South Africa or the Republic of Ireland.</p> <p style="margin-bottom: 14px;">Completion of Year 12 or equivalent secondary schooling in English.</p> <p style="margin-bottom: 14px;">Applicants without documented evidence of English language proficiency may complete an online Language, Literacy, Numeracy and Digital Literacy (LLND) assessment and achieve a satisfactory outcome to meet AIA’s entry requirements.</p> <p><strong>Note:</strong> English language requirements and exemptions may vary depending on visa requirements and individual circumstances. Please contact AIA for further details or visit the <a href="https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/student-500#HowTo" rel="noopener" target="_blank">Department of Home Affairs website</a>.</p> </div>',
    apply_form = 'https://auscanus.edu.au/courses/certificate-iv-in-disability-support/',
    updated_at = NOW()
WHERE cricos_course_code = '118321C';

UPDATE courses SET
    course_description = '<div class="content"> <p>This qualification reflects the role of support workers who complete specialised tasks and functions in aged services; either in residential, home or community-based environments. Workers will take responsibility for their own outputs within defined organisation guidelines and maintain quality service delivery through the development, facilitation and review of individualised service planning and delivery.</p> <p>Workers may be required to demonstrate leadership and have limited responsibility for the organisation and the quantity and quality of outputs of others within limited parameters.</p> <p>To achieve this qualification, the candidate must have completed at least 120 hours of work as detailed in the Assessment Requirements of the units of competency.</p> </div>',
    total_course_duration = '52 weeks',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="content"> <p>This course is available to international students. There are no specific entry requirements listed in the qualification details or training package; however, applicants must meet Auscanus Institute of Australia’s entry requirements below:</p> <p><strong>Applicants must:</strong></p> <p style="margin-bottom: 14px;">Be 18 years of age or older at the time of course commencement.</p> <p style="margin-bottom: 14px;">Have successfully completed Year 12 or equivalent secondary schooling.</p> <p style="margin-bottom: 14px;">Demonstrate English language proficiency through one of the following approved tests: IELTS Academic 6.0, TOEFL iBT 60, PTE Academic 50, or equivalent English language proficiency.</p> <p>English language competence may also be demonstrated through documented evidence of any of the following:</p> <p style="margin-bottom: 14px;">Completion of a recognised ELICOS program with an English proficiency level considered equivalent to the course entry requirements.</p> <p style="margin-bottom: 14px;">Completion of at least two (2) years of study in Australia at AQF Level 4 or higher.</p> <p style="margin-bottom: 14px;">Minimum five (5) years of study in English in Australia, the United Kingdom, the United States of America, Canada, New Zealand, South Africa or the Republic of Ireland.</p> <p style="margin-bottom: 14px;">Completion of Year 12 or equivalent secondary schooling in English.</p> <p style="margin-bottom: 14px;">Applicants without documented evidence of English language proficiency may complete an online Language, Literacy, Numeracy and Digital Literacy (LLND) assessment and achieve a satisfactory outcome to meet AIA’s entry requirements.</p> <p><strong>Note:</strong> English language requirements and exemptions may vary depending on visa requirements and individual circumstances. Please contact AIA for further details or visit the <a href="https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/student-500#HowTo" rel="noopener" target="_blank">Department of Home Affairs website</a>.</p> </div>',
    apply_form = 'https://auscanus.edu.au/courses/certificate-iv-in-ageing-support/',
    updated_at = NOW()
WHERE cricos_course_code = '118320D';

UPDATE courses SET
    course_description = '<div class="content"> <p>This qualification reflects the role of individuals who apply specialised knowledge and skills, together with experience in leadership and management, across a range of enterprise and industry contexts.</p> <p>Individuals at this level use initiative and judgement to plan and implement a range of leadership and management functions, with accountability for personal and team outcomes within broad parameters.</p> <p>They use cognitive and communication skills to identify, analyse and synthesise information from a variety of sources and transfer their knowledge to others, and creative or conceptual skills to express ideas and perspectives or respond to complex problems.</p> </div>',
    total_course_duration = '78 weeks',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="content"> <p>This course is available to international students. Entry into this qualification is limited to applicants who meet one of the following requirements:</p> <p style="margin-bottom: 14px;">Successful completion of a Diploma or Advanced Diploma from the BSB Training Package (current or superseded equivalent versions); or</p> <p style="margin-bottom: 14px;">A minimum of two (2) years equivalent full-time relevant workplace experience in an operational or leadership role within an enterprise.</p> <p><strong>Applicants must also:</strong></p> <p style="margin-bottom: 14px;">Be 18 years of age or older at the time of course commencement.</p> <p style="margin-bottom: 14px;">Have successfully completed Year 12 or equivalent secondary schooling.</p> <p style="margin-bottom: 14px;">Demonstrate English language proficiency through one of the following approved tests: IELTS Academic 6.0, PTE Academic 50, or equivalent English language proficiency.</p> <p>English language competence may also be demonstrated through documented evidence of any of the following:</p> <p style="margin-bottom: 14px;">Completion of a recognised ELICOS program with an English proficiency level considered equivalent to the course entry requirements.</p> <p style="margin-bottom: 14px;">Completion of at least two (2) years of study in Australia at AQF Level 4 or higher.</p> <p style="margin-bottom: 14px;">Minimum five (5) years of study in English in Australia, the United Kingdom, the United States of America, Canada, New Zealand, South Africa or the Republic of Ireland.</p> <p style="margin-bottom: 14px;">Completion of Year 12 or equivalent secondary schooling in English.</p> <p><strong>Note:</strong> English language requirements and exemptions may vary depending on visa requirements and individual circumstances. Please contact AIA for further details or visit the <a href="https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/student-500#HowTo" rel="noopener" target="_blank">Department of Home Affairs website</a>.</p> </div>',
    apply_form = 'https://auscanus.edu.au/courses/advanced-diploma-of-leadership-and-management/',
    updated_at = NOW()
WHERE cricos_course_code = '111216E';

UPDATE courses SET
    course_description = '<div class="content"> <p>This qualification reflects the role of individuals working as developing and emerging leaders and managers in a range of enterprise and industry contexts.</p> <p>As well as assuming responsibility for their own performance, individuals at this level are likely to provide leadership, guidance and support to others. They may also have some responsibility for organising and monitoring the output of teams.</p> <p>They apply solutions to a defined range of predictable and unpredictable problems and analyse and evaluate information from a variety of sources.</p> </div>',
    total_course_duration = '52 weeks',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="content"> <p>This course is available to international students. There are no specific entry requirements listed in the qualification details or training package; however, applicants must meet Auscanus Institute of Australia’s entry requirements below:</p> <p><strong>Applicants must:</strong></p> <p style="margin-bottom: 14px;">Be 18 years of age or older at the time of course commencement.</p> <p style="margin-bottom: 14px;">Have successfully completed Year 12 or equivalent secondary schooling.</p> <p style="margin-bottom: 14px;">Demonstrate English language proficiency through one of the following approved tests: IELTS Academic 6.0, TOEFL iBT 60, PTE Academic 50, or equivalent English language proficiency.</p> <p>English language competence may also be demonstrated through documented evidence of any of the following:</p> <p style="margin-bottom: 14px;">Completion of a recognised ELICOS program with an English proficiency level considered equivalent to the course entry requirements.</p> <p style="margin-bottom: 14px;">Completion of at least two (2) years of study in Australia at AQF Level 4 or higher.</p> <p style="margin-bottom: 14px;">Minimum five (5) years of study in English in Australia, the United Kingdom, the United States of America, Canada, New Zealand, South Africa or the Republic of Ireland.</p> <p style="margin-bottom: 14px;">Completion of Year 12 or equivalent secondary schooling in English.</p> <p style="margin-bottom: 14px;">Applicants without documented evidence of English language proficiency may complete an online Language, Literacy, Numeracy and Digital Literacy (LLND) assessment and achieve a satisfactory outcome to meet AIA’s entry requirements.</p> <p><strong>Note:</strong> English language requirements and exemptions may vary depending on visa requirements and individual circumstances. Please contact AIA for further details or visit the <a href="https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/student-500#HowTo" rel="noopener" target="_blank">Department of Home Affairs website</a>.</p> </div>',
    apply_form = 'https://auscanus.edu.au/courses/certificate-iv-in-leadership-and-management/',
    updated_at = NOW()
WHERE cricos_course_code = '111213H';

UPDATE courses SET
    course_description = '<div class="content"> <p><b>(Note: This qualification does not contain any specialisation)</b></p> <p>This qualification reflects the role of individuals in a variety of Business Services job roles. These individuals may have frontline management accountabilities.</p> <p>Individuals in these roles carry out moderately complex tasks in a specialist field of expertise that requires business operations skills. They may possess substantial experience in a range of settings but seek to further develop their skills across a wide range of business functions.</p> </div>',
    total_course_duration = '52 weeks',
    offshore_tuition_fee = '',
    entry_requirements = '',
    apply_form = 'https://auscanus.edu.au/courses/diploma-of-business/',
    updated_at = NOW()
WHERE cricos_course_code = '111214G';

UPDATE courses SET
    course_description = '<div class="content"> <p>This qualification reflects the role of individuals who apply knowledge, practical skills and experience in leadership and management across a range of enterprise and industry contexts.</p> <p>Individuals at this level display initiative and judgement in planning, organising, implementing and monitoring their own workload and the workload of others. They use communication skills to support individuals and teams to meet organisational or enterprise requirements.</p> <p>They may plan, design, apply and evaluate solutions to unpredictable problems, and identify, analyse and synthesise information from a variety of sources.</p> </div>',
    total_course_duration = '52 weeks',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="content"> <p>This course is available to international students. There are no specific entry requirements listed in the qualification details or training package; however, applicants must meet Auscanus Institute of Australia’s entry requirements below:</p> <p><strong>Applicants must:</strong></p> <p style="margin-bottom: 14px;">Be 18 years of age or older at the time of course commencement.</p> <p style="margin-bottom: 14px;">Have successfully completed Year 12 or equivalent secondary schooling.</p> <p style="margin-bottom: 14px;">Demonstrate English language proficiency through one of the following approved tests: IELTS Academic 6.0, TOEFL iBT 60, PTE Academic 50, or equivalent English language proficiency.</p> <p>English language competence may also be demonstrated through documented evidence of any of the following:</p> <p style="margin-bottom: 14px;">Completion of a recognised ELICOS program with an English proficiency level considered equivalent to the course entry requirements.</p> <p style="margin-bottom: 14px;">Completion of at least two (2) years of study in Australia at AQF Level 4 or higher.</p> <p style="margin-bottom: 14px;">Minimum five (5) years of study in English in Australia, the United Kingdom, the United States of America, Canada, New Zealand, South Africa or the Republic of Ireland.</p> <p style="margin-bottom: 14px;">Completion of Year 12 or equivalent secondary schooling in English.</p> <p style="margin-bottom: 14px;">Applicants without documented evidence of English language proficiency may complete an online Language, Literacy, Numeracy and Digital Literacy (LLND) assessment and achieve a satisfactory outcome to meet AIA’s entry requirements.</p> <p><strong>Note:</strong> English language requirements and exemptions may vary depending on visa requirements and individual circumstances. Please contact AIA for further details or visit the <a href="https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/student-500#HowTo" rel="noopener" target="_blank">Department of Home Affairs website</a>.</p> </div>',
    apply_form = 'https://auscanus.edu.au/courses/diploma-of-leadership-and-management/',
    updated_at = NOW()
WHERE cricos_course_code = '111215F';

UPDATE courses SET
    course_description = '<div class="content"> <p>This qualification reflects the role of highly skilled senior operators who use a broad range of hospitality skills combined with managerial skills and sound knowledge of industry to coordinate hospitality operations. They operate independently, have responsibility for others and make a range of operational business decisions.</p> <p>This qualification provides a pathway to work in any hospitality industry sector as a departmental or small business manager. The diversity of employers includes restaurants, hotels, motels, catering operations, clubs, pubs, cafés, and coffee shops. This qualification allows for multiskilling and for acquiring targeted skills in accommodation services, cookery, food and beverage and gaming.</p> <p>The skills in this qualification must be applied in accordance with Commonwealth and State/Territory legislation, Australian standards and industry codes of practice.</p> <p>No occupational licensing, certification or specific legislative requirements apply to this qualification at the time of publication.</p> </div>',
    total_course_duration = '104 weeks',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="content"> <p>This course is available to international students. There are no specific entry requirements listed in the qualification details or training package; however, applicants must meet Auscanus Institute of Australia’s entry requirements below:</p> <p><strong>Applicants must:</strong></p> <p style="margin-bottom: 14px;">Be 18 years of age or older at the time of course commencement.</p> <p style="margin-bottom: 14px;">Have successfully completed Year 12 or equivalent secondary schooling.</p> <p style="margin-bottom: 14px;">Demonstrate English language proficiency through one of the following approved tests: IELTS Academic 6.0, TOEFL iBT 60, PTE Academic 50, or equivalent English language proficiency.</p> <p>English language competence may also be demonstrated through documented evidence of any of the following:</p> <p style="margin-bottom: 14px;">Completion of a recognised ELICOS program with an English proficiency level considered equivalent to the course entry requirements.</p> <p style="margin-bottom: 14px;">Completion of at least two (2) years of study in Australia at AQF Level 4 or higher.</p> <p style="margin-bottom: 14px;">Minimum five (5) years of study in English in Australia, the United Kingdom, the United States of America, Canada, New Zealand, South Africa or the Republic of Ireland.</p> <p style="margin-bottom: 14px;">Completion of Year 12 or equivalent secondary schooling in English.</p> <p style="margin-bottom: 14px;">Applicants without documented evidence of English language proficiency may complete an online Language, Literacy, Numeracy and Digital Literacy (LLND) assessment and achieve a satisfactory outcome to meet AIA’s entry requirements.</p> <p><strong>Note:</strong> English language requirements and exemptions may vary depending on visa requirements and individual circumstances. Please contact AIA for further details or visit the <a href="https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/student-500#HowTo" rel="noopener" target="_blank">Department of Home Affairs website</a>.</p> </div>',
    apply_form = 'https://auscanus.edu.au/courses/diploma-of-hospitality-management/',
    updated_at = NOW()
WHERE cricos_course_code = '114255G';

UPDATE courses SET
    course_description = '<div class="content"> <p>This qualification reflects the role of chefs and cooks who have a supervisory or team leading role in the kitchen. They operate independently or with limited guidance from others and use discretion to solve non-routine problems.</p> <p>This qualification provides a pathway to work in organisations such as restaurants, hotels, clubs, pubs, cafes and coffee shops, or to run a small business in these sectors. The skills in this qualification must be applied in accordance with Commonwealth and State or Territory legislation, Australian standards and industry codes of practice.</p> <p> </p> <p>No occupational licensing, certification or specific legislative requirements apply to this qualification at the time of publication.</p> </div>',
    total_course_duration = '78 weeks',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="content"> <p>This course is available to international students. There are no specific entry requirements listed in the qualification details or training package; however, applicants must meet Auscanus Institute of Australia’s entry requirements below:</p> <p><strong>Applicants must:</strong></p> <p style="margin-bottom: 14px;">Be 18 years of age or older at the time of course commencement.</p> <p style="margin-bottom: 14px;">Have successfully completed Year 12 or equivalent secondary schooling.</p> <p style="margin-bottom: 14px;">Demonstrate English language proficiency through one of the following approved tests: IELTS Academic 6.0, TOEFL iBT 60, PTE Academic 50, or equivalent English language proficiency.</p> <p>English language competence may also be demonstrated through documented evidence of any of the following:</p> <p style="margin-bottom: 14px;">Completion of a recognised ELICOS program with an English proficiency level considered equivalent to the course entry requirements.</p> <p style="margin-bottom: 14px;">Completion of at least two (2) years of study in Australia at AQF Level 4 or higher.</p> <p style="margin-bottom: 14px;">Minimum five (5) years of study in English in Australia, the United Kingdom, the United States of America, Canada, New Zealand, South Africa or the Republic of Ireland.</p> <p style="margin-bottom: 14px;">Completion of Year 12 or equivalent secondary schooling in English.</p> <p style="margin-bottom: 14px;">Applicants without documented evidence of English language proficiency may complete an online Language, Literacy, Numeracy and Digital Literacy (LLND) assessment and achieve a satisfactory outcome to meet AIA’s entry requirements.</p> <p><strong>Note:</strong> English language requirements and exemptions may vary depending on visa requirements and individual circumstances. Please contact AIA for further details or visit the <a href="https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/student-500#HowTo" rel="noopener" target="_blank">Department of Home Affairs website</a>.</p> </div>',
    apply_form = 'https://auscanus.edu.au/courses/certificate-iv-in-kitchen-management/',
    updated_at = NOW()
WHERE cricos_course_code = '114254H';

UPDATE courses SET
    course_description = '<div class="content"> <p>This qualification reflects the role of cooks who use a wide range of well-developed cookery skills and sound knowledge of kitchen operations to prepare food and menu items. Using discretion and judgement, they work with some independence and under limited supervision using plans, policies and procedures to guide work activities.</p> <p>Completion of this qualification contributes to recognition as a trade cook.</p> <p>This qualification provides a pathway to work as a cook in organisations such as restaurants, hotels, clubs, pubs, cafes, and coffee shops. The skills in this qualification must be applied in accordance with Commonwealth and State or Territory legislation, Australian standards and industry codes of practice.</p> <p>No occupational licensing, certification or specific legislative requirements apply to this qualification at the time of publication.</p> </div>',
    total_course_duration = '52 weeks',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="content"> <p>This course is available to international students. There are no specific entry requirements listed in the qualification details or training package; however, applicants must meet Auscanus Institute of Australia’s entry requirements below:</p> <p><strong>Applicants must:</strong></p> <p style="margin-bottom: 14px;">Be 18 years of age or older at the time of course commencement.</p> <p style="margin-bottom: 14px;">Have successfully completed Year 12 or equivalent secondary schooling.</p> <p style="margin-bottom: 14px;">Demonstrate English language proficiency through one of the following approved tests: IELTS Academic 6.0, TOEFL iBT 60, PTE Academic 50, or equivalent English language proficiency.</p> <p>English language competence may also be demonstrated through documented evidence of any of the following:</p> <p style="margin-bottom: 14px;">Completion of a recognised ELICOS program with an English proficiency level considered equivalent to the course entry requirements.</p> <p style="margin-bottom: 14px;">Completion of at least two (2) years of study in Australia at AQF Level 4 or higher.</p> <p style="margin-bottom: 14px;">Minimum five (5) years of study in English in Australia, the United Kingdom, the United States of America, Canada, New Zealand, South Africa or the Republic of Ireland.</p> <p style="margin-bottom: 14px;">Completion of Year 12 or equivalent secondary schooling in English.</p> <p style="margin-bottom: 14px;">Applicants without documented evidence of English language proficiency may complete an online Language, Literacy, Numeracy and Digital Literacy (LLND) assessment and achieve a satisfactory outcome to meet AIA’s entry requirements.</p> <p><strong>Note:</strong> English language requirements and exemptions may vary depending on visa requirements and individual circumstances. Please contact AIA for further details or visit the <a href="https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/student-500#HowTo" rel="noopener" target="_blank">Department of Home Affairs website</a>.</p> </div>',
    apply_form = 'https://auscanus.edu.au/courses/certificate-iii-in-commercial-cookery/',
    updated_at = NOW()
WHERE cricos_course_code = '114253J';

UPDATE courses SET
    course_description = '<div class="content"> <p>General English (ELICOS) helps adult international students build practical English for everyday communication, community participation and life in Australia. Across five levels from Elementary to Advanced, students develop speaking, listening, reading and writing, supported by vocabulary, grammar and pronunciation practice.</p> <p>Students may enrol at the level appropriate to their current English proficiency. AIA uses placement information and assessment to support the starting-level decision and identify learning needs.</p> <p>General English may also support students who plan to continue to English for Academic Purposes (EAP) or further study. Entry into any VET or other course remains subject to the current entry requirements for that course, applicable government requirements and AIA’s assessment.</p> </div>',
    total_course_duration = '58 weeks',
    offshore_tuition_fee = '',
    entry_requirements = '',
    apply_form = 'https://auscanus.edu.au/courses/elicos-general-english/',
    updated_at = NOW()
WHERE cricos_course_code = '115159K';

UPDATE courses SET
    course_description = '<div class="content"> <p>English for Academic Purposes (EAP) is designed for adult international students who want to develop the English skills used in vocational and tertiary study. Across Intermediate, Upper-Intermediate and Advanced levels, students practise academic reading, writing, listening and speaking in contexts such as lectures, tutorials, presentations, research and assignments.</p> <p>The course supports students to build confidence with academic conventions, including note-taking, summarising, paraphrasing, essay and report writing, referencing and critical thinking.</p> <p>EAP may support preparation for further study. Entry into any VET, higher education or other course remains subject to the current entry requirements of the chosen course or provider, applicable government requirements and AIA’s assessment.</p> </div>',
    total_course_duration = '34 weeks',
    offshore_tuition_fee = '',
    entry_requirements = '',
    apply_form = 'https://auscanus.edu.au/courses/elicos-academic-purposes/',
    updated_at = NOW()
WHERE cricos_course_code = '115160F';

UPDATE courses SET
    course_description = '',
    total_course_duration = '',
    offshore_tuition_fee = '',
    entry_requirements = '',
    apply_form = 'https://auscanus.edu.au/courses/hospitality-stream-operations/',
    updated_at = NOW()
WHERE cricos_course_code = '';

UPDATE courses SET
    course_description = '',
    total_course_duration = '',
    offshore_tuition_fee = '',
    entry_requirements = '',
    apply_form = 'https://auscanus.edu.au/courses/leadership-management-stream/',
    updated_at = NOW()
WHERE cricos_course_code = '';

UPDATE courses SET
    course_description = '',
    total_course_duration = '',
    offshore_tuition_fee = '',
    entry_requirements = '',
    apply_form = 'https://auscanus.edu.au/courses/commercial-cookery-stream-plus-ccs-2/',
    updated_at = NOW()
WHERE cricos_course_code = '';

UPDATE courses SET
    course_description = '<div class="content"> <p>This qualification reflects the role of individuals who apply highly specialised knowledge and skills in the field of organisational learning and capability development. Individuals in these roles generate and evaluate complex ideas. They also initiate, design and execute major learning and development functions within an organisation. Typically, they would have full responsibility and accountability for the personal output and work of others.</p> <p>This qualification may apply to leaders and managers in an organisation where learning is used to build organisational capability. The job roles that relate to this qualification may also include RTO Manager and RTO Director.</p> </div>',
    total_course_duration = '52 weeks',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="content"> <p>This course is available to international students. There are no specific entry requirements listed in the qualification details or training package; however, applicants must meet Auscanus Institute of Australia’s entry requirements below:</p> <p><strong>Applicants must meet one of the following academic or work experience requirements:</strong></p> <p style="margin-bottom: 14px;">Successful completion of an Australian Diploma qualification or higher, or equivalent; or</p> <p style="margin-bottom: 14px;">Successful completion of Year 12 or equivalent secondary schooling with a minimum of two (2) years equivalent full-time relevant workplace experience in an operational or leadership role within an enterprise.</p> <p><strong>Applicants must also:</strong></p> <p style="margin-bottom: 14px;">Be 18 years of age or older at the time of course commencement.</p> <p style="margin-bottom: 14px;">Demonstrate English language proficiency through one of the following approved tests: IELTS Academic 6.0, TOEFL iBT 60, PTE Academic 50, or equivalent English language proficiency.</p> <p>English language competence may also be demonstrated through documented evidence of any of the following:</p> <p style="margin-bottom: 14px;">Completion of a recognised ELICOS program with an English proficiency level considered equivalent to the course entry requirements.</p> <p style="margin-bottom: 14px;">Completion of at least two (2) years of study in Australia at AQF Level 4 or higher.</p> <p style="margin-bottom: 14px;">Minimum five (5) years of study in English in Australia, the United Kingdom, the United States of America, Canada, New Zealand, South Africa or the Republic of Ireland.</p> <p style="margin-bottom: 14px;">Completion of Year 12 or equivalent secondary schooling in English.</p> <p><strong>Note:</strong> English language requirements and exemptions may vary depending on visa requirements and individual circumstances. Please contact AIA for further details or visit the <a href="https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/student-500#HowTo" rel="noopener" target="_blank">Department of Home Affairs website</a>.</p> </div>',
    apply_form = 'https://auscanus.edu.au/courses/graduate-diploma-of-management-learning/',
    updated_at = NOW()
WHERE cricos_course_code = '117128A';

UPDATE courses SET
    course_description = '<div class="content"> <p>This qualification reflects the role of community services workers involved in the delivery, management and coordination of person-centred services to individuals, groups, and communities.</p> <p>At this level, workers have specialised skills in community services and work autonomously within their scope of practice under broad directions from senior management.</p> <p>Workers support people to make change in their lives to improve personal and social wellbeing and may also have responsibility for the supervision of other workers and volunteers. They may also undertake case management and program coordination.</p> <p>To achieve this qualification, the candidate must have completed at least 200 hours of work as detailed in the Assessment Requirements of units of competency. The skills in this qualification must be applied in accordance with Commonwealth and State or Territory legislation, Australian standards and industry codes of practice.</p> </div>',
    total_course_duration = '104 weeks',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="content"> <p>This course is available to international students. There are no specific entry requirements listed in the qualification details or training package; however, applicants must meet Auscanus Institute of Australia’s entry requirements below:</p> <p><strong>Applicants must:</strong></p> <p style="margin-bottom: 14px;">Be 18 years of age or older at the time of course commencement.</p> <p style="margin-bottom: 14px;">Have successfully completed Year 12 or equivalent secondary schooling.</p> <p style="margin-bottom: 14px;">Demonstrate English language proficiency through one of the following approved tests: IELTS Academic 6.0, TOEFL iBT 60, PTE Academic 50, or equivalent English language proficiency.</p> <p>English language competence may also be demonstrated through documented evidence of any of the following:</p> <p style="margin-bottom: 14px;">Completion of a recognised ELICOS program with an English proficiency level considered equivalent to the course entry requirements.</p> <p style="margin-bottom: 14px;">Completion of at least two (2) years of study in Australia at AQF Level 4 or higher.</p> <p style="margin-bottom: 14px;">Minimum five (5) years of study in English in Australia, the United Kingdom, the United States of America, Canada, New Zealand, South Africa or the Republic of Ireland.</p> <p style="margin-bottom: 14px;">Completion of Year 12 or equivalent secondary schooling in English.</p> <p style="margin-bottom: 14px;">Applicants without documented evidence of English language proficiency may complete an online Language, Literacy, Numeracy and Digital Literacy (LLND) assessment and achieve a satisfactory outcome to meet AIA’s entry requirements.</p> <p><strong>Note:</strong> English language requirements and exemptions may vary depending on visa requirements and individual circumstances. Please contact AIA for further details or visit the <a href="https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/student-500#HowTo" rel="noopener" target="_blank">Department of Home Affairs website</a>.</p> </div>',
    apply_form = 'https://auscanus.edu.au/courses/diploma-of-community-services/',
    updated_at = NOW()
WHERE cricos_course_code = '118319H';

UPDATE courses SET
    course_description = '<div class="content"> <p>This qualification reflects the role of individuals in the community, home or residential care setting who work under supervision and delegation as a part of a multi-disciplinary team, following an individualised plan to provide person-centred support to people who may require support due to ageing, disability or some other reason.</p> <p>These individuals take responsibility for their own outputs within the scope of their job role and delegation. Workers have a range of factual, technical and procedural knowledge, as well as some theoretical knowledge of the concepts and practices required to provide person-centred support.</p> <p>The skills in this qualification must be applied in accordance with Commonwealth and State/Territory legislation, Australian standards and industry codes of practice.</p> <p>To achieve this qualification, the candidate must have completed at least 120 hours of work as detailed in the Assessment Requirements of the units of competency.</p> </div>',
    total_course_duration = '52 weeks',
    offshore_tuition_fee = '',
    entry_requirements = '<div class="content"> <p>This course is available to international students. There are no specific entry requirements listed in the qualification details or training package; however, applicants must meet Auscanus Institute of Australia’s entry requirements below:</p> <p><strong>Applicants must:</strong></p> <p style="margin-bottom: 14px;">Be 18 years of age or older at the time of course commencement.</p> <p style="margin-bottom: 14px;">Have successfully completed Year 12 or equivalent secondary schooling.</p> <p style="margin-bottom: 14px;">Demonstrate English language proficiency through one of the following approved tests: IELTS Academic 6.0, TOEFL iBT 60, PTE Academic 50, or equivalent English language proficiency.</p> <p>English language competence may also be demonstrated through documented evidence of any of the following:</p> <p style="margin-bottom: 14px;">Completion of a recognised ELICOS program with an English proficiency level considered equivalent to the course entry requirements.</p> <p style="margin-bottom: 14px;">Completion of at least two (2) years of study in Australia at AQF Level 4 or higher.</p> <p style="margin-bottom: 14px;">Minimum five (5) years of study in English in Australia, the United Kingdom, the United States of America, Canada, New Zealand, South Africa or the Republic of Ireland.</p> <p style="margin-bottom: 14px;">Completion of Year 12 or equivalent secondary schooling in English.</p> <p style="margin-bottom: 14px;">Applicants without documented evidence of English language proficiency may complete an online Language, Literacy, Numeracy and Digital Literacy (LLND) assessment and achieve a satisfactory outcome to meet AIA’s entry requirements.</p> <p><strong>Note:</strong> English language requirements and exemptions may vary depending on visa requirements and individual circumstances. Please contact AIA for further details or visit the <a href="https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing/student-500#HowTo" rel="noopener" target="_blank">Department of Home Affairs website</a>.</p> </div>',
    apply_form = 'https://auscanus.edu.au/courses/certificate-iii-in-individual-support/',
    updated_at = NOW()
WHERE cricos_course_code = '118318J';