UPDATE courses SET
    course_description = '<div aria-labelledby="headingOne" class="accordion-collapse collapse show" data-bs-parent="#accordionExample" id="collapseOne"> <div class="accordion-body"> <div class="theory-box"> <p>This qualification provides a trade outcome in wall and floor tiling for residential and commercial construction work. The qualification has a core unit of competency requirements that cover common skills for the construction industry, as well as the specialist field of work, wall and floor tiling. Tilers work with materials like ceramic, glass, slate, marble, and clay. They cut these materials and lay tiles on walls and floors, both interior and exterior. They may also add decorative touches to their basic work.</p> </div> </div> </div>',
    total_course_duration = '96 weeks',
    offshore_tuition_fee = '24000',
    entry_requirements = '<div aria-labelledby="headingEight" class="accordion-collapse collapse" data-bs-parent="#accordionExample" id="collapseEight"> <div class="accordion-body"> <div class="theory-box"> <p>To ensure an appropriate learning opportunity, candidates need to demonstrate a capacity to undertake study at a Cert III level, this can be demonstrated via the following:</p> <table border="0" cellpadding="0" cellspacing="0" class="table-bordered table table-hover"> <tbody> <tr> <td><strong>English Language Requirement (International Students):</strong></td> <td>IELTS 5.5 Or equivalent PTE Academic Test Score or other equivalent English language test scores (e.g., TOEFL, ISLPR, CSWE, General English, EAP, etc).</td> </tr> <tr> <td><strong>Academic Level</strong></td> <td>Year 12 or equivalent high school certificate.</td> </tr> <tr> <td><strong>Minimum Age</strong></td> <td>18 years or over at the time of commencement.</td> </tr> </tbody> </table> <p><strong>Note: </strong>Students who do not meet the minimum English requirement for this course will need to package this course with an appropriate English Course before they can proceed into this course/qualification.</p> <p><strong>Note: </strong>Students are expected to be physically fit in order to take this course, as it involves physical activities such as lifting materials.</p> </div> </div> </div>',
    apply_form = 'https://acmi.wa.edu.au/certificate-III-in-wall-and-floor-tiling.php',
    created_at = NOW(),
    updated_at = NOW()
WHERE cricos_course_code = '116684C';

UPDATE courses SET
    course_description = '<div aria-labelledby="headingOne" class="accordion-collapse collapse show" data-bs-parent="#accordionExample" id="collapseOne"> <div class="accordion-body"> <div class="theory-box"> <p>This qualification reflects the trade-qualified role of a bricklayer, blocklayer, or paver who may have responsibility for undertaking heritage bricklaying, refractory bricklaying, bricklaying, blocklaying, and paving work in residential, industrial, and commercial contexts, in both existing and new constructions.</p> </div> </div> </div>',
    total_course_duration = '96 weeks',
    offshore_tuition_fee = '24000',
    entry_requirements = '<div aria-labelledby="headingEight" class="accordion-collapse collapse" data-bs-parent="#accordionExample" id="collapseEight"> <div class="accordion-body"> <div class="theory-box"> <p>To ensure an appropriate learning opportunity, candidates need to demonstrate a capacity to undertake study at a Cert III level, this can be demonstrated via the following:</p> <table border="0" cellpadding="0" cellspacing="0" class="table-bordered table table-hover"> <tbody> <tr> <td><strong>English Language Requirement (International Students):</strong></td> <td>IELTS 5.5 Or equivalent PTE Academic Test Score or other equivalent English language test scores (e.g., TOEFL, ISLPR, CSWE, General English, EAP, etc).</td> </tr> <tr> <td><strong>Academic Level</strong></td> <td>Year 12 or equivalent high school certificate.</td> </tr> <tr> <td><strong>Minimum Age</strong></td> <td>18 years or over at the time of commencement.</td> </tr> </tbody> </table> <p><strong>Note: </strong>Students who do not meet the minimum English requirement for this course will need to package this course with an appropriate English Course before they can proceed into this course/qualification.</p> <p><strong>Note: </strong>Students are expected to be physically fit in order to take this course, as it involves physical activities such as lifting materials.</p> </div> </div> </div>',
    apply_form = 'https://acmi.wa.edu.au/certificate-III-in-bricklaying-and-blocklaying.php',
    created_at = NOW(),
    updated_at = NOW()
WHERE cricos_course_code = '116725K';

UPDATE courses SET
    course_description = '<div aria-labelledby="headingOne" class="accordion-collapse collapse show" data-bs-parent="#accordionExample" id="collapseOne"> <div class="accordion-body"> <p><strong>BSB50120 Diploma of Business (Operations) </strong>This qualification reflects the role of individuals in a variety of Business Services job roles. These individuals may have frontline management accountabilities. </p> <p>Individuals in these roles carry out moderately complex tasks in a specialist field of expertise that requires business operations skills. They may possess substantial experience in a range of settings, but seek to further develop their skills across a wide range of business functions.</p> </div> </div>',
    total_course_duration = '52 weeks',
    offshore_tuition_fee = '9500',
    entry_requirements = '<div aria-labelledby="headingSix" class="accordion-collapse collapse" data-bs-parent="#accordionExample" id="collapseSix"> <div class="accordion-body"> <p>To ensure an appropriate learning opportunity, candidates need to demonstrate a capacity to undertake study at a Diploma level, this can be demonstrated via the following: </p> <table border="0" cellpadding="0" cellspacing="0" class="table-bordered table table-hover"> <tbody> <tr> <td><strong>English Language(International Students) </strong></td> <td>IELTS Academic 6.0 Or PTE Academic Test Score of minimum 50 in each component or others equivalent (e.g., TOEFL, ISLPR, CSWE, General English, EAP) English language test scores.</td> </tr> <tr> <td><strong>Academic Level </strong></td> <td>Year 12 or equivalent high school certificate </td> </tr> <tr> <td><strong>Minimum Age </strong></td> <td>18 years or over at the time of commencement. </td> </tr> </tbody> </table> <p><strong>Note: </strong>Students who do not meet the minimum English requirement for this course will need to package this course with an appropriate English Course before they can proceed into this course/qualification.</p> </div> </div>',
    apply_form = 'https://acmi.wa.edu.au/certificate-in-diploma-of-business.php',
    created_at = NOW(),
    updated_at = NOW()
WHERE cricos_course_code = '106897F';

UPDATE courses SET
    course_description = '<div aria-labelledby="headingOne" class="accordion-collapse collapse show" data-bs-parent="#accordionExample" id="collapseOne"> <div class="accordion-body"> <div class="theory-box"> <p><strong>BSB60120 Advanced Diploma of Business</strong> reflects the role of individuals in a variety of Business Services job roles. These individuals may have general management accountabilities. </p> <p>Individuals in these roles carry out complex tasks in a specialist field of expertise. They may undertake technical research and analysis and will often contribute to setting the strategic direction for a work area. </p> <p>Conversely, it may also apply to those with little or no vocational experience, but who possess sound theoretical business skills and knowledge that they would like to develop in order to create further educational and employment opportunities. </p> <p>The course covers a range of competencies essential for management processes and effective leadership in an organisation and it helps develop communication skills to support individuals and teams to meet organisational or enterprise requirements. Learners will also develop skills and knowledge in managing teams, work relationships, continuous improvement, professional development, and workplace learning. </p> </div> </div> </div>',
    total_course_duration = '52 weeks',
    offshore_tuition_fee = '9500',
    entry_requirements = '<div aria-labelledby="headingSeven" class="accordion-collapse collapse" data-bs-parent="#accordionExample" id="collapseSeven"> <div class="accordion-body"> <div class="theory-box"> <p>To ensure an appropriate learning opportunity, candidates need to demonstrate a capacity to undertake study at Advanced Diploma level, this can be demonstrated via the following:</p> <table border="0" cellpadding="0" cellspacing="0" class="table-bordered table table-hover"> <tbody> <tr> <td><strong>English Language(International Students) </strong></td> <td>IELTS Academic 6.0 Or PTE Academic Test Score of minimum 50 in each component or others equivalent (e.g., TOEFL, ISLPR, CSWE, General English, EAP) English language test scores.</td> </tr> <tr> <td><strong>Academic Level </strong></td> <td>Year 12 or equivalent high school certificate.</td> </tr> <tr> <td><strong>Minimum Age </strong></td> <td>18 years or over at the time of commencement. </td> </tr> </tbody> </table> <p><b>Entry to this qualification is limited to those who:</b></p> <p style="margin-bottom: 0;">Have completed a Diploma or Advanced Diploma from the BSB Training Package (current or superseded equivalent versions).</p> <p style="margin-bottom: 0;">or</p> <p>Have two years equivalent full-time relevant workplace experience in an operational or leadership role in an enterprise.</p> <p><strong>Note: </strong>Students who do not meet the minimum English requirement for this course will need to package this course with an appropriate English Course before they can proceed into this course/qualification.</p> </div> </div> </div>',
    apply_form = 'https://acmi.wa.edu.au/certificate-in-advanced-diploma-of-business.php',
    created_at = NOW(),
    updated_at = NOW()
WHERE cricos_course_code = '106898E';

UPDATE courses SET
    course_description = '<div aria-labelledby="headingOne" class="accordion-collapse collapse show" data-bs-parent="#accordionExample" id="collapseOne"> <div class="accordion-body"> <div class="theory-box"> <p><b>RII50520 Diploma of Civil Construction Design</b> Qualification reflects the role of individuals working as designers or design paraprofessionals who support professional engineers. They perform tasks involving a high level of autonomy and requiring the application of significant judgement in planning and determining the selection of equipment/roles/techniques for themselves and others. They are required to develop site specific work designs to ensure the implementation of the client’s site requirements. They demonstrate the application of a broad range of technical, managerial, coordination and planning skills.</p> <p>Students will learn the calculation, estimation and foundation measurement of civil construction projects. Students will also get an opportunity to establish required skill and knowledge in relation to detail drafting, technical specification and bills of the quantities for the building projects.</p> </div> </div> </div>',
    total_course_duration = '65 weeks',
    offshore_tuition_fee = '16000',
    entry_requirements = '<div aria-labelledby="headingEight" class="accordion-collapse collapse" data-bs-parent="#accordionExample" id="collapseEight"> <div class="accordion-body"> <div class="theory-box"> <p>To ensure an appropriate learning opportunity, candidates need to demonstrate a capacity to undertake study at Diploma level, this can be demonstrated via the following:</p> <table border="0" cellpadding="0" cellspacing="0" class="table-bordered table table-hover"> <tbody> <tr> <td><strong>English Language (International Students) </strong></td> <td>IELTS Academic 6.0 Or PTE Academic Test Score of minimum 50 in each component or others equivalent (e.g., TOEFL, ISLPR, CSWE, General English, EAP) English language test scores.</td> </tr> <tr> <td><strong>Academic Level</strong></td> <td>Year 12 or equivalent high school certificate.</td> </tr> <tr> <td><strong>Minimum Age </strong></td> <td>18 years or over at the time of commencement.</td> </tr> </tbody> </table> <p><strong>Note: </strong>Students who do not meet the minimum English requirement for this course will need to package this course with an appropriate English Course before they can proceed into this course/qualification.</p> </div> </div> </div>',
    apply_form = 'https://acmi.wa.edu.au/diploma-of-civil-construction-design.php',
    created_at = NOW(),
    updated_at = NOW()
WHERE cricos_course_code = '107304F';

UPDATE courses SET
    course_description = '<div aria-labelledby="headingOne" class="accordion-collapse collapse show" data-bs-parent="#accordionExample" id="collapseOne"> <div class="accordion-body"> <div class="theory-box"> <p><b>RII60520 Advanced Diploma of Civil Construction Design</b> Qualification reflects the role of individuals working as designers or design paraprofessionals who support professional engineers. </p> </div> </div> </div>',
    total_course_duration = '39 weeks',
    offshore_tuition_fee = '12000',
    entry_requirements = '<div aria-labelledby="headingFour" class="accordion-collapse collapse" data-bs-parent="#accordionExample" id="collapseFour"> <div class="accordion-body"> <div class="theory-box medical-care"> <p>Completion of <strong>RII50520 </strong>Diploma of Civil Construction Design is required for entry into <strong>RII60520 </strong>Advanced Diploma of Civil Construction Design course.</p> </div> </div> </div>',
    apply_form = 'https://acmi.wa.edu.au/advanced-diploma-of-civil-construction-design.php',
    created_at = NOW(),
    updated_at = NOW()
WHERE cricos_course_code = '107305E';

UPDATE courses SET
    course_description = '<div aria-labelledby="headingOne" class="accordion-collapse collapse show" data-bs-parent="#accordionExample" id="collapseOne"> <div class="accordion-body"> <div class="theory-box"> <p>This qualification reflects the role of individuals who apply highly specialised knowledge and skills in the field of organisational learning and capability development. Individuals in these roles generate and evaluate complex ideas. They also initiate, design and execute major learning and development functions within an organisation. Typically, they would have full responsibility and accountability for the personal output and work of others. This qualification may apply to leaders and managers in an organisation where learning is used to build organisational capability. The job roles that relate to this qualification may also include RTO Manager and RTO Director. </p> <a class="btn btn-success" href="https://training.gov.au/Training/Details/BSB80120" rel="noreffer,noopner" target="_blank">FInd on training.gov.au</a> </div> </div> </div>',
    total_course_duration = '104 weeks',
    offshore_tuition_fee = '19400',
    entry_requirements = '<div aria-labelledby="headingThree" class="accordion-collapse collapse" data-bs-parent="#accordionExample" id="collapseThree"> <div class="accordion-body"> <div class="theory-box medical-care"> <p>To ensure an appropriate learning opportunity, student need to demonstrate a capacity to undertake study this qualification can be demonstrated via the following: </p> <p><strong>International Students </strong></p><div></div><p></p> <div class="list"> <ul> <li>Completion of a recognised degree or diploma or advanced diploma or equivalent. (Any field) </li> <li>Year 12 High school </li> <li>Student must be aged 18 or older </li> <li>Upper-intermediate Level of English or </li> <li>IELTS Academic 6.0 or </li> <li>PTE Academic Test Score of minimum 50 in each component or </li> <li>Others equivalent. (e.g., TOEFL, ISLPR, CSWE, General English, EAP) English language test scores.</li> </ul> </div> <p>You may be exempted to provide evidence of English Language competence if you have successfully completed below: </p> <div class="list"> <ul> <li>5 years study evidence in an English-speaking country. </li> <li>At least 6 months of a Certificate IV level course in an Australian RTO. </li> <li>An English foundation course in Australia </li> </ul> </div> <p><strong>Note: </strong>Student will need to meet the Department of Home Affairs (DHA) www.homeaffairs.gov.au English language requirements for student visa applications. <strong>Note:</strong> promotional options may be available. For detailed information, kindly contact your agent or the ACMi admissions team.</p> </div> </div> </div>',
    apply_form = 'https://acmi.wa.edu.au/BSB80120-graduate-diploma-of-management-learning.php',
    created_at = NOW(),
    updated_at = NOW()
WHERE cricos_course_code = '108557K';

UPDATE courses SET
    course_description = '<div aria-labelledby="headingOne" class="accordion-collapse collapse show" data-bs-parent="#accordionExample" id="collapseOne"> <div class="accordion-body"> <div class="theory-box"> <p><b>CPC50320 Diploma of Building and Construction (Management)</b> qualification develops the knowledge and skills for senior management roles in the building and construction industry. Graduates may pursue careers as Project Managers, Construction Managers, Estimating Managers, or Sales Managers.</p> </div> </div> </div>',
    total_course_duration = '52 weeks',
    offshore_tuition_fee = '12000',
    entry_requirements = '<div aria-labelledby="headingEight" class="accordion-collapse collapse" data-bs-parent="#accordionExample" id="collapseEight"> <div class="accordion-body"> <div class="theory-box"> <p>To ensure an appropriate learning opportunity, candidates need to demonstrate a capacity to undertake study at Diploma level, this can be demonstrated via the following:</p> <table border="0" cellpadding="0" cellspacing="0" class="table-bordered table table-hover"> <tbody> <tr> <td><strong>English Language Requirement (International Students):</strong></td> <td>IELTS Academic 6.0 Or PTE Academic Test Score of minimum 50 in each component or others equivalent (e.g., TOEFL, ISLPR, CSWE, General English, EAP) English language test scores.</td> </tr> <tr> <td><strong>Academic Level</strong></td> <td>Year 12 or equivalent high school certificate..</td> </tr> <tr> <td><strong>Minimum Age</strong></td> <td>18 years or over at the time of commencement.</td> </tr> </tbody> </table> <p><strong>Note: </strong>Students who do not meet the minimum English requirement for this course will need to package this course with an appropriate English Course before they can proceed into this course/qualification.</p> </div> </div> </div>',
    apply_form = 'https://acmi.wa.edu.au/CPC50320-diploma-of-building-and-construction.php',
    created_at = NOW(),
    updated_at = NOW()
WHERE cricos_course_code = '118886K';