UPDATE courses SET
    course_description = '<div class="elementor-widget-container"> <p>Advanced Diploma of Business reflects the role of individuals in a variety of Business Services job roles. These individuals may have general management accountabilities.</p> <p>Individuals in these roles carry out complex tasks in a specialist field of expertise. They may undertake technical research and analysis, and will often contribute to setting the strategic direction for a work area.</p> <p>The qualification is suited to individuals who are responsible for the supervision and leadership of a team or work area (including by managing staff performance and making staffing decisions).</p> </div>',
    total_course_duration = '52 Weeks',
    offshore_tuition_fee = '15000',
    entry_requirements = '<div class="elementor-widget-container"> <p>To be considered for enrolment, applicants must:</p> <ul style="margin-left: 25px"> <li>Be at least 18 years of age.</li> <li>Have completed at least the equivalent of Year 12.</li> <li>Have an IELTS Academic score of 6.0 with test results no more than 2 years old.</li> <li>Complete a Core Skills Check. <p><em>Note: Applicants identified as at risk will be required to complete a full LLND assessment and a Course Pre-Entry Review (including an interview where required) to confirm their suitability before enrolment.</em></p></li> <li>Have access to a computer or laptop with a reliable internet connection, webcam, and microphone, to complete online learning, assessments, and Learning Management System (LMS) requirements.</li> </ul> <p><em style="display: block;padding-top:24px">Applicants do not need to provide IELTS (or equivalent) results if they can provide documented evidence of either:</em></p> <ul style="margin-left: 25px"> <li>Completion of at least 6 months of a Certificate IV level course at an Australian RTO, or</li> <li>Successful completion of a Brighton College English Placement Test.</li> </ul> <p><em style="display: block;padding-top:24px">Note: Other recognised English tests (e.g. PTE Academic, TOEFL) can be accepted. Applicants must provide their results so equivalence to IELTS Academic 6.0 can be confirmed.</em></p> </div>',
    apply_form = 'https://brighton.edu.au/courses/advanced-diploma-of-business/',
    updated_at = NOW()
WHERE cricos_course_code = '105065K';
UPDATE courses SET
    course_description = '<div class="elementor-widget-container"> <p class="ait4">This qualification reflects the role of highly skilled senior managers who use a broad range of hospitality skills combined with specialised managerial skills and substantial knowledge of industry to coordinate hospitality operations. They operate with significant autonomy and are responsible for making strategic business management decisions.</p> <p class="ait4">This qualification provides a pathway to work in any hospitality industry sector and for a diversity of employers including restaurants, hotels, motels, catering operations, clubs, pubs, cafés, and coffee shops. This qualification allows for multi-skilling and for acquiring targeted skills in accommodation services, cookery, food and beverage and gaming.</p> </div>',
    total_course_duration = '104 Weeks',
    offshore_tuition_fee = '15500',
    entry_requirements = '<div class="elementor-widget-container"> <p>To be considered for enrolment, applicants must:</p> <ul style="margin-left: 25px"> <li>Be at least 18 years of age.</li> <li>Have completed at least the equivalent of Year 12.</li> <li>Have an IELTS Academic score of 6.0 with test results no more than 2 years old.</li> <li>Complete a Core Skills Check.<br/> <em>Note: Applicants identified as at risk will be required to complete a full LLND assessment and a Course Pre-Entry Review (including an interview where required) to confirm their suitability before enrolment.</em></li> <li>Have access to a computer or laptop with a reliable internet connection, webcam, and microphone, to complete online learning, assessments, and Learning Management System (LMS) requirements.</li> </ul> <p><em style="display: block;padding-top: 24px">Applicants do not need to provide IELTS (or equivalent) results if they can provide documented evidence of either:</em></p> <ul style="margin-left: 25px"> <li>Completion of at least 6 months of a Certificate IV level course at an Australian RTO, or</li> <li>Successful completion of a Brighton College English Placement Test.</li> </ul> <p><em style="display: block;padding-top:24px">Note: Other recognised English tests (e.g. PTE Academic, TOEFL) can be accepted. Applicants must provide their results so equivalence to IELTS Academic 6.0 can be confirmed.</em></p> </div>',
    apply_form = 'https://brighton.edu.au/courses/advanced-diploma-of-hospitality-management/',
    updated_at = NOW()
WHERE cricos_course_code = '111092A';
UPDATE courses SET
    course_description = '<div class="elementor-widget-container"> <p class="RTOWorksBodyText">Advanced Diploma of Information Technology reflects the role of individuals in a variety of information and communications technology (ICT) roles who have significant experience in specialist technical skills, or managerial business and people management skills.</p> <p class="RTOWorksBodyText">Individuals in these roles carry out complex tasks in a specialist field, working independently, leading a team or a strategic direction of a business. They apply their skills across a wide range of industries and business functions, or as a business owner (sole trader/contractor).</p> </div>',
    total_course_duration = '104 Weeks',
    offshore_tuition_fee = '24000',
    entry_requirements = '<div class="elementor-widget-container"> <p>To be considered for enrolment, applicants must:</p> <ul style="margin-left: 25px"> <li>Be at least 18 years of age.</li> <li>Have completed at least the equivalent of Year 12.</li> <li>Have an IELTS Academic score of 6.0 with test results no more than 2 years old.</li> <li>Complete a Core Skills Check.<br/> <em>Note: Applicants identified as at risk will be required to complete a full LLND assessment and a Course Pre-Entry Review (including an interview where required) to confirm their suitability before enrolment.</em></li> <li>Have access to a computer or laptop with a reliable internet connection, webcam, and microphone, to complete online learning, assessments, and Learning Management System (LMS) requirements.</li> </ul> <p><em style="display: block;padding-top:24px">Applicants do not need to provide IELTS (or equivalent) results if they can provide documented evidence of either:</em></p> <ul style="margin-left: 25px"> <li>Completion of at least 6 months of a Certificate IV level course at an Australian RTO, or</li> <li>Successful completion of a Brighton College English Placement Test.</li> </ul> <p><em style="display: block;padding-top:24px">Note: Other recognised English tests (e.g. PTE Academic, TOEFL) can be accepted. Applicants must provide their results so equivalence to IELTS Academic 6.0 can be confirmed.</em></p> </div>',
    apply_form = 'https://brighton.edu.au/courses/advanced-diploma-of-information-technology/',
    updated_at = NOW()
WHERE cricos_course_code = '105309F';
UPDATE courses SET
    course_description = '<div class="elementor-widget-container"> <p>CHC33021 Certificate III in Individual Support reflects the role of workers in the community and/or residential setting who follow an individualized plan to provide person-centered support to people who may require support due to ageing, disability or some other reason. Work involves using discretion and judgement in relation to individual support as well as taking responsibility for own outputs. Workers have a range of factual, technical and procedural knowledge, as well as some theoretical knowledge of the concepts and practices required to provide person-centred support.</p> <p>To achieve this qualification, the candidate must have completed at least 120 hours of work as detailed in the Assessment Requirements of the units of competency.</p> <p>The latest release of the qualification can be found at: <a href="https://training.gov.au/Training/Details/CHC33021" rel="noopener" target="_blank">https://training.gov.au/Training/Details/CHC33021</a></p> </div>',
    total_course_duration = '45 Weeks',
    offshore_tuition_fee = '16000',
    entry_requirements = '<div class="elementor-widget-container"> <p>To be considered for enrolment, applicants must:</p> <ul style="margin-left: 25px"> <li>Be at least 18 years of age.</li> <li>Have completed at least the equivalent of Year 11.</li> <li>Have an IELTS Academic score of 6.0 (or equivalent), with test results no more than 2 years old.</li> <li>Complete a Core Skills Check.<br/> <em>Note: Applicants identified as at risk will be required to complete a full LLND assessment and a Course Pre-Entry Review (including an interview where required) to confirm their suitability before enrolment.</em></li> <li>Have access to a computer or laptop with a reliable internet connection, webcam, and microphone, to complete online learning, assessments, and Learning Management System (LMS) requirements.</li> </ul> <p><em style="display: block;padding-top: 24px">Applicants do not need to provide IELTS (or equivalent) results if they can provide documented evidence of either:</em></p> <ul style="margin-left: 25px"> <li>Completion of at least 6 months of a Certificate III level course at an Australian RTO, or</li> <li>Successful completion of a Brighton College English Placement Test.</li> </ul> <p><em style="display: block;padding-top: 24px">Note: Other recognised English tests (e.g. PTE Academic, TOEFL) can be accepted. Applicants must provide their results so equivalence to IELTS Academic 6.0 can be confirmed.</em></p> </div>',
    apply_form = 'https://brighton.edu.au/courses/certificate-iii-in-individual-support/',
    updated_at = NOW()
WHERE cricos_course_code = '112949D';
UPDATE courses SET
    course_description = '<div class="elementor-widget-container"> <p>Certificate IV in Ageing Support reflects the role of support workers who complete specialised tasks and functions in aged services; either in residential, home or community-based environments. Workers will take responsibility for their own outputs within defined organisation guidelines and maintain quality service delivery through the development, facilitation and review of individualized service planning and delivery.</p> <p>Workers may be required to demonstrate leadership and have limited responsibility for the organisation and the quantity and quality of outputs of others within limited parameters.</p> <p>To achieve this qualification, the candidate must have completed at least 120 hours of work as detailed in the Assessment Requirements of the units of competency.</p> <p>The latest release of the qualification can be found at: <a href="https://training.gov.au/Training/Details/CHC43015" rel="noopener" target="_blank">https://training.gov.au/Training/Details/CHC43015</a></p> </div>',
    total_course_duration = '52 Weeks',
    offshore_tuition_fee = '16000',
    entry_requirements = '<div class="elementor-widget-container"> <p>To be considered for enrolment, applicants must:</p> <ul style="margin-left: 25px"> <li>Be at least 18 years of age.</li> <li>Have completed at least the equivalent of Year 12.</li> <li>Have an IELTS Academic score of 6.0 (or equivalent), with test results no more than 2 years old.</li> <li>Complete a Core Skills Check.<br/> <em>Note: Applicants identified as at risk will be required to complete a full LLND assessment and a Course Pre-Entry Review (including an interview where required) to confirm their suitability before enrolment.</em></li> <li>Have access to a computer or laptop with a reliable internet connection, webcam, and microphone, to complete online learning, assessments, and Learning Management System (LMS) requirements.</li> </ul> <p><em style="display: block;padding-top:24px">Applicants do not need to provide IELTS (or equivalent) results if they can provide documented evidence of either:</em></p> <ul style="margin-left: 25px"> <li>Completion of at least 6 months of a Certificate III level course at an Australian RTO, or</li> <li>Successful completion of a Brighton College English Placement Test.</li> </ul> <p><em style="display: block;padding-top:24px">Note: Other recognised English tests (e.g. PTE Academic, TOEFL) can be accepted. Applicants must provide their results so equivalence to IELTS Academic 6.0 can be confirmed.</em></p> </div>',
    apply_form = 'https://brighton.edu.au/courses/certificate-iv-in-ageing-support/',
    updated_at = NOW()
WHERE cricos_course_code = '102358K';
UPDATE courses SET
    course_description = '<div class="elementor-widget-container"> <p>BSB40120 Certificate IV in Business(Leadership) reflects the role of individuals in a variety of Business Services job roles. These individuals may have supervisory performance accountabilities. Individuals in these roles carry out a mix of specialist and moderately complex administrative or operational tasks that require self -development skills. They use well-developed skills and a broad knowledge base to apply solutions to a defined range of unpredictable problems and analyse information from a variety of sources. They may provide leadership and guidance to others with some limited responsibility for the output of others.</p> </div>',
    total_course_duration = '39 Weeks',
    offshore_tuition_fee = '15000',
    entry_requirements = '<div class="elementor-widget-container"> <p>To be considered for enrolment, applicants must:</p> <ul style="margin-left: 25px"> <li>Be at least 18 years of age.</li> <li>Have completed at least the equivalent of Year 12.</li> <li>Have an IELTS Academic score of 6.0 (or equivalent), with test results no more than 2 years old.</li> <li>Complete a Core Skills Check.<br/> <em>Note: Applicants identified as at risk will be required to complete a full LLND assessment and a Course Pre-Entry Review (including an interview where required) to confirm their suitability before enrolment.</em></li> <li>Have access to a computer or laptop with a reliable internet connection, webcam, and microphone, to complete online learning, assessments, and Learning Management System (LMS) requirements.</li> </ul> <p><em style="display: block;padding-top:24px">Applicants do not need to provide IELTS (or equivalent) results if they can provide documented evidence of either:</em></p> <ul style="margin-left: 25px"> <li>Completion of at least 6 months of a Certificate III level course at an Australian RTO, or</li> <li>Successful completion of a Brighton College English Placement Test.</li> </ul> <p><em style="display: block;padding-top:24px">Note: Other recognised English tests (e.g. PTE Academic, TOEFL) can be accepted. Applicants must provide their results so equivalence to IELTS Academic 6.0 can be confirmed.</em></p> </div>',
    apply_form = 'https://brighton.edu.au/courses/certificate-iv-in-business-leadership',
    updated_at = NOW()
WHERE cricos_course_code = '115207G';
UPDATE courses SET
    course_description = '<div class="elementor-widget-container"> <p>Certificate IV in Kitchen Management reflects the role of chefs and cooks who have a supervisory or team leading role in the kitchen. They operate independently or with limited guidance from others and use discretion to solve non-routine problems.</p> <p class="ait4">This qualification provides a pathway to work in organisations such as restaurants, hotels, clubs, pubs, cafes and coffee shops, or to run a small business in these sectors.</p> </div>',
    total_course_duration = '78 Weeks',
    offshore_tuition_fee = '20000',
    entry_requirements = '<div class="elementor-widget-container"> <p>To be considered for enrolment, applicants must:</p> <ul style="margin-left: 25px"> <li>Be at least 18 years of age.</li> <li>Have completed at least the equivalent of Year 12.</li> <li>Have an IELTS Academic score of 6.0 (or equivalent), with test results no more than 2 years old.</li> <li>Complete a Core Skills Check.<br/> <em>Note: Applicants identified as at risk will be required to complete a full LLND assessment and a Course Pre-Entry Review (including an interview where required) to confirm their suitability before enrolment.</em></li> <li>Have access to a computer or laptop with a reliable internet connection, webcam, and microphone, to complete online learning, assessments, and Learning Management System (LMS) requirements.</li> </ul> <p><em style="display: block;padding-top:24px">Applicants do not need to provide IELTS (or equivalent) results if they can provide documented evidence of either:</em></p> <ul style="margin-left: 25px"> <li>Completion of at least 6 months of a Certificate III level course at an Australian RTO, or</li> <li>Successful completion of a Brighton College English Placement Test.</li> </ul> <p><em style="display: block;padding-top:24px">Note: Other recognised English tests (e.g. PTE Academic, TOEFL) can be accepted. Applicants must provide their results so equivalence to IELTS Academic 6.0 can be confirmed.</em></p> </div>',
    apply_form = 'https://brighton.edu.au/courses/certificate-iv-in-kitchen-management/',
    updated_at = NOW()
WHERE cricos_course_code = '109545F';
UPDATE courses SET
    course_description = '<div class="elementor-widget-container"> <p class="ait4">Diploma of Business reflects the role of individuals in a variety of Business Services job roles. These individuals may have frontline management accountabilities.</p> <p class="ait4">Individuals in these roles carry out moderately complex tasks in a specialist field of expertise that requires business operations skills. They may possess substantial experience in a range of settings but seek to further develop their skills across a wide range of business functions. (<a href="https://training.gov.au/Training/Details/39c3502f-a9f3-4824-969d-64eee8d3b40e" rel="noopener" target="_blank">https://training.gov.au</a>)</p> </div>',
    total_course_duration = '52 Weeks',
    offshore_tuition_fee = '15000',
    entry_requirements = '<div class="elementor-widget-container"> <p>To be considered for enrolment, applicants must:</p> <ul style="margin-left: 25px"> <li>Be at least 18 years of age.</li> <li>Have completed at least the equivalent of Year 12.</li> <li>Have an IELTS Academic score of 6.0 with test results no more than 2 years old.</li> <li>Complete a Core Skills Check.<br/> <em>Note: Applicants identified as at risk will be required to complete a full LLND assessment and a Course Pre-Entry Review (including an interview where required) to confirm their suitability before enrolment.</em></li> <li>Have access to a computer or laptop with a reliable internet connection, webcam, and microphone, to complete online learning, assessments, and Learning Management System (LMS) requirements.</li> </ul> <p><em style="display: block;padding-top:24px">Applicants do not need to provide IELTS (or equivalent) results if they can provide documented evidence of either:</em></p> <ul style="margin-left: 25px"> <li>Completion of at least 6 months of a Certificate IV level course at an Australian RTO, or</li> <li>Successful completion of a Brighton College English Placement Test.</li> </ul> <p><em style="display: block;padding-top:24px">Note: Other recognised English tests (e.g. PTE Academic, TOEFL) can be accepted. Applicants must provide their results so equivalence to IELTS Academic 6.0 can be confirmed.</em></p> </div>',
    apply_form = 'https://brighton.edu.au/courses/diploma-of-business-business-operations/',
    updated_at = NOW()
WHERE cricos_course_code = '104718H';
UPDATE courses SET
    course_description = '<div class="elementor-widget-container"> <p>CHC52025 Diploma of Community services reflects the roles of community services, case management and social housing workers involved in managing, coordinating and/or delivering person-centered services to individuals, groups and communities.</p> <p>At this level, workers have specialized skills in community services and work autonomously under broad directions from senior management. Workers are usually providing direct support to individuals or groups of individuals. Workers may also have responsibility for the supervision of other workers and volunteers and/or case management; program coordination or the development of new business opportunities.</p> <p>The latest release of the qualification can be found at <a href="https://training.gov.au/Training/Details/CHC52025" rel="noopener" target="_blank">https://training.gov.au/Training/Details/CHC52025</a></p> </div>',
    total_course_duration = '78 Weeks',
    offshore_tuition_fee = '20000',
    entry_requirements = '<div class="elementor-widget-container"> <p>To be considered for enrolment, applicants must:</p> <ul style="margin-left: 25px"> <li>Be at least 18 years of age.</li> <li>Have completed at least the equivalent of Year 12.</li> <li>Have an IELTS Academic score of 6.0 with test results no more than 2 years old.</li> <li>Complete a Core Skills Check.<br/> <em>Note: Applicants identified as at risk will be required to complete a full LLND assessment and a Course Pre-Entry Review (including an interview where required) to confirm their suitability before enrolment.</em></li> <li>Have access to a computer or laptop with a reliable internet connection, webcam, and microphone, to complete online learning, assessments, and Learning Management System (LMS) requirements.</li> </ul> <p><em style="display: block;padding-top:24px">Applicants do not need to provide IELTS (or equivalent) results if they can provide documented evidence of either:</em></p> <ul style="margin-left: 25px"> <li>Completion of at least 6 months of a Certificate IV level course at an Australian RTO, or</li> <li>Successful completion of a Brighton College English Placement Test.</li> </ul> <p><em style="display: block;padding-top:24px">Note: Other recognised English tests (e.g. PTE Academic, TOEFL) can be accepted. Applicants must provide their results so equivalence to IELTS Academic 6.0 can be confirmed.</em></p> </div>',
    apply_form = 'https://brighton.edu.au/courses/diploma-of-community-services/',
    updated_at = NOW()
WHERE cricos_course_code = '118764J';
UPDATE courses SET
    course_description = '<div class="elementor-widget-container"> <p class="ait4">This qualification reflects the role of highly skilled senior operators who use a broad range of hospitality skills combined with managerial skills and sound knowledge of industry to coordinate hospitality operations. They operate independently, have responsibility for others and make a range of operational business decisions.</p> <p class="ait4">This qualification provides a pathway to work in any hospitality industry sector as a departmental or small business manager. The diversity of employers includes restaurants, hotels, motels, catering operations, clubs, pubs, cafés, and coffee shops. This qualification allows for multiskilling and for acquiring targeted skills in accommodation services, cookery, food and beverage and gaming.</p> </div>',
    total_course_duration = '78 Weeks',
    offshore_tuition_fee = '15500',
    entry_requirements = '<div class="elementor-widget-container"> <p>To be considered for enrolment, applicants must:</p> <ul style="margin-left: 25px"> <li>Be at least 18 years of age.</li> <li>Have completed at least the equivalent of Year 12.</li> <li>Have an IELTS Academic score of 6.0 with test results no more than 2 years old.</li> <li>Complete a Core Skills Check.<br/> <em>Note: Applicants identified as at risk will be required to complete a full LLND assessment and a Course Pre-Entry Review (including an interview where required) to confirm their suitability before enrolment.</em></li> <li>Have access to a computer or laptop with a reliable internet connection, webcam, and microphone, to complete online learning, assessments, and Learning Management System (LMS) requirements.</li> </ul> <p><em style="display: block;padding-top:24px">Applicants do not need to provide IELTS (or equivalent) results if they can provide documented evidence of either:</em></p> <ul style="margin-left: 25px"> <li>Completion of at least 6 months of a Certificate IV level course at an Australian RTO, or</li> <li>Successful completion of a Brighton College English Placement Test.</li> </ul> <p><em style="display: block;padding-top:24px">Note: Other recognised English tests (e.g. PTE Academic, TOEFL) can be accepted. Applicants must provide their results so equivalence to IELTS Academic 6.0 can be confirmed.</em></p> </div>',
    apply_form = 'https://brighton.edu.au/courses/diploma-of-hospitality-management/',
    updated_at = NOW()
WHERE cricos_course_code = '111093M';
UPDATE courses SET
    course_description = '<div class="elementor-widget-container"> <p>This qualification reflects the role of individuals in a variety of information and communications technology (ICT) roles who have established specialised skills in a technical ICT function.</p> <p>Individuals in these roles carry out moderately complex tasks in specialist fields, working independently, as part of a team or leading deliverables with others. They may apply their skills across a wide range of industries, business functions and departments,or as a business owner (sole trader/contractor).</p> </div>',
    total_course_duration = '65 Weeks',
    offshore_tuition_fee = '17000',
    entry_requirements = '<div class="elementor-widget-container"> <p>To be considered for enrolment, applicants must:</p> <ul style="margin-left: 25px"> <li>Be at least 18 years of age.</li> <li>Have completed at least the equivalent of Year 12.</li> <li>Have an IELTS Academic score of 6.0 with test results no more than 2 years old.</li> <li>Complete a Core Skills Check.<br/> <em>Note: Applicants identified as at risk will be required to complete a full LLND assessment and a Course Pre-Entry Review (including an interview where required) to confirm their suitability before enrolment.</em></li> <li>Have access to a computer or laptop with a reliable internet connection, webcam, and microphone, to complete online learning, assessments, and Learning Management System (LMS) requirements.</li> </ul> <p><em style="display: block;padding-top:24px">Applicants do not need to provide IELTS (or equivalent) results if they can provide documented evidence of either:</em></p> <ul style="margin-left: 25px"> <li>Completion of at least 6 months of a Certificate IV level course at an Australian RTO, or</li> <li>Successful completion of a Brighton College English Placement Test.</li> </ul> <p><em style="display: block;padding-top:24px">Note: Other recognised English tests (e.g. PTE Academic, TOEFL) can be accepted. Applicants must provide their results so equivalence to IELTS Academic 6.0 can be confirmed.</em></p> </div>',
    apply_form = 'https://brighton.edu.au/courses/diploma-of-information-technology-cyber-security/',
    updated_at = NOW()
WHERE cricos_course_code = '105308G';
UPDATE courses SET
    course_description = '<div class="elementor-widget-container"> <p>The English for Academic Purposes (EAP) course is designed to prepare international students, from a range of backgrounds and nationalities, to undertake tertiary study in Australia.</p> <p>Students enrolled for this course will have as their specific study objective the completion of a tertiary level course in an Australian tertiary institution.</p> <p>The focus of this EAP course is developing the skills areas in English, which the student will require to study alongside native speakers in tertiary courses. However, students entering the EAP course at the lower level will not necessarily have access to the language base, which makes the use of these skills a possibility. For this reason the balance of the EAP course will move systematically from a language focus to a skills focus as the student progresses through the levels from EAP Level 1 to EAP Level 2.</p> </div>',
    total_course_duration = '26 Weeks',
    offshore_tuition_fee = '9100',
    entry_requirements = '<div class="elementor-widget-container"> <p>There are no specific educational pre-requisites for entry into this course, as entry into this level is based on assessment of English language proficiency. However, it is anticipated that a majority of students will have completed Year 10 or equivalent.</p> <p>Successful completion of Intermediate level or above of the General English course will permit admission to the EAP Level 1.</p> <p>Successful completion of Upper Intermediate level or above of the General English course or EAP Level 1 course will permit admission to the EAP Level 2</p> <p>The acceptable level in international tests required for entry to the courses is outlined below</p> <ul> <li>IELTS Band 5.0 with no band &lt; 4.5 = EAP Level 1</li> <li>IELTS Band 5.5 with no band &lt; 5.0 = EAP Level 2</li> </ul> </div>',
    apply_form = 'https://brighton.edu.au/courses/english-for-academic-purposes/',
    updated_at = NOW()
WHERE cricos_course_code = '111960F';
UPDATE courses SET
    course_description = '<div class="elementor-widget-container"> <p>The General English course is designed to prepare students for conversation, everyday situations and daily interactions that take place when travelling or living in an English-speaking country. Students learn and practice skills such as listening, reading, writing, and speaking in an interactive environment. Students commence at the level according to their current ability. Levels of difficulty increase over the duration of the course to assist students develop their skills and to be more confident and fluent in English.</p> <p>Successful completion of this course may allow the student to study other ELICOS courses such as English for Academic Purposes or Vocational Education and Training or Higher Education courses.</p> </div>',
    total_course_duration = '78 Weeks',
    offshore_tuition_fee = '27300',
    entry_requirements = '<div class="elementor-widget-container"> <p>International students must be at least 18 years of age.</p> <p>There are no specific educational pre-requisites for entry into this course, as entry into this level is based on assessment of English language proficiency. However, it is anticipated that a majority of students will have completed Year 10 or equivalent.</p> <p>Students will be assessed at orientation using the Oxford Placement Test and an interview.</p> <p>The appropriate class level requirements is shown in the table below:</p> <table> <tbody> <tr> <td>Starter Level</td> <td colspan="2">No minimum entry requirements</td> <td></td> </tr> <tr> <td rowspan="3">Elementary Level</td> <td>CEFR Level</td> <td>A1</td> </tr> <tr> <td>PTE Academic</td> <td>Not Applicable</td> </tr> <tr> <td>IELTS</td> <td>Not Applicable</td> </tr> <tr> <td rowspan="3">Pre-Intermediate Class Level</td> <td>CEFR Level</td> <td>A2</td> </tr> <tr> <td>PTE Academic</td> <td>Not Applicable</td> </tr> <tr> <td>IELTS</td> <td>Not Applicable</td> </tr> <tr> <td rowspan="3">Intermediate Class Level</td> <td>CEFR Level</td> <td>B1</td> </tr> <tr> <td>PTE Academic</td> <td>36-43</td> </tr> <tr> <td>IELTS</td> <td>4-5</td> </tr> <tr> <td rowspan="3">Upper-Intermediate Class Level</td> <td>CEFR level</td> <td>B2</td> </tr> <tr> <td>PTE Academic</td> <td>50-58</td> </tr> <tr> <td>IELTS</td> <td>5.5-6.5</td> </tr> <tr> <td rowspan="3">Advanced class level</td> <td>CEFR level</td> <td>C1</td> </tr> <tr> <td>PTE Academic</td> <td>73-79</td> </tr> <tr> <td>IELTS</td> <td>7-8</td> </tr> </tbody> </table> </div>',
    apply_form = 'https://brighton.edu.au/courses/general-english/',
    updated_at = NOW()
WHERE cricos_course_code = '111959K';
UPDATE courses SET
    course_description = '<div class="elementor-widget-container"> <p class="ait4">This qualification reflects the role of individuals who apply highly specialised knowledge and skills in the field of organisational learning and capability development. Individuals in these roles generate and evaluate complex ideas. They also initiate, design and execute major learning and development functions within an organisation. Typically, they would have full responsibility and accountability for the personal output and work of others.</p> <p class="ait4">This qualification may apply to leaders and managers in an organisation where learning is used to build organisational capability. The job roles that relate to this qualification may also include RTO Manager and RTO Director.</p> </div>',
    total_course_duration = '52 Weeks',
    offshore_tuition_fee = '15500',
    entry_requirements = '<div class="elementor-widget-container"> <p>To be considered for enrolment, applicants must:</p> <ul style="margin-left: 25px"> <li>Be at least 18 years of age.</li> <li>Have completed at least the equivalent of an AQF Level 5 or higher, or equivalent of a three (3) year bachelor’s degree overseas.</li> <li>Have an IELTS Academic score of 6.5 (or equivalent), with test results no more than 2 years old.</li> <li>Complete a Core Skills Check.<br/> <em>Note: Applicants identified as at risk will be required to complete a full LLND assessment and a Course Pre-Entry Review (including an interview where required) to confirm their suitability before enrolment.</em></li> <li>Have access to a computer or laptop with a reliable internet connection, webcam, and microphone, to complete online learning, assessments, and Learning Management System (LMS) requirements.</li> </ul> <p><em style="display: block;padding-top:24px">Applicants do not need to provide IELTS (or equivalent) results if they can provide documented evidence of either:</em></p> <ul style="margin-left: 25px"> <li>Completion of at least 6 months of a Diploma level course at an Australian RTO, or</li> <li>Successful completion of a Brighton College English Placement Test.</li> </ul> <p><em style="display: block;padding-top:24px">Note: Other recognised English tests (e.g. PTE Academic, TOEFL) can be accepted. Applicants must provide their results so equivalence to IELTS Academic 6.5 can be confirmed.</em></p> </div>',
    apply_form = 'https://brighton.edu.au/courses/graduate-diploma-of-managementlearning/',
    updated_at = NOW()
WHERE cricos_course_code = '105059H';
UPDATE courses SET
    course_description = '<div class="elementor-widget-container"> <p>The Pearson Test of English (PTE) Examination Preparation course has been designed for students seeking to acquire the language and test taking skills required to undertake the PTE. This course specifically prepares students for the Pearson Test of English (PTE) at Level 1 (B1) Examination. The PTE is recognised by many universities, employers and governments around the world.</p> <p>The PTE course is made up of 10 units of study, each of which is delivered over a week. It teaches reading, writing, listening and speaking skills which are necessary for the exam how to approach each exam task, as well as essential grammar and vocabulary.</p> </div>',
    total_course_duration = '39 Weeks',
    offshore_tuition_fee = '13650',
    entry_requirements = '<div class="elementor-widget-container"> <table> <tbody> <tr> <td>ITEM</td> <td colspan="2">NEEDED</td> <td></td> </tr> <tr> <td>Education level requirements</td> <td>There are no specific educational pre-requisites for entry into this course, as entry into this level is based on assessment of English language proficiency. However, it is anticipated that a majority of students will have completed year 10 or equivalent.</td> </tr> <tr> <td>English language requirements</td> <td>IELTS 5.0 or above</td> </tr> <tr> <td>Age requirements</td> <td>18 and above</td> </tr> </tbody> </table> </div>',
    apply_form = 'https://brighton.edu.au/courses/pearson-test-of-english-preparation',
    updated_at = NOW()
WHERE cricos_course_code = '115214H';
