-- Update provider institution details
UPDATE provider_institution SET
    intake_date = 'January, February, April, May, July, August, September, November',
    updated_at = NOW()
WHERE cricos_provider_code = '03854G';

UPDATE courses SET
    course_description = '<div> <div> <p>This qualification reflects the role of individuals who apply knowledge, practical skills and experience in leadership and management across a range of enterprise and industry contexts.</p><p>Individuals at this level display initiative and judgement in planning, organising, implementing and monitoring their own workload and the workload of others. They use communication skills to support individuals and teams to meet organisational or enterprise requirements.</p><p>They plan, design, apply and evaluate solutions to unpredictable problems, and identify, analyse and synthesise information from a variety of sources.</p> </div> </div>',
    total_course_duration = '52 weeks',
    offshore_tuition_fee = 17800,
    onshore_tuition_fee = 17800,
    enrolment_fee = 250,
    materials_fee = 400,
    entry_requirements = '<h4>Entry Requirements</h4><div><p>Australian Federation College has the following entry requirements. You must:</p><ul><li>Be at least 18 years of age at commencement of course;</li><li>Have completed Australian year 12 or equivalent OR successfully completed AQF Cert IV qualification or above;</li><li>Prior commencement, participate in a non-intrusive course entry assessment to determine suitability for the course and student needs. Where support needs are identified, Australian Federation College may implement support strategies, develop a Student Support Plan, provide additional learning support or recommend alternative study pathways where appropriate. The assessment can be accessed through the LLND Portal- <a href="https://learn.afcollege.edu.au/login">https://learn.afcollege.edu.au/login</a></li><li>Meet Australian student visa subclass 500 requirements;</li><li>Have an IELTS* score of 6 (test results must be no more than 2 years old).</li></ul><p>English language competence can also be demonstrated through documented evidence of any of the following:</p><ul><li>Educated for at least 5 years in an English-speaking country where the medium of instructions was in English; or</li><li>Completed at least a Certificate IV level course in an Australian RTO.</li></ul><p>*<em>Note that other English language tests such as PTE and TOEFL can be accepted. Students are required to provide their results so that Australian Federation College can confirm they are equivalent to IELTS 6. Refer to ECT for further guidance. </em></p></div>',
    apply_form = 'https://afcollege.edu.au/bsb50420-diploma-of-leadership-and-management/',
    updated_at = NOW()
WHERE cricos_course_code = '104415A';
UPDATE courses SET
    course_description = '<div> <div> <p>This qualification reflects the role of individuals who apply specialised knowledge and skills, together with experience in leadership and management, across a range of enterprise and industry contexts.</p><p><br/>Individuals at this level use initiative and judgement to plan and implement a range of leadership and management functions, with accountability for personal and team outcomes within broad parameters.</p><p><br/>They use cognitive and communication skills to identify, analyse and synthesise information from a variety of sources and transfer their knowledge to others, and creative or conceptual skills to express ideas and perspectives or respond to complex problems.</p> </div> </div>',
    total_course_duration = '52 weeks',
    offshore_tuition_fee = 11800,
    onshore_tuition_fee = 11800,
    enrolment_fee = 250,
    materials_fee = 400,
    entry_requirements = '<h4>Entry Requirements</h4><div><p>Australian Federation College has the following entry requirements. You must:</p><ul><li>Be at least 18 years of age at commencement of course;</li><li>Have completed a Diploma or Advanced Diploma from the BSB Training Package (current or superseded equivalent versions) such as BSB50420; or have two years’ equivalent full-time relevant work experience in an operational or leadership role in an enterprise.</li><li>Prior commencement, participate in a non-intrusive course entry assessment to determine suitability for the course and student needs. Where support needs are identified, Australian Federation College may implement support strategies, develop a Student Support Plan, provide additional learning support or recommend alternative study pathways where appropriate. The assessment can be accessed through the LLND Portal- <a href="https://learn.afcollege.edu.au/login">https://learn.afcollege.edu.au/login</a></li><li>Meet Australian student visa subclass 500 requirements;</li><li>Have an IELTS* score of 6 (test results must be no more than 2 years old).</li></ul><p>English language competence can also be demonstrated through documented evidence of any of the following:</p><ul><li>Educated for at least 5 years in an English-speaking country where the medium of instructions was in English; or</li><li>Completed at least a Certificate IV level course in an Australian RTO.</li></ul><p>*<em>Note that other English language tests such as PTE and TOEFL can be accepted. Students are required to provide their results so that Australian Federation College can confirm they are equivalent to IELTS 6. Refer to ECT for further guidance.</em></p></div>',
    apply_form = 'https://afcollege.edu.au/bsb60420-advanced-diploma-of-leadership-and-management/',
    updated_at = NOW()
WHERE cricos_course_code = '108185M';
UPDATE courses SET
    course_description = '<div> <div> <p>This qualification reflects the role of individuals who apply highly specialised knowledge and skills in the field of organisational learning and capability development. Individuals in these roles generate and evaluate complex ideas. They also initiate, design and execute major learning and development functions within an organisation. Typically, they would have full responsibility and accountability for the personal output and work of others.<br/>This qualification may apply to leaders and managers in an organisation where learning is used to build organisational capability. The job roles that relate to this qualification may also include RTO Manager and RTO Director.</p> </div> </div>',
    total_course_duration = '104 weeks',
    offshore_tuition_fee = 32000,
    onshore_tuition_fee = 32000,
    enrolment_fee = 250,
    materials_fee = 1250,
    entry_requirements = '<h4>Entry Requirements</h4><div><p>Australian Federation College has the following entry requirements. You must:</p><ul><li>Have completed Australian year 12 or equivalent OR successfully completed AQF Cert IV qualification or above;</li><li>Prior commencement, participate in a non-intrusive course entry assessment to determine suitability for the course and student needs. Where support needs are identified, Australian Federation College may implement support strategies, develop a Student Support Plan, provide additional learning support or recommend alternative study pathways where appropriate. The assessment can be accessed through the LLND Portal- <a href="https://learn.afcollege.edu.au/login">https://learn.afcollege.edu.au/login</a></li><li>Participate in a course entry interview to determine suitability for the course and student needs;</li><li>Meet Australian student visa subclass 500 requirements;</li><li>Have an IELTS* score of 6 (test results must be no more than 2 years old).</li></ul><p>English language competence can also be demonstrated through documented evidence of any of the following:</p><ul><li>Educated for at least 5 years in an English-speaking country where the medium of instructions was in English; or</li><li>Completed at least a Certificate IV level course in an Australian RTO.<br/>*<em>Note that other English language tests such as PTE and TOEFL can be accepted. Students are required to provide their results so that Australian Federation College can confirm they are equivalent to IELTS 6. Refer to ECT for further guidance.</em></li></ul></div>',
    apply_form = 'https://afcollege.edu.au/bsb80120-graduate-diploma-of-management/',
    updated_at = NOW()
WHERE cricos_course_code = '111026M';
UPDATE courses SET
    course_description = '<div> <div> <p>This qualification reflects the role of commercial cooks who have a supervisory or team leading role in the kitchen. They operate independently or with limited guidance from others and use discretion to solve non-routine problems.</p><p>This qualification provides a pathway to work in organizations such as restaurants, hotels, clubs, pubs, cafes and coffee shops, or to run a small business in these sectors.</p> </div> </div>',
    total_course_duration = '78 weeks',
    offshore_tuition_fee = 21000,
    onshore_tuition_fee = 21000,
    enrolment_fee = 250,
    materials_fee = 1750,
    entry_requirements = '<h4>Entry Requirements</h4><div><p>Australian Federation College has the following entry requirements:</p><ul><li>Be at least 18 years of age at commencement of course;</li><li>• Have completed Australian year 12 or equivalent OR successfully completed AQF Cert III qualification or above;<br/>• Prior commencement, participate in a non-intrusive course entry assessment to determine suitability for the course and student needs. Where support needs are identified, Australian Federation College may implement support strategies, develop a Student Support Plan, provide additional learning support or recommend alternative study pathways where appropriate. The assessment can be accessed through the LLND Portal- <a href="https://learn.afcollege.edu.au/login">https://learn.afcollege.edu.au/login</a></li><li>Meet Australian student visa subclass 500 requirements; and</li><li>Have an IELTS* score of 6 (test results must be no more than 2 years old).</li></ul><p>English language competence can also be demonstrated through documented evidence of any of the following:</p><ul><li>Educated for at least 5 years in an English-speaking country where the medium of instructions were in English; or</li><li>Completed at least a Certificate IV level course in an Australian RTO.</li></ul><p><em>*Note that other English language tests such as PTE and TOEFL can be accepted. Students are required to provide their results so that Australian Federation College can confirm they are equivalent to IELTS 6.</em></p></div>',
    apply_form = 'https://afcollege.edu.au/sit40521-certificate-iv-in-kitchen-management/',
    updated_at = NOW()
WHERE cricos_course_code = '110636D';
UPDATE courses SET
    course_description = '<div> <div> <p>This qualification reflects the role of highly skilled senior operators who use abroad range of hospitality skills combined with managerial skills and sound knowledge of industry to coordinate hospitality operations. They operate independently, have responsibility for others and make a range of operational business decisions.</p><p>This qualification provides a pathway to work in any hospitality industry sectors a departmental or small business manager. The diversity of employers includes restaurants, hotels, motels, catering operations, clubs, pubs, cafés, and coffee shops.</p> </div> </div>',
    total_course_duration = '65 weeks',
    offshore_tuition_fee = 15000,
    onshore_tuition_fee = 15000,
    enrolment_fee = 250,
    materials_fee = 1500,
    entry_requirements = '<h4>Entry Requirements</h4><div><p>Australian Federation College has the following entry requirements:</p><ul><li>Be at least 18 years of age at commencement of course;</li><li>Have completed Australian year 12 or equivalent OR successfully completed AQF Cert IV qualification or above;</li><li>Prior commencement, participate in a non-intrusive course entry assessment to determine suitability for the course and student needs. Where support needs are identified, Australian Federation College may implement support strategies, develop a Student Support Plan, provide additional learning support or recommend alternative study pathways where appropriate. The assessment can be accessed through the LLND Portal- <a href="https://learn.afcollege.edu.au/login">https://learn.afcollege.edu.au/login</a></li><li>Meet Australian student visa subclass 500 requirements; and</li><li>Have an IELTS* score of 6 (test results must be no more than 2 years old). English language competence can also be demonstrated through documented evidence of any of the following:</li></ul><ul><li>Educated for at least 5 years in an English-speaking country where the medium of instructions was in English; or</li><li>Completed at least a Certificate IV level course in an Australian RTO.</li></ul><p><em>*Note that other English language tests such as PTE and TOEFL can be accepted. Students are required to provide their results so that Australian Federation College can confirm they are equivalent to IELTS 6. Refer to ECT for further guidance.</em></p></div>',
    apply_form = 'https://afcollege.edu.au/sit50422-diploma-of-hospitality-management/',
    updated_at = NOW()
WHERE cricos_course_code = '111929E';
UPDATE courses SET
    course_description = '<div> <div> <p>This qualification reflects the role of highly skilled senior managers who use a broad range of hospitality skills combined with specialised managerial skills and substantial knowledge of industry to coordinate hospitality operations. They operate with significant autonomy and are responsible for making strategic business management decisions.</p><p>This qualification provides a pathway to work in any hospitality industry sector and for a diversity of employers including restaurants, hotels, motels, catering operations, clubs, pubs, cafés, and coffee shops. This qualification allows for multi-skilling and for acquiring targeted skills in accommodation services, cookery, food and beverage and gaming.</p><p>The skills in this qualification must be applied in accordance with Commonwealth and State/Territory legislation, Australian standards and industry codes of practice.</p> </div> </div>',
    total_course_duration = '104 weeks',
    offshore_tuition_fee = 26000,
    onshore_tuition_fee = 26000,
    enrolment_fee = 250,
    materials_fee = 1500,
    entry_requirements = '<h4>Entry Requirements</h4><div><p>Australian Federation College has the following entry requirements:</p><ul><li>Be at least 18 years of age at course commencement;</li><li>• Have completed Australian year 12 or equivalent OR successfully completed AQF Cert IV qualification or above. <br/>• Prior commencement, participate in a non-intrusive course entry assessment to determine suitability for the course and student needs. Where support needs are identified, Australian Federation College may implement support strategies, develop a Student Support Plan, provide additional learning support or recommend alternative study pathways where appropriate. The assessment can be accessed through the LLND Portal- <a href="https://learn.afcollege.edu.au/login">https://learn.afcollege.edu.au/login</a></li><li>Meet Australian student visa subclass 500 requirements; and</li><li>Have an IELTS* score of 6.0 (test results must be no more than 2 years old). English language competence can also be demonstrated through documented evidence of any of the following:<ul><li>Educated for at least 5 years in an English-speaking country where the medium of instructions was in English; or</li><li>Completed at least a Certificate IV level course in an Australian RTO within the last 2 years;</li></ul></li></ul><p><em>*Note that other English language tests such as PTE and TOEFL can be accepted. Students are required to provide their results so that Australian Federation College can confirm they are equivalent to IELTS 6.0. Refer to ECT for further guidance.</em></p></div>',
    apply_form = 'https://afcollege.edu.au/sit60322-advanced-diploma-of-hospitality-management/',
    updated_at = NOW()
WHERE cricos_course_code = '118106K';
UPDATE courses SET
    course_description = '<div> <div> <p>This qualification reflects the role of individuals in a variety of information and communications technology (ICT) roles who have established specialised skills in a technical ICT function.</p><p>Individuals in these roles carry out moderately complex tasks in a specialist field, working independently, as part of a team or leading a deliverable with others. They may apply their skills across a wide range of industries, business functions and departments, or as a business owner (sole trader/contractor).</p> </div> </div>',
    total_course_duration = '65 weeks',
    offshore_tuition_fee = 17250,
    onshore_tuition_fee = 17250,
    enrolment_fee = 250,
    materials_fee = 500,
    entry_requirements = '<h4>Entry Requirements</h4><div><p>Australian Federation College has the following entry requirements. You must:</p><ul><li>Be at least 18 years of age at commencement of course;</li><li>Have completed Australian year 12 or equivalent OR successfully completed AQF Certificate IV qualification or above;</li><li>Prior commencement, participate in a non-intrusive course entry assessment to determine suitability for the course and student needs. Where support needs are identified, Australian Federation College may implement support strategies, develop a Student Support Plan, provide additional learning support or recommend alternative study pathways where appropriate. The assessment can be accessed through the LLND Portal <a href="https://learn.afcollege.edu.au/login">https://learn.afcollege.edu.au/login</a></li><li>Meet Australian student visa subclass 500 requirements;</li><li>Have an IELTS* score of 6 (test results must be no more than 2 years old).</li></ul><p>English language competence can also be demonstrated through documented evidence of any of the following:</p><ul><li>Educated for at least 5 years in an English-speaking country where the medium of instructions was in English; or</li><li>Completed at least a Certificate IV level course in an Australian RTO.</li></ul><p>*<em>Note that other English language tests such as PTE and TOEFL can be accepted. Students are required to provide their results so that Australian Federation College can confirm they are equivalent to IELTS 6. Refer to ECT for further guidance.</em></p></div>',
    apply_form = 'https://afcollege.edu.au/ict50220-diploma-of-information-technology/',
    updated_at = NOW()
WHERE cricos_course_code = '108184A';
UPDATE courses SET
    course_description = '<div> <div> <p>This qualification reflects the role of individuals in a variety of information and communications technology (ICT) roles who have significant experience in specialist technical skills, or managerial business and people management<br/>skills.</p><p>Individuals in these roles carry out complex tasks in a specialist field, working independently, leading a team or a strategic direction of a business. They apply their skills across a wide range of industries and business functions, or<br/>as a business owner (sole trader/contractor).</p> </div> </div>',
    total_course_duration = '78 weeks',
    offshore_tuition_fee = 20800,
    onshore_tuition_fee = 20800,
    enrolment_fee = 250,
    materials_fee = 500,
    entry_requirements = '<h4>Entry Requirements</h4><div><p>Australian Federation College has the following entry requirements. You must:</p><ul><li>Be at least 18 years of age at commencement of course;<br/>Have completed Australian year 12 or equivalent OR successfully completed AQF Certificate IV qualification or above;<br/>Prior commencement, participate in a non-intrusive course entry assessment to determine suitability for the course and student needs. Where support needs are identified, Australian Federation College may implement support strategies, develop a Student Support Plan, provide additional learning support or recommend alternative study pathways where appropriate. The assessment can be accessed through the LLND Portal- <a href="https://learn.afcollege.edu.au/login">https://learn.afcollege.edu.au/login</a></li><li>Meet Australian student visa subclass 500 requirements;</li><li>Have an IELTS* score of 6 (test results must be no more than 2 years old).</li></ul><p>English language competence can also be demonstrated through documented evidence of any of the following:</p><ul><li>Educated for at least 5 years in an English-speaking country where the medium of instructions was in English; or</li><li>Completed at least a Certificate IV level course in an Australian RTO.</li></ul><p>*<em>Note that other English language tests such as PTE and TOEFL can be accepted. Students are required to provide their results so that Australian Federation College can confirm they are equivalent to IELTS 6. Refer to ECT for further guidance.</em></p></div>',
    apply_form = 'https://afcollege.edu.au/ict60220-advanced-diploma-of-information-technology/',
    updated_at = NOW()
WHERE cricos_course_code = '108186K';
UPDATE courses SET
    course_description = '<div> <div> <p>This qualification reflects the role of individuals in a variety of information and communications technology (ICT) roles who have significant experience in specialist technical skills, or managerial business and people management skills.</p><p>Individuals in these roles carry out complex tasks in a specialist field, working independently, leading a team or a strategic direction of a business. They apply their skills across a wide range of industries and business functions, or as a business owner (sole trader/contractor).</p> </div> </div>',
    total_course_duration = '104 weeks',
    offshore_tuition_fee = 24850,
    onshore_tuition_fee = 24850,
    enrolment_fee = 250,
    materials_fee = 600,
    entry_requirements = '<h4>Entry Requirements</h4><div><p>Australian Federation College has the following entry requirements. You must:</p><ul><li>Be at least 18 years of age at commencement of course;</li><li>Have completed Australian year 12 or equivalent OR successfully completed AQF Certificate IV qualification or above;</li><li>Prior commencement, participate in a non-intrusive course entry assessment to determine suitability for the course and student needs. Where support needs are identified, Australian Federation College may implement support strategies, develop a Student Support Plan, provide additional learning support or recommend alternative study pathways where appropriate. The assessment can be accessed through the LLND Portal- <a href="https://learn.afcollege.edu.au/login">https://learn.afcollege.edu.au/login</a></li><li>Meet Australian student visa subclass 500 requirements;</li><li>Have an IELTS* score of 6 (test results must be no more than 2 years old).</li></ul><p>English language competence can also be demonstrated through documented evidence of any of the following:</p><ul><li>Educated for at least 5 years in an English-speaking country where the medium of instructions was in English; or</li><li>Completed at least a Certificate IV level course in an Australian RTO.</li></ul><p>*<em>Note that other English language tests such as PTE and TOEFL can be accepted. Students are required to provide their results so that Australian Federation College can confirm they are equivalent to IELTS 6. Refer to ECT for further guidance. Refer to the ECT for further guidance.</em></p></div>',
    apply_form = 'https://afcollege.edu.au/advanced-diploma-of-information-technology-telecommunications-network-engineering-specialisation/',
    updated_at = NOW()
WHERE cricos_course_code = '108186K';
UPDATE courses SET
    course_description = '<div> <div> <p>This qualification reflects the role of support workers who complete specialised tasks and functions in aged services; either in residential, home or community based environments. Workers will take responsibility for their own outputs within defined organisation guidelines and maintain quality service delivery through the development, facilitation and review of individualised service planning and delivery.</p><p>Workers may be required to demonstrate leadership and have limited responsibility for the organisation and the quantity and quality of outputs of others within limited parameters.</p> </div> </div>',
    total_course_duration = '52 weeks',
    offshore_tuition_fee = 14000,
    onshore_tuition_fee = 14000,
    enrolment_fee = 250,
    materials_fee = 1000,
    entry_requirements = '<h4>Entry Requirements</h4><div><p>Australian Federation College has the following entry requirements:</p><ul><li>Be at least 18 years of age at course commencement;</li><li>• Have completed Australian year 12 or equivalent OR successfully completed AQF Certificate III qualification or above;</li><li>Prior commencement, participate in a non-intrusive course entry assessment to determine suitability for the course and student needs. Where support needs are identified, Australian Federation College may implement support strategies, develop a Student Support Plan, provide additional learning support or recommend alternative study pathways where appropriate. The assessment can be accessed through the LLND Portal- <a href="https://learn.afcollege.edu.au/login">https://learn.afcollege.edu.au/login</a></li><li>Meet Australian student visa subclass 500 requirements; and</li><li>Have an IELTS* score of 6.0 (test results must be no more than 2 years old). English language competence can also be demonstrated through documented evidence of any of the following:<ul><li>Educated for at least 5 years in an English-speaking country where the medium of instructions was in English; or</li><li>Completed at least a Certificate IV level course in an Australian RTO within the last 2 years;</li></ul></li></ul><p><em>*Note that other English language tests such as PTE and TOEFL can be accepted. Students are required to provide their results so that Australian Federation College can confirm they are equivalent to IELTS 6.0. Refer to ECT for further guidance.</em></p></div>',
    apply_form = 'https://afcollege.edu.au/chc43015-certificate-iv-in-ageing-support/',
    updated_at = NOW()
WHERE cricos_course_code = '119917M';
UPDATE courses SET
    course_description = '<div> <div> <p>This qualification prepares individuals for roles in delivering, managing, and coordinating person-centered services to individuals, groups, and communities.</p><p>At this level, professionals possess specialized skills in community services, working independently within their scope of practice while following guidance from senior management.</p><p>Graduates are equipped to support people in making meaningful changes to enhance their personal and social well-being. They may also take on responsibilities such as supervising staff and volunteers, managing cases, and coordinating programs.</p> </div> </div>',
    total_course_duration = '72 weeks',
    offshore_tuition_fee = 24000,
    onshore_tuition_fee = 24000,
    enrolment_fee = 250,
    materials_fee = 1450,
    entry_requirements = '<h4>Entry Requirements</h4><div><p>Australian Federation College has the following entry requirements:</p><ul><li>Be at least 18 years of age at commencement of course;</li><li>Have completed Australian year 12 or equivalent OR successfully completed AQF Cert IV qualification or above.</li><li>Prior commencement, participate in a non-intrusive course entry assessment to determine suitability for the course and student needs. Where support needs are identified, Australian Federation College may implement support strategies, develop a Student Support Plan, provide additional learning support or recommend alternative study pathways where appropriate. The assessment can be accessed through the LLND Portal- <a href="https://learn.afcollege.edu.au/login">https://learn.afcollege.edu.au/login</a></li><li>Meet Australian student visa subclass 500 requirements; and</li><li>Have an IELTS* score of 6 (test results must be no more than 2 years old).</li></ul><p>English language competence can also be demonstrated through documented evidence of any of the following:</p><ul><li>Educated for at least 5 years in an English-speaking country where the medium of instructions were in English; or</li><li>Completed at least a Certificate IV level course in an Australian RTO within the last 2 years.</li></ul><p><em>*Note that other English language tests such as PTE and TOEFL can be accepted. Students are required to provide their results so that Australian Federation College can confirm they are equivalent to IELTS 6. Refer to ECT for further guidance.</em></p></div>',
    apply_form = 'https://afcollege.edu.au/chc52025-diploma-of-community-services/',
    updated_at = NOW()
WHERE cricos_course_code = '118794C';
UPDATE courses SET
    course_description = '<div> <div> <p>This qualification reflects the role of workers who are middle managers or managers across a range of community sector organisations. These people work independently and report to executive management, directors or boards of management. They undertake a range of functions requiring the application of knowledge and skills to achieve results in line with the organisation’s goals and strategic directions.</p><p>At this level, workers have responsibility for planning and monitoring service delivery, recruitment and performance management of other paid or unpaid workers, managing risk and contributing to continuous improvement within the scope of their specific role. This may include management of a specific programs or project, or broader management of a community-based organisation, early childhood education service, not-for-profit organisation or community centre.</p> </div> </div>',
    total_course_duration = '71 weeks',
    offshore_tuition_fee = 18000,
    onshore_tuition_fee = 18000,
    enrolment_fee = 250,
    materials_fee = 600,
    entry_requirements = '<h4>Entry Requirements</h4><div><p>Australian Federation College has the following entry requirements:</p><ul><li>Be at least 18 years of age at commencement of course;</li><li>Have completed Australian year 12 or equivalent OR successfully completed AQF Cert IV qualification or above;</li><li>Prior commencement, participate in a non-intrusive course entry assessment to determine suitability for the course and student needs. Where support needs are identified, Australian Federation College may implement support strategies, develop a Student Support Plan, provide additional learning support or recommend alternative study pathways where appropriate. The assessment can be accessed through the LLND Portal- <a href="https://learn.afcollege.edu.au/login">https://learn.afcollege.edu.au/login</a></li><li>Meet Australian student visa subclass 500 requirements; and</li><li>Have an IELTS* score of 6 (test results must be no more than 2 years old).</li></ul><p>English language competence can also be demonstrated through documented evidence of any of the following:</p><ul><li>Educated for at least 5 years in an English-speaking country where the medium of instructions were in English; or</li><li>Completed at least a Certificate IV level course in an Australian RTO within the last 2 years.</li></ul><p><em>*Note that other English language tests such as PTE and TOEFL can be accepted. Students are required to provide their results so that Australian Federation College can confirm they are equivalent to IELTS 6. Refer to ECT for further guidance.</em></p></div>',
    apply_form = 'https://afcollege.edu.au/chc62015-advanced-diploma-of-community-sector-management/',
    updated_at = NOW()
WHERE cricos_course_code = '111025A';
UPDATE courses SET
    course_description = '<div> <div> <p>This qualification reflects the role of those working in decision-making and supervisory roles on farms, stations and related rural businesses.</p><p>At this level, workers take personal responsibility and exercise autonomy in undertaking complex work. They must analyze information and exercise judgement to complete a range of advanced skilled activities.</p> </div> </div>',
    total_course_duration = '52 weeks',
    offshore_tuition_fee = 14000,
    onshore_tuition_fee = 14000,
    enrolment_fee = 250,
    materials_fee = 1000,
    entry_requirements = '<h4>Entry Requirements</h4><div><p>Australian Federation College has the following entry requirements:</p><ul><li>Be at least 18 years of age at commencement of course;</li><li>Have completed Australian year 12 or equivalent OR successfully completed AQF Cert IV qualification or above.</li><li>Prior commencement, participate in a non-intrusive course entry assessment to determine suitability for the course and student needs. Where support needs are identified, Australian Federation College may implement support strategies, develop a Student Support Plan, provide additional learning support or recommend alternative study pathways where appropriate. The assessment can be accessed through the LLND Portal- <a href="https://learn.afcollege.edu.au/login">https://learn.afcollege.edu.au/login</a></li><li>Meet Australian student visa subclass 500 requirements; and</li><li>Have an IELTS* score of 6 (test results must be no more than 2 years old).</li></ul><p>English language competence can also be demonstrated through documented evidence of any of the following:</p><ul><li>Educated for at least 5 years in an English-speaking country where the medium of instructions was in English; or</li><li>Completed at least a Certificate IV level course in an Australian RTO within the last 2 years.</li></ul><p><em>*Note that other English language tests such as PTE and TOEFL can be accepted. Students are required to provide their results so that Australian Federation College can confirm they are equivalent to IELTS 6. Refer to ECT for further guidance.</em></p></div>',
    apply_form = 'https://afcollege.edu.au/ahc51422-diploma-of-agribusiness-management/',
    updated_at = NOW()
WHERE cricos_course_code = '111931M';
UPDATE courses SET
    course_description = '<div> <div> <p>This qualification reflects the role of an individual working as a senior civil works designer or a para-professional designer, who supports professional engineers. They perform tasks that are broad, specialised, complex and technical and include strategic areas and initiating activities. They are responsible for the design of complex projects to ensure the implementation of the client’s site requirements and are required to demonstrate self-directed application of theoretical and technical knowledge and initiate solutions to technical problems or management requirements.<br/><br/><strong>Licensing, legislative, regulatory or certification considerations<br/><br/></strong>Licensing, legislative, regulatory and certification requirements that apply to this qualification can vary between states, territories and industry sectors. Users must check requirements with relevant body before applying the qualification.</p> </div> </div>',
    total_course_duration = '104 weeks',
    offshore_tuition_fee = 30000,
    onshore_tuition_fee = 30000,
    enrolment_fee = 250,
    materials_fee = 1000,
    entry_requirements = '<h4>Entry Requirements</h4><div><p>Australian Federation College has the following entry requirements:</p><ul><li>Be at least 18 years of age at course commencement;</li><li>Have completed Australian year 12 or equivalent OR successfully completed AQF Certificate IV qualification or above;</li><li>Prior commencement, participate in a non-intrusive course entry assessment to determine suitability for the course and student needs. Where support needs are identified, Australian Federation College may implement support strategies, develop a Student Support Plan, provide additional learning support or recommend alternative study pathways where appropriate. The assessment can be accessed through the LLND Portal- <a href="https://learn.afcollege.edu.au/login">https://learn.afcollege.edu.au/login</a></li><li>Meet Australian student visa subclass 500 requirements; and</li><li>Have an IELTS* score of 6 (test results must be no more than 2 years old). English language competence can also be demonstrated through documented evidence of any of the following:<ul><li>Educated for at least 5 years in an English-speaking country where the medium of instructions was in English; or</li><li>Completed at least a Certificate IV level course in an Australian RTO within the last 2 years;</li></ul></li></ul><p><em>*Note that other English language tests such as PTE and TOEFL can be accepted. Students are required to provide their results so that Australian Federation College can confirm they are equivalent to IELTS 6. Refer to ECT for further guidance.</em></p></div>',
    apply_form = 'https://afcollege.edu.au/rii60520-advanced-diploma-of-civil-construction-design/',
    updated_at = NOW()
WHERE cricos_course_code = '114858B';
UPDATE courses SET
    course_description = '<div> <div> <p>The General English course is designed to prepare students for conversation, everyday situations and daily interactions that take place when travelling or living in an English-speaking country. Students learn and practice the four macro-skills of listening, reading, writing and speaking in an interactive environment. Levels of difficulty increase over the duration of the course to assist students to develop their skills and to be more confident and fluent in English.<br/>The course is structured into 6 levels (Starter, Elementary, Pre-intermediate, Intermediate, Upper Intermediate and Advanced). Each of the levels has a duration of 10 weeks (the study period) and the course in total is 70 weeks (including holidays). The specific outcomes for each level are detailed in the section of this curriculum document on course outcomes.</p> </div> </div>',
    total_course_duration = '10-70 weeks',
    offshore_tuition_fee = NULL,
    onshore_tuition_fee = NULL,
    enrolment_fee = NULL,
    materials_fee = NULL,
    entry_requirements = '<h4>Entry Requirements</h4><div><p>Australian Federation College has the following entry requirements:</p><ul><li>Be at least 18 years of age at course commencement;</li><li>For students studying this course alone, there is no IELTS requirement.</li><li>Students will be assessed by Australian Federation College during the enrolment process using the Oxford Placement Test and an interview. They will then be placed in the appropriate class level which is best suited to their needs.</li></ul></div>',
    apply_form = 'https://afcollege.edu.au/general-english-elicos/',
    updated_at = NOW()
WHERE cricos_course_code = '116758A';
